### ISSUE TITLE
Hidden embedded toot becomes very tall

### ISSUE THREAD

**Issue by BenLubar** [mastodon/mastodon#10159]
### Expected behaviour

The toot should be a reasonable height.

### Actual behaviour

The toot is very tall.

### Steps to reproduce the problem

https://jsfiddle.net/s1on0kdc/1/embedded/html,result/

```
<p>Normal:</p>

<iframe src="https://mastodon.lubar.me/@ben/101693761835624754/embed" class="mastodon-embed" style="max-width: 100%; border: 0" width="400"></iframe><script src="https://mastodon.lubar.me/embed.js" async="async"></script>

<p>Hidden:</p>

<details>
<iframe src="https://mastodon.lubar.me/@ben/101693761835624754/embed" class="mastodon-embed" style="max-width: 100%; border: 0" width="400"></iframe><script src="https://mastodon.lubar.me/embed.js" async="async"></script>
</details>
```

### Specifications

It appears on every instance I've checked, most using v2.7.3.

I'm using Chrome 72.0.3626.121 on Windows 10

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this issue can be reliably reproduced on an updated version please request that this issue be reopened or open a new issue. For either option please provide updated logs/troubleshooting on a recent release. Thank you.
