### ISSUE TITLE
Block id profile page access to avoid user enumeration

### ISSUE THREAD

**Issue by CGsama** [mastodon/mastodon#10445]
### Pitch

Block non admin group direct access user profile page from user id. 
E.g. https://[domain]/web/accounts/[digit]

### Motivation

This will be vulnerable to user enumeration.
Some user may care about hide their existence in an instance, but this id access can dump all user profile from an instance, at lease a list of all usernames.

**Comment by trwnh** [comment]
I don't think this makes any sense. Those are URL routes for the web app, and they are getting the information directly from the Mastodon API, i.e. via `/api/v1/` instead of via `/web/`, so the webapp route `/web/accounts/:id` will correspond to the API route `/api/v1/accounts/:id`.

If you're worried that accounts can be enumerated by user via API, then the real solution is to stop assigning/using auto-incrementing integer IDs, and to start using some other method of generating user IDs.

**Comment by CGsama** [comment]
Got your idea, so one way of patching should be using something like hash of incremental id with sever side salt? Sounds like it would touches lots part of code lol. Is there an exist interface I can change the generator?

**Comment by trwnh** [comment]
I'm not sure but I'd like to know this too, for a hypothetical global UID system.
