### ISSUE TITLE
Reset password by user name

### ISSUE THREAD

**Issue by jedahan** [mastodon/mastodon#10933]
I forgot what email address I used to sign up to my cybre.space instance. To reset, I need to provide an address. I provided a bunch, but none of them were correct.

It would be nice if I could just say "please send a password reset for @username@instance" so I wouldn't have to think about it.

**Comment by nightpool** [comment]
have you considered just asking your admins?

(....in this case, me?)

**Comment by trwnh** [comment]
>have you considered just asking your admins [for the email attached to an account]

that sounds like a recipe for social engineering.

a password reset request emailed to an unknown account provides a potential attacker with zero knowledge.

**Comment by madranet** [comment]
I've just run into the same problem myself today.  

Pity no-one addressed this.  It must be quite common for people to sign up for a service and forget what email they used to do so. As well as the fact that many of us have multiple email addresses already, services like Gmail allow customising the address by adding _'+\<something\>'_ to it –a device which is commonly used to detect the origin of spam. So now I'm expected to try all my email addresses and [for each one] all the variations of _myname+<something representing 'mastodon'>@provider.com_ that I may have used.

Why can i not just request a password reset with my username?

**Comment by landaire** [comment]
I also ran into this email today while re-evaluating Mastodon after the Twitter acquisition. I signed up in 2017 and my password manager didn't save the email I registered with (I also use my email provider's `+label` feature similar to @madranet). I cannot login or reset email by username even though I know the username and its password.

**Comment by karate** [comment]
Same for me. My password manager saved the username and password. I have no idea of the email I've used.

@madranet has a very good point about custom gmail addresses with `+something`.

**Comment by 4rrache** [comment]
Me too, l actually prepped for the abandon Twitter ship and secured my username and now haha the joke’s on me… can’t login because I can’t remember what email I used…

**Comment by akippnn** [comment]
> have you considered just asking your admins?
> 
> (....in this case, me?)

that's pretty nice, but for bigger instances (like mastodon.social) an average user like me would have no idea how to contact the instance admins.

**Comment by madranet** [comment]
So disappointing that, just over four years since the issue was initially raised, there's still been no progress on this. Or even any acknowledgement or response from the development team.

Sadly, this  unresponsive attitude seems to be endemic amongst fediverse developers. I was also the originartor of one of the original calls for Pixelfed tro allow[ import from Instagram](https://github.com/pixelfed/pixelfed/issues/765) --also back in 2019.  Which has only just been [unreliably] addressed.

How on earth does the collective Fediverse expect to wean people off Twitter, Instagram, Facebook, etc. when their collective development teams just ignore the very real hurdles that are preventing people from getting on board?  The incumbents can afford to be uncaring deaf to user complaints. They have countless millions of users already signed up. The wannabes don't have that luxury. You really need to try harder.

**Comment by Gargron** [comment]
Allowing password resets or login attempts by public username alone would drastically increase the surface area for hijacking attempts; if nothing else by spamming account owners with "Somebody tried resetting your password, was it you?" e-mails.

**Comment by akippnn** [comment]
> So disappointing that, just over four years since the issue was initially raised, there's still been no progress on this. Or even any acknowledgement or response from the development team.

It's not really addressed because the alternative is to try all the email accounts. It's a non-elegant solution (especially when you get rate limited and have multiple accounts to test AND letting the instance admins know all of your email accounts) but you're not going to lose that account.

I could make a PR to add this feature, though I'm not as qualified to do that (especially since I don't use Ruby or the SMTP server that Mastodon uses) and I doubt it be merged.

> Allowing password resets or login attempts by public username alone would drastically increase the surface area for hijacking attempts; if nothing else by spamming account owners with "Somebody tried resetting your password, was it you?" e-mails.

The spamming point is a non-issue, quite frankly, since it's not that difficult to set message filtering. Gmail provides this OOTB already: https://support.google.com/mail/answer/6579?hl=en (TL;DR the setting button next to the search to create a filter.)

I agree there's some sort of line to be drawn here between convenience and account security, but I don't think it's a drastic of an increase as you say. Through social engineering, sure there's a good chance, but I don't think people should be that eager to forward an email to someone, when the email should be clear enough for them to realize "Someone pressed the 'forgot my email' option."

**Comment by madranet** [comment]
> Sadly, this unresponsive attitude seems to be endemic amongst fediverse developers.

![SS 2023-08-29 at 14 16 30](https://github.com/mastodon/mastodon/assets/669658/7b85c30f-5748-4ad4-b4dd-c7cbc48100c0)

I rest my case!

**Comment by akippnn** [comment]
I made a separate issue because this feature request is for a "password reset via username" which is not what (I believe) any of us want here. Also I think we should keep the respectful discourse while avoiding any generalizations about people or group of people, since I recognize that this project is a voluntary effort non-profit.

**Comment by madranet** [comment]
> I think we should keep the respectful discourse while avoiding any generalizations about people or group of people, since I recognize that this project is a voluntary effort non-profit.

If that's a reference to me; I don't think I was being any of those things. 

I loathe Twitter, Instagram, Facebook et al and I was really excited by the advent of the Fediverse. And I really wanted it to succeed. However, I have found an attitude almost bordering on apathy on the part of the teams beyond the various Fediverse apps I've tried to use. Whatever the reality "behind the scenes", in public, they give the impression by their responses [or lack thereof] to user problems that they really don't care, or take anything on board. 

As I keep saying; Twitter, Instagram have an established user base of  literally billions. What, apart from a lot of worthy sounding soundbites is the Fediverse actually offering to tempt people to leave those sites [and all their freinds and content there] behind and join the Fediverse?  A generally inferior user experience, no way to bring your existing content with you and --on top of this-- an [apparent] attittude amongst the developer teams that amounts to "It is what it is. Take it or leave it".

I really don't think it's "disrespectful" to give constructive criticism to someone or something you want to succeed. And, if I was part of the development team behind one of these projects, I'd be falling over myself to take on board user input as to how we could make things better. Not, as is all too often the case, responding with 'Meh. You're holding it wrong'.

**Comment by akippnn** [comment]
> I really don't think it's "disrespectful" to give constructive criticism to someone or something you want to succeed.

I'm not really saying otherwise; I'm more like trying a mediator role to an issue I believe is being easily overlooked, which is unfortunate how the latter is the case as it is right now. I think it's just that we're referencing things that have nothing to do with the issue itself so there's a bit too much of a noise rather than actual constructive criticism, if that makes sense.

**Comment by RayCulp** [comment]
Other services solve this problem by allowing a user to enter their user name, and if the user name is found in the database, an email is sent directly to the registered email address. It is up to the user then to check their inboxes. Unless a hacker has access to your emails, this will not help them gain access to your Mastodon account.
