### ISSUE TITLE
assets:precompile fails without error 

### ISSUE THREAD

**Issue by oufmilo** [mastodon/mastodon#11135]
[Issue 5696](https://github.com/tootsuite/mastodon/issues/5696) 

I have the same problem when i run assets:precompile, i never have this before...
Someone have an idea ?
Thanks

```
yarn install v1.16.0
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/6] Linking dependencies...
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 22.85s.
Compiling…
Compilation failed:
```

**Comment by nightpool** [comment]
probably the same out of memory error as #5696. how much memory does the machine you're compiling it on have? does it have a swap file?

**Comment by oufmilo** [comment]
Its very strange, I never have this message before. 
My instance is running on a hetzner server. 
2 vCpu 
8go RAM 
80go Disk space 
20TB Traffic 

I don't understand and I've making updates 2.9.2 it's working but I have this compilation failed.

**Comment by oufmilo** [comment]
Up ? No solution ?

**Comment by ichi-i** [comment]
I am experiencing the same issue.
2GB RAM + 3GB SWAP.

**Comment by ichi-i** [comment]
Apologies for bumping this, but since no error is returned, after weeks of troubleshooting I have no idea what to try anymore.

During the past two weeks I have been troubleshooting this problem without success.
I have tried multiple Ruby versions, ensuring that everything is updated, assigning ridiculous amounts of SWAP (up to 25GB) to ensure that memory wasn't choking the task, and stopping mastodon services.

I also noticed that if I do not run `yarn` before running `RAILS_ENV=production bundle exec rails assets:precompile` the output would look like this:
```
~/live$ RAILS_ENV=production bundle exec rails assets:precompile
yarn install v1.17.3
[1/6] Validating package.json...
[2/6] Resolving packages...
Done in 2.91s.
Compiling…
Compilation failed:

```
For some reason, it skips 4 steps.

However, if I first run `yarn` and then (try to) precompile the assets, then the output is:
```
~/live$ RAILS_ENV=production bundle exec rails assets:precompile
yarn install v1.17.3
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/6] Linking dependencies...
warning " > react-redux-loading-bar@4.0.8" has incorrect peer dependency "react-redux@^3.0.0 || ^4.0.0 || ^5.0.0".
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 47.91s.
Compiling…
Compilation failed:

~/live$
```
In both cases, the compilation fails without error.
Unlike #5696 no error has ever been returned even though I have tried to precompile assets more than 20 times now.

Doing a `git checkout` at v2.9.2 just to be sure did not help either.

**Comment by JetForMe** [comment]
I'm running into this today trying to update v3.5.3 to v4.0.2

**Comment by schalkneethling** [comment]
> I'm running into this today trying to update v3.5.3 to v4.0.2

Me as well and running `RAILS_ENV=production bundle exec rails assets:precompile` again now ends with:

```
yarn install v1.22.4
[1/6] Validating package.json...
[2/6] Resolving packages...
success Already up-to-date.
Done in 2.23s.
Everything's up-to-date. Nothing to do
```

This leads to:

```
ActionView::Template::Error (Webpacker can't find media/images/preview.png in /home/mastodon/live/public/packs/manifest.json. Possible causes:
Nov 18 23:20:27 mycelium-network-mastodon bundle[2115]: 1. You want to set webpacker.yml value of compile to true for your environment
```

Is there a way to force webpack to try again?

**Comment by schalkneethling** [comment]
@JetForMe I ended up going into `/home/mastodon/live` after `su - mastodon` and running the `package.json` script directly via Yarn:

```
yarn build:production
```

I then restarted all the processes, and I am back up and running.

**Comment by eledroos** [comment]
@schalkneethling I tried that command, with the same issues as others in this thread, and received a 

`error Command failed with exit code 1.`

I can't get the assets to precompile on a Digital Ocean droplet. They fail the first time and then I get the `Everything's up-to-date. Nothing to do` the second time.

**Comment by eledroos** [comment]
Okay so if you `touch package.json` it'll actually recognize something has changed, and try to recompile when you re-run the `RAILS_ENV=production bundle exec rails assets:precompile` command.

**Comment by highb** [comment]
I think the most likely problem here is that the asset build is running out of memory on small systems.

I run a mastodon VM on a digital ocean droplet with 2GB of memory and was seeing the asset precompile fail with no error like other folks here. I got it to work if I stopped all mastodon services, then ran `RAILS_ENV=production bundle exec rails assets:clobber assets:precompile`. Summary of steps below for others to copy if you are in a similar VM-based environment.

```
systemctl stop mastodon-web.service 
systemctl stop mastodon-sidekiq.service 
systemctl stop mastodon-streaming.service 
sudo su - mastodon
cd ~/live
RAILS_ENV=production bundle exec rails assets:clobber assets:precompile
systemctl start mastodon-sidekiq.service 
systemctl start mastodon-streaming
systemctl start mastodon-streaming.service 
systemctl start mastodon-web.service 
```

**Comment by eledroos** [comment]
@highb you rule, this worked for me -- thank you!

**Comment by Mathspy** [comment]
I also ran into this issue but forgot to post my solution. It was the same OOM error as I am also using the same DigitalOcean instance, instead of taking the instance offline however I used the instructions here: https://techbits.io/mastodon-4-upgrade/#compilation-failed to create a 4GB swapfile. If you don't want to take your instance offline or upgrade its specs just because of migrations I recommend this route

Here are the instructions from techbits in case something happens to that blog post one day:
```sh
sudo fallocate -l 4G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
```
Make sure to run them as root not as `mastodon` user if you are using the 1-click DigitalOcean app

**Comment by nightpool** [comment]
We primarily use GitHub as a bug and feature tracker. For usage questions, troubleshooting of deployments and other individual technical assistance, please Github Discussions, Discord, or Mastodon itself

Feel free to continue the discussion of the issue here, but I'm going to be marking the ticket as "closed". This won't affect your ability to comment on it, it's just a reflection of the fact that it's not a defect in the mastodon software, just a problem with your individual deployment.

**Comment by JetForMe** [comment]
At the very least, it's a defect in the docs and output of the upgrade process: it doesn't say it fails because it's out of memory, making it very hard to figure out how to solve the issue.
