### ISSUE TITLE
Replacement UX Project

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#11429]
The UX is 70% good enough.... but I'd love to see a community or official project to give Mastodon enough refinement to get the rest of the way

I think it's pretty universally known that UX in FOSS is just pretty bad and we should get the task to designers and professionals to make something amazing.

I mean 3.0 is coming up soon but maybe something to aim for 3.5?

**Comment by CitrusFruits** [comment]
I don't think the UX is perfect, but I also certainly don't think it's worth entirely replacing. I have my own thoughts on what needs tweaking, but could you be specific in what you think is bad about the UX?

**Comment by Shleeble** [comment]
There are plenty of talented UX professionals, and I'd love to see them given a chance to push us over the edge.

It might be worth raising all of the things I think we could improve tho as examples.

**Comment by Shleeble** [comment]
https://www.behance.net and https://dribbble.com/

has some awesome examples if you search for twitter concept or twitter redesign

**Comment by Gargron** [comment]
I have studied a lot of prior art on these sites when coming up with Mastodon's design. A lot of things on there are outright impractical, like making profiles "pretty" by forgetting that bio text, links, locations and header images exist.

**Comment by Shleeble** [comment]
This is one of those things... it's not something for tomorrow, but it's definitely something "we" should consider for the ideal of reaching and supporting a mass audience....  and yeah. Yeah. you kind of need to set your requirements before you hire people to generate new designs.

I might put my money where my mouse is tho and expand on this... maybe we'll see

**Comment by CitrusFruits** [comment]
I was mostly asking because I was curious if you personally had anything in particular in mind, since I have a few ideas myself.

I guess I might fall into that category of "UX Professional", although not in the designer sense; I work as a software engineer/tech lead for a web component framework. I love the idea of Mastodon but I too have noticed some shortcomings of Mastodon's UX that really set it back from the polish of for profit social networks and other general web apps. If you'd like to see my list of first impressions on the Mastodon UX and what some tweaks would be I'd be happy to share.

I'm trying to figure out how to get involved, but this is my first foray into the world of open source and I'm a little unsure on how to contribute. I can write code, but addressing anything in the UX through a PR would be a moot point unless there is a clear direction.

**Comment by Shleeble** [comment]
UX is a weird beast.. and some of the complaints already have tickets...

* notifications don't group.. I don't need 25 notifications for 25 likes #11297 #7698 #9182
ETC

**Comment by CitrusFruits** [comment]
@Gargron are you the one who ultimately makes design calls in for Mastodon? While I think @Shleeble is a little unclear on what he's advocating for other than general UX improvements, I don't think that's reason enough to dismiss the idea of discussing UX entirely. I mean, off the top of my head, there's already a couple of things I see in the app that could be addressed _without an entire redesign_.

- Buttons don't have an "active" state (or at least don't have one any different than the hover state)
- Instances of contrast ratios being too low (#11420)
- The same icons are reused for different concepts in the right nav (Local/Follows and followers, Lists/User generated lists)
- "Logout" is in an unconventional place

Additionally, there are a couple more subjective things: there's some information hierarchy issues in the preference page, the "Boost" icon looks like retweet even though the underlying language is different, and in general I think font awesome should be ditched because of its dated aesthetic.
