### ISSUE TITLE
Do not set a cookie on non logged-in client (European law)

### ISSUE THREAD

**Issue by Exagone313** [mastodon/mastodon#1181]
Hi,

When a client visits any page of Mastodon (even *about* pages), a cookie is set. This violates a [European law](http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm) (that may be stupid, but it's not the issue to discuss here) that says to ask a user *before* setting a cookie (!= setting cookie and say we have set a cookie).

As I understand it, setting a cookie on the remote follow page *when submitting form* is acceptable, but not when simply visiting *about* pages, profiles, posts. Of course when logging-in, it's needed and accepted.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by SethMichaelLarson** [comment]
Shouldn't this be a thing that only instances hosted in Europe care about?

**Comment by Exagone313** [comment]
Note that the main developer seems to live in Europe, so he is concerned too.

**Comment by nicolasblanco** [comment]
The EU laws about cookies clearly *excludes* from consent cookies set for user‑input cookies (session-id) and authentication.

This is written here: http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm

Mastodon uses the default Rails `session_id` cookie which is used only for session control and is not under the consent EU law.

**Comment by Exagone313** [comment]
You are wrong, this cookie is unique to any visitor, logged or not.

**Comment by nicolasblanco** [comment]
@Exagone313 : of course this cookie is unique otherwise you could still the session of another user, that's the main use of a session cookie! As said, session cookies does ***not*** fall into the EU law.

The cookies which fall into the consent law are cookies provided by 3rd parties (like if you use a tracker from another company or stuff like that).

**Comment by SethMichaelLarson** [comment]
From the document it looks like `session-id` cookies need to be used to track user input. I'd have to agree that "visiting" a website isn't "input". Just because the cookie being named "session_id" doesn't mean it conforms to the definition provided in the document.

**Comment by nicolasblanco** [comment]
The Rails session_id cookie is only used to be attached to forms to track user input and does not fall into the EU law.

But the main mastodon.social web site also puts a Cloudflare cookie (cfuid). This cookie may fall into the EU law as it is a 3rd party cookie. But the other cookies are of course up to the instance owner...

**Comment by Exagone313** [comment]
@nicolasblanco Please clear your cookies and visit /about or /about/more or any public page, and let me know if you have entered any input to get a cookie on each of these pages.

**Comment by Gargron** [comment]
This is default behaviour of Rails. I do not believe that such cookies fall under the EU law, as it is not a cookie meant to track you *across* different websites.

First time I hear about the Cloudflare cookie (I haven't noticed). I only use Cloudflare in front of static assets. This could be problematic, but I have not heard of the cookie law being applied by anyone.

**Comment by nicolasblanco** [comment]
@Exagone313 

please read Chapter 5 of the EU law: http://ec.europa.eu/justice/data-protection/article-29/documentation/opinion-recommendation/files/2012/wp194_en.pdf

Read again the law and tell me where it is written that the user MUST do some input or MUST be authenticated for a non-consent cookie to be set? All right, it is never written 👍.

The Rails session cookie is set to detect authentication abuses and security (used against CSRF) for **every** user, authenticated or not. Because CSRF protection has to be enabled for every form and every users, not only logged or authenticated ones. This is why the cookie is set on every page.

The Rails session cookie falls into the 3 first points of the EU law below, it is used for point 1 (session_id), point 2 (authentication) and point 3 (security).

**Comment by Exagone313** [comment]
What prevents the CSRF token to be put in an input hidden field?

**Comment by nicolasblanco** [comment]
@Gargron : IMHO, you should not do anything because like you say it is not applied. See those articles: https://silktide.com/the-stupid-cookie-law-is-dead-at-last/
and also:
http://www.theinquirer.net/inquirer/news/2455454/eus-ineffective-and-annoying-cookie-law-to-be-reviewed

@Exagone313 : this is also the case. It seems that you don't know Rails, which is the framework used by Mastodon. Like said, this is done and managed by Rails, it cannot be disabled without opening a lot of security issues. If you have any problems with that, please look at: http://guides.rubyonrails.org/security.html
As said several times, cookies used for security purposes are not under the consent EU cookie law.

**Comment by Exagone313** [comment]
As said before, not having a form the page does not require any security-related cookie.
The law applies whether or not you use X or Y framework/library.

**Comment by nicolasblanco** [comment]
@Exagone313 : 

It seems you have not read the law. They do not speak about the technology but only about the goal of a cookie to decide whether the cookie falls under the law or not.

So let's recap.

What is the goal of the Rails session cookie? It is about security (P3), auth (P2) and session (P1).
Is it a 3rd party cookie? No. Is it used to track the user across several sites? No. It's not under the EU law. Final point, end of debate.

**Comment by nicolasblanco** [comment]
@Gargron : about the Cloudflare cookie, it is third party but its goal is security and load balancing, not tracking or advertising. So I would say it does not fall into the mandated consent current EU law.

**Comment by Exagone313** [comment]
Please tell me how is it about:
1) Security, when there is nothing to deal with security when visiting a website, as in clicking links and scrolling only
2) Authentication, when logged-in
3) User input, when no form on the page

**Comment by Pajn** [comment]
The goal of the cookie does not matter, the user must have given it's explicit consent. An explicit consent for the cookie is not needed if it's technically necessary to deliver a feature that have been explicitly requested by the user. So a session cookie is fine if the user logs in as you must have that to keep track of the user, but it's not fine to set a session cookie if the user has not logged in because
1. The user have not taken any explicit action
2. It's not technically necessary (being a limitation in you chosen tech stack is not the same as necessary).

However I would be very surprised if it is not possible to turn of the session cookie for users that are not signed in. It's a major flaw that should be reported to rails in such a case.

**Comment by Exagone313** [comment]
To fix this issue, you need to check if a session exists before setting a cookie, on a page where a cookie is not necessary. Apparently with rails, it's not like that by default, that means Mastodon explicitly saves some information about a user at this point.

**Comment by nicolasblanco** [comment]
@Pajn : I've just read again *5 Summary and guidelines* of the EU law. I still don't see where it is written in the law that a session MUST be authenticated or a session is only begun when the user has validated his consent.

In Rails the session cookie is put all the time, because it has nothing to do with the logic of being authenticated or not. The session is considered the time the user stays and navigate on the same site, it is separate from the logic of being authenticated or not, which is business logic.

If I remember correctly, the main reason Rails always initializes one session cookie is to reuse the exact same CSRF and security tokens for the time the user stays and uses the site.

Where do you see in the law that a session means the user is authenticated or that the user must have submitted some input to be considered in a session?

**Comment by Exagone313** [comment]
We're confused about two types of session: client-side session (the time between the browser is opened and closed) and server-side session (indexed by a unique token stored in a cookie). In the law, it's about the first type, and I've been using this term as in the second type.

**Comment by Pajn** [comment]
@nicolasblanco 
The law doesn't mention sessions, cookies, tracking or even computers. It's totally technique neutral (at least the Swedish version, every country must implement the directive as a law by themselves so it can vary a bit).
The law only mentions explicit consent, or implicit consent if storing data is necessary to deliver a service that the user have explicitly requested.

Sure, the law is stupid (it is) and there are so many pages that do not follow it so the risk of being noticed is virtually zero so it could go unfixed and we'll probably never hear a word from anyone. But in Mastodons case there is no reason not to follow it. There is nothing that needs the session before you sign in (maybe remote follow, but that's an explicit action as well). However if this is not easily fixable so that Rails only sends a session cookie it there are data in the session object I think that's an issue that should be reported and fixed first. Every Rails app in the world should not need to go through a lot of hoops to be able to follow the law in a whole continent.

**Comment by Exagone313** [comment]
@nicolasblanco See Art. 32 (especially II.) on [this page](https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000886460&categorieLien=cid) (FR).

**Comment by Exagone313** [comment]
I submitted this issue so that instance owners can install Mastodon serenely. I don't want to bother you. I want to help you. I personally don't like to be out-of-law, as I run a (private) instance, even if I shouldn't be sued (may not be the case for a bigger instance, with someone wanting to hit Mastodon).

**Comment by sjalander** [comment]
This remains an issue, with Mastodon setting at least 2 cookies without an active login session. Simply browsing Mastodon causes this.

As previously stated, this is against EU regulations and limits the usefulness of Mastodon.

For example, I need to move away from showing my X (twitter) feed on my website to something else just because of this issue, and I was hoping that Mastodon would be the solution. With the current situation it obviously is not.

**Comment by mjankowski** [comment]
Last relevant update here is ~8 years old ... going to close this on the assumption that we are going to continue using rails default cookie behaviour for the foreseeable future.

I am not a lawyer and I have never baked (legally speaking) any cookies.

**Comment by Exagone313** [comment]
My view on the topic has changed, I think unauthenticated sessions are fine if you can prove that it is not used for unlawful tracking and from my understanding it's not the case here. I'm still not a lawyer though.

There are many cases of abuse around user data going on right now that should be fought against and I think that Mastodon is not our enemy here.
