### ISSUE TITLE
"Block direct messages from people you don't follow" is a mute, not a block

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#11882]
A friend and I just did some testing of the "Block direct messages from people you don't follow" feature. There are multiple problems we discovered which could be resolved as part of a single fix.

## Problem

First off, a minor thing, on mastodon.social specifically the feature is in a surprising place— it is under Preferences->Notifications despite not being specifically a notifications feature (direct messages are blocked in multiple parts of the interface, not just from the notifications column). I was not able to find the checkbox myself at first.

**My main issue**: The feature acts more like a mute than a block. (This is the case despite the fact the setting uses the word "block", and "block" and "mute" are both verbs in Mastodon.) A user X may DM a user Y who has "Block direct messages from people you don't follow" turned on. The only effect of the checkbox is that any DMs sent while the checkbox is on will be hidden from user Y's view. User X will not know their DM went into a black hole.

A third, more minor issue: If a DM has been hidden by the checkbox, if the checkbox is later un-checked, the DM from the checkboxed period stays hidden (except for the #9424 loophole). This is a surprising behavior.

The above issues are separate from #9424.

## Proposed fix

In **addition** to the current hiding behavior, user profiles could publish a flag for "you may only DM if I am following you". This would allow Mastodon instances to check for the flag before sending a DM, and if the flag is present AND the instance does not see that target user is following, display a warning or prevent sending the message.

Because of federation, nothing at the protocol level would stop a user from sending a DM anyway, but because the hiding would still apply the DM would not get read (and since the user is disregarding a clearly marked sign, there is no sympathy for them getting killfiled).

## Motivation

"Block direct messages from people you don't follow" is a good feature. Abusive users can be more abusive in DMs because there is less third-party visibility of their abusive acts. High profile accounts can receive uncomfortable or overly-friendly DMs from well-meaning strangers.

Let's say we don't care about the feelings of abusive users. But in the case of a well-meaning user who is simply overstepping a personal boundary, the hiding behavior is a problem. A well-meaning user X has no idea that user Y would prefer to not receive DMs from people they don't know, and they don't know that their DM was never received. User X might think user Y is ignoring them, or being rude. User X might send user Y an important question and interpret silence as a negative answer. User X might continue sending multiple DMs to check to see if the first DM was received, wasting their time. And in a really pathological case, user X might send Y a DM, send Y normal message "did you get my DM?" to follow up, user Y might uncheck the nonfollower-DMs checkbox or follow X, but the message is still in a black hole, confusing everyone. All of these outcomes are bad and could create awkward social situations.

Giving X explicit feedback through the protocol that their DMs are unwelcome would avoid these first few awkward situations, and make the feature more fit the user expectations created by the use of the word "block".

The protocol-level public flag would also solve my third "minor problem"— even if the current behavior stays and messages sent under DM interdiction are permanently lost, *this would become expected behavior because* (barring race conditions) *the DM was breaking a clearly advertised rule*.

**Comment by huitema** [comment]
I saw the same point raised [in a recent discussion](https://federate.social/@mattblaze/109400609570243324). Users do have an ability to "Block direct messages from people you don't follow", but _"unfortunately that turns out to be the worst of all worlds. It just silently drops them at the receiver side without any indication to the sender."_ 

Issue #9424 attacks the same problem from a different angle, by complaining that while the intended recipient did not see the DM, the DM is still visible in the context of the sender, leading to inconsistent views. The point here is different: there should be some kind of feedback to the message sender, which could be:

* before posting the message, get warned that "recipient is blocking incoming DMs and will not see your toot", or,
* after sending a message, get some kind of notification that "your direct message was not seen by the recipient."

There is a related issue with "mentions". If an account is blocking notification from people they don't follow, mentions by third parties will not be notified.

Of course, any solution to that issue will need to consider the effect of spam and other DOS attacks. Suppose an account is being bombed by spam messages, or spam notifications. It is probably not a great idea to send explicit responses to each an everyone of them.

**Comment by simon-frankau** [comment]
If there is interest in this feature, I would be keen to work on it. I can imagine many users of "Block DMs from people you don't follow" would prefer to let people who want to send them DMs know that they can't, rather than just black-hole.

To work on this, I'd want to know:
 * If such a contribution is likely to be accepted.
 * Which approach to take (pre-emptive warning vs. bounce message).

I imagine that, apart from race conditions, the "check before send" approach is simpler than a bounce, since, as mentioned above, bounces need to cope with spam attacks, laser effects etc.

What's the best way to get clarity on the above so that I or someone else can move ahead with implementation?

(Or is this not how it's done? https://github.com/mastodon/mastodon/blob/main/CONTRIBUTING.md seems to suggest this approach might work, but I've not contributed before.)

**Comment by mikekasprzak** [comment]
> In addition to the current hiding behavior, user profiles could publish a flag for "you may only DM if I am following you". This would allow Mastodon instances to check for the flag before sending a DM, and if the flag is present AND the instance does not see that target user is following, display a warning or prevent sending the message.

I would recommend that this concept of blocking goes further up the stack, to the ActivityPub protocol.

I run a web service that I'd like to connect with the Fediverse, and one thing we don't want (or need) is DMs. Rather than violate the request of the sender for their comment to be private, or quietly throwing them away, I'd rather the sender knew we don't accept private comments.

**Comment by mcclure** [comment]
The "Block direct messages from people you don't follow" feature has now been entirely removed and replaced with a new "Filter notifications" feature. However, I still think the proposed feature in this issue (an ability to hard cut off DMs from people you don't follow, and notify those users that their DMs will not be received) would be a good one. I don't know whether to rewrite this feature or to close it and file a new one.

**Comment by trwnh** [comment]
a new issue would be best, yes.

**Comment by mcclure** [comment]
As suggested, I [posted an updated version of this feature request](https://github.com/mastodon/mastodon/issues/29722).

**Comment by MzTea1** [comment]
Blocking
