### ISSUE TITLE
Trends not visible on mobile browsers

### ISSUE THREAD

**Issue by MoiraPrime** [mastodon/mastodon#12043]
![image](https://user-images.githubusercontent.com/11623577/65994407-d303b000-e458-11e9-9657-9a2030cfcece.png)

### Expected behaviour

Expected trending hashtags to show in generally the same place they do in the desktop UI

### Actual behaviour

Trends do not appear at all.

### Steps to reproduce the problem

1. Open mobile browser
2. Log in to your Mastodon instance
3. Click "Get Started" or the hamburger menu, whatever you want to call it.
4. Trends do not appear.

### Specifications
v3.0.0rc2

Tested on both Google Chrome and Firefox Preview for Android

**Comment by distel-f** [comment]
Trends are also invisbile on small screens, because there's no way to scroll down to see them. If your screen is not high enough you just don't see them. 

tested in firefox + chrome on mac

<img width="364" alt="Bildschirmfoto 2019-10-14 um 09 54 20" src="https://user-images.githubusercontent.com/56404892/66736290-156db980-ee69-11e9-8579-2fd12ef9f405.png">
in this screenshot you can see how the last column looks for me with my browser window the maximum size on my 13 inch computer screen. next I hide the toolbar and bookmarks bar of the browser so that there is more room for displaying the website and it gives me a glimpse of 1 trend: 

<img width="371" alt="Bildschirmfoto 2019-10-14 um 09 54 57" src="https://user-images.githubusercontent.com/56404892/66736378-4948df00-ee69-11e9-938d-7242ac329063.png">

I'm not sure if this warrants opening a new issue, so I'm leaving this here.

**Comment by UberActivist** [comment]
I think this is closely related to my other issue #12042

**Comment by distel-f** [comment]
> I think this is closely related to my other issue #12042

yes, I think it's the same problem!

**Comment by Cassolotl** [comment]
*Not all hashtags are shown on a smaller screen < 1080p #11565*

**Comment by Gargron** [comment]
I think this is a different issue, @Cassolotl, and I think this one might be resolved. On mobile, you can browse trending hashtags under the Explore screen.
