### ISSUE TITLE
Change the post character limit to 1,000 characters

### ISSUE THREAD

**Issue by elaine-jackson** [mastodon/mastodon#12223]
### Pitch

You can use up to 1,000 characters for the alt text in an image on Mastodon. That said I think we should make the post text limit the same by changing it to 1,000 characters. 

### Motivation
This would make the alt text for images and post limits consistent with one another.

**Comment by trwnh** [comment]
posts are currently 500, bios are currently 500, image descriptions are currently 1500. i don't think it's strictly necessary to make these numbers all *consistent*, since they serve different purposes.

**Comment by Cassolotl** [comment]
Also it's admin-configurable, so one could ask their admin to change it, or they could move to an instance with a higher character limit.

**Comment by nsuchy** [comment]
> Also it's admin-configurable, so one could ask their admin to change it, or they could move to an instance with a higher character limit.

What happens if I make an instance with a 10,000 or 100,000 character limit when it federates with other instances? Could a rouge instance spam the feed that way? Would the only recourse be to block the domain from federating?

**Comment by trwnh** [comment]
sites with 100,000 character limits already exist. sites with no character limit exist. currently, long posts are collapsed in timelines once they exceed a certain height.

as far as what the *default* should be, 500 makes about as much sense as any other arbitrary cutoff. that's already enough for a few short paragraphs. it's a soft default as it is.

**Comment by vviictor** [comment]
> Also it's admin-configurable, so one could ask their admin to change it, or they could move to an instance with a higher character limit.

How, where?

**Comment by indiealexh** [comment]
> > Also it's admin-configurable, so one could ask their admin to change it, or they could move to an instance with a higher character limit.
> 
> How, where?

You had to edit code at this time. A better thing would be to make it configurable via an environment variable or a admin setting.

**Comment by unknownconstant** [comment]
Mastodon is meant to be part of a federated ecosystem. If other servers or services are publishing content which cannot be produced from your local mastodon instance then there should be some sort of UI indication of this when Mastodon displays it in your feed.

As a user I found it confusing seeing very long posts in my feed, as an admin, I found it confusing there's no way to easily change this without recompiling. Changing the limits as a once off is ok, but to do this in production you're committing to editing and re-compiling every future release of Mastodon, obviously introducing problematic complexity and delays to updates.

I think there's a very obvious any easy change to use environment variables to customise this, the argument against hasn't been clarified past 'I like the number 500', which imo isn't particularly strong because you can still leave it at 500 in the variable.

**Comment by unknownconstant** [comment]
Yeah maybe thats what happened, either way it's still a confusing experience.

Maybe a healthy middle ground is to support having text or markdown as a media attachment, then the main text on the post becomes a subject / title. I guess you can do this already but you'd need to have an external blog already and seems intuitive for it to be in mastodon already

**Comment by volkriss** [comment]
Keep in mind that ActivityPub supports longer compositions like Article and Page, so when talking about federation it wouldn't be Mastodon breaking things by providing such content. Rather, Mastodon can expect to deal with longer content incoming and needs to not break.

The rest of this is personal opinion:
I see doing away with twitter-style threads by lifting the cap as being one of the major contributions Mastodon can make toward improving social media. When people are sending out a dozen posts in a row because they can't fit what they have to say in a single post, that's a failure of the tool to do what they need to enable thoughtful expression. It's always amazing to me that people tolerate it.

**Comment by volkriss** [comment]
> This is not a good default. Users frequently use multiple posts since they run into character limits. Those post then appear out of context in timelines.

I hate to say so, but FYI, many people actively prefer this, or at least prefer short posts so strongly that they'd accept those multiple posts in the tradeoff.

Many people feel that short posts are a core part of the user experience Mastodon is looking for, and long posts would ruin the experience.

It's not my preference, but I wanted to mention that side of the argument, as it explains why the character limits are still low by default. Many consider it a feature, not a bug, and they're the ones that would need to be convinced.

**Comment by foss-** [comment]
> Many people feel that short posts are a core part of the user experience Mastodon is looking for, and long posts would ruin the experience.

Can you share more about this user experience, were fragmented posts, that I often see from mastodon users ruin my timeline and create an urge to un-follow or block those users because following what they are trying to say becomes unnecessarily hard?

**Comment by trwnh** [comment]
> How is this feature request `Completed` when the default limit still is 500 characters?

github didn't differentiate between closed issues back then
