### ISSUE TITLE
Support more poll options (science says seven)

### ISSUE THREAD

**Issue by domi41** [mastodon/mastodon#12612]
### Pitch

[Majority Judgment](https://en.wikipedia.org/wiki/Majority_judgment) polling is a very elegant way of polling.  It's _kind of_ new.

The researchers recommend seven (7) as the number of options (they call them mentions).

A bot could rather easily leverage multiple polls to establish a majority judgment tally and opinion profiles.
That's what `@limaju@botsin.space` will be for. 
> (so far it's a spaghetti of test python code waiting to be straightened, put online and hooked to notifications to answer commands via direct messages)

### Motivation

Majority Judgment solves some of the critical issues the _single-member district_ (winner takes all) our universal suffrage is suffering from.  Social networks ought to have the finest deliberation tools available.  Finesse, nuance and subtlety are achieved by giving more choice.

---

We've seen this talked around, but did not see any definitive response about it.
Sorry if this already has been answered, at least now people searching for "more poll options" will find it.

**Comment by Cassolotl** [comment]
There's *Make number of poll choices configurable #10609*, which is similar?

And for those who are choosing instances for personal accounts I'm pretty sure instances running the Glitch fork have more poll options available.

**Comment by openscience** [comment]
Yes, 7 would already be an improvement...

**Comment by kolgza** [comment]
Personally, I think just going with approval voting would be the best, because it's both simple and easy to implement, and also incredibly effective as a voting system.

Actually it's what Telegram messenger uses for it's polls.
![image](https://user-images.githubusercontent.com/46303203/83276730-95f6e580-a1c0-11ea-98a1-679d95456ecd.png)

Here is more information about it from the [Center for Election Science.](https://www.electionscience.org/library/approval-voting/).

**Comment by kolgza** [comment]
I also don't 
\

**Comment by kolgza** [comment]
I also don't think it makes sense to have 5~7 possible scores for a poll when they're likely aren't going to be more than a few candidates. Even if the maximum number of were to be increased, I doubt that there would be many polls that have more than 5 or 6 candidates.

**Comment by kolgza** [comment]
As it turns out. Mastodon already supports approval voting. It just wasn't obvious.

#13944

**Comment by domi41** [comment]
Approval Voting is a special form of Majority Judgment with exactly two grades : _Approve_ and _Reject_.
It would also be a good step forward and I'd like that, especially since the UI can be tailored in the clients as you showed in the previous screenshot.  Do you have insight into why both raising the cap and allowing Approval Voting cannot both be done ?  Can there be multiple kinds of Polls (uninominal, like there is now, and majority judgment with N grades → approval voting for N=2, for example) in ActivityPub ?

Any insight into all this would be greatly appreciated.

> I also don't think it makes sense to have 5~7 possible scores for a poll when they're likely aren't going to be more than a few candidates.

I (we) have use for polls with more than 13 candidates, when using Majority Judgment, and for even more when polling on European Elections.  In the context of that many candidates, the range *Excellent*, *Very Good*, *Good*, *Acceptable*, *Poor*, or *Reject* feels more subtle and appropriate than only *Accept* and *Reject*.

**Comment by kolgza** [comment]
I suppose that there is no reason to not implement score voting, or majority judgement, or STAR, or any other cardinal voting system.

The thing is that I just think that approval voting is the best system. Despite being much less expressive than any other voting system, it still tends to elect the Condorcet winner. The only *real* problem I have with it is the fact that it doesn't satisfy the later-no-harm criterion.

I also just feel like more expressive electoral systems are more susceptible to strategic voting.

---

> Any insight into all this would be greatly appreciated.
> > I also don't think it makes sense to have 5~7 possible scores for a poll when they're likely aren't going to be more than a few candidates.

This... was based on a misconception that I had—where for some reason, I thought that it didn't make sense to use score voting unless the number of candidates was greater than or equal to the number of grades. In other words I didn't think that using score voting made sense unless there were at least *n* candidates.

I actually now think the opposite is true—as the number of candidates increases, it makes less sense to use expressive ballots, because of the increased difficulty of filling out a ballot.

**Comment by kolgza** [comment]
Anyway, approval voting was already implement, and I think it's a very adequate voting system. I only wish it was the default (and that the number of potential candidates was higher).

**Comment by emmetoneillpdx** [comment]
While it's really great that approval-based polls are a thing in Mastodon, I'd also like to show my support for adding a separate **preferential voting system** option. Here are some reasons why I think ranked polls are also worth including:

- Preferential voting systems force (in a good way) the voter to either specify the order of their preference (as in ranked-choice) or quantify the degree of their approval (as in STAR). While binary approval systems are definitely great at finding a popular consensus, they tend to treat the approval of two options as a statement of _equal preference_, which is rarely if ever the case.
- With approval voting, a voter who approves of all the options is not moving the needle in any direction, which is effectively the same as not participating at all. With preferential systems this is either impossible (RCV) or less likely (STAR).
- While some polling questions lend themselves better to approval voting (for example, "what do you want for dinner tonight?"), other questions in my opinion lend themselves better to preferential voting (for example, "what is the best N64 game?).

At any rate, I don't want to start a debate here over the effectiveness of approval voting systems vs preferential voting systems, because I believe that both have their place, with well-understood strengths and weaknesses. It's already a great thing that approval polls are supported, and I think it would be even better to support ranked polls as well.

[Implementation note: A think a relatively nice user experience for voting in ranked polls would be to have the user sort the various options using drag and top, where the top represents the most preferred option and the bottom the least.]

[Also, as an aside, I think the maximum number of poll options should be made higher. There may already be a separate issue for this, but 4 max options is too few...]

**Comment by JorgeStolfi** [comment]
Please see #23295.

**Comment by sudarkoff** [comment]
Just wanted to add my voice to this. Likert scale is very common in polling and it requires at least 5 options.

**Comment by indigoxela** [comment]
If this were a poll (:stuck_out_tongue_winking_eye:) I'd also vote for more options.

But not configurable per instance, which - to my understanding - could lead to problems across Fediverse instances, but a higher limit for MAX_OPTIONS by default. This request seems to pop up regularly, and it seems relatively easy to implement. I'm not qualified to provide a PR, though.

Seven seems like a very good compromise to me.

More sophisticated polls, as also suggested, should IMO go to a separate issue, as it may require more effort to implement, and more discussions about what and how.

**Comment by grinapo** [comment]
> Just wanted to add my voice to this. Likert scale is very common in polling and it requires at least 5 options.

Or multichoice which needs at least one additional option "none of the above", otherwise the vote isn't counted.

I shall go to the source and try to find the limit......

**Comment by bantryblues** [comment]
#10609 is a much simpler issue that seems to have been forgotten.  It is to just increase the number of options.  

Glitch-soc already does that. 

 there are also instructions on the web for how to change it in Masodon instances with small changes to two files.  They have to redo it every time they upgrade. 

https://qa.mastoadmin.social/questions/10010000000000001/how-do-i-increase-the-number-of-options-available-in-a-poll-on-my-mastodon-instance

why not do the simple fix now while continuing to look at this one?
