### ISSUE TITLE
View other users feed.

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#12811]
I'd like to be able to see the mastodon feed of the people (All of the people they follow).
Obviously not including the locked accounts.

**Comment by trwnh** [comment]
there's a lot of problems and limitations to this:
- people can choose to hide their network
- even if they don't, you will only ever know accounts local to your instance (the info is incomplete)
- if you want to fetch their network from the origin instance, you will require an OAuth token with read:accounts scope from that instance instead of yours

**Comment by Gargron** [comment]
GNU social had an option to view anyone's home feed and I felt it was very stalkerish and intrusive.

**Comment by Shleeble** [comment]
Twitter had the option for a while and I was a HUGE fan.. great way to find new people to follow by spending a little time in other peoples timelines

**Comment by trwnh** [comment]
>I felt it was very stalkerish and intrusive.

Somewhat unrelated but I would add that features like this also incentivize(d) me to push for hiding your network in more ways. Contact address books should not be presumed to be public knowledge by default.

Creepiness aside, it still has the technical limitations mentioned above. I think the best you will get in this regard is to write a third-party app, because it doesn't really make sense for Mastodon as a native feature -- Mastodon clients fetch data from their local instance. Your app will have to extract the domain from a user's address, register itself as a client of that instance, obtain an OAuth token, request that user's following list, and then request the statuses of each of those users in order to construct a timeline. It would also be computationally expensive depending on the number of users followed and how many statuses you want to fetch from each. There's no easier way to do it unless you're proposing e.g. an extension to the Home Timeline API that lets you fetch any arbitrary user's home timeline without authentication... which is a total non-starter.
