### ISSUE TITLE
/ partition going full even after media remove

### ISSUE THREAD

**Issue by Korbak** [mastodon/mastodon#13121]
Hi,

We run an instance since a couple of years now on a Debian virtual sever, and we can't get over our frequently 100% full storage. We kept scaling our /home and running `media remove` and `media remove-orphans`. This time, it doesn't make it.

Our /home is 89% full (60Gb), but our / is now 100% full (on 20Gb).
We don't know what to do next. Is this just a scaling problem, or is there any secret rake we don't know about?

We can make our / bigger, but we need to know id it's really all of it, or if there's anything we can clean to limit the size of the used storage.

Thanks a lot for your work and help :).

**Comment by ThibG** [comment]
It looks like the database itself is growing too large now. There are two things you might want to do about that:
- cull remote accounts that do not longer exist (`tootctl accounts cull`)
- remove old remote statuses from your database: `tootctl status remove` will remove old statuses (by default older than 90 days) that haven't been faved, boosted, or bookmarked by local users, and don't have replies (this condition is a bit weird and makes it so that running the command multiple times will possibly remove different statuses, but eh). By default it doesn't remove statuses from followed accounts, but that can be changed too.
