### ISSUE TITLE
Text input field and emoji selection in dark mode have a white background

### ISSUE THREAD

**Issue by powerriegel** [mastodon/mastodon#13258]
Dark mode is not fully dark on mastodon. Emoji selection is affected, too. 

### Expected behaviour

The text area should be dark, too

### Actual behaviour

it has a white background

### Specifications

Firefox 74 on Ubuntu 19.10

![Screenshot_2020-03-13 gruene social](https://user-images.githubusercontent.com/11870663/76661976-09536880-657d-11ea-8a41-ed68781cdada.png)

**Comment by unbeatable-101** [comment]
Oof, was just going to report this, but it is a year-old issue, maybe I'll take a crack at it.

**Comment by powerriegel** [comment]
It does not seem anybody is interested in this.

**Comment by ShalokShalom** [comment]
Yep. I am annoyed by this too. You can use Darkreader, to fix this. Respect, that it is in the "global dark list" so you have to activate it yourself. 

I urge this to be resolved, since using DarkReader adds up render time. 

![image](https://user-images.githubusercontent.com/6344099/191206778-f20de7f0-a07f-4474-adc3-06fd0eddc702.png)

![image](https://user-images.githubusercontent.com/6344099/191206856-630131e7-3ed5-43a5-b105-0b03c8029d8c.png)

https://github.com/darkreader/darkreader#readme

![image](https://user-images.githubusercontent.com/6344099/191207222-6dc685a7-1b3d-42f3-b2de-0852c775881c.png)

**Comment by Gusted** [comment]
> I urge this to be resolved, since using DarkReader adds up render time.

I prefer for Dark Reader to not solve this, given mastodon already has a quite good dark mode. So I've opened a PR to fix the compose form being light themed: #19205 (@ShalokShalom If that PR is rejected, I will opt-in to make a Dark Reader fix).
