### ISSUE TITLE
Transferred my acct but my follower count is showing 68, should be over 800?

### ISSUE THREAD

**Issue by misslysinyc** [mastodon/mastodon#13525]
hey all. Had to transfer my acct due to targeted harassment &malicious reporting on an unmoderated and unsupported instance since the people running it refused to help me despite numerous reports of posts doxxing me and emails to ask for assistance etc. was eventually told the instance is “community moderated” and nobody does support / reviews reports / removes restrictions / enforces TOS etc so I chalked my old acct up as an unrecoverable loss and made a new one to transfer to. Was expecting my followers to be transferred to my new acct and visitors to old acct redirected. Unfortunately this hasn’t been the case. New acct is displaying a follower count of only 68 when it should be over 800. When I click to look at my followers they’re all there but it is very detrimental to me that visitors think I have only 60 something follows as this is my business acct and that undermines my credibility significantly. I am concerned my followers are not actually seeing my posts as afew have reached out via email to ask me why my old acct is inactive, this seems to imply the redirect is also not working... There seems to be no option to simply import my followers directly, which I understand, I’m hoping someone can help me resolve this issue as I am not very familiar with the platform and may have simply overlooked a potential fix. Thank you!

**Comment by Gargron** [comment]
If upon browsing your followers list you can see that all (or close to) 800 followers are there, then be rest assured, they receive your posts. The "redirect" has no impact whatsoever on who receives posts. The followers number is a cache and as such can be wrong sometimes, it's unusual that it would be this wrong but there's been similar reports.

If your new admin is cooperative, the number can be fixed by running `tootctl cache recount accounts`.
