### ISSUE TITLE
Switch to Alpine or Buster Slim Docker images

### ISSUE THREAD

**Issue by killua99** [mastodon/mastodon#13747]
### Pitch & Motivation
Lets start with the point that is not about size, is about the whole ecosystem. Alpine Linux are meant to start with just the necessary package to boot the minimal requirements to use Linux and from that point install and compile your apps base on what you need nothing more nothing less non extra library than Mastodon wont need to execute.

Thats it, you will get a smaller image because of it, unnecessary libraries or apps | packages wont be there. If a library from Ubuntu LTS get a security issue we will need to compile again the image for an external non Mastodon related library. That's the key advance of been using Alpine or slim images. We will care only about security issues about Mastodon libraries related.

Docker is different than using a VM structure it provides certain layers of networking and how it interact with the host that make it strong for deployments and stability.

With a simple `ps aux` using Ubuntu LTS vs Alpine you will get my point.

Alpine seems to be more solid solution for Docker use than Ubuntu LTS.

**Comment by SuperSandro2000** [comment]
```
$ docker run ubuntu:focal
root@9f7384f1dd5a:/# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1 15.0  0.0   4108  3408 pts/0    Ss   10:49   0:00 /bin/bash
root         8  0.0  0.0   5880  2892 pts/0    R+   10:49   0:00 ps aux
root@9f7384f1dd5a:/# exit

```
$ docker run alpine
/ # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 /bin/sh
    6 root      0:00 ps aux
/ #
```

I don't get your point. Could you elaborate?

My experiences in the past with Ubuntu vs Alpine and some questions:
Big projects like Mastodon which use more than a few external libraries gain not much by switching to Alpine. They pull so many packages and libraries in that in the end we only save a tiny amount of packages and build time increases.
Python projects lose a lot of pre-compiled wheels. Is that the same with gems?
Jemalloc can improve performance drastically especially for big instances. Are we sure we want to lose this?
The entire ecosystem is more well tested with glibc and Debian/Ubuntu than Alpine. There may be bugs with musl we don't even know about now.

**Comment by Wonderfall** [comment]
Hey @killua99, SuperSandro2000 made a good point: for a project as huge as Mastodon with tons of dependencies, Alpine doesn't make a big difference in the end. Sure, if you compare base images, Alpine will be significantly leaner, and thus a great choice for small to moderate softwares.

That being said, I still prefer Alpine in fact for the very reason it uses musl instead, which isn't as bloated as glibc and provides less attack surface, among other things. Plus, you'll still get smaller images, but there's not much of a difference if you ask me. I know it very well since I run my own Mastodon image based on Alpine since 2017; while musl is sometimes a source of incompatibility, it's relatively rare for modern softwares, and I can assure you it's not an issue with the stack Mastodon uses.

Having reworked some of my images recently (including Mastodon), I also made one based on the current one since I was very curious about the size gain. You can find it [here](https://github.com/Wonderfall/mastodon/blob/main/Dockerfile).

I also took some liberties while remaining conservative so it can be a drop-in replacement:
- Instead of [retrieving node](https://github.com/tootsuite/mastodon/blob/main/Dockerfile#L6-L26) manually, we'll just leverage the multi-stage build to provide a node+ruby image. Also no more compilation, we just get Ruby from their official image.
- Compiling GNU Libiconv is needed to ensure full character encoding capabilites for nokogiri. It works without it, but there has been issues in the past, so it's just precaution.
- We also compile Jemalloc since Alpine doesn't provide it anymore. I personally use Hardened Malloc since I don't care much about micro-benchmarks and RAM usage, but you have the choice.
- Node is updated to v14 since it's now [compatible](https://github.com/tootsuite/mastodon/commit/49814d579932496b52cd8f6a0194c21c21f83099). Streaming is fully working as of current main code.
- I couldn't make it work with the current Mastodon version, but I also managed to get Flóðgátt running well in the past. It had to be built from source since the binary provided works with glibc, not a big deal.
- I re-arranged the Dockerfile to be easier to maintain.

I share this Dockerfile for anyone who wants to try an Alpine-based image. I won't submit a PR, I use my own images and I don't want to be responsible for random issues which could be very well happening. On the other side, I've been using Mastodon on Alpine for 4 years now without issues related to it/musl.

Hope this insight helps the issue.

**Comment by Wonderfall** [comment]
> Why are you not using https://pkgs.alpinelinux.org/package/edge/community/x86_64/gnu-libiconv?

Well, I imagine I could! I haven't checked but back then, they didn't have a gnu-libiconv package, so that's good to know.

> Its not a micro optimization. It can decrease memory usage by 80 to 90% or Gigabytes which shouldn't be overlooked.
See for example https://storck.io/posts/psa-switch-ruby-docker-to-jemalloc-now/

I didn't say it's a micro-optimization, I talked about microbenchmarking. But I agree jemalloc has huge benefits in RAM Usage especially with Ruby, I noticed that too.

(I just don't care much about benchmarks and RAM usage personally. That's why I use hardened malloc instead which focuses more on hardening against heap corruption vulnerabilities. Yet I wouldn't ship it by default, jemalloc is fine for most people and allows them to run Mastodon without the need of a high-end server.)

**Comment by killua99** [comment]
Would be great to have a tag with alpine, not dropping the Ubuntu option to give more options to pick.

I'm gonna look your Dockerfile @Wonderfall I've been working with my own build and supporting Jemalloc and everything that the Ubuntu version does, also compiling for others architecture such amr64.

Is something that add more than value comparing the job it requiere

**Comment by killua99** [comment]
We could close this case, Ubuntu isn't use anymore, the process has been refined and the size lowered.

Altho it does feel an alpine addition would be great but atm, is out of scope.
