### ISSUE TITLE
Integrate GIFWY into Mastodon

### ISSUE THREAD

**Issue by koyuawsmbrtn** [mastodon/mastodon#13775]
### Pitch

Having a way to search and put in GIFs would be very nice and wouldn't need the now Facebook-owned Giphy or searching the internet for GIFs

### Motivation

https://mstdn.social/@stux/104177748100565477

**Comment by resynth1943** [comment]
GIFWY is available here: https://gifwy.com

I would love to see this. Ultimately, it creates an easy entry barrier into an open-source and privacy-conscious alternative to GIPHY, which is now owned by Facebook.

**Comment by mstdn** [comment]
Cool pitch guys! Gifwy.com is made with a simple WordPress script with some plugins. Maybe it would be a better idea to start this from scratch so we can build a dedicated API with a good working federation system :-) 

I'm open for all options!

**Comment by Andre601** [comment]
Perhaps another site could be https://gifbox.me ?
It's not federated, but at least it's not owned by any large company... Also no ads I guess and made by one of the Revolt.chat devs, so that's (at least for me) pretty neat.

But in general would I love to have a gif picker available for Mastodon... Or at the very least have links to Tenor posts render as actual gifs, if possible.

**Comment by vmstan** [comment]
GIPWY appears to have folded. There are other requests for native GIF support, closing.
