### ISSUE TITLE
ActivityPub ids with # symbol are not resolvable 

### ISSUE THREAD

**Issue by koehn** [mastodon/mastodon#13879]
### Expected behaviour

Per the [ActivityPub specification](https://www.w3.org/TR/activitypub/#obj-id), IDs must either be `null` or:

> Publicly dereferencable URIs, such as HTTPS URIs, with their authority belonging to that of their originating server. (Publicly facing content SHOULD use HTTPS URIs).

### Actual behaviour
Mastodon ids include information in the fragment (`#`) section, which renders the portion of the ID beyond the fragment symbol as unresolvable by HTTP-conforming libraries such as [libcurl](https://ec.haxx.se/cmdline/cmdline-urls#fragment).

### Steps to reproduce the problem
`curl -vH 'Accept: application/activity+json' 'https://mastodon.technology/@norztech#likes/836349#Like'`

`curl` (correctly) sends:
```
> GET /@norztech HTTP/2
> Host: mastodon.technology
> User-Agent: curl/7.64.1
> Accept: application/activity+json
```

**Comment by koehn** [comment]
Related to https://github.com/friendica/friendica/issues/8700

**Comment by nightpool** [comment]
These URLs aren't intended to be resolvable currently, yes. We created unique identifiers in this case to encourage compatibility with some other integrations that wanted Likes to be uniquely identifiable.

 However, i don't think saying that fragment URLs in general aren't resolvable is correct—to resolve an identifier like `https://cybre.space/users/nightpool#main-key`, you can fetch `https://cybre.space/users/nightpool` and then look for the object in the graph with the id `https://cybre.space/users/nightpool#main-key`.

**Comment by koehn** [comment]
You make a valid point, however multiple `#` symbols in a URL violates the URL specification; also the likes in question don't exist in the JSON returned.

**Comment by Gargron** [comment]
I think we only put one `#` into the IDs, not sure where the `#Like` in your example comes from as I don't remember putting it there...

**Comment by nightpool** [comment]
@koehn yeah, you're correct, the Likes in question are intentionally non-resolvable since we haven't built that, but we added a unique `id` for other apps that did want a unique identifier and didn't care about resolvability. I would recommend we either add a unique, resolvable route for a user's likes, or remove the id altogether (as recommended by the spec for ephemeral objects). 

One security concern that makes things a little complicated here is the possibility of enumeration. We definitely don't want to make user's likes enumerable. @koehn if the likes endpoint was unique, but returned a 403 for anyone except the user whose content was liked, would that work for you? (not saying we're going to build that, just wondering about your use-case)

**Comment by Gargron** [comment]
Null-IDs are not desired because then managing the undos becomes impossible if they arrive out of order.

**Comment by nightpool** [comment]
@Gargron it's stilo possible, but it does get slightly more complicated. I would do something like:

1. when you see a delete, DECR a redis key based on (type, actor, object).
  a. if the key = 0, delete the appropriate Like.
2. when you see a Like, INCR the same key.
   a. if the key = 1, create the object.

So if, for example, you get 3 deletes followed by 2 likes, you'll end up at -1, and never create a Like object.

**Comment by koehn** [comment]
My use case is this: 

1. There are users A, B, and C. Users B & C both follow user A. All are on different servers
    A. User A is on Friendica;
    B. User B is on Mastodon;
    C. User C is on my server. 
2. User A creates a `Note` and sends it to Users B & C. So far so good. 
3. User B likes the Note and sends a `Like` to user A. The like has a non-resolvable ID. 
4. User A's server receives the `Like` and attempts to federate it by sending it to User C, who is on my server.
5. Seeing that the `Like` is sent by User A (based on http-signature), but the `actor` is User C, my server decides not to trust that User A's message is valid, so my server tries to get it's own copy from User B's server. That doesn't work because the ID isn't actually resolvable. 
6. Here we are. 

Honestly the way that this gets federated is bizarre to me (it seems that User B's server should be sending the `Like` to Users A & C, but 🤷🏼‍♂️). But I haven't yet learned the nuances of how different servers deliver messages in ActivityPub.

**Comment by koehn** [comment]
FWIW this is a **lot** simpler in an object database.

**Comment by nightpool** [comment]
Hmm.... what is the audience of the `Like`s we're currently sending? I don't believe they're meant to be disclosed/retransmitted publicly like that.

**Comment by vpzomtrrfrt** [comment]
See also #13571

**Comment by mjankowski** [comment]
Is this still relevant in current server versions -- and/or, did the "I dont  think we generate values like that" aspect get sorted out here?

Basically ... is this still actionable, or basically just historical document at this point?

**Comment by trwnh** [comment]
i don’t think it ever was actionable

> Seeing that the Like is sent by User A (based on http-signature), but the actor is User C, my server decides not to trust that User A's message is valid, so my server tries to get it's own copy from User B's server. That doesn't work because the ID isn't actually resolvable.

this is a protocol-level issue for several reasons. on one hand, activities MUST have identifiers and they SHOULD be fetchable via HTTPS, but there are no guarantees here; a recent AP issue triage of null-id behavior concluded that null-id is incorrect jsonld and should never have been specified. what you *can* do is omit the id when your activity is transient, but this is generally never the case.

as far as trust and verification go, there are three options, and fetching from origin is just one option. the other options are to forward the object with an embedded proof, or forward the object with a `Forwarded` HTTP `Signature`. more generally, a lot of protocol work needs to go into either agreeing upon beforehand or otherwise negotiating supported verification mechanisms.

there’s also the issue that an Activity should not be forwarded unless it explicitly addresses a collection you own, and you allow this to be forwarded. for example, A sends a Create Note, B responds with a Like Note addressed to A and also addressed cc A’s followers. in this case, A might forward B’s activity to A’s followers, but A’s followers might want to verify the activity really came from B and wasn’t forged by A. this is out of scope of activitypub.

this kind of issue probably needs to be raised elsewhere. at most, mastodon could make activities fetchable, but there are valid reasons not to.

**Comment by nightpool** [comment]
I mean, we could certainly choose to LD sign Like activities and target them at followers, or make them resolvable, this isn't some sort of "there's no way to do this in the spec" issue. We just haven't for privacy / complexity reasons.
