### ISSUE TITLE
Support (and prefer) the matrix username format @user:domain.ext

### ISSUE THREAD

**Issue by sgryphon** [mastodon/mastodon#15012]
### Pitch

Current usernames look very much like an email address, or at least that they contain an email address, @user@domain.ext 

This would be a constant source of confusion, as people try to use the email address part, that won't work.

The format used by matrix is good for 'at' mentions, readable, and represents what people would expect for a social media handle, yet distinctly not an email address, @user:domain.ext 

### Motivation

Handles should look like what people expect for social media, and must contain a domain, but should not be confused with email addresses. The @user@domain.ext syntax also just looks ugly.

* Note that this is not about the internal ID, which for something like ActivityPub is a URI of some kind, etc, but the way that users are displayed in the UI, found, and referred to, etc.

* If a username contains ":", then it would need to be escaped (although it may be better to not allow it). Usually they wont ("_" and "." are often used in things like email, and also "+" for extra/ignored info in emails), but ":" is usually not seen (and would need to be quoted).  The simplest escaping would be something like using "\" as an escape character, with 2 escape sequences for "\:" and "\\".

* Legacy support would need to be maintained for the the existing format of "@user@domain.ext", as it is currently commonly used.

* The federated-social community is still in relative infancy, but growing fast. The earlier a change is made the better.

* There could be some confusion with actual matrix, i.e. trying to send a direct message to @user:domain.ext vs trying to mention in a post; or receiving a direct message vs receiving a post, both from @user:domain.ext.    Or receiving a direct message from @user2:domain.other and then trying to follow them and find they don't exist. 

Maybe direct message addresses (like matrix, or email), should remain separate?

I still like the matrix format much better than the double-@ format. And both are part of the Fediverse.

**Comment by ChlorideCull** [comment]
>I still like the matrix format much better than the double-@ format. And both are part of the Fediverse.

Matrix is not part of the Fediverse by most definitions, it uses their own protocol.

**Comment by sgryphon** [comment]
> Matrix is not part of the Fediverse by most definitions, it uses their own protocol.

I guess. They are only loosely mentioned on sites like https://the-federation.info/ and are chat-like, rather than blog-like.  But then again, Diaspora also uses a separate protocol, as do some other systems.  Plus there is some fair cross over as a lot of social media platforms have both blog like and direct messaging.

I do think their name format is nicer though, although maybe there is something else better.

**Comment by mkljczk** [comment]
Diaspora is usually not considered to be a part of the Fediverse as well

**Comment by waweic** [comment]
I understand your problems, although I do not think that this is a definitive solution:

* Using something different than the @-symbol to delimit the username from host info bugs me, because this is basically the literal meaning for "at"
* This is standard, we use it for everything, from JIDs to ssh-URIs
* I did not like when Matrix decided to go nonstandard, breaking support for bridges etc. and most URI handling libs (RFC 3986 specifies an @ to delimit the username from host information)
    - This was not even necessary, because Matrix states they even want to hide these adresses as far as possible
* This proposal does not fix the  problem, it just moves it to another domain, namely confusion with Matrix IDs (which are nonstandard)
* You say the double @-syntax looks ugly. I say that the "colon" syntax sounds ugly. (Compare "john at site dot com" to "john colon site dot com")

By the way, if Matrix is part of the Fediverse, E-Mail also is
