### ISSUE TITLE
Embedding posts and scrolling on their own

### ISSUE THREAD

**Issue by osapon** [mastodon/mastodon#15281]
### Expected behaviour

I don't want they to scroll.

### Actual behaviour

I embed a video post with audio, it seems to automatically scroll to the embedding location when the page is viewed.
Doesn't happen with images or videos that have no sound.

### Steps to reproduce the problem

These are no problem.
https://diary.osa-p.net/2020/11/blog-post.html
https://diary.osa-p.net/2020/11/mastodon-issue-2.html
https://diary.osa-p.net/2020/11/mastodon-issue-3.html

This is a phenomenon that occurs.
https://diary.osa-p.net/2020/11/mastodon-issue-4.html

### Specifications

Mastodon v3.2.0
Chrome 87.0.4280.88
Firefox 84.0b8
Checked at.

**Comment by Akkiesoft** [comment]
I have same problem.

https://akkiesoft.hatenablog.jp/entry/20201205/1607096581

## Specifications

Mastodon v3.1.4
Chrome 87.0.4280.88

**Comment by Akkiesoft** [comment]
There is still a problem...

I was create test page for this issue:
https://akkiesoft.github.io/mastodon-issue-15281/

Here is the capture. I was tested on Mastodon v3.4.3 /Chrome 96.0.4664.110@Mac.

https://user-images.githubusercontent.com/422590/148004267-b1986d7a-97f8-4871-816d-0a419752eced.mp4

**Comment by MitarashiDango** [comment]
This issue seems to be caused by calling the `HTMLElement.focus()` method inside React by setting the `autoFocus` attribute of the play button implemented in the video player to `true`.
https://github.com/mastodon/mastodon/blob/e0bdaeab657d9a320aaf506d98ca82d41e7bfdd5/app/javascript/mastodon/features/video/index.js#L620

Also, for posts embedded in other websites, I think you need not to focus on the play button.
Therefore, I think it is necessary to process to determine whether the post is embedded.

**Comment by Akkiesoft** [comment]
This problem remains in Mastodon 4.0.0.

https://akkiesoft.github.io/mastodon-issue-15281/test-maud-io.html

**Comment by Akkiesoft** [comment]
I built my own Mastodon server.

Then I deleted ```autoFocus``` and run server, the problem has been resolved and no other differences in behavior from the original can be found.

https://akkiesoft.github.io/mastodon-issue-15281/test-mugiko-moe.html

**Comment by Akkiesoft** [comment]
@ClearlyClaire added ```autoFocus``` in #12498.

I seem to this attribute inserts when a status embedded but causes this problem.
So I think ```autoFocus``` don't need in embedded status.

How about ?
