### ISSUE TITLE
Can't login Mastodon via Hidden services

### ISSUE THREAD

**Issue by yingziwu** [mastodon/mastodon#15310]
### Expected behaviour

Via Hidden service, Tor browser login normally.

### Actual behaviour

Tor browser can't log in Mastodon via hidden services, and get error ``Security verification failed. Are you blocking cookies?``

![422 Unprocessable Entity](https://user-images.githubusercontent.com/22741471/101499322-0ac38d00-3965-11eb-9ce5-8fa1eab202d4.png)

mastodon-web log
```
[aa01a2c2-66cb-4ae2-9dce-c405c010236a] method=POST path=/auth/sign_in format=html controller=Auth::SessionsController action=create status=422 duration=2144.59 view=1823.16 db=260.17
```

chrome har log and tcpdump packets: [har-pcap.zip](https://github.com/tootsuite/mastodon/files/5659949/har-pcap.zip)

### Steps to reproduce the problem

**Step 1**: Use docker to install the [latest](https://www.github.com/tootsuite/mastodon/tree/765626a3a766ce212e73a1a51f6a048cc19ffc63) version Mastodon.

[env.production.zip](https://github.com/tootsuite/mastodon/files/5659966/env.production.zip)

I try to add ``ALLOW_ACCESS_TO_HIDDEN_SERVICE=true`` and ``ALTERNATE_DOMAINS=ko6h7dhb3sbygcs6iiodiavjlhomvcjn36wffoyhkgxpavz6u62jm5qd.onion``, but no use.

**Step 2**: Setting nginx.

[nginx-configs.zip](https://github.com/tootsuite/mastodon/files/5659970/nginx-configs.zip)

**Step 3**: Setting hosts.

Add the follow line to `/etc/hosts`

```
127.0.0.1 ko6h7dhb3sbygcs6iiodiavjlhomvcjn36wffoyhkgxpavz6u62jm5qd.onion
```

**Step 4**: Visit the following urls on chromium and try to log in.

- https://mastodon.lo.bgme.me/about 
- http://ko6h7dhb3sbygcs6iiodiavjlhomvcjn36wffoyhkgxpavz6u62jm5qd.onion/about

You will succeed in mastodon.lo.bgme.me, but failed in ko6h7dhb3sbygcs6iiodiavjlhomvcjn36wffoyhkgxpavz6u62jm5qd.onion.

### Specifications

Mastodon version: [latest](https://www.github.com/tootsuite/mastodon/tree/765626a3a766ce212e73a1a51f6a048cc19ffc63)

```
$ docker images
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
postgres             9.6-alpine          5116b8393895        3 weeks ago         36.5MB
redis                6.0-alpine          c1949ec48c51        5 weeks ago         31.2MB
tootsuite/mastodon   latest              0f2f7b44677b        7 weeks ago         1.86GB
```

**Comment by Kjwon15** [comment]
You should edit config files to disable force HTTPS redirect for onion domain

**Comment by yingziwu** [comment]
> You should edit config files to disable force HTTPS redirect for onion domain

You can download my nginx config.
I have remove HTTP Strict Transport Security header and 302 redirect to HTTPS don't affect login.

Besides, even if I add 

```
proxy_redirect https://$host http://$host;
``` 

Remove HTTPS redirect , still can't login.

**Comment by yingziwu** [comment]
The real nginx config of my instance.

```
server {
  listen 127.0.0.1:80;
  server_name mastodon.ko6h7dhb3sbygcs6iiodiavjlhomvcjn36wffoyhkgxpavz6u62jm5qd.onion;
  location ~ ^/(emoji|packs|system/accounts/avatars|system/media_attachments/files) {
    add_header Cache-Control "public, max-age=31536000, immutable";
    try_files $uri @proxy;
  }
  location @proxy {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Proxy "";
    proxy_pass_header Server;

    proxy_redirect https://$host http://$host;
    sub_filter 'https://$host/' 'http://$host/';
    sub_filter 'https://bgme.me/' 'http://$host/';
    sub_filter '"streaming_api_base_url":"wss://bgme.me"' '"streaming_api_base_url":"ws://$host"';
    sub_filter 'https://img.bgme.me/' 'http://img.ko6h7dhb3sbygcs6iiodiavjlhomvcjn36wffoyhkgxpavz6u62jm5qd.onion/';
    proxy_hide_header Content-Security-Policy;
    add_header Content-Security-Policy "base-uri 'none'; default-src 'none'; frame-ancestors 'none'; font-src 'self' https://bgme.me; img-src 'self' https: data: blob: https://bgme.me http://img.ko6h7dhb3sbygcs6iiodiavjlhomvcjn36wffoyhkgxpavz6u62jm5qd.onion; style-src 'self' 'unsafe-inline' https://bgme.me; media-src 'self' https: data: https://bgme.me; frame-src 'self' https:; manifest-src 'self' https://bgme.me; connect-src 'self' data: blob: https://bgme.me https://img.bgme.me wss://bgme.me; script-src 'self' https://bgme.me; child-src 'self' blob: https://bgme.me; worker-src 'self' blob: https://bgme.me";

    sub_filter_once off;
    sub_filter_types application/json;
    proxy_set_header Accept-Encoding "";

    proxy_pass http://backend;
    proxy_buffering on;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    proxy_cache CACHE;
    proxy_cache_valid 200 7d;
    proxy_cache_valid 410 24h;
    proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
    add_header X-Cached $upstream_cache_status;

    tcp_nodelay on;
  }
  location /api/v1/streaming {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto http;
    proxy_set_header Proxy "";

    proxy_pass http://127.0.0.1:8080;
    proxy_buffering off;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    tcp_nodelay on;
  }
  include snippets/mastodon.conf;
}
```

**Comment by ThibG** [comment]
I guess this could be caused by the `secure` attribute in cookies?

**Comment by gloomy-ghost** [comment]
I got nginx to log the request cookie header containing `_mastodon_session`, so I guess the problem isn't with the client.

**Comment by gloomy-ghost** [comment]
turns out it's the `Origin` header, yet another time bitten by reverse proxy not replacing enough fields...

**Comment by yingziwu** [comment]
> turns out it's the `Origin` header, yet another time bitten by reverse proxy not replacing enough fields...

Via tcpdump, the POST Request from Hidden service has correct ``Origin`` header.

![image](https://user-images.githubusercontent.com/22741471/102525869-c6d23580-4092-11eb-8ccb-61fa6e9c41d7.png)
![image](https://user-images.githubusercontent.com/22741471/102526223-45c76e00-4093-11eb-9c93-acc8065852bb.png)

From the tcpdump records, I can't find the different on HTTP Request between   ``mastodon.lo.bgme.me`` and  ``ko6h7dhb3sbygcs6iiodiavjlhomvcjn36wffoyhkgxpavz6u62jm5qd.onion``.

@ThibG I think this problems isn't on client.

**Comment by yingziwu** [comment]
The POST from ``ko6h7dhb3sbygcs6iiodiavjlhomvcjn36wffoyhkgxpavz6u62jm5qd.onion`` don't have following headers:
- ``Sec-Fetch-Site``
-  ``Sec-Fetch-Mode``
- ``Sec-Fetch-User``
- ``Sec-Fetch-Dest``

Is [Fetch metadata request header](https://developer.mozilla.org/en-US/docs/Glossary/Fetch_Metadata_Request_Header) required?

**Comment by yingziwu** [comment]
@ThibG 
> I guess this could be caused by the `secure` attribute in cookies?

According to tcpdump packet capture record, I agree that the attribut [Secure](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Secure) cause this problem.

![mastodon.lo.bgme.me](https://user-images.githubusercontent.com/22741471/102526223-45c76e00-4093-11eb-9c93-acc8065852bb.png)
![ko6h7dhb3sbygcs6iiodiavjlhomvcjn36wffoyhkgxpavz6u62jm5qd.onion](https://user-images.githubusercontent.com/22741471/102525869-c6d23580-4092-11eb-8ccb-61fa6e9c41d7.png)

**Comment by yingziwu** [comment]
@ThibG 
Fix this problem, after adding ``proxy_cookie_flags ~ nosecure;`` to nginx.conf.

**Comment by yingziwu** [comment]
@ThibG 
But Tor Browser should treat onion site as secure site.
According to tcpdump packet capture record, in the real environment, cookies are indeed received.

![image](https://user-images.githubusercontent.com/22741471/102574577-01ff5380-40e9-11eb-990c-c35c16f824a4.png)

**Comment by gloomy-ghost** [comment]
I'll elaborate on my previous comment - `/auth/sign_in` gives a 422 error when the `Origin` header is unmatched with the main site domain, which can be fixed by rewriting the field or dropping it altogether.

I'm rather puzzled why changing the cookie's `secure` attribute would also work, since it shouldn't really matter to TBB. If you have the `proxy_cookie_flags` directive available on your nginx for testing, I would suggest compare the sign in request and check what actually changed.

**Comment by cohosh** [comment]
I was also able to reproduce this issue.

For me, there were two different problems blocking logins to mastodon onion services. One was the secure cookie problem mentioned above. Another was an nginx directive that assumes all requests are sent over https and causes a domain mismatch for requests sent to onion services over plain http.

The fix for the second problem was to modify the `X-Forwarded-Proto` header in the default nginx config to forward the actual scheme of the request instead of always forwarding https. This is a very simple and safe change to make, since it was not providing any protections, just making an assumption about the scheme.

For the first problem (secure cookies), I haven't validated @yingziwu's solution to use the `proxy_cookie_flags` directive because this is only available for the most recent (nonstable) version of nginx.

IMO a better way to handle this is to open a separate ticket to detangle how the mastodon application code handles http vs https requests. There are many different ways in which mastodon attempts to force all connections to go over https, and secure cookies is just one of them (rails appears to not send secure cookies over plain HTTP connections at all). As you can see from the mastodon [documentation for hidden services](https://docs.joinmastodon.org/admin/optional/tor/#gotchas), users frequently have to manually modify the protocol in the URL bar when visiting the onion service. I would like to see a more usable solution here, but it has to be done carefully to ensure we aren't stripping TLS protections for regular (non-onion) versions of the site.

**Comment by cohosh** [comment]
I opened a pull request for this #15498
