### ISSUE TITLE
Upgrade from 3.2.1 to 3.3.0 Single user login issue

### ISSUE THREAD

**Issue by xiya233** [mastodon/mastodon#15459]
### Expected behaviour

open https://example.com/auth/sign_in login and 302 redirect to /

### Actual behaviour

open https://example.com/auth/sign_in login and 302 redirect to https://example.com/@user?max_id=105258253822879037

### Steps to reproduce the problem

docker-compose pull
docker-compose up -d
docker-compose run --rm -e SKIP_POST_DEPLOYMENT_MIGRATIONS=true web rails db:migrate
docker-compose restart
docker-compose run --rm web bin/tootctl cache clear
docker-compose run --rm web rails db:migrate
docker-compose restart

### Specifications

Chrome 87.0.4280.88 reproduce
Chrome 86.0.4240.198 cannot be reproduced

**Comment by xiya233** [comment]
Update:

This bug also exists with the completely new 3.3.0 installation

1. Affected browser version:

Chrome 87.0.4280.88

Edge 87.0.664.66

2. Send 21 messages to construct the "max_id=xxx" URL

3. Login redirect 302

Unaffected browser version:

Chrome 86.0.4240.198

Brave 87.0.4280.101

**Comment by ThibG** [comment]
This is not browser-dependent but caused by having a query-string in the URL. Mastodon is built to redirect to the last visited page on log-in, except if it's `/about` or the single user's root page (`/@user`), but `/@user?max_id=…` isn't treated the same way as `/@user`, and maybe it should be for that purpose.

**Comment by xiya233** [comment]
> This is not browser-dependent but caused by having a query-string in the URL. Mastodon is built to redirect to the last visited page on log-in, except if it's `/about` or the single user's root page (`/@user`), but `/@user?max_id=…` isn't treated the same way as `/@user`, and maybe it should be for that purpose.

Thank you for your reply, I see what you mean

My question is that when I visit `https://example.com/@user` and log in from here, it does not redirect 302 to the logged in page, but to `/@user?max_id=...`

I recorded a GIF for your information

![mastodon](https://user-images.githubusercontent.com/33951857/103330537-e27b0a00-4a9c-11eb-91e6-a7347000fe51.gif)

**Comment by Gargron** [comment]
It is possible that at some point pre-login you visited a version of the page with ?max_id=xxx, and, due to the bug @ThibG mentioned, this page was marked down as your "go back to" page for after-login, since the version of the page without ?max_id=xxx does not override it. Clearing the session should fix it.

**Comment by xiya233** [comment]
> It is possible that at some point pre-login you visited a version of the page with ?max_id=xxx, and, due to the bug @ThibG mentioned, this page was marked down as your "go back to" page for after-login, since the version of the page without ?max_id=xxx does not override it. Clearing the session should fix it.

Cleared all sessions and browser cache, it still exists
