### ISSUE TITLE
Make "Follow Requests" button always visible in single column mode

### ISSUE THREAD

**Issue by snoozysoft** [mastodon/mastodon#16178]
In the three column "advanced interface" mode, the follow request button is always present in the "Getting Started" column, and automatically updates as you receive new requests. For some reason, this is not true within the single column interface mode; if you receive new follow requests whilst in this mode you have to refresh the entire page just to get them to show up and once you've processed said request, the button disappears once more.

The only way one would ever know when you have a new request in this mode is if you received an email notification (unreliable, plus requires checking somewhere else just to see a notification) or if a third party app notifies you (equally unreliable, also requires that you have said third party app to begin with). I genuinely don't understand why this button doesn't function exactly the same as it does in the advanced interface mode, especially since single column mode can clearly handle live updating of notifications with...well, the notifications button. 

I've been looking deeply into this and from what I can tell, this behaviour is [straight up baked into tootsuite](https://github.com/tootsuite/mastodon/blob/c3aef491d66aec743a3a53e934a494f653745b61/app/javascript/mastodon/features/ui/components/follow_requests_nav_link.js#L33) to begin with for some reason.

Yes I'm fully aware that this is a very small and non urgent change, but I personally consider such a thing to be a huge QoL difference in usage.

**Comment by matildepark** [comment]
Hi there — I just put a fix in at #16652. I believe it fixes the _spirit_ of this issue, because:

> In the three column "advanced interface" mode, the follow request button is always present in the "Getting Started" column, and automatically updates as you receive new requests. For some reason, this is not true within the single column interface mode

Isn't correct. Both modes don't update the follow request count until refresh. This is because while we get a notification over the streaming API for a new follow request, we don't actually handle it and update state. The fix isn't that we put a permanent button that itself doesn't ever update either — the fix is that both modes have a reactive element for follow requests, just like they do for notifications, so you aren't waiting for emails.
