### ISSUE TITLE
Cannot transition from dialog to unmounted composer

### ISSUE THREAD

**Issue by noellabo** [mastodon/mastodon#16515]
### Expected behaviour

If you press the reply button in the image dialog or overwrite confirmation dialog, you will be taken to the composer.

### Actual behaviour

If you press the reply button in the image dialog or overwrite confirmation dialog, the transition to composer will not occur.

### Steps to reproduce the problem

Shrink your browser to a width that hides the composer with a single column, or try it on mobile.

1. Click on the image
2. Press the reply button

Another reproduction method

1. Enter something in the composer
2. Press the reply button

### Specifications

Occurs after https://github.com/mastodon/mastodon/pull/16499.

**Comment by ClearlyClaire** [comment]
I can reproduce this. Interestingly, this doesn't occur on glitch-soc, from which most of the new code is… I will investigate this.

**Comment by ClearlyClaire** [comment]
This seem caused by `this.context.router.history` lagging behind the actual history, so while the `replyCompose` action does push a new item to the browser history, the code in `modal_root` thinks it's still in a modal-related history item. I am not sure how to best handle that, but I'll continue looking.

**Comment by noellabo** [comment]
I applied the fix and confirmed that the issue was resolved.
