### ISSUE TITLE
Hide a specific status

### ISSUE THREAD

**Issue by Geobert** [mastodon/mastodon#1669]
Feature to hide one status only (instead of muting a guy for one status)

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by voidzero** [comment]
Would be happy if the priority could go up. Today I wanted to show Mastodon to someone, and luckily just before I did I opened the federated timeline and saw an image that's, let's say, not family friendly.

I know images can be hidden, but this is not persistent so closing and reopening the timeline just shows it again.

I don't want to mute or block people, but I want to hide statuses for this reason. And I'd like this to be a persistent setting, perhaps in my browser's local cache or something.

It would also be nice if hiding images could be made persistent - I'm not sure if it's ok to just ask for this in this issue, or to create a new issue for it.

**Comment by magicalskye** [comment]
yes, sometimes i get triggered / annoyed by a toot and it just. has to go. but i don't want to silence the whole person because they're cool and they don't know that something innocuous is triggering to me. 

also sometimes the formatting of a toot or an image may be visually distracting and make it hard for me to focus on other things, or may cause visual overload.

so this is an accessibility issue.

**Comment by wxcafe** [comment]
So uh since this has been linked on mastodon and is seeing more attention again, I'm wondering if the "mute conversation" that mastodon has had since 1.3.3 would answer this concern correctly? 
<img width="250" alt="screen shot 2017-06-17 at 20 05 28" src="https://user-images.githubusercontent.com/3009327/27255164-d8715e0a-5398-11e7-832e-0c14f1ca16bf.png">

**Comment by Cassolotl** [comment]
@wxcafe Thank you! :)

**Comment by Cassolotl** [comment]
I wanted to add that the X-Kit extension for Tumblr has this feature, and I use it surprisingly often:

![screen_shot_2018-08-26_at_12_31_10](https://user-images.githubusercontent.com/6607512/44627815-1de4f700-a92c-11e8-9fcd-b4ed94cbe3c3.png)

![screen shot 2018-08-26 at 12 31 24](https://user-images.githubusercontent.com/6607512/44627816-21787e00-a92c-11e8-81df-8df9ce93ab83.png)

**Comment by bannisdale** [comment]
@joyeusenoelle Looks like you can safely start with this one now. ;-)

**Comment by guigeekz** [comment]
@joyeusenoelle have you made any progress on this project? I'd like to work on it, but if there's already a branch that exists it might help. Thanks!

**Comment by bannisdale** [comment]
@guigeekz It really doesn't look like anything has been done in this direction so far.

**Comment by guigeekz** [comment]
All right, well, in that case, I'll get on it :-)

**Comment by Cassolotl** [comment]
The pull request that would resolve this issue just got closed for inactivity. This feature request has been open for over four years now.

**Comment by trwnh** [comment]
you can do this now with the revamped filter system -- there's an option to filter an individual post. i guess this issue can be closed?
