### ISSUE TITLE
LoadError: cannot load such file -- rexml/document (during build)

### ISSUE THREAD

**Issue by jernst** [mastodon/mastodon#16720]
### Expected behaviour

build should not fail

### Actual behaviour

build failed

### Steps to reproduce the problem

When running `bundle exec rails assets:precompile`:
``
rails aborted!
LoadError: cannot load such file -- rexml/document
``

Fix: add dependency to Gemfile:
`gem 'rexml'`

### Specifications

Mastondon 3.4.1
On Arch/x86_64 with ruby 3.0.1

**Comment by ClearlyClaire** [comment]
I can reproduce this issue. I had not noticed it earlier because it is pulled as a development dependency, but for some reason, one of our production dependencies seem to implicitly depend on it, which is fine on pre-3.0 Ruby, but not starting from Ruby 3.0.

This seems to be caused by the version of the `ruby-saml` gem we currently use not explicitly declaring it. That gem is pulled by `omniauth-saml` which explicitly requires that version of `ruby-saml`. The development version of `omniauth-saml` requires an up-to-date `ruby-saml`, but there are currently no release of `omniauth-saml` which allows a recent enough version.
