### ISSUE TITLE
I can't delete my account

### ISSUE THREAD

**Issue by Hideyo169** [mastodon/mastodon#17015]
### Pitch

I've been trying to delete my account, I've checked security and it's not there.

### Motivation

Could someone please help.

**Comment by ClearlyClaire** [comment]
It's in `/auth/edit`, but it can be disabled by your instance admin. Reach out to them if the option is not there.

@Gargron this being optional has been implemented by #3852 and I'm not fully convinced by the rationale. Now that we have support for delayed deletion, can we reconsider this so that account deletion cannot be disabled?
