### ISSUE TITLE
Mastodon and Peertube , videos federation

### ISSUE THREAD

**Issue by AnonymousWebHacker** [mastodon/mastodon#17031]
### Pitch

I'm not sure if it's a peertube or mastodon incident.

When a Mastodon instance fully follows a peertube instance, the videos uploaded on Peertube can be viewed on Mastodon. This works perfect.
 
Now, when a video is uploaded with a title for example "My First VideoX", the video is published on Mastodon with that name.
If I enter the peertube, and change the name of the video to "My First Video" (eliminating the x) , in Peertube, it changes the name, but in Mastodon, the old name stays, it never gets to update the name

### Motivation

You need to update the video name in Mastodon

**Comment by nightpool** [comment]
Mastodon is a microblog service, and it does not allow users to edit posts, as a UX requirement. Since Peertube videos are converted to Mastodon posts when Mastodon receives them from Peertube servers, they have the same restrictions as any other Mastodon post. If we do allow users to edit posts in the future (see #6829 and #16697 for current in-progress work along these lines), we'll certain try to make sure we're compatible with Peertube's video editing feature.

**Comment by AnonymousWebHacker** [comment]
I think you confuse what I meant.
I don't want to edit a remote post, or someone else's. I mean that if in Peertube, they upload a video, and then update (changing the name) it should change autoamtico the same in Mastodon

**Comment by nightpool** [comment]
When you're changing the name of a video in Peertube, what Mastodon sees is that you're editing the Mastodon post announcing that a video was uploaded. You have to think of both endpoints of the federated network.

**Comment by AnonymousWebHacker** [comment]
I just hope they can add this in the next updates
