### ISSUE TITLE
Strange text selection in "/share" page

### ISSUE THREAD

**Issue by Akkiesoft** [mastodon/mastodon#17295]
### Steps to reproduce the problem

1. open /share page (e.g. using mastoshare)
    * sample: https://<YOUR MASTODON SERVER>/share?text=Issues%20%C2%B7%20ruby-gnome%2Fruby-gnome%0Ahttps%3A%2F%2Fgithub.com%2Fruby-gnome%2Fruby-gnome%2Fissues)

### Expected behaviour

Perhaps the text is NOT selected.

### Actual behaviour

Text is selected. Perhaps text is selected from after the first space to end of text.

### Specifications

* Mastodon: v3.4.3, v3.4.4
* OS: macOS 11.6.2
* Browser
    * Google Chrome: 97.0.4692.71
    * Firefox 96.0.1
    * Safari 15.2 (16612.3.6.1.8, 16612)

Screen shot:
<img width="221" alt="showing the /share page. text is selected automatically." src="https://user-images.githubusercontent.com/422590/149549765-a1717922-b284-4fe4-bc15-5400bdba848a.png">

**Comment by ClearlyClaire** [comment]
This is a side-effect of a feature that pre-selects mentions past the first one when you reply to multiple users, so that additional mentions can easily be deleted, kept, or moved to a new line.

This feature has been written under the assumption that a non-empty initial state for the composer would always be caused by replying to someone, which, as can been seen here, is not the case.

I will work on a fix shortly.
