### ISSUE TITLE
MIME Type issue

### ISSUE THREAD

**Issue by quiint** [mastodon/mastodon#17685]
### Steps to reproduce the problem

1. Open Mastodon in the browser
2. View console

### Expected behaviour

All JS and CSS appears as normal

### Actual behaviour

Unstyled elements, JS not working

### Specifications

Brave, MacOS Catalina
CSS: 
`Refused to apply style from 'https://[mastodon]/inert.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`
JS:
`net::ERR_ABORTED 404`
I can log in successfully, but only a white screen appears.

**Comment by quiint** [comment]
Reverse proxy configuration is from the Mastodon example, and `public/` is readable.

**Comment by ClearlyClaire** [comment]
Check your nginx logs, possibly, restart `mastodon-web`, as it is possible you may have recompiled assets without reloading it?

**Comment by hackdefendr** [comment]
Can I add to this issue since I'm also seeing the same?

I just installed a fresh mastodon server, version 3.5.3 is what shows up at the bottom. However, I do not see any CSS/JS loaded, with developer console showing a bunch of 404's for every asset file. I checked and the files are there and readable. The only difference in my install is the location of mastodon user home. Everything else is by the book, and I saw no errors during compile time. Here are the things I have already done to try and resolve this myself:

- removed and rebuilt the assets using `...rails assets:clobber` and `...rails assets:precompile`
- triple checked every config file to make sure paths were all correct
- searched the joinmastodon forums and tried every possible solution
- searched every log only to find the same 404 errors with no hint of why
- cleared every cache I can think of, including disabling Cloudflare's cache altogether.

Nothing has worked so far, leading me to believe either I missed a step, or there is an issue with how I installed it. When I created the mastodon user, I put the home folder on my /data partition and changed every step to point to /data/mastodon instead of /home/mastodon, that is the only change and shouldn't matter since home folders can exist anywhere.

At this point, I am about to wipe everything and start from scratch because I just don't know how else to fix this.

**Comment by ClearlyClaire** [comment]
Can you check the output of: `stat /data`, `stat /data/mastodon` and `stat /data/mastodon/live`?

**Comment by hackdefendr** [comment]
Hi Claire,

Like this?
```
$ sudo -u www-data stat /data/mastodon/live
  File: /data/mastodon/live
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 811h/2065d	Inode: 51648132    Links: 23
Access: (0770/drwxrwx---)  Uid: (  997/mstadmin)   Gid: (  997/mstadmin)
Access: 2022-06-16 15:26:10.786636044 +0000
Modify: 2022-06-16 15:21:31.412091198 +0000
Change: 2022-06-16 15:21:31.412091198 +0000
 Birth: -
```
That 0770 doesn't look right.

**Comment by ClearlyClaire** [comment]
Yeah seems like that's your issue!

**Comment by tomtom94** [comment]
```
root@scw-happy-mcclintock:~# stat /home/mastodon/live
  File: /home/mastodon/live
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: fc01h/64513d	Inode: 1295481     Links: 22
Access: (0775/drwxrwxr-x)  Uid: ( 1001/mastodon)   Gid: ( 1001/mastodon)
Access: 2022-12-21 23:19:20.211859786 +0000
Modify: 2022-12-21 23:21:41.781196563 +0000
Change: 2022-12-21 23:21:41.781196563 +0000
 Birth: 2022-12-21 23:02:39.343650924 +0000
```

what's the point ? I am 0775
