### ISSUE TITLE
getting user id for replying, retooting or starring

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [mastodon/mastodon#17694]
so yes. i wanted to automate my account a little (about rules were not asking. only bout api. its on my butt what will happen.)

so yes - to retoot, follow, reply, star, bookmark and all the rest user can do thru website bots have no access (only server moderation have ids which mostly is dead)

is it a security feature or api lacking for connecting to users thru api ? (docs say only about v1 version. i know about v2 but even if - according to your discourse i viewed from google - i'd need user token they'll generate)

PS: i type it here because : libera chat throws me out without reason and if i connect thru tor asks for login smh
PS 2 : im not gonna use any discourse derivative just because i already registered tons of it (microsoft, kde, gnome, google, stackoverflow, some github chats - even private ones etc etc)
maybe if you have discord i can join (but probly will get ban. better here)

resources i was trying to use : 

- https://discourse.joinmastodon.org/t/how-to-get-mastodons-user-id-from-mastodon-account-acct-username-server/1658/2
- https://docs.joinmastodon.org/methods/accounts/
- also this : https://mastodonpy.readthedocs.io/en/stable/#id-unpacking

maybe would you just put id in the url or make it in 'developer mode' similar to discord one? (context menu)

**Comment by hacknorris-aka-penguin** [comment]
@Gargron

**Comment by ClearlyClaire** [comment]
You don't need user ids for replying, boosting and faving toots, only toot ids. In any case, account and toot ids are not hidden at all, you definitely have access to them: whenever you see an object in the API, you have its `id`.

To get a toot `id` from an URL, use `/api/v2/search?resolve=true&q=https://status_url`.
To get an account `id` from an URL, you can also use `/api/v2/search?resolve=true&q=https://account_url` or `/api/v2/search?resolve=true&q=@user@domain`.

Since 3.4.0, you can also use `/api/v1/accounts/lookup?acct=user@domain` which is used for a quick lookup of an account that is already known to the instance.

Also note that this question would have been better in https://github.com/mastodon/mastodon/discussions rather than in an issue, and please refrain from tagging people for no reason.

**Comment by hacknorris-aka-penguin** [comment]
k, thanks =]

**Comment by dellagustin** [comment]
Just commenting to mentioned that @ClearlyClaire answer in this question also worked for me with the question I posted at https://socialhub.activitypub.rocks/t/is-it-possible-to-get-the-status-id-from-the-ap-url-of-a-note/2343.
