### ISSUE TITLE
Add "status_max_length" instance parameter

### ISSUE THREAD

**Issue by alkemist** [mastodon/mastodon#1781]
Add the ability for instance admin to edit the maximum number of characters per status

![capture du 2017-04-14 17-43-07](https://cloud.githubusercontent.com/assets/293229/25047926/de7994e8-2139-11e7-9fcb-fd11ca2a904b.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by pixocode** [comment]
I will need a person with front/reactjs skills :/

**Comment by novadeviator** [comment]
+1
i would also really like to see this. I have an instance using masto.host. It's really great and easy to run your own instance. But customisations are not possible, because there's no access to commandline. Supposedly there are number of instance there too (around 50?). I'm sure we would all benefit from an ability to change status_max_length from the admin ui.

**Comment by simonlbn** [comment]
Most Mastodon instances I have seen running now change the code to allow statuses longer than 500 characters, so I think it would be great to have this as a built feature in rather than requiring code changes.

While the code changes required for changing the length are minimal, the fact that it's in code and not configuration means e.g. hosted instances, where the hosting company not unreasonably want to run stock code for it to be manageable, don't have the option. This is the specific reason I care about this.

**Comment by PinballsWizard** [comment]
I'd love to see an enhancement along these lines make it in.  Managing code changes isn't insurmountable, but even exposing this as a .env option would be appreciated.

**Comment by mjankowski** [comment]
This ability has been requested in many places but consistently rejected. Closing during to unlikely to happen.

This setting did recently move to a code constant and I know some forks/instances edit that to change this value.
