### ISSUE TITLE
Notification of ghost edits of boosted toots

### ISSUE THREAD

**Issue by jelv** [mastodon/mastodon#17910]
I've got notifications of edit's that didn't happen:

![image](https://user-images.githubusercontent.com/7106279/160837322-403b2c89-7875-4f42-a4b6-3cb659767154.png)

### Steps to reproduce the problem

1. Boost toot
2. Wait a few years
3. Edit shows up in notifications

I've got 3 notifications:
https://octodon.social/@cwebber/99733907515951885
Post from 2018. Is edited today. [User ](https://octodon.social/@cwebber/108045499682139839) confirmed they didn't edit it
![image](https://user-images.githubusercontent.com/7106279/160836349-da0a9206-6dbe-441b-bb08-0cb0d23514c6.png)

https://fosstodon.org/@plasmamobile/105196536981428537
Unconfirmed edit.
![image](https://user-images.githubusercontent.com/7106279/160836645-e6a48c85-839c-473a-a3b0-666e85c6d9ad.png)

https://mastodon.technology/@lib_reviews/99868097986592983
Unconfirmed edit.
![image](https://user-images.githubusercontent.com/7106279/160836738-4bb97b50-1573-49ff-9af8-337f578f12ab.png)

Seems spooky.

### Expected behaviour

I can confirm 1 edit didn't.  That one shouldn't be there

### Actual behaviour

Notifications of edits showed up

### Specifications

Mastodon.social. Chrome. Win 11.

**Comment by realpixelcode** [comment]
I've noticed the same behaviour with 2 of my toots that Mastodon falsely claims have been edited: https://social.tchncs.de/@pixelcode/106641705226345428 and https://social.tchncs.de/@pixelcode/106534952553197299

I got the "ghost notifications" on my mastodon.social profile that had boosted both toots.

**Comment by ClearlyClaire** [comment]
I have been able to reproduce these issues, which seem caused by the serialization of those toots having changed due to the following things:
- generated HTML for external links using different values of the `rel` attribute depending on Mastodon version
- capitalization of tags changing after the post was authored, thus changing the links' targets
- media URL changing because of change in the authoring instance's configuration (changing media storage backend/server)

I am honestly not sure how to address these. The check could reasonably be updated to ignore changes to stuff like `rel` attributes, but technically the tag URLs *have* changed, and so have the media URL, even if that is not from user intervention…
