### ISSUE TITLE
Federating with Lemmy - Don't boost comments

### ISSUE THREAD

**Issue by UserThre3** [mastodon/mastodon#18069]
### Steps to reproduce the problem

1. Subscribe to Lemmy community
2. Wait for new comments
3. Check Home timeline, it's flooded with comments to subscribed communities.

Discussion on Lemmy github re. this issue https://github.com/LemmyNet/lemmy/issues/2224

### Expected behaviour

Nothing. Comments should be attached to the post.

### Actual behaviour

Comments gets boosted in the same way as community posts

### Specifications

Mastodon 3.5.1
Lemmy 0.16.3

**Comment by nightpool** [comment]
I'm sorry, but this bug report doesn't make any sense. If you follow the community, you'll get all of the posts the community makes in your home timeline. If the community is sending us `Announce` activity (like Lemmy [says they are](https://github.com/LemmyNet/lemmy/issues/2224)), then you'll get those boosts in your home timeline. That's what `Announce` means. If Lemmy wants them to not appear in their follower's timelines, then they can do something besides `Announce`ing them. (For example, they could use [Inbox Forwarding](https://www.w3.org/TR/activitypub/#inbox-forwarding))

**Comment by aschrijver** [comment]
FYI cc @Nutomic in case you missed Nightpool's comment :)

**Comment by Nutomic** [comment]
@aschrijver Thanks for the heads up!

@nightpool I dont see how the inbox filtering is related, it seems to be for delivering activities in case the original sender couldnt deliver them. In this case the problem is that Mastodon receives and displays activities from Lemmy (Announce/Create/Note) which the user doesnt want to see. This is due to a recent change in Mastodon, previously it didnt accept activities with this type at all.

**Comment by rokejulianlockhart** [comment]
So... whose fault is it?

**Comment by Snowpop** [comment]
Also experiencing this issue. Hope we can find a solution!

**Comment by Sir-Photch** [comment]
+1

**Comment by steelswords** [comment]
Same problem here. It's very annoying. Started a week or so ago for me on fosstodon.org

**Comment by nightpool** [comment]
> I dont see how the inbox filtering is related, it seems to be for delivering activities in case the original sender couldnt deliver them

Not sure how what something "seems to be for" is relevant. This mechanism is the way every single other ActivityPub server implements reply forwarding. It's specifically said in the text of the spec to be designed to solve the ghost reply problem. i.e. "for groups to send activities to their followers". If Lemmy wants to use boosts instead then that's their prerogative, but it's pretty clear that most users are annoyed by that decision.

**Comment by Archenoth** [comment]
Sorry if the last response actually did send a notification, but just in case, uh, paging @Nutomic!

(Also, pardon the bump! I figured replying to this instead of making a new issue would probably be the least annoying way to ask if there was a way for lemmy and mastodon to coexist in a way that takes over your timeline less, and figuring out if this was even the right place to ask about that)

**Comment by Nutomic** [comment]
@Archenoth What do you ping me for? Federation is working fine between Lemmy instances, and Im not getting paid to solve Mastodon problems.

**Comment by Archenoth** [comment]
@Nutomic the tl;dr version is that @nightpool's comment seemed to suggest the ball is in Lemmy's court again, so I was wondering if you'd seen it, since this is where the most recent conversation about this problem has been

(Sorry if you had ^^')

The less-tl;dr version is that , even though both this issue [and the original one in the Lemmy repo](https://github.com/LemmyNet/lemmy/issues/2224) are closed, the original issue @UserThre3 reported in both places still remains! If you follow a lemmy community of mostly any size from mastodon, it will overwhelm your feed by boosting all activity inside every post into your feed--enough traffic to completely monopolize your feed if you don't follow thousands of people

- It seems like the original reason Lemmy did this was so that it would federate properly (I can confirm it does!)
- Lemmy and Mastodon also both seem to be implementing ActivityPub just fine too, so this isn't about that either

However, the suggestion to use [Inbox Forwarding](https://www.w3.org/TR/activitypub/#inbox-forwarding) as a way to federate replies without needing to `Announce` every one of them was because it seems like the original Lemmy feature was to make it able to interop with mastodon, and that is currently _preeeeetty_ broken, and this would be a standards-compliant way to make that less so

**Comment by Archenoth** [comment]
Oh! And the ping was because it seemed like this issue might fall through the cracks since both sides were mutually okay with waiting for a fix from a project that didn't feel like there was anything to do

So I was hoping drawing your attention here would either lead to either a _"Mastodon needs to do X for this to work"_ or a _"Oh! Lemmy would need to X for this to work"_ so that we could figure out a way for Mastodon and Lemmy to interact in a usable way (Because this issue seems to be a pretty common reason for people not doing that)

Sorry for the extra inbox traffic ^^'

**Comment by Nutomic** [comment]
I think I explained this already before, but gonna clarify it once more: The Activitypub standard allows many different ways to implement the same functionality, so what Mastodon and Lemmy are doing is both in line with the standard. Specifically Lemmy implements [FEP-1b12](https://codeberg.org/fediverse/fep/src/branch/main/fep/1b12/fep-1b12.md) which is the de facto Fediverse standard for group federation. Im not sure if inbox forwarding would work for Lemmy. There is a high chance it wont because Lemmy has to forward much more complex data than only simple `Note`s. In any case its way too late to change this now, as it would require a major rewrite of Lemmy code, thorough testing and some way to make a backwards compatible migration. Lots of work with zero benefit for Lemmy users. Believe me we have tons of work which is much more important and less effort. And no, Mastodon interop was never "the original Lemmy feature". The main feature was always federation between Lemmy instances.

So the solution here is for Mastodon to implement group support according to FEP-1b12, and render group posts differently from microblogging posts. There is https://github.com/mastodon/mastodon/pull/19059 which goes in this direction, although for some reason it implements group federation in a way thats intentionally incompatible with Lemmy, and hasnt been updated in a year.

To be honest I doubt that posting this will really change anything. Mastodon maintainers probably wont read this, and they dont seem to have any interest to improve Lemmy compatibility. But maybe I will be proven wrong.

**Comment by Archenoth** [comment]
Oh, damn. Yeaaaah I think it makes total sense why that would be a no-go ^^'

Thank you for explaining! (And hopefully the masto-side eventually ends up being able to handle this more gracefully!)

**Comment by rvyhvn** [comment]
Hi,

From my personal experience, this specific behavior (boosted replies cluttering timelines without context) is a significant barrier for new users I've tried to onboard to the Fediverse. They often cite this "timeline noise" and fragmented conversational flow as a primary reason to return to centralized platforms.

Improving the contextual display for `Announced` content originating from diverse Fediverse services would be crucial for enhancing user retention and broader Fediverse adoption. I hope this issue will actually be fixed soon.

**Comment by nightpool** [comment]
Mastodon is correctly displaying the activities that all different servers are generating. As Nutomic mentions above, the ActivityPub standard allows for many different ways to forward activities to interested recipients. If you're not interested in having an Announce activity displayed, then choose a different method for activity forwarding

**Comment by rvyhvn** [comment]
Sure, ActivityPub allows for flexibility in how activities are handled, but this isn’t about protocol compliance, it’s about the end-user experience.

From a user’s perspective, boosted replies without context feel like clutter. New users don’t know or care about “Announce activities” or AP internals. They just see a disjointed timeline and bounce.

So yes, Mastodon may be technically doing the right thing, but the result is still friction that hurts adoption. That’s worth solving, regardless of who’s “correct.”

**Comment by Snowpop** [comment]
I agree with rvyhbn. Its about user experience.
