### ISSUE TITLE
Gemfile doesn't match dependency minimal ruby version

### ISSUE THREAD

**Issue by djetelina** [mastodon/mastodon#18076]
### Steps to reproduce the problem

1. Get a mac
2. Clone repo
3. Try to run `rake mastodon:setup`
4. Follow instructions of terminal and `bundle install` to get rake
5. Fail, because `letter_opener_web-2.0.0 requires ruby version >= 2.7, which is incompatible with the current version, ruby 2.6.8p205`
6. Install ruby through brew
7. Run `rake mastodon:setup`
8. Fail, because `Your Ruby version is 3.1.2, but your Gemfile specified >= 2.5.0, < 3.1.0`

### Expected behaviour

Gemfile should specify `>=2.7`

### Actual behaviour

It doesn't

### Specifications

Commit hash: `f47a9ddc9ffca22258ec9e4b12ca51db8cac1eac`

BTW, in ideal world I wouldn't need any of this and there exists another way to generate secrets and keys (if there is, sorry I missed it).

**Comment by ClearlyClaire** [comment]
Ah, good catch. We tried to remain compatible with 2.5 if possible but apparently missed one dependency. It's probably not worth supporting 2.5 anymore anyway since it's been EOL for a while now.

You can generate the secrets in another way, they are just 64 hex-encoded random bytes.

You can generate them from any ruby version by doing, in `irb` for instance:
```ruby
require 'securerandom'
puts SecureRandom.hex(64)
```

**Comment by djetelina** [comment]
That's great to know, thank you very much!
If someone happens to google this and is in the same boat as me, here's how to do the same in python :) 

```python
import secrets
secrets.token_hex(64)
```
