### ISSUE TITLE
Add the ability for an admin to manage domain blocks via API

### ISSUE THREAD

**Issue by catgoat** [mastodon/mastodon#18140]
### Pitch

As an admin, I would like to be able to manage domain blocks via API for my instance similar to how I manage accounts and reports. 

### Motivation

Blocking via UI can be slow. I would like to be able to block multiple instances at once or at least be able to script such an action for myself. 

Right now I can handle almost all other moderation aspects outside of the app and be alerted when I need to take action and take it by using just the api and some custom script for my instance. This makes moderation a lot easier. However, domain blocks can’t be managed this way. 

So, admins would benefit from being able to write their own tools and users would benefit from a happier admin able to respond to things more efficiently :).

**Comment by ChlorideCull** [comment]
This would be incredibly nice, because right now I have to give my utility scripts a username and password so it can authenticate and run with session cookies.

The script I use the most just allows me to pass a domain and one of a couple predefined reasons, and it will block it and make sure the publicly listed reason is one of the correct ones - if anyone wants more motivation.

**Comment by ClearlyClaire** [comment]
This is planned!

**Comment by catgoat** [comment]
@ClearlyClaire this is such good news!! I've been running my instance since 2017 and this has been a constant struggle so I'm so looking forward to it.

**Comment by ClearlyClaire** [comment]
Can you have a look at #18247 and see if that would address your concerns? I initially planned to do that as part of a larger admin API work effort but I figured this can be done separately.

**Comment by catgoat** [comment]
Yes, that would do it. Thank you, this will be super helpful.
