### ISSUE TITLE
Follow a thread

### ISSUE THREAD

**Issue by robsonsobral** [mastodon/mastodon#18298]
### Pitch

I would like to have a way to follow a thread. Possible ways:

- to have an option for replies of liked toots to show up on your timeline;
- to have a specific button to follow replies of a toot;

### Motivation

Sometimes, we just want to follow a discussion to see where it goes or before to colaborate on it.

**Comment by brendanjones** [comment]
Would definitely use this. This would save Mastodon from behaviours you see on other platforms like commenting a single "." in order to get notifications about replies.

Suggestions for implementation:
- Add an option to the "..." button on toots, labelled "Follow thread", or "Follow toot". 
- Following a toot would give you notifications about replies as if the followed toot was your own.
- Following a toot would have replies show up in your timeline(s) as if the followed toot was your own.

**Comment by ricardotedim** [comment]
Something like a "boost & follow" option would also be interesting in case the current behavior of not receiving any notifications for boosted toots remains the same.

**Comment by hermannoffen** [comment]
I was looking for this exact feature, too.
Sometimes I boost a toot, which e.g. asks a question I cannot answer myself but would be interested in answers as well.
I'd really appreciate to get notifications, when there are replys to the boosted toot, eventually.

**Comment by brendanjones** [comment]
Notifications for people boosting your own post sounds nice, but should be a separate issue.

Just noticed this issue is actually a duplicate of https://github.com/mastodon/mastodon/issues/7969.

**Comment by robsonsobral** [comment]
> Just noticed this issue is actually a duplicate of #7969.

Now we have 2 issues with 19 upvotes each. Dammed. I'm sorry.

**Comment by placoderm** [comment]
I would also like this. 

I'm new using mastodon, so I don't understand how I am supposed to stay engaged in a new post that comes into my home thread. Obviously there won't be any comments as soon as it pops up. But what if I want to see later what other people have written? Do I just have to bookmark it and then remember to go back and look?

**Comment by brendanjones** [comment]
@placoderm you're better posting your comment on https://github.com/mastodon/mastodon/issues/7969, given this one is closed.

**Comment by placoderm** [comment]
🤦🏻‍♂️ Thanks!
