### ISSUE TITLE
Support Cat Ears

### ISSUE THREAD

**Issue by easrng** [mastodon/mastodon#18337]
### Pitch

Misskey allows users to add cat ears to their profile picture. This is an excellent feature that Mastodon should adopt. This is implemented by adding a `https://misskey-hub.net/ns#isCat` property to the Actor JSON, linked to a checkbox in user settings marked "User is a cat" or similar. This can't be emulated by adding cat ears in the profile image itself as the ears extend outside of the image.

![A screenshot showing how Misskey adds cat ears to a profile picture.](https://user-images.githubusercontent.com/23086727/167145090-32fc0b68-b26e-4a19-abe5-2a1d53bb6418.png)

### Motivation

Many Mastodon users are "cat girls" or would otherwise benefit from being able to add cat ears to their profile picture.

**Comment by periish** [comment]
a standard extension functionality would help alleviate the need for some odder parts of the mastodon-fork set (such as those that add LaTeX support)

**Comment by periish** [comment]
final note: pleroma-catify matches based on a user's display name. presumably, an integration mastodon extension functionality may allow an extension to declare a settings interface, as to avoid this

**Comment by the-techwitch** [comment]
A more standard thing would having custom profile picture frame or something like that.

**Comment by periish** [comment]
Are misskey standards worth interoperating with?

**Comment by heartles** [comment]
Misskey also, when a user has cat mode on, does a few simple text transformations in the client when the post is displayed.

Any instances of the letters "na" together becomes "nya", so for example, my name would go from Jaina to Jainya.

Also, the word "everyone" gets replaced with "everynyan".

These are probably out of scope, especially with @the-techwitch 's proposal regarding custom profile frames, but it's worth mentioning.

**Comment by orlea** [comment]
Do you really want this feature?
This feature is an inside joke within a very small portion of the Misskey community in Japan.

**Comment by spiralw** [comment]
It's gotten quite popular outside of Japan as well recently

**Comment by EvelynSubarrow** [comment]
> Do you really want this feature? This feature is an inside joke within a very small portion of the Misskey community in Japan.

Some non-Japanese Misskey users also use this feature, I'm not sure it's so obscure. It's quite a well-known Misskey feature, at least among people I talk to on fediverse.

**Comment by Toromino** [comment]
> It's gotten quite popular outside of Japan as well recently

Yea, Misskey has grown quite a lot

**Comment by Gargron** [comment]
Mastodon and Misskey have quite different design goals. Misskey has a lot of "for fun" features like virtual, Sims-like rooms, an integrated analog clock face, spinning text... and cat ears on avatars that transform your text into meowing.

I consider such features to be distractions. And this is quite a ridiculous protocol extension to support. `isCat`? I don't think this feature was designed with protocol support in mind, otherwise, as another commenter pointed out, it would've been generalized to avatar portrait frames, or at least to arbitrary animals.

Which, I'll add, would still be a very impractical feature to support across diverse client applications and interfaces.
