### ISSUE TITLE
Accessibility: Include alternate typefaces as options (Bionic Reading, Dyslexie/OpenDyslexic, etc.)

### ISSUE THREAD

**Issue by ADHDefy** [mastodon/mastodon#18508]
### Pitch

Add an accessibility feature that would allow neurodivergent users to use an alternate typeface more conducive to their neurotype. 

For example, there is a typeface called Bionic Reading that can make it much easier for people with ADHD and similar brains to read more fluidly, read faster, and read with more comprehension. There are also options like Dyslexie, or the open source alternative OpenDyslexic, that aid dyselxic readers.

Bionic Reading
Website: https://bionic-reading.com/
API Docs: https://rapidapi.com/bionic-reading-bionic-reading-default/api/bionic-reading1/
EDIT: Open source variant here > https://github.com/axoletl/not-br

Open Dyslexic
Website: https://opendyslexic.org/

### Motivation

As a Mastodon user with ADHD (Exhibit A: my username), I have found that Mastodon is significantly better for my mental health than mainstream social media by a long shot, and I love the communities I'm discovering within as I learn more about it. Speaking personally, having the option to use a typeface like Bionic Reading built-in would be a huge asset in usability, and it would then be conveniently available to me on the desktop site, mobile site, and likely incorporated into third-party applications, as well. 

One of the most beautiful things about Mastodon, and the Fediverse as a whole, is that it has attracted an astonishingly diverse userbase, including many neurodivergent users and users that take advantage of the accessibility features. I think a huge part of that is because Mastodon is free, open, feature-rich, and each instance can be whatever you need it to be. In fact, it's cool to see how even the community pitches in, like how so many people take the time to write out image description text. I think a lot of users would be excited to have the option to use a font better suited to their brain, and it would be a welcome addition to an already impressive suite of accessibility features.

**Comment by Gargron** [comment]
There is a preference to use the system's default font in the web app

**Comment by ADHDefy** [comment]
True, but it seems to only work for desktop, which means I am unable to use it in the webapp version.

**Comment by nightpool** [comment]
On the web, accessibility is about *interoperability* and *customization*. The responsibility of a website is to provide the "semantic platform" that browsers can use to allow users to customize their own experience. While we're not able to support every single font that people may want to use with Mastodon, users should have the freedom to customize their browsers and devices as they see fit to be able to meet their own individual accessibility needs. This is a core bedrock principle of accessibility, and is the foundation that the web (and Mastodon as a part of it) is built on.

On Android, Chrome doesn't support customization through browser extensions It's one of the only mobile browsers with this limitation. If you're finding it difficult to customize your Chrome-based browser on Android, I would suggest installing Firefox Mobile and using https://addons.mozilla.org/en-US/firefox/addon/bireader/, which should serve the same purpose.

> True, but it seems to only work for desktop, which means I am unable to use it in the mobile webapp version

This setting will work for any browser that supports `system-ui`. Any typeface that you can install onto your Android system and select as the main system UI font will work with Mastodon. On some Android versions, this may require root access. I would recommend going the Firefox extension route instead of this route.

**Comment by trwnh** [comment]
i think one can recognize the theoretical responsibilities of a web browser but also admit that the reality is not like that and could be improved. given that mastodon is less of a "web site" and more of a "web app", it can be expected that mastodon can/should implement application functionality beyond that of the web browser, if it helps their users. changing your browser font to OpenDyslexic is one thing, but "bionic reading" is something that cannot be easily or readily achieved on all devices or platforms, so i think there is value in requesting a feature to do just that, in much the same way that a native application might implement these features for their linux/android/etc versions.

**Comment by nightpool** [comment]
@trwnh I am not aware of any device that does not have *some* possible support for browser extensions (as mentioned, even though Android Chrome doesn't have them, Firefox on Android does)

**Comment by koyuawsmbrtn** [comment]
Can this feature be reconsidered? Bionic reading would help me a lot.
