### ISSUE TITLE
RSS feed title displays publishing date

### ISSUE THREAD

**Issue by wo80** [mastodon/mastodon#18553]
### Steps to reproduce the problem

Receive RSS from a server running version 3.5.3

### Expected behaviour

The `title` tag of an RSS `item` should display the actual title of the post.

### Actual behaviour

The `title` tag of an RSS `item` displays the publishing date of the post.

### Specifications

Seems to be a regression in current release 3.5.3, see
https://github.com/mastodon/mastodon/blob/2b8dc58b7ff7fb708687c08a75c99b3fb30efc49/app/views/tags/show.rss.ruby#L10-L13

**Comment by Gargron** [comment]
> The `title` tag of an RSS `item` should display the actual title of the post.

Well, that's the problem. Posts don't have titles.

**Comment by Strubbl** [comment]
The previous behaviour to have the toot's text as title was way better. Now i only see a list of dates in my RSS reader instead of words which i can read and skim faster.

**Comment by Strubbl** [comment]
related: #18446

**Comment by trwnh** [comment]
for what it's worth, tumblr rss feeds use the text content when there is no title, and they use title when there is a title

mastodon could use cw for title, and if no cw is applied, then use content

as far as capping the content to a certain character count, tumblr seems to cap at 102 characters (idk why exactly 102). so something around 100 while preserving word boundaries seems reasonable...

**Comment by MrtnKk** [comment]
I would also prefer some kind of excerpt of the text body for the title instead of the creation date. The RSS `item` already comes with the creation date in the pubDate tag so what's the point of showing it twice in any feed reader? 
https://github.com/mastodon/mastodon/blob/2b8dc58b7ff7fb708687c08a75c99b3fb30efc49/app/views/tags/show.rss.ruby#L11-L14

Imagine looking for a past toot and the feed reader only showing two columns of the same publication date? See the screenshot in pandora's toot [above](https://github.com/mastodon/mastodon/issues/18553#issuecomment-1140518036) for an example.

**Comment by trwnh** [comment]
idk i still think showing content excerpt + full content (or even short full content + short full content) is better than showing date + date

**Comment by wo80** [comment]
@Gargron As @trwnh said, showing date + date is definitly redundant for ALL feed readers, while showing some content in the title might be redundant for SOME, but surely not for all. And by all means: a short survey on mastodon cannot be taken as representative.

Personally I igrnore probably 80% of the headlines in my feed reader by skipping over the titles (since today most news sites unfortunatly go for quantity instead of quality) and since version 3.5.3 seem to have reached all mastodon servers I follow, I haven't read any toot.

**Comment by mdrockwell** [comment]
My understanding is that the title tag isn't required for entries in an RSS feed. My preferred solution would be to simply not include a title unless there is a content warning, then use the content warning text as the title.

I currently syndicate my Mastodon posts to Micro.blog using the account's RSS feed and since the latest update all of my posts syndicated to Micro.blog just show the date and a link to the original post now, which isn't ideal.

I can understand why it wouldn't be the best solution for everyone if it simply didn't include a title, though. I know some RSS readers handle this more gracefully than others. The second best option, in my opinion, would be to use the text of the post as the title instead. No matter what is chosen, there would be an issue of duplicated content in the feed (which is why I prefer no title tags at all), but if we're going to duplicate something, the content of the post at least seems more useful than any other piece of information related to the post. If we're going to duplicate something, it should be the content.

As for truncation, is there really a reason to truncate at all? Wouldn't most RSS readers handle longer titles pretty well? And if the decision is to truncate, why not go for something a bit longer — like half the default post length or something?

**Comment by manton** [comment]
@MrtnKk Feel free to test with my blog RSS feed… It has a mix of title-less microblog posts and full-length posts. I keep the `<title>` element there, but it's just blank. https://www.manton.org/feed.xml

**Comment by MrtnKk** [comment]
@manton Thanks for feed url. As you said, the title tag is not omitted but just empty. I wanted to test the edge case of an omitted title tag because I'm curious what Liferea would do in that case. 

Nevertheless I tested your feed with emtpy title tag and made a screenshot:

![liferea_empty-title](https://user-images.githubusercontent.com/106548322/172053366-b7728a6d-3e77-4951-8730-65e1c2257c51.png)

Liferea adds a 'No Title' string in the feed list.

```
#: ../src/ui/item_list_view.c:483 
 msgid "*** No title ***" 
 msgstr "*** Kein Titel ***"
```

**Comment by trwnh** [comment]
> The problem with using an excerpt in the title is that it's _wrong_. There is no title. It would put the work of handling short, title-less posts in the feed instead of in the feed reader where it belongs. With excerpts, feed readers don't have a chance to display these Mastodon posts correctly. With an empty (or missing) title, feed readers can be smart about showing the post as it's intended to be seen.

there's "technically correct" and then there's "best experience" -- and the reality of most feed readers is that they do not handle it well when there are posts without titles. unfortunately, it's a catch-22. do you do what's "right" at the cost of a worse experience, and no guarantee that feed readers fix their experience? or do you just provide that better experience at the cost of reinforcing what's "wrong", and giving no incentive for feed readers to fix their experience?

i think the latter makes more sense, as it would be better for feed readers to handle title-less posts *before* feeds start publishing without a title. this is likely the motivation for tumblr (for example) using an excerpt of content.

**Comment by MrtnKk** [comment]
Upon further investigation I found out that Liferea supports [postprocessing filtering](https://lzone.de/liferea/scraping.htm). This means you can subscribe to a feed and pipe its content into a script which augments the feed/extracts certain bits before displaying it in Liferea.

So I wrote a shot little python script to remove all title elements from @manton's feed to test this edge case in Liferea.

`#!/usr/bin/env python3

from sys import stdin, stdout
from xml.etree.ElementTree import ElementTree

tree = ElementTree()
tree.parse(stdin)

for node in tree.findall('./channel/item'):
    for title in node.findall('title'):
        node.remove(title)

tree.write(stdout, encoding='unicode')`

Unfortunately Liferea still only shows `*** No title ***` (see screenshot [above](https://github.com/mastodon/mastodon/issues/18553#issuecomment-1146807065)). I guess Liferea must then be considered to **not** handle an empty title correctly.

**Comment by gudzpoz** [comment]
I want to add that the current title (publishing date) seems to be in English only and in UTC (seriously?) (I might get it wrong though) and I do not think there is a way to localize that correctly on the server side.

Even if it servers only as a placeholder, I do doubt whether it is actually appropriate to present such fields directly to the users, since, for internationalization purposes, you expect clients, instead of server APIs, to handle rendering of dates.

**Comment by Gargron** [comment]
Title removed in #18640
