### ISSUE TITLE
Limit height of images in timelines to 2:3 instead of cropping

### ISSUE THREAD

**Issue by zakwilson** [mastodon/mastodon#18686]
### Pitch

By default, Mastodon currently crops images in timelines to a 16:9 aspect ratio if they're taller than that; there is a setting to disable the crop completely. I propose ~~changing the default aspect ratio to 2:3~~ no crop by default unless the height exceeds 2:3.

### Motivation

* Photography is a large and important component of what people share on social media across (almost) all platforms/software
* 16:9 results in most photographs being displayed cropped, which makes Mastodon less appealing as a place to share photography
* 3:2 and 4:3 are the native aspect ratios of the vast majority of stills cameras and smartphones
* Shooting in portrait orientation is popular, making 2:3 the tallest common uncropped aspect ratio for photographs
* Having a default ~~crop~~ height limit is desirable; extremely tall images in timelines can be disruptive
* Defaults matter; most users don't change them
* Because Mastodon is the most popular fediverse software by a large margin, its defaults affect the appeal of the entire fediverse for sharing photography

I looked through the commit history and issues briefly and could not find any rationale given for 16:9, so I can't address the original motivation for that choice here.

**Comment by leecalvink** [comment]
16:9 is indeed weird to be the default on Mastodon, or anywhere really. Decent for panoramas of mountains but people aren't uploading landscape photography more than other things. I think it should be changed to 3:2 or 4:3 as the default as that is the native ratio for most people casually posting pictures.

**Comment by garryknight** [comment]
Agreed. 16x9 often leaves me guessing what I'm looking at. When I'm looking at dozens of posts with photos every day, and often more, having to click each one to view it properly, then click again to close it, is painful to me as an arthritis sufferer.

It's good when the web interface or an app allows me to choose the placement of the 16x9 'window onto the photo but it's often difficult to decide which part to obscure, and sometimes leaves the photo looking decidedly odd.

I know about the option, on the web interface, at least, to turn off cropping but many people are still using monitors at HD or lower resolution.

**Comment by trwnh** [comment]
What about 1:1?

**Comment by zakwilson** [comment]
Setting the height limit to 2:3 would allow 1:1.

I may have been unclear in the original description. I'm proposing changing this:

`style.height = width / (16/9);`

to this:

`style.height = Math.min(style.height, width / (2/3));`

**Comment by trwnh** [comment]
I think fixed 1:1 allows for the most robustness in layout without being too tall *or* too wide. a grid of squares is very straightforward to display.

**Comment by zakwilson** [comment]
This issue relates to single images shown in timelines in Mastodon's web UI. Those are currently cropped to 16:9 by default; I'm proposing that they not be cropped by default unless taller than 2:3. I don't think posts in timelines are ever displayed as grids.

Single images should not be cropped to 1:1 by default because that would still mean most images are displayed cropped.

Posts with multiple images are handled differently and beyond the scope of what I'm proposing. A larger overhaul of how posts with media are handled might be valuable, but the change I'm proposing here is not so broad in scope.

**Comment by trwnh** [comment]
There is an option for not cropping btw: /settings/preferences/appearance and then under "Post layout" uncheck the box for "Crop images in non-expanded posts to 16x9"

![image](https://user-images.githubusercontent.com/10606431/199365108-2e49cd5f-7188-4331-9484-bc02fca70070.png)

There's no max height on that, but you could add one.

**Comment by zakwilson** [comment]
I know there's a setting, but defaults matter; most people don't change them. Most people using Mastodon will see almost all photographs cropped unless they click to expand, and I think that's a terrible default.

A height limit is, however a good idea if images are not cropped because posting an image with an extremely tall aspect ratio is a vector for abuse.

**Comment by Gargron** [comment]
I think for a lot of people it matters how many posts can fit on the screen at the same time. I've received complaints about some design changes lately in a similar way. So in that sense 16:9 is better than 2:3 or 3:2.

**Comment by zakwilson** [comment]
If some users strongly desire a more compact layout, perhaps the solution is to replace the "crop images" setting with a "maximum image height/aspect" setting. I maintain that the ideal default value is 2:3 since that would leave most photographs uncropped while still cropping pathological images.

An alternate solution would be to keep the existing setting, but default it to off and hardcode a very generous limit like 1:4. I tested DMing myself a 1:10 image and that would definitely be disruptive in a timeline.

**Comment by trwnh** [comment]
@pcora there is an option to disable cropping btw https://github.com/mastodon/mastodon/issues/18686#issuecomment-1299381533

**Comment by zakwilson** [comment]
> How about no cropping at all?

I am broadly in favor of no cropping at all, but posting extremely tall images is a potential mechanism for abuse, so it's probably a good idea to have a limit. Furthermore as Gargon said, some users want to force a compact view no matter how badly it mangles photographs in their feed, so the height limit should be user-adjustable.

I have cropping disabled for both myself and visitors to my instance, but defaults matter.

**Comment by zakwilson** [comment]
It looks like glitch-soc has addressed this with an option to scale rather than crop images. That, too is an improvement because:

* It presents the work as the photographer intended, just small
* Viewers can tell there's more to see, while Mastodon's default crop does not make it obvious the image is cropped

**Comment by Znuff** [comment]
I'm hijacking this discussion, but is there a way to disable the resize/crop for all new accounts, by default? Even if I have to edit the database somehow

**Comment by zakwilson** [comment]
@Znuff it will use the setting from config/settings.yml for all new accounts.

**Comment by mhaluska** [comment]
> @Znuff it will use the setting from config/settings.yml for all new accounts.

This is fine, but it's hard to maintain this file because of future changes, would be better have this saved in db as "default profile" settings.

**Comment by interpixels** [comment]
I also think that the default crop should ideallly be 2:3. This is the standard aspect ratio of most modern cameras in vertical.
But heck, pretty much everything would be better than 16:9. Even Instagram, which I consider a user-hostile and artist-hostile platform, has 4:5. And Twitter also accepts vertical images.

1. How many people will even realize that it is possible to change the default aspect ratio? I think it is mostly photographers / graphic artists / developers and web designers who are even familiar with that term. I know an owner of an ad agency who didn't even understand what aspect ratio meant when I mentioned it to him.

2. Most people will not change the default and the result is a butchered visual experience if someone is into photography or visual content. I recently installed an Android app (Fedilab) and that option is buried and renamed there. And Fedilab doesn't even respect the setting that I had set in the web version. It took me a long time to find that option, at first I thought that it wasn't even possible to change the nasty crop in Fedilab.

3. I see absolutely zero real advantages of the default crop being 16:9. Is the scroll speed faster? Even if so, the difference is marginal, negligible and negated when the user has to click/tap every time to see the full picture. We may think what we want about Instagram and Twitter for various reasons (and I don't like them), but the fact is that they must have done a lot of research in that area with a huge amount of data. And apparently they have concluded that supporting vertical aspect ratios as the default is good.

4. Changing the default setting is only possible if the user is logged in. But Mastodon can also be viewed anonymously in a browser (and rightly so). Now, please imagine a photographer / graphic artist considering a Mastodon account. They will perform some test search to see what Mastodon is like. And if they see a stream of artworks butchered by the default crop, many may think: "WTF, this looks bad" and never set up an account.
 
I am quite new to Mastodon and have become a huge fan. As a visual content creator I think it has the potential to become the best thing for us since bread came sliced. But the awareness that if I post vertical content, most people will probably see in a butchered form, is driving me nuts every day when I think of it.

Why not do it in a user-friendly way giving people a choice? The default crop 2:3 to present correctly the beauty of visual content posted on Mastodon to all people, including anonymous viewers. And if someone complains, they could always change it to 1:1, 3:2, 16:9 or no crop in the settings. The full version of the image is loaded anyway already in the browser, with crop or without it.

Conclusion: I see zero advantages of the current setup, only serious disadvantes. In many cases the rather brutal crop can destroy the beauty of the artwork in the default view. 

I'm sorry if my language was a bit too passionate or emotional, but this is the way I feel about Mastodon and this topic. 
I am truly amazed seeing what Eugen and the developers have achieved, it is such a fantastic platform, but this little thing is such a major facepalm moment for me that I can't stop thinking of it. Cheers!

**Comment by markrprior** [comment]
> I think for a lot of people it matters how many posts can fit on the screen at the same time. I've received complaints about some design changes lately in a similar way. So in that sense 16:9 is better than 2:3 or 3:2.

But is that a case of the tail wagging the dog? Shouldn't the default be something that appeals to the majority and then have a way of tuning it for those that have issues with the default setting?

Also making it attractive for those that aren't logged in (ie potential new users) should be a consideration on how the defaults for the web are defined.

**Comment by kraftskunk** [comment]
Definitely agree with this.

**Comment by be8ch** [comment]
I am also in favour of changing the default setting. Personally I would suggest displaying all media at its original aspect ratio (so all images appear uncropped in the timeline) rather than simply replacing 16:9 with another arbitrary choice.

But if there has to be a standard aspect ratio then 1:1 or 2:3 would be far better than the current choice.

**Comment by zakwilson** [comment]
Another way to handle this is to use a fixed-size area for images and scale them to fit; glitch-soc, a more experimental fork of Mastodon offers this as an option. I'd be happy if it was Mastodon's default, though a setting to make the max height of the image area taller would be nice.

**Comment by interpixels** [comment]
> I am also in favour of changing the default setting. Personally I would suggest displaying all media at its original aspect ratio (so all images appear uncropped in the timeline) rather than simply replacing 16:9 with another arbitrary choice.
> 
> But if there has to be a standard aspect ratio then 1:1 or 2:3 would be far better than the current choice.

There should be some kind of limitation to prevent abuse by individuals who would like to post images 1 million pixel tall :)
I wouldn't say that 2:3 is just "another arbitrary choice". Most modern cameras (DSLRs, mirrorless, compacts) have 3:2 sensors, so in vertical orientation they produce 2:3 photos. Therefore, it seems natural to me. If you take a photo with a camera in vertical orientation, you shouldn't be afraid that it will get butchered when you post it on Mastodon.

**Comment by zakwilson** [comment]
After further investigation and reflection, I now think the best solution would be:

* No cropping, ever. Only scaling.
* Max height to trigger scaling should be based on a percentage of the viewport height, as a user setting with some reasonable default (I like 50%).

I should probably open a new issue for that as it has drifted a bit from the original proposal.

**Comment by marktheascetic** [comment]
Anti-crop here.  I have had to drag about 100 images to my desktop just so that I can see the whole image at once.

**Comment by zakwilson** [comment]
Fixed in #26132
