### ISSUE TITLE
`from:` term is not working properly for remote user

### ISSUE THREAD

**Issue by tribela** [mastodon/mastodon#18791]
### Steps to reproduce the problem

1. search `from:localuser` on search bar
2. results are shown. (which are posts that I interacted)
3. search `from:user@fromremote.tld` on search bar
4. results are empty.
...

### Expected behaviour

Results are posts that I interacted before

### Actual behaviour

Nothing shown

### Specifications

Mastodon v3.5.3, v3.5.3+glitch
Browser: firefox

**Comment by VyrCossont** [comment]
Confirmed on 4.0.0rc2. Searching `from:localuser` succeeds, while `from:localuser@localdomain.tld` also fails.

I suspect the issue is [here in `app/services/search_service.rb`](https://github.com/mastodon/mastodon/blob/eb51e43fb4386120f77f2ff99581f15018a81bd4/app/services/search_service.rb#L90-L94): an `@` or `#` anywhere in the query will skip full-text search unless the query also contains a ` ` (space), and in fact, disabling this check on a test instance produced the expected results. I think the right thing to do here is to process all queries as if they were full-text searches, unless the search `type` is explicitly set to `accounts` or `hashtags`.

**Comment by VyrCossont** [comment]
This seems to have been fixed somewhere between 4.0.0rc2 and 4.3.0-nightly.2024-05-29. Searching for `from:remoteuser@domain.tld` works properly for me now.
