### ISSUE TITLE
Audit log shows two timezones

### ISSUE THREAD

**Issue by KNTRO** [mastodon/mastodon#18966]
### Steps to reproduce the problem

1. If you're an admin or a mod of an instance, go to [instance_domain]/admin/action_logs
2. Look for a report resolved with a note
3. You will see two timezones, the local time under "Audit log" and the UTC timezone under "Notes"
![Mastodon_audit_log](https://user-images.githubusercontent.com/2568821/184498353-f209c298-fe80-4116-bbbd-0d46cca6ad9c.jpg)

### Expected behaviour

One unique timezone should be used

### Actual behaviour

Two timezones are used instead

### Specifications

Mastodon Web v3.5.3

**Comment by ClearlyClaire** [comment]
Good catch! Pretty much all other timestamps are rewritten client-side with the local timezone, while the report notes are formatted server-side and not rewritten client-side.

I suppose this is because they don't display the full time but only the date for things earlier than the day they were posted, but I'm not sure this is a worthy distinction, and they should be rewritten using local time either way.

**Comment by KNTRO** [comment]
Still happens on v4.0.2.
![image](https://user-images.githubusercontent.com/2568821/209880648-63b86d2e-5f21-48bc-90a3-777e133b4741.png)

**Comment by ClearlyClaire** [comment]
https://github.com/mastodon/mastodon/pull/21878 is more recent than 4.0.2
