### ISSUE TITLE
The URL to a post when logged in should be the same as the external URL to that post

### ISSUE THREAD

**Issue by BigZaphod** [mastodon/mastodon#19075]
### Pitch

Ideally the URL in my browser when viewing posts in the web UI should be the same as the external URL to avoid confusion when sharing links to posts.

### Motivation

I initially wrote this as a thread but decided to make it an official issue: https://mastodon.social/web/@bigzaphod/108902355844690165

A Mastodon thing that has tripped me up a number of times now is that the URL in my address bar when viewing a post in the web interface is *not* the URL I should apparently be using to share a post externally.

When I'm logged into the web UI the URLs have a "/web/" component in the path which seems to cause people who click on it to be prompted to login.

If I use the share button on a post, I get presented with a standard share popup on macOS - but it doesn't give me a Share Link option because, I suspect, the web app is also sending along the text of a post and that must somehow disqualify the "share link" action from showing up.

But if click on Messages, for example, I get the share window.. and it has both the text and the *actual* external link I should be using to share a link to a post at the bottom.

![](https://files.mastodon.social/media_attachments/files/108/902/360/837/826/959/original/5ec9a40f078c4ac1.png)

![](https://files.mastodon.social/media_attachments/files/108/902/363/847/792/503/original/06ee7b5b4f3f434c.png)

Given the problems using the stupid share stuff in macOS in general, I usually avoid it and prefer to just clicking the Share button in Safari itself to share a link to the page I'm on, or just copy the URL manually and paste it somewhere.

But then we're back to the beginning - the URL that gets shared with that process has "/web/" in it and the recipient can't use it without signing in which is a high barrier.

Ideally the URL in my browser when viewing posts in the web UI should be the same as the external URL so this sort of thing can't happen at all.

**Comment by BigZaphod** [comment]
Ok after additional investigations (check the thread replies) it seems like maybe the URLs with /web/ in them redirect to the external URL anyway and someone around here is confused (probably me)?!

I know I've been bitten by this a couple of times in the past when I posted links to mastodon.social posts on Twitter and then people told me it was prompting them to login. I noticed at the time that the links had /web/ in them.

Of course I went and ranted about this today but didn't check it first. So either it *used* to do this and has since been fixed or this is a per-instance situation.. or I'm just totally out to lunch here. The possibilities are endless.

**Comment by Cassolotl** [comment]
Okay so I've got a couple of thoughts here: the bit where I feel like this might not be possible, and the workaround that I use, and a Github feature request that I opened ages ago that might resolve this a bit.

**1. The bit where I feel like this might not be possible**

So let's say I'm on queer.party (cos I am) and you're on mastodon.social (I don't know if you are). I post something, and that post is hosted on queer.party, and the URL for that post looks something like https://queer.party/@cassolotl/108902550148660585 - it has the instance URL in it.

Your web UI is on *your* instance, mastodon.social. So when you're logged in you can view any post in your right-hand column of the web UI, but the URL has to start with your instance URL - probably https://mastodon.social/web/somethingorother

So they can't be the same because they're on different instances. And it might be possible to set up some kind of redirect thing, but then what if you're signed into more than one instance at once because you've got an account on *both* thing.whatsit and mastodon.social? Maybe a couple of extra steps, like "which instance's web UI would you like to view this tweet in? [selectable options]"

So I think maybe it is possible to set up something like what you're asking for, but it might be a bit convoluted, and I think the reason it hasn't happened is because of the surprisingly simple workaround. Which leads me nicely to...

**2. The surprisingly simple workaround**

For people new to the fediverse this is probably not intuitive AT ALL, but if you copy a fediverse post URL (e.g. https://queer.party/@cassolotl/108902550148660585) and paste it into your own home instance of mastodon's search bar and press enter, the post appears there under the search bar and you can boost it, reply to it, etc. Like so:

<img width="303" alt="Screenshot 2022-08-28 at 22 54 23" src="https://user-images.githubusercontent.com/6607512/187095972-3569a50b-4eba-4199-abdf-3ce1e440d452.png">

**3. Feature requests that might be related**

Clicking a URL of a toot in the web UI should open the toot in the search area #2136

[Feature request] Outside of web UI, all toots could have an "open in web UI" button #10808

**Comment by BigZaphod** [comment]
I didn't even think about cross-instance stuff and that certainly makes some things more complicated - I was just having issues sharing links to my own posts on mastodon.social from my twitter account. I'd naturally just copy the URL from the address bar in the mastodon.social web UI, and then paste it in Twitter and then get people complaining that the URL I posted was wanting them to login.

However that doesn't actually seem to be happening *today*... so I have to wonder if this has changed somehow or what other circumstances might lead to a URL copy-pasted like this causing others to have to login.

I know in my case I've only ever tried to share links to my own posts, so the cross-instance situation shouldn't be something I was encountering - but it's very good to have this spelled out the way you did here, @Cassolotl, because that's info I needed to know. Despite having a Mastodon account for awhile I still keep falling back to non-federated/twitter-like assumptions all the time!

**Comment by Cassolotl** [comment]
Aw, glad I helped!

>I'd naturally just copy the URL from the address bar in the mastodon.social web UI, and then paste it in Twitter and then get people complaining that the URL I posted was wanting them to login.

I've gotten into the habit of right-clicking the timestamp on posts and choosing "copy link's URL", because that always leads to the page for the post itself, if that helps. And the post will show up to anyone regardless of whether they're logged in, provided it's a public or unlisted post. 👍

**Comment by ClearlyClaire** [comment]
The original suggestion of showing a remote instance's URL in the browser's address bar when you are viewing it on your own instance is simply not possible.

There also have been several changes since this issue has been open that should clear some confusion and hopefully improve the user experience:
- the server-side rendered pages have been removed, and everything uses the web interface even when logged out. This means there is no `/web` link anymore (links to remote content will redirect logged-out users)
- the search bar's prompt has been changed to “Search or paste URL”, which should better inform people about the “surprisingly simple workaround” you mentioned
