### ISSUE TITLE
Missing toots on local & public

### ISSUE THREAD

**Issue by mstdn** [mastodon/mastodon#19459]
### Steps to reproduce the problem

1. Update to latest source
2. Check local & global timeline
3. See toots not being there. Or very old ones while there are new ones.
...

### Expected behaviour

See new toots

### Actual behaviour

No new toots

### Specifications

Masto 3.5.3 main

**Comment by mstdn** [comment]
Little update, when I set my UI lang to Dutch my toots won't appear on the Public or Local timeline while I do NOT have selected any pref languages in settings!

On EN UI things work fine. It seems UI lang filters toots automatically?

**Comment by Gargron** [comment]
Related: #19291

**Comment by databu** [comment]
Not sure if this is the same issue, but since today my local and federated timelines on https://mastodon.online are empty. My UI language is English, and I also tried to explicitly enable English, German and a few other languages in the settings, but they stay empty. 

Local shows:
> The local timeline is empty. Write something publicly to get the ball rolling!

Federated shows:
> There is nothing here! Write something publicly, or manually follow users from other servers to fill it up

**Comment by databu** [comment]
There seem to be [scaling issues on mastodon.online](https://discord.com/channels/231908446830723072/734462071177216042/1039015219642515456), so probably my issue is related to that.
