### ISSUE TITLE
Dark Mode - Edit box is not dark

### ISSUE THREAD

**Issue by VikOlliver** [mastodon/mastodon#19561]
### Steps to reproduce the problem

1. Set Web GUI preferences to Dark Mode
2. Go to main page.
3. Enter a new toot.

### Expected behaviour

Expect white text on a dark background.

### Actual behaviour

You are now looking at black text on a white background.

### Detailed description

Complaining that the edit box isn't in dark mode in Dark Mode may seem like nit-picking. Far from it.

Dark Mode is not a trendy toy. It is actually a fix for an accessibility issue: Partially sighted people can see white text on black far easier than black text on white.

While it may look all aesthetical, it's not helping accessibility.

### Specifications

Mastodon v3.5.1
Firefox 105.0
Ubuntu 20.06

**Comment by VikOlliver** [comment]
Note: Medical references will state that half of people with visual issues will find dark text on white to be more readable. But it is unlikely that they will be choosing dark mode.

**Comment by Gargron** [comment]
Related: #19205

**Comment by mgifford** [comment]
@VikOlliver just wanted to say that visual disabilities are just one group that can benefit from dark mode. Not everyone likes it, some people need it (I know someone who just needs it in the morning). Some people get headaches when they spend to long staring at a white screen. 

Main thing is that allowing people to personalize how content is displayed helps everyone. Maybe I just want to be using dark mode when it is dark outside and less light is needed, or because they want to save battery power.
