### ISSUE TITLE
Wrong F-Droid link previews

### ISSUE THREAD

**Issue by Moe23333** [mastodon/mastodon#19573]
### Steps to reproduce the problem

1. Send a detail link of an App on F-Droid
2. Click the link preview

### Expected behaviour

link to the correct link

### Actual behaviour

linked to the incorrect link

### Detailed description

As the picture:
![image](https://user-images.githubusercontent.com/35591595/198945764-9452cd46-c7c3-423b-9984-960f3b416740.png)

There are some examples that have this problem that be tested on mastodon.social
https://mastodon.social/@Moe23333/109261329314483136
https://mastodon.social/@Moe23333/109261395969713809

### Specifications

Mastodon 4.0.0rc1 (on https://mastodon.social)

**Comment by ClearlyClaire** [comment]
Related to #19538. Basically, preview cards try to link to the “normalized” representation of a post (mainly to avoid internally duplicating preview cards). In this particular case, it's because F-Droid app pages contain `<link rel="canonical" href='https://f-droid.org/'/>`, basically stating that https://f-droid.org represents the same resource as https://f-droid.org/en/packages/org.wikipedia/. Arguably, that is an issue with the F-Droid website, although we should probably find a way to present the preview card with the original link regardless of how the preview card is stored internally.

**Comment by obfusk** [comment]
F-Droid issue: https://gitlab.com/fdroid/fdroid-website/-/issues/643

**Comment by uniqx** [comment]
F-Droid finally fixed their bug, so I guess this issue can be closed for good now.
