### ISSUE TITLE
keyboard navigation: bottom focused toot not scrolled into view

### ISSUE THREAD

**Issue by herrgahr** [mastodon/mastodon#19591]
### Steps to reproduce the problem

1. be using Firefox
2. go to a scrollable list like Home
3. Focus a toot
4. press 'j' often enough to cause downwards scrolling

### Expected behaviour

the bottom (newly focused) toot should be scrolled into view

### Actual behaviour

in ~ 9 out of 10 cases, only avatar + username is visible

### Specifications

Mastodon 3.5.3 and Mastodon 4.0.0rc1

Firefox 105.0.1
> Issue **not** present on Chromium 106.0.5249.91

Arch Linux

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this issue can be reliably reproduced on an updated version please request that this issue be reopened or open a new issue. For either option please provide updated logs/troubleshooting on a recent release. Thank you.
