### ISSUE TITLE
Federated links break Open In New Tab

### ISSUE THREAD

**Issue by SamStephens** [mastodon/mastodon#19652]
### Steps to reproduce the problem

1. Log into the web interface of the Mastodon instance that's your home
2. On your homescreen, find anything in your feed that is from a federated instance (post, tag, user, etc).
3. CTRL-click the link, or use Open In New Tab.

### Expected behaviour

I expect CTRL-click to take me to the post/tag/user on my home instance, just like clicking it would.

### Actual behaviour

I'm taken to the instance the post/tag/user lives on, where I cannot interact with it.

### Detailed description

I'd imagine I'm not the only person who wants to be able to spin things off into multiple tabs as part of my normal social media workflow. Use cases like looking at a replying user later without interrupted my reading of a thread, or losing my place within it.

### Specifications

Not specific to any Mastodon version AFAIK.

**Comment by SamStephens** [comment]
Probably https://github.com/mastodon/mastodon/issues/19075 deserves to be considered alongside this.

**Comment by ClearlyClaire** [comment]
My perspective may be skewed as a long-time Mastodon user (and developer), but when I middle-click/ctrl-click the link, I expect it to open the remote content on its original source, and would greatly dislike if it changed to opening another tab of the local instance.

That being said, I understand your use case, and while I can't offer you a fully satisfying solution at the moment, the following two existing Mastodon features may alleviate the issue somewhat:
- you can bookmark posts to later get back to them
- you can paste a remote address in the search box to view it locally
- there is an “advanced web interface” setting to have a multi-column interface, which lets you see a thread in a separate column while still keeping your position in pinned columns

**Comment by SamStephens** [comment]
> My perspective may be skewed as a long-time Mastodon user (and developer), but when I middle-click/ctrl-click the link, I expect it to open the remote content on its original source, and would greatly dislike if it changed to opening another tab of the local instance.

The thing here is that it may be a familiar Mastodon experience, but it violates web standard behaviors. You're breaking the normal behavior of a link. Hijacking "Open In New Tab", and changing the behavior to be "Open *Original Source* In New Tab". It's a useful function to have, but I would argue it's not something that should hijack a standard function.

**Comment by trwnh** [comment]
isn't that backwards? the normal behaviour of a link is to take you to the URL that it links to. if anything, having a remote link open on the local instance is what would require hijacking the link. and in fact, this "hijacking" is exactly what's happening when you click a link inside a federated post -- the client detects it as a Mention or a Hashtag or whatever, and loads it in-app instead of loading it externally.

consider the following html generated by the webapp:

```
<a class="u-url mention status-link" href="https://nya.social/@natalie" rel="nofollow noopener noreferrer" target="_blank" title="natalie@nya.social">@<span>natalie</span></a>
```

the "web standard" behavior would be to load the remote website (nya.social), regardless of whether you open it in the same tab or in a new tab.

**however**, what is *actually* done is to attach a click handler event to the link, in javascript. this way, you load the Mention inside the webapp -- you load it locally *instead of* opening the remote website.

to behave as you are proposing, you would essentially have to replace the link URL (`nya.social/@natalie`) with a proxy URL (`mastodon.example/@natalie@nya.social`) or otherwise "hijack" the new tab behavior of your browser.

**Comment by SamStephens** [comment]
What I've missed here is that the href links to the original source rather than the local instance. Regardless, the Javascript is hijacking web standard behavior.

> to behave as you are proposing, you would essentially have to replace the link URL (nya.social/@natalie) with a proxy URL (mastodon.example/@natalie@nya.social) or otherwise "hijack" the new tab behavior of your browser.

My suggestion is that the link URL is an URL on the local instance, not on the original source; no hijacking involved. Just a normal HTML link that any piece of HTML reading software can understand, no Javascript magic.

**Comment by ryliejamesthomas** [comment]
Due to how federation works it's much more useful for the link to go to the original post on the original instance, as that will give you a better view of the following conversation. Especially useful if you're on a small instance. This's also how I expect a permalink to behave.

I think it would be logical if middle/Ctrl-clicking on the post body could open the post on the reader's instance though.

**Comment by trwnh** [comment]
Middle/CTRL click on post body seems far more feasible to implement, yeah.

**Comment by SamStephens** [comment]
> Due to how federation works it's much more useful for the link to go to the original post on the original instance, as that will give you a better view of the following conversation.

It's not useful for the link to go to the original instance, because I don't take my identity along with me. Any time I'm taken away from my local instance, the infrastructure of Mastodon as a bunch of federated instances is leaking into my experience, I'm losing that continuity of remaining logged in as me.

I'd argue that the links provided for posts/users/etc on a local instance should be within the context of that instance, because that's the experience a user wants; to interact with content *with their Mastodon identity*. And then a Share link or similar provides a canonical link.

This is pretty similar to the experience provided on a lot of websites. For instance, when I'm browsing YouTube, the links I see for videos include a bunch of context specific to my identity and browsing experience. For example https://www.youtube.com/watch?v=-FhhB9teHqU&list=WL&index=8 is the URL for a video I was viewing as the 8th video in my watchlist. Useful in the context of me experiencing YouTube in the context of my identity, but not for sharing. The share button gives me https://youtu.be/-FhhB9teHqU - a canonical link for that video, separate to the context of my identity.

Likewise, I suggest links on an instance should be local to that instance for the user experience, and then a share button gives the canonical link to a resource on it's home Mastodon instance.

**Comment by SamStephens** [comment]
Independent to this issue, I do still want to argue it's an antipattern for a link to have Javascript that takes you to an URL other than the href of the link. As I first complained, it breaks Open In New Tab. But it also breaks all sorts of other use cases. It breaks Copy Link or Bookmark Link. It breaks TamperMonkey scripting. It breaks other extensions that do useful things with links.

One of the powerful things about HTML and markup languages is that you simply provide the semantic markup (this is a link to a particular place), and then it's up to the consumer what they do with that. You're breaking that by adding Javascript that is inconsistent with the href specified in the links.

Which is not to say that having the Javascript itself is bad; there's nothing wrong with hijacking a link to dynamically update the page and URL. But the end result should be equivalent to what would happen if the href of the link was navigated to.

**Comment by trwnh** [comment]
Once again, there is no Javascript for taking you to a URL other than the href. What is happening is that the URL is effectively being loaded within the webapp instead of within your browser. What is happening with New Tab *is* taking you to the href. So that's not broken.

What you seem to be arguing for or otherwise expecting is that normal clicking should open the remote website in the same tab. This would put you in the state which you argue is "not useful". Arguably, this state can be made (more) useful by having cross-domain authorization, so that the remote website has access to your account and you can interact natively there. But this is a massive change to the trust model -- you now have to trust every single website you visit instead of trusting just one website (the one that hosts your account).

It is only *because* of the Javascript hijacking that you can remain "within the context of your local instance".

The alternative, if you wish to stay completely local, is to rewrite and proxy every single URL.

**Comment by SamStephens** [comment]
@trwnh we may have a difference in terminology here.

> What you seem to be arguing for or otherwise expecting is that normal clicking should open the remote website in the same tab.

I am not arguing this.

Maybe a concrete example will make things clearer.

My local instance is mastodon.nzoss.nz. I'm currently viewing a toot in my timeline, The link shown for this toot is https://mastodon.ar.al/@aral/109290545572206366 , the canonical URL on the home instance of the toot.

However when I click on this toot, my browser URL is updated to https://mastodon.nzoss.nz/web/@idanoo@mastodon.nz/109295163972495076. If I copy this URL and paste it into a fresh tab, it takes me to the toot as viewed from my home instance.

I am arguing that when the mastodon.nzoss.nz Mastodon instance renders the link for this toot, it should render it with the href being https://mastodon.nzoss.nz/web/@idanoo@mastodon.nz/109295163972495076, reflecting that clicking the link takes me to the toot in the context of my local instance. That way the link's href reflects what the link actually does (show me the toot via my local instance), and I'm free to copy/paste, Open In New Tab, or script it to my hearts content.

**Comment by trwnh** [comment]
So rewrite and proxy every single URL, then?

**Comment by SamStephens** [comment]
> So rewrite and proxy every single URL, then?

I'm not sure what you mean by this sorry.

I am suggesting that as these links take you to URLs on the local mastodon, such as https://mastodon.nzoss.nz/web/@idanoo@mastodon.nz/109295163972495076 for my example above, they are links to the local mastodon instance. I am suggesting that it's easier for users to understand if the href of these links reflects the destination they actually take users to.

You are already "rewriting" every single URL. When I click on the time of a Toot with remote URL https://mastodon.ar.al/@aral/109290545572206366 when I'm using my home mastodon.nzoss.nz instance, some part of the onclick handling sets my current browsers URL to https://mastodon.nzoss.nz/web/@idanoo@mastodon.nz/109295163972495076, meaning the logic to generate a local URL for a remote object already exists.

I'm simply suggesting that it's more user friendly to use that local URL as the href for these links, rather than only using that URL once you actually click them. It could be done either in the client-side template that actually renders the status, using the existing logic you have for generating local URLs, or serverside as an additional attribute of the status object that's returned in JSON.

**Comment by trwnh** [comment]
Yes, okay, so "rewrite and proxy" means like so:

- You have the original URL (remote.site/@friend/1234)
- You have the proxied URL (local.site/@friend@remote.site/5678)
- Statuses are delivered from remote.site to local.site with the original URL
- You want the webapp to rewrite all of those original URLs so that they are proxied URLs

This is of course doable, as you have noticed, the Javascript web-app hijacks Mentions and Hashtags but not canonical status URLs, and your browser takes you to the proxied URL. In fact, some other software such as Pleroma also does the same. But this has the side effect of letting you browse cached copies of one remote website on a different remote website. See for example https://pl.nulled.red/users/AHM3kxcDi6t2Hqri7c as a way to browse `mastodon.social/users/trwnh`.

I think for Mastodon, this should not be an issue, as proxy URLs seem to currently redirect to canonical URLs for logged-out viewers. For logged-in viewers, proxy URLs should load the web-app as you are expecting. Maybe this is indeed "better", as long as the redirect is kept for logged-out users. What do you think, @ClearlyClaire?

Probably the most sensible way to approach this request is as follows:

1) Use proxy URLs everywhere
2) Add a menu item to load the canonical URL (call it something like "Open on external website")

**Comment by laurelnaiad** [comment]
Hi, I'm a newbie to Mastodon as well as a web developer and a big "open in new window" person as a web content consumer.

As this is my first appearance in this repo, I want to say THANK YOU to the team for such an awesome product and awesome community. I'm loving it, and doing my best to slide in an unobtrusive way.

That said, *this issue* is one that has dragged me out of my attempts to lay low while I get my feet wet. The current behavior really confounded me for a day or two, until I realized I was getting different behavior for opening links [to user profiles or to toots] in new windows than I was for single clicking them.

Having realized that the different behavior is consistent and must be a design decision, now I'm just puzzled and somewhat frustrated about the design.

Newbies are going to trip over this a lot, and surely already are doing so. They may not express it with any reference to something that resembles the root cause, but they are going to be impacted most especially when the Follow button/Favorite buttons/etc. works on some pages and not others and when they are suddenly looking at a page which looks a lot like the last page they were on, except they don't seem to be logged into it, and essentially nothing works on the page. 

I don't think the current inconsistent behavior is doing anything good for uptake, and is probably resulting in some people just wandering off thinking the site is buggy or confusing, perhaps expressing their frustration on other platforms.

I totally understand the use case for giving people a path to the origin server's [canonical] view of a profile or post. But until or unless the canonical view becomes a functional view for the user (with working follow button/favorite buttons/ability to reply, etc.) it should not be the place where users end up for ctrl-click/open in new window scenarios. Open in New Window does not mean Open Canonical View on Server Where I Don't Have an Account, at least not to the Mastodon-uninitiated.

Therefore, I second the proposal for an "Open [Post or Profile] on External Site" button and/or menu item for cases where a user wants to switch their context to the canonical server, and for the `<a> href` nav URLs to always provide the URL for the domain the user is currently browsing.

Cheers,
Daphne

**Comment by marckranat** [comment]
further to the article here about the SEO concerns which I see already expressed.
https://www.seroundtable.com/mastodon-rel-noferrer-tracking-34391.html
I am concerned as not seeing a referer adds weight when assessing bot like behaviour in many WAFs.

**Comment by SamStephens** [comment]
> further to the article here about the SEO concerns which I see already expressed. https://www.seroundtable.com/mastodon-rel-noferrer-tracking-34391.html I am concerned as not seeing a referer adds weight when assessing bot like behaviour in many WAFs.

The use of `rel="noreferrer"` is not under discussion here, and it's not considered good manners to hijack issues like this. It appears there no issue against this repository for the use of `noreferrer`; I suggest you create a new one. Thanks.

**Comment by SamStephens** [comment]
Thanks for creating the pull request @trwnh . I do intend to get to the point where I can contribute myself, but I've had a lot on - although I did just contribute a tiny documentation fix https://github.com/mastodon/documentation/pull/1011 lol.

**Comment by kococomi** [comment]
I don't like this change at all. 

Though I do understand the need to view a remote post in the context of one's own instance (you might unexpectedly run into idiots you've blocked years ago when opening a remote post on their own server, and you might not want to take the risk of seeing them at all). BUT let's not forget Mastodon is a **decentralized** social platform, people on a small instance might need to open posts on their original page more than 20 times a day (otherwise they would miss tons of information. you could easily see only 11 of the 200 replies of one post if you are on a single user instance).

To me it would be a good idea to add an icon after `status__relative-time` or `detailed-status__datetime` to indicate clicking the button will open a new window. I am doing this for my own instance for years as some people who've used Mastodon for a long time might still be unaware of this feature if the icon is absent. It would be nice if you keep`status__relative-time` redirecting users to view the post on their own instance and add the icon only for `detailed-status__datetime` and utilize the button to redirect users to its original page, because how it works now is pretty weird - you click on `detailed-status__datetime` on a status's detailed page and it brings you to the exact same page. Then why do we need this button at all?

<img width="576" alt="Screen Shot 2022-11-17 at 9 05 10 am" src="https://user-images.githubusercontent.com/76918202/202305674-2193eda4-419e-4f45-a81c-370511c7da80.png">

I mean I 100% understand the need of some people to view posts on their own instance but I do think for a decentralized platform there should be a much easier way to view things on their original servers as well, cause that's how Fediverse works.

**Comment by orithena** [comment]
As far as I can see, implementing a fix for this issue opened up a can of worms. I can see #20744, #20593, #21244 and #21203 addressing the same underlying issue from multiple points of view.

Implementing this issue has broken a deep-rooted UX assumption that right-clicking/long-pressing the timestamp (or, if present, title) of a public post (or a profile picture, too) and copying the link to clipboard copies the canonical, shareable, in any context valid URL of that post (or profile)! And if that link is opened in a new tab, one could copy that same canonical, shareable URL from the browsers address bar.

I cannot remember that I ever used an app that violates this principle. What I've seen is that the whole area of a post is often used as an action button to "focus" that post in-app -- with the tiny exception of the timestamp, which always gives access to the canonical URL (if such a thing exists in the app at all).

Although I'm not an instance admin, I know that at least some admins are wary of inadvertently proxying certain content over their server. With the arguments in #21203 plus the above principle in mind, the "in-app URL" introduced by this implementation can be construed as the canonical URL (even if it is just a proxy URL), insinuating to law enforcement that the instance admin would be responsible.

It also breaks "open in new tab" in the advanced web interface for me, where I really expect to leave the app when I open a post/profile in a new tab. (Instead, I get a new instance of the app in the new tab, showing the same view of the post on the far right, i.e. out of view because of my many columns... but I wanted to escape exactly that view to see the full thread on the remote instance, lest I give the tenth identical answer to a question).

I'd vote to reopen this issue to find a different implementation. I'm sorry to say that I don't see a good solution to the original request in this issue that does not break the above mentioned principle. The nearly-good solution would be a browser extension that makes remote posts immediately interactionable, like [this Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/mastodon-simplified-federation/) did for Mastodon 3.

(Sorry that I'm being passionate about that point. I've been telling non-technical people that principle for a decade now...)

**Comment by SamStephens** [comment]
@orithena there's cans of worms either way.

I would argue that the UX principle that links within a web application should be real links trumps the other principles here. The expectation that if a link when left clicked takes me to a location within the web application, that link should be a real link with the href being the destination within the web application, that I can copy, right click etc.

You may feel like this breaks "open in new tab" for you. I'd argue the previous behavior was broken; it's a fairly standard usage pattern to want to open statuses, users etc into new tabs that you can look at later and interact with using your identity.

You can still get to the canonical URL, it's there on the triple dot menu as Open original page and Copy link to post.

I can see an argument for making the timestamp a link to the original post; that if you left click it, it opens the post in a new tab. It'd certainly be worth opening an issue for that feature.

But going back to the previous behavior breaks fundamental web conventions around how a link should work, how interactions with it should be consistent where you click it, copy it, or open it in a new tab, and going back would be a mistake.

**Comment by ClearlyClaire** [comment]
> I can see an argument for making the timestamp a link to the original post; that if you left click it, it opens the post in a new tab. It'd certainly be worth opening an issue for that feature.

That used to be the behavior before #16171. I believe this was an intentional change, but no rationale was provided.

**Comment by SamStephens** [comment]
@orithena this is much more basic than the semantic behavior of the links themselves. This as a basic part of Progressive Enhancement. That Javascript should improve and streamline the behavior of elements, but not change or provide behaviors. In this case, taking a link into the web application, and enhancing it so that link is enacted by changing the state of the current page, rather than taking you to a new page.

Part of progressive enhancement is so that websites work without Javascript; which doesn't apply to Mastodon as it requires Javascript. But part of it is so that parity is maintain between interactions with the element that invoke the Javascript (in this case, clicking the element and seeing the post within the web application), and interactions with the element that use the elements non-enhanced behavior (CTRL-clicking the element to open the post within the web application in a new tab).

> But due to the decentralized nature of the Fediverse, opening a remote post in a new tab is effectively navigating to a different website, controlled by a different entity (even if most instances look the same!), so you cannot be authenticated there (unless you use a browser extension). 

Which is exactly why it's important the parity of element behavior is maintained, why this change is important. Because otherwise people CTRL-click posts and people, and then are baffled why it behaves differently to a left click, why they cannot interact with the content as themselves in the new tab.

> And I think that users should become aware that they are effectively changing websites/apps.

Which they are now aware of, because they have to use "Open original page" to change website/app.

> I think it is paramount that the canonical URL is not muddied by proxy URLs as it is implemented currently. In other words: If users want to copy the canonical URL to a post, they should not have the option of copy-pasting any URL other than the canonical URL!

That's impossible due to the nature of the Fediverse, because we're always viewing content through our own web application. Even before this change, if I clicked on a post in my timeline, and then copied what's in the URL bar, I'd be copying the "proxy URL" in the web application for my local instance, not the canonical URL.

**Comment by SamStephens** [comment]
@ClearlyClaire 
> > I can see an argument for making the timestamp a link to the original post; that if you left click it, it opens the post in a new tab. It'd certainly be worth opening an issue for that feature.
> 
> That used to be the behavior before #16171. I believe this was an intentional change, but no rationale was provided.

Definitely seems like it'd be worth revisiting in light of this change.
