### ISSUE TITLE
Notification Sounds doubled/duplicate with desktop notifications enabled 

### ISSUE THREAD

**Issue by Schykle** [mastodon/mastodon#19691]
### Steps to reproduce the problem

After enabling desktop notifications on the site, it appears that the website still makes a notification sound of its own independent of the desktop notifications.

There seems to be no toggle to control this which means notifications get duplicated, which is especially problematic on Android if the site is still running because it'll make noises in the background in addition to the desktop notifications. This leads to site notification sounds being able to subvert do not disturb settings or ringer control settings on Android.

### Expected behaviour

On-site notifications should be muted after enabling desktop notifications, or there should be a toggle for doing so

### Actual behaviour

Site notification sounds still happen despite desktop push notifications being enabled

### Specifications

Mastodon 3.5.3
Chrome 107.0.5304.91

Android

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this issue can be reliably reproduced on an updated version please request that this issue be reopened or open a new issue. For either option please provide updated logs/troubleshooting on a recent release. Thank you.
