### ISSUE TITLE
Add the ability to sort servers by popularity, and add server recommendations

### ISSUE THREAD

**Issue by innosflew** [mastodon/mastodon#19726]
### Pitch

Add the ability to sort servers by number of users/popularity, or date of creation, or numbers of posts on the server etc. on the [Mastodon website](https://joinmastodon.org/servers) and on the mobile apps in the server browser. And by default it should sort them by number of users/popularity.

Also, add a tab for a small number of recommended servers by the mastodon devs that they trust and are popular, such as mastodon.social, mastodon.online and/or mstdn.social etc.

### Motivation

I've been browsing Twitter for days now looking for feedback about Mastodon and the biggest complaint I see everywhere is about it is the server browser, and how it's overwhelming and confusing to a lot of people.

I think it would help newcomers if they could easily find the most popular servers or the servers with the most amount of users. I could be wrong but right now to me it seems the server browser just sorts them based on some other random metric.

It would also help a lot if the Mastodon devs were to recommend a couple hand picked servers as well.

**Comment by ClearlyClaire** [comment]
One issue with sorting servers by popularity, or number of users, is that you are encouraging centralization, with large servers mechanically getting more traction because they are large in the first place, while we ideally want to spread the load and power on multiple servers.

The onboarding and instance selection flow obviously needs improvements, but I'm not sure sorting by popularity/user count is a change that makes much sense in this context.

**Comment by SolarAquarion** [comment]
A better mechanism would be a way to automatically find ways to "Balance" the servers. So it lists the different ranks of "Popularity"
