### ISSUE TITLE
Translations do not get pulled from Crowdin

### ISSUE THREAD

**Issue by playmobilmeister** [mastodon/mastodon#19844]
### Pitch

We have 4-6 months old translations in CrowdIn still not updated on v3.5.3. while I understand that this is not a priority project-wise, many newcomers are complaining about this status quo. my understanding is that version 4.0 does not include new translations. Am I right ? and what can I do to push this issue ? thanks

### Motivation

anyone who is not using the English interface will benefit from better translations of the UI.

**Comment by connyduck** [comment]
4.0 does include new translations

**Comment by playmobilmeister** [comment]
Ok, good to know. so it's just not mentioned in the changelog, then ?

**Comment by connyduck** [comment]
Apparently not, but translations are in the diff https://github.com/mastodon/mastodon/compare/v3.5.3...v4.0.0rc1

**Comment by ronilaukkarinen** [comment]
We have noticed the same. Many Finnish translations that are fixed are not being pulled to the versions for some reason. The most notable is the "Follow" button word which has been wrong in since 4.0 and continues to be wrong in 4.1.1. I don't know what's the procedure here, but the Gargron's version is right, the newer is downvoted and wrong. Yet the newer is in the version. See [this](https://crowdin.com/translate/mastodon/52/en-fi#4478).

![image](https://user-images.githubusercontent.com/1534150/229334975-4abf21ef-3280-485e-ab04-b3d108d51eb1.png)

The same goes with some other translations. Today the Finnish community found the "Suspended" word is incorrectly "Jäähy" in the `about.domain_blocks.suspended.title` key in source in version 4.1.1 [here](https://github.com/mastodon/mastodon/blob/2f7c3cb628ddf0438452325c52359f575aab6890/config/locales/fi.yml#L400). However, in the Crowdin it's been great for years, latest fix has been sitting there for four months, see [here](https://crowdin.com/translate/mastodon/52/en-fi?filter=basic&value=0#13404).

So what gives? Why the translations are not being pulled to the versions from Crowdin?

**Comment by playmobilmeister** [comment]
> We have noticed the same. Many Finnish translations that are fixed are not being pulled to the versions for some reason. The most notable is the "Follow" button word which has been wrong in since 4.0 and continues to be wrong in 4.1.1. I don't know what's the procedure here, but the Gargron's version is right, the newer is downvoted and wrong. Yet the newer is in the version. See [this](https://crowdin.com/translate/mastodon/52/en-fi#4478) and [this](https://github.com/mastodon/mastodon/blob/ab85f59c30ff523cb2a6551ca1f36779c2fa81f3/app/javascript/mastodon/locales/fi.json#L32).
> 
> ![image](https://user-images.githubusercontent.com/1534150/229334975-4abf21ef-3280-485e-ab04-b3d108d51eb1.png)
> 
> The same goes with some other translations. Today the Finnish community found the "Suspended" word is incorrectly "Jäähy" in the `about.domain_blocks.suspended.title` key in source in version 4.1.1 [here](https://github.com/mastodon/mastodon/blob/2f7c3cb628ddf0438452325c52359f575aab6890/config/locales/fi.yml#L400). However, in the Crowdin it's been great for years, latest fix has been sitting there for four months, see [here](https://crowdin.com/translate/mastodon/52/en-fi?filter=basic&value=0#13404).
> 
> So what gives? Why the translations are not being pulled to the versions from Crowdin?

Since opening the issue back in November, a further update occurred and finally included our contributions. I undestand your justified frustration and think it takes too long. Not sure who is responsible for pulling them or wether there is evena  person responsible or what can be done. It would have helped if there was a chart somewhere explaining who we can direct these questions too, but I could not find one. I'm keeping this issue open in the meantime
