### ISSUE TITLE
Make toot composition text area have the chosen language assigned to it

### ISSUE THREAD

**Issue by JosePedroDias** [mastodon/mastodon#19858]
### Pitch

Composing toots already allows for specifying the language the toot is written on.
That language choice should be reflected onto the text area by setting its `lang` attribute https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang so the creator gets access to the browser's spell checking features.

### Motivation

People writing toots in multiple languages and/or languages other than the instance's language will still get the benefits of the browser's spell checker features.

**Comment by ClearlyClaire** [comment]
As far as I can tell, that should be addressed by #18544 (present in 4.0.0rc1).

**Comment by Boldewyn** [comment]
Unfortunately, #18544 was about a different feature, i.e. the already posted and now rendered posts. This issue is about the concrete `<textarea>` where people write their posts.

Or more concretely, before this line:

https://github.com/mastodon/mastodon/blob/c3aef491d66aec743a3a53e934a494f653745b61/app/javascript/mastodon/components/autosuggest_textarea.js#L219

should be another line

```jsx
    lang={somehow_get_language_from_dropdown}
```

that reflects what the current author has selected in the language dropdown, https://github.com/mastodon/mastodon/blob/42f9693d0032b5e165568f89d4bf611016a88955/app/javascript/mastodon/features/compose/containers/language_dropdown_container.js .

**Comment by ClearlyClaire** [comment]
Oops, you're right! #23240 should address that

**Comment by Boldewyn** [comment]
Woah, cool! Really looking forward to this patch getting deployed! :tada:  Thank you!
