### ISSUE TITLE
Server Admin pages not available

### ISSUE THREAD

**Issue by gdanov** [mastodon/mastodon#19866]
### Steps to reproduce the problem

1. upgraded to from 4.0.0RC1 to RC2
2. tried to see my sidekiq dashboard
3. figured out all other admin pages listed [here](https://github.com/McKael/mastodon-documentation/blob/master/Running-Mastodon/Administration-guide.md#administration-web-interface) (accounts excl.) are missing too
...

### Expected behaviour

see my sidekiq page

### Actual behaviour

http 404

### Detailed description

nothing relevant is visible in the logs

### Specifications

Mastodon	4.0.0rc2
Ruby	3.0.4p208
PostgreSQL	14.5
Redis	7.0.5

**Comment by ClearlyClaire** [comment]
> 2\. tried to see my sidekiq dashboard

The link has moved to the bottom, it's not in the “Administration” section anymore. If it does not show up for you, it's because you need to have the `Owner` role, which you may not have if you haven't run migrations fully or updated to `main` before 4.0.0rc1 was released.

If you updated before 4.0.0rc1 was released, use `tootctl accounts modify --role=Owner your_account` to give yourself the “Owner” role.

**Comment by gdanov** [comment]
thanks, changing the role did the trick
