### ISSUE TITLE
Link verification on 4.x instance not shown for users on instances running version lower than 4.x

### ISSUE THREAD

**Issue by sn0opy** [mastodon/mastodon#19986]
### Steps to reproduce the problem

1. Have an account on mastodon.social or any instance running 4.0.0rc1
2. Click on users on a Mastodon instance running 3.x which have verified links in their profile. Example (me): `@sn0opy@hessen.social`

### Expected behaviour

Checkmark should appear next to verified link for accounts on instances running version 3.x

### Actual behaviour

Link is being shown as not verified until one opens the profile of said user on their instance directly

### Detailed description

Viewing the profile directly on hessen.social instance (running 3.5.3)
![image](https://user-images.githubusercontent.com/49074/200293659-f0824083-1bc3-474e-ab7d-93ea6e6e9f7c.png)

Searching for the user while being on mastodon.social (running 4.0.0rc1)
![image](https://user-images.githubusercontent.com/49074/200294152-5def5e07-4726-44fe-8ba3-8bbfd3656226.png)

Links are properly being displayed as verified for users on instances running on 4.x
![image](https://user-images.githubusercontent.com/49074/200294755-2bf4dfc5-2989-490a-b387-f4f79ce526cb.png)

This doesn't seem to affect 3.x users viewing profiles on other 3.x instances.

### Specifications

Doesn't seem to be a front-end issue. Only affects users on 4.x instances viewing profiles on instances running 3.x

**Comment by afontenot** [comment]
Each instance does its own verification. Some instances (including mastodon.social) are currently believed to be having problems due to overload, so that's probably your issue. See some of the comments here: https://github.com/mastodon/mastodon/issues/19949

Your older account probably has a cached verification and that's why it works on mastodon.social.

**Comment by sn0opy** [comment]
> Each instance does its own verification. Some instances (including mastodon.social) are currently believed to be having problems due to overload, so that's probably your issue. See some of the comments here: https://github.com/mastodon/mastodon/issues/19949
That issue talks about 2 problems. The one I pointed out above + the fact, that subdomains seem to cause issues as well.

> Your older account probably has a cached verification and that's why it works on mastodon.social.
Good point, but I don't think so. The verification on my mastodon.social account happened yesterday evening while the verification on hessen.social happened while I created this issue. 

There are other accounts that have their profiles verified days if not weeks ago that do not appear to be verified. Verification of my own link (on mastodon.social) evening appeared immediately yesterday. I don't think it's some kind of issue with a queue unless there's a priority queue for link verification of users on the same instance.

**Comment by afontenot** [comment]
> I don't think it's some kind of issue with a queue unless there's a priority queue for link verification of users on the same instance.

Not priority, it just seems to be kind of random. When the queue tries to verify a link, if the site doesn't respond in five seconds, and fetching the page finish in 10 seconds, it gives up. It's possible that most links are failing to verify on mastodon.social and you got lucky with yours. I (and many others) haven't been able to get our links verified, even though we're on the same instance.

**Comment by wgmyers** [comment]
Submitter of #19949 here - I attempted to test the timeout thing by temporarily replacing the homepage on www.mysite.org with minimal HTML containing only the verification link and resaved my profile to trigger the verification, trying both with and without the 'www'.

Profile updated fine (hovering over the link showed the addition/removal of 'www') but nada verification wise. Meanwhile myname.mysite.org and othersubdomain.mysite.org (similar codebase and same server on all three sites) still both work fine.

Unless there's caching going on so my target-side changes made no difference. I don't know. Certainly my 'www' site is normally the slowest-loading of the three due to the Bandcamp embed.

FWIW I also tried to make a minimal test case using code from `app/services/verify_link_service.rb` but got as far as realising this would also need `app/lib/request.rb` and a concomitant cascade of dependencies so gave up - it looks like it would be easier to actually stand up a complete test Mastodon instance to poke at this further, which I don't currently have handy. Pointing this out to save anyone else trying the same approach.

**Comment by j3j5** [comment]
FWIW, I just tried adding a verification links on an instance running `v3.5.3` and it worked instantly, tried the same on `mastodon.social` (running `v4.0.0rc1` atm) and the links are not being picked up. Not sure if it's a bug or is related to the big amount of new users and the profile taking longer to verify the links, but they were in place since at least 12 hours ago.

**Comment by sn0opy** [comment]
> FWIW, I just tried adding a verification links on an instance running `v3.5.3` and it worked instantly, tried the same on `mastodon.social` (running `v4.0.0rc1` atm) and the links are not being picked up. Not sure if it's a bug or is related to the big amount of new users and the profile taking longer to verify the links, but they were in place since at least 12 hours ago.

This is rather related to the initial report of 19949. 

In this issue I am talking about the verification of federated instances running lower versions than 4.0.0rc1 does not show up.

**Comment by afontenot** [comment]
So, just to be clear about this issue, the first comment says that this applies to *any* 4.0.0rc1 server. (Presumably because the changes are irrelevant) it would apply to 4.0.0rc2 as well.)

> mastodon.social or any instance running 4.0.0rc1

I wonder whether anyone has checked this? The original report says that @sn0opy tried it on mastodon.social which is under the load problem I described that seems to be impacting all or almost all verifications. I think it would go some way to validating this issue if someone could say for sure that this impacts other servers.

Note that each instance does its own link verification, they don't trust each other. So if this issue only seems to affect mastodon.social, my presumption would be that there's no bug with 4.x. Rather, the issue is just that link verification is failing on mastodon.social for virtually all (uncached) links due to load.

**Comment by wgmyers** [comment]
Yeah, looks that way. FWIW, my link on mastodon.social that was not working (despite two other identical links on the same webserver using different subdomains behaving fine) is... now working. Some kind of load / caching issue I guess?

**Comment by sn0opy** [comment]
I was assuming it was a genereal 4.x issue, because I double checked it with another 4.x instance and didn't see the verification mark either. It does seem to work just fine now on any instance I tested.

**Comment by benjamin051000** [comment]
I'm seeing this issue here: 

https://mastodon.social/@organicmaps@fosstodon.org -> No verified checkmark

https://fosstodon.org/@organicmaps -> verified checkmark

I'm also logged into my account on mastodon.social on the official iOS app and do not see the verified checkmark, which is in-line with the website. I'm only seeing verification on the instance that actually owns the account.

**Comment by benjamin051000** [comment]
Okay... I don't know what changed, but now I'm seeing it on both sites (expected behavior)

**Comment by benjamin051000** [comment]
Okay, you may need to search for the account on another instance. For me, clicking the mastodon.social link above is redirecting me to fosstodon.social, which is confusing if you don't notice.
