### ISSUE TITLE
It would be nice if sharing code was more readable

### ISSUE THREAD

**Issue by ioquatix** [mastodon/mastodon#20100]
### Pitch

It would be nice to support markdown backticks and triple backticks (ideally with optional syntax highlighting) for making code more readable.

### Motivation

Right now, code is presented in non-monospace font which can make it hard to read. Many users of Mastodon are technical and would probably enjoy this feature for sharing code samples.

**Comment by ioquatix** [comment]
Relates to https://github.com/mastodon/mastodon/issues/13544

**Comment by ioquatix** [comment]
Relates to https://github.com/mastodon/mastodon/pull/10629

**Comment by solnic** [comment]
I'd add to this that sharing code as images is super wasteful and so if we could share nice code snippets inside toots it would make a huge difference.

**Comment by ioquatix** [comment]
Relates to https://github.com/mastodon/mastodon/pull/10787 althought I'd probably advise against Kramdown, as it has known incompatibilities with CommonMark (even if we just choose a subset of formatting operations).

**Comment by ioquatix** [comment]
@Gargron would you be willing to entertain a PR that added very basic support for code fences `<pre>` and inline code `<code>`? Based on previous discussions, it looks like that would be an acceptable first step?

**Comment by afontenot** [comment]
I don't like the idea of making users enter html tags directly. I think any version of this should strive to be markdown compatible in case something like #10787 is revisited in the future.

**Comment by ioquatix** [comment]
@afontenot I also don't like the idea of making users enter HTML tags directly and I think being compatible with markdown is a good goal, which is what is suggested in the proposal here (supporting backticks).

**Comment by ioquatix** [comment]
Based on what I've seen in the discussions so far, I'd propose an incremental approach. The most useful one to me personally is code fences and backticks and this is a signficiant improvement to readability (monospace font) which is also easily ignored (raw text looks okay I guess). Orthogonally, I'm also in support of inline formatting. Block formatting I'm less sure about, but I personally think incremental steps here will yield better results (let's start with something simple we can all agree on).

**Comment by gigatexal** [comment]
in a similar vein, would be nice if mastodon supported markdown in posts/toots.

**Comment by afontenot** [comment]
I was annoyed enough by the issues with sharing code on Mastodon that I built a custom tool to allow embedding external code (from Pastebin and Gists) directly on Mastodon using oembed. It works pretty well (including syntax highlighting!) although Mastodon's oembed fetching is a little slow and sometimes requires a refresh. (It can fail entirely if your instance is overloaded.)

Free to use at https://paste.social. I plan to keep it running as long as I can.

Sorry to self-promote here, but I'm not making any money on this (no ads or tracking scripts - ever), and I think this could help some folks share code on Mastodon. (It might work on other sites that use oembed, but Mastodon in particular responds best to the "video" oembed type, so that's what I use.)

**Comment by fredrikaverpil** [comment]
Should we close this in favor for https://github.com/mastodon/mastodon/issues/13544 as this seems to be a duplicate issue?

Then we can join efforts in spreading the awareness of the original issue, without fragmentation.

**Comment by robsonsobral** [comment]
#18958

**Comment by ioquatix** [comment]
Closing in favour of #13544
