### ISSUE TITLE
require https:// for link verification

### ISSUE THREAD

**Issue by AlanBell** [mastodon/mastodon#20242]
### Pitch

at the moment the profile link verification works with both http and https connections. I think it would be ideal to only validate https connections so that at the point of verification the server is checking for a valid ssl certificate.

### Motivation

Stops someone spoofing a website to verify them as someone else (fairly hard to arrange but it can be done) This gives a slightly higher level of assurance to the green mark.

**Comment by ineffyble** [comment]
Makes sense but I am reminded of XKCD 1172.

**Comment by AlanBell** [comment]
> Makes sense but I am reminded of XKCD 1172.

lol, yes, but in defence of it, this won't invalidate any existing validations that may have been performed to http sites, so I don't think it will cause confusion to an existing user.
Great to see a PR for it, fantastic work, I am just getting to grips with the code myself, I can read it but I am not good enough with Ruby to hack on it yet!

**Comment by kurtseifried** [comment]
One comment in favor of HTTPS: Webfinger (a cornerstone of Mastodon) requires HTTPS https://www.rfc-editor.org/rfc/rfc7033.html 

A WebFinger request is an HTTPS request to a WebFinger resource.  A
   WebFinger resource is a well-known URI [[3](https://www.rfc-editor.org/rfc/rfc7033.html#ref-3)] using the HTTPS scheme
   constructed along with the required query target and optional link
   relation types.  WebFinger resources MUST NOT be served with any
   other URI scheme (such as HTTP).

Requiring HTTPS across the board makes sense, especially in an era with letsencrypt.org being free.

**Comment by steevithak** [comment]
Is there any way to verify an HTTP website with this change in place? I'm helping to migrate an organizational account to Mastodon and we've been unable to verify their main site (presumably because of this http issue). Their long term road map calls for migration to HTTPS but it's a large, complex mediawiki site and not a case where they can just buy a cert and add it to the server in order to get their mastodon "verified" checkbox.
