### ISSUE TITLE
Dashboard not updating data.

### ISSUE THREAD

**Issue by plgonzalezrx8** [mastodon/mastodon#20268]
### Steps to reproduce the problem

1. Log in as the Owner/Admin Account
2. Navigate to the Administrator Dashboard
3. Users, Interactions, and Reports are not updating and remain at zero.

This is happening on a fresh install on a brand-new server. Everything else is working properly and perfectly.

### Expected behaviour

Dashboard should update the count for users, interactions and reports.

### Actual behaviour

All the values remain at zero.

### Specifications

Mastodon 3.5.3
Ruby 3.0.3
Postgres 15.0
Redis 5.0.7
Ubuntu 20.04

**Comment by Gargron** [comment]
Even after 5-10 minutes? Results get cached

**Comment by plgonzalezrx8** [comment]
Yes Sir, the server has been running for about 2-3 hours now. Everything seems to be working perfectly, except the dashboard. Federation, follows, I checked everything and there are no problems anywhere. This is the only part that seems to be broken on my install. I did the set up twice cause yesterday when initially set up I had the same issue and I thought I might have skipped a step or something from the documentation so did it all over again today. Exact results, and I am not entirely sure where to start looking to find a solution.

**Comment by lutoma** [comment]
We've run into the same issue and done some debugging. Looking at the response to the admin dashboard API request (`/api/v1/admin/measures`), the values for each day in `data` are as expected, but the value in `total` only reflects the situation of the previous day.

If I manually increase the `end_at` value in the request to be the date of tomorrow instead of today, it returns a correct total value.

We use UTC as system time on our servers, so our current suspicion is that this somehow causes some timestamp somewhere to be cut off a bit too early, resulting in the data ending a day too early.

@plgonzalezrx8 Are your servers also set to UTC by any chance?

**Comment by silsha** [comment]
It looks like the current date and time in the dashboard is shortened to a date.
https://github.com/mastodon/mastodon/blob/5e796dc6f85b37c8378fe01cfd8ac23222c89eea/app/controllers/admin/dashboard_controller.rb#L11

In the SQL query for the time series, the date is also truncated.
https://github.com/mastodon/mastodon/blob/5e796dc6f85b37c8378fe01cfd8ac23222c89eea/app/lib/admin/metrics/measure/new_users_measure.rb#L29

but this does not happen for `perform_total_query`, so only entries up to 0:00 UTC of the respective day are counted (or in other words: today is ignored):
https://github.com/mastodon/mastodon/blob/5e796dc6f85b37c8378fe01cfd8ac23222c89eea/app/lib/admin/metrics/measure/new_users_measure.rb#L10-L12

**Comment by VanillaDeath** [comment]
I'm also experiencing this on my instance, the stats update only once a day at around 20:30 my time (0:00 UTC). Using docker-compose setup.
