### ISSUE TITLE
Card not showing on mastodon.social post, but working on mindly.social

### ISSUE THREAD

**Issue by thiagomgd** [mastodon/mastodon#20353]
### Steps to reproduce the problem

1. My blog's posts are not showing up as cards on mastodon.social and universeodon.com, but working on mindly.social
2. Example post: https://geekosaur.com/post/november-book-haul/ 
3. Tried different post 'layouts', all work on mindly.social, and not on the other 2. Examples:

a) `SOME_TEXT LINK #HASHTAG`
b) `SOME_TEXT LINK`
c) `LINK`

### Expected behaviour

There should be a card showing on the post, and also present on the API, under 'card'

### Actual behaviour

Nothing showing on the UI, 'card' attribute on API is empty

### Specifications

Google Chrome Version 107.0.5304.110 (Official Build) (x86_64)
macOS 12.6.1

Error on mastodon.social (v4.0.0rc1) and universeodon.com (v4.0.0rc2)
Works on mindly.social (v3.5.3)

**Comment by afontenot** [comment]
This is probably due to overload. I'm seeing a issues where mastodon.social fails to hit an oembed endpoint, seemingly at random, and then the issues will resolve a few hours later. If the instance isn't fetching your page, it can't collect the necessary metadata to build the card. It's unfortunate and irritating but I don't think it's a Mastodon bug per se. Hopefully the problem goes away soon.

**Comment by thiagomgd** [comment]
Oh, I think you are correct. Tried it again today and it worked. Since by coincidence it failed on 2 v4 instances, and worked on a v3.5 instance, I thought it could be a bug.
