### ISSUE TITLE
Mastodon 4.0.0rc2 doesn't show custom messages when registration is closed

### ISSUE THREAD

**Issue by ralfr** [mastodon/mastodon#20361]
### Steps to reproduce the problem

When going to Administration > Registrations and switching to "Nobody can signup" there is a field for a custom message.

### Expected behaviour

The custom message will be shown to users trying to create an account.

### Actual behaviour

A default dialog is shown without the custom message.

### Specifications

Mastodon 4.0.0rc2 on Ubuntu 20.

**Comment by erbridge** [comment]
So it looks like the issue here is that [`state.getIn(['server', 'server', 'registrations', 'message'])`](https://github.com/mastodon/mastodon/blob/main/app/javascript/mastodon/features/closed_registrations_modal/index.js#L9) isn't returning the message. I'm a bit suspicious of the `server` reducer. It looks to me like that should be `['server', 'registrations', 'message']` not `['server', 'server', 'registrations', 'message']` when looking at the [reducer implementation](https://github.com/mastodon/mastodon/blob/main/app/javascript/mastodon/reducers/server.js#L35). I don't have the confidence in this assessment to attempt a fix, but it might be a starting point?

**Comment by ClearlyClaire** [comment]
Most likely this is because of the 3 minutes long cache server-side. Does this still occur after waiting a while?

@erbridge `['server', 'server', 'registrations', 'message']` is confusing but it's the right path to the attribute.

**Comment by erbridge** [comment]
Ok. With a second read of the reducer this morning, I can see that now. Thanks.
