### ISSUE TITLE
Support ActivityPub over HTTP/3

### ISSUE THREAD

**Issue by eloydegen** [mastodon/mastodon#20523]
### Pitch

First, I could not find whether the HTTP version is implementation defined or specification defined. In case it is the latter, this issue should be closed and moved to an ActivityPub repository.

In case we could support it, it has quite some performance benefits as it removes the head of line blocking and has better header compression. It only supports TLS 1.3 so there is less risk of downgrade attacks to older TLS versions.

HTTP/3 is oficially an IETF Internet Standard since June, but the software implementations of it are generally still quite alpha state, so I assume this issue will be kept open for quite some time, but when support for it reaches upstream and distro packages, we're closer to resolving it.

### Motivation

More performance and security for server-to-server communication

**Comment by mjankowski** [comment]
I'm going to close this not because we cant/shouldnt do it - but because it will just wind up happening (or not) someday based on things almost entirely out of control of the project itself.

I suspect that whenever there is good support in http servers, rails, rack, etc - it will "Just Work™"

Good overview for interested parties - https://www.cloudflare.com/learning/performance/what-is-http3/
