### ISSUE TITLE
[Feature request] "Posts and replies" tab on profiles could deliberately omit boosts

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#20575]
### Pitch

The "posts and replies" tab on profiles could contain *only* the person's posts and replies, without boosts.

The "posts" tab would continue to be the default view and would continue to include boosts.

### Motivation

When I'm looking at someone's profile, I like to be able to see all their posts, so I can decide whether I want to follow someone or not. If that person boosts a lot, it can be hard work to mentally filter out all the boosts and pay attention to only their original posts.

I look at someone's "posts and replies" tab when I want to look a bit more closely at the kind of person they are and how they use social media. (E.g. are they a reply guy? do they harass people?)

It makes sense to have a boost-free view, because when you follow someone you have the option to hide their boosts, so someone might want a preview of what that would be like before deciding to follow them.

I think making the "posts and replies" tab boost-free meets this need without taking anything away (you can see their boosts on the "posts without replies" tab), and without having to make a whole new tab/view.

I usually achieve this on Twitter by searching for (from:username), but obviously we don't have that on the Fediverse!

**Comment by trwnh** [comment]
i think this would make the tabs confusing, as there wouldn't be a way to see all posts anymore. but something like #18413 or #10011 would probably cover this

**Comment by skerit** [comment]
I'd go a step further: just show no boosts in the "Posts" tab and maybe add a new separate "Boosts" tab. Or add them to "Posts and replies".

**Comment by cityeyes** [comment]
Just posted about this yesterday! I don't mind them in my feed, but I believe it should be the _default_ that they're hidden in profiles because it's often so difficult to see what content individual people are creating when boosts are outnumbering their own posts 10 to 1 or more.

This is especially true with the emphasis on boosting to multiply reach across instances. I want to promote things that I like and think should be seen, but I also want to create and share a good amount of my own words and photos without flooding my profile out.

I think splitting them off to another tab could work without being too complicated. Posts, posts and replies, boosts, media. Something like that.

At the very least, maybe hide boosts in the primary profile page by default

All I know is that it's definitely got potential to become a usability issue. I've, more than once, given up on adding someone who might have a profile that I'm interested in because I didn't want to dig through a bunch of boosts to find what they've got to say.

**Comment by Cassolotl** [comment]
> I think splitting them off to another tab could work without being too complicated. Posts, posts and replies, boosts, media.

I'm not into that, because part of what I'm curious about is how much people boost (in relation to original posts), and that's impossible to work out if they're entirely separate.

> i think this would make the tabs confusing, as there wouldn't be a way to see all posts anymore.

That seems fine to me. It's not like you see all of someone's posts in Home while following someone, right? You don't see their replies to people you don't follow. Whether or not you see followers-only posts on profiles is context-dependent. There might be other things you don't see that I don't know about.

> but something like https://github.com/mastodon/mastodon/issues/18413 or https://github.com/mastodon/mastodon/issues/10011 would probably cover this

They're way more granular than I would expect to see outside of something in settings, but yes, they would cover this.

**Comment by trwnh** [comment]
Closing in favor of #10011

**Comment by Cassolotl** [comment]
This issue is resolved by merged PR #26302.
