### ISSUE TITLE
Emoji before link changes after publish

### ISSUE THREAD

**Issue by djprmf** [mastodon/mastodon#20707]
### Steps to reproduce the problem

1. Write a toot that starts with a emoji, followed by a link
2. Publish the toot
3. The emoji goes to the end of that link in the final message

### Expected behaviour

The emoji should stay in the correct location

### Actual behaviour

The emoji goes to the end of the link

### Detailed description

In the new version 4.0.0, if a toot is send with a emoji, immediatly followed by a link, in the final message the emoji goes to the end of that link.

The issue also happens to messages that have been sent before the new version - all the toots.

### Specifications

Windows 11 - Chrome/Brave/Firefox

**Comment by erAck** [comment]
Same in Bio text, the first emoji of a paragraph and everything following in that paragraph is moved to the end of the paragraph. Can be circumvented by adding another newline to insert an empty line at strategic places..

But I heard there's already a bugfix release for this underway, so that's probably
https://github.com/mastodon/mastodon/releases/tag/v4.0.1

**Comment by ClearlyClaire** [comment]
Yeah, fixed by #20677, sorry for that
