### ISSUE TITLE
Ability to see which hashtags I follow

### ISSUE THREAD

**Issue by marco-meer** [mastodon/mastodon#20763]
### Pitch

Thank you for introducing the feature to follow hashtags. I was wondering whether the hashtags I follow can be included in /relationships or somewhere else.

### Motivation

Everyone would benefit from having an overview of hashtags they follow. One loses overview when following an increasing number of hashtags.

**Comment by andypiper** [comment]
I'd suggest broadening this:

- ability to see which hashtags the user follows (possibility in the user preferences, with users follows)
 - as noted above, it can be difficult to remember if there are a larger number of hashtags being followed
- (advanced web UI) ability to add a column for a hashtag.
 - this is possible today, if a search is pinned, but these have to be re-entered as new searches and pinned in the advanced UI
- add followed hashtags to data export panel (alongside lists and follows)

**Comment by andypiper** [comment]
Relates to https://github.com/mastodon/mastodon/pull/18862

**Comment by coffeehabit** [comment]
Yeah this was a bit of an oversight I'd say lol. I thought they'd add a section in the **Preferences -> Follows and Followers** section.

Also, the ability to add hashtags to Lists would be great to divide things up but I suppose that'd be a bit more advanced.

**Comment by sammcj** [comment]
I went and logged a bug report for this somehow without finding this existing issue first.

Here's my report:
---

### Steps to reproduce the problem

1. Follow hashtags
2. Go to your 'Following' list (e.g. https://mastodon.social/@username/following)
3. Can't find the followed hashtags

### Expected behaviour

Following should show hashtags you're following

### Actual behaviour

Hashtags are missing

### Detailed description

It's not obvious where you can find your followed hashtags anywhere in the UI.

They don't show up under:

- Following (e.g. https://mastodon.social/@username/following)
- Settings -> Follows and followers
- Explore -> Hashtags (I think there should also be a + next to hashtags there to (un)follow them)

![following](https://user-images.githubusercontent.com/862951/204663925-2cecd26b-bceb-4050-83e4-395c8038cd6d.png)

![explore-hashtags](https://user-images.githubusercontent.com/862951/204663853-70a8096a-9213-4b22-b46f-462f60c34a02.png)

![settings-following](https://user-images.githubusercontent.com/862951/204664329-ea4f6495-cbc5-47b9-b635-185498d6abe8.png)


### Specifications

Mastodon v4.0.2

**Comment by jayrope** [comment]
+1 Subscribing to hashtags could be very useful, but it makes no sense to have this, when there is no quick option to view & edit all hashtag subscriptions.

**Comment by tyrosinase** [comment]
It seems to be exposed in the API, so if there are clients that give access it would be nice to know, so admins could refer users to it as a stopgap.
