### ISSUE TITLE
Option to notify user when a moderation report is resolved

### ISSUE THREAD

**Issue by dariusk** [mastodon/mastodon#20899]
### Pitch

As a moderator reviewing reports from users, I would like a check box that says something like "notify this user when their report is resolved". On resolving the report, it would send the user a message, perhaps via email notification if they have it turned on, or through the "Notifications" timeline, letting them know that the report was resolved and how it was resolved. Possibly it could pass a note along from the mod that was added in the report review interface.

### Motivation

Right now this is what moderation looks like for me:

- I get a report from a user
- I investigate the report
- I resolve the report
- I DM the user saying "I took action on your report and you won't have to deal with that account anymore"

Automating that last step would reduce the work I have to do as a mod overall.

I realize that notifying the user is not always what you want to do in all contexts, hence my suggestion that it be a check box.

**Comment by Crashdoom** [comment]
This would be awesome! If we can add an optional message to be sent in the notification and / or customize the notification text, that'd be a great bonus too.

**Comment by ineffyble** [comment]
Solves the same requirement as #14474 but with a different suggested implementation.

**Comment by simon-brooke** [comment]
Seems also very similar to #1685.

**Comment by ThisIsMissEm** [comment]
This seems reasonable, but we also need to keep in mind that there might be multiple reports for the same content, and one resolution, so all reports would receive the resolution message.

Though you also don't want to get into a back & forth with an individual user over "why didn't you take action on the thing I reported!! you should've taken action!", as that can easily eat a lot of time from moderation teams.

**Comment by hanswundersam** [comment]
Can't stress the importance of such a feature enough: Since August 2023, every Mastodon server admin based in the EU is subject to some of the obligations under the DSA, and in particular [Article 16](924937) requires each admin/mod to "notify that individual or entity [that notified infringing content] of its decision in respect of the information to which the notice relates, providing information on the possibilities for redress in respect of that decision." The DSA contains a number of other obligations which Mastodon should provide features for to prevent admins to be non-compliant en masse.
