### ISSUE TITLE
Introduce an optional status page

### ISSUE THREAD

**Issue by spaceottercode** [mastodon/mastodon#21123]
### Pitch

As commonly provided by SAAS providers, it would be nice if there was a page where one (a non admin user) could view or check up on the health and any ongoing remedies occuring on the instance.

### Motivation

While people will always ask, it would be nice to give users the ability to check for themselves, & share links w inquiring users.

**Comment by GiantCrocodile** [comment]
And maybe planned maintenances, e. g. when a Mastodon instance will be updated next weekend.

**Comment by rbairwell** [comment]
For planned maintenance, instance admins do have the ability to set an instance wide "Announcement" (although I've only seen this used on 1 of 5 servers)

Example:
![image](https://user-images.githubusercontent.com/775269/203053623-a160049c-adc0-4d2a-83bf-afa3c349043a.png)

For a status page to work "properly" (and not just be a manually updated status page as many providers use - statuspage.io relies on many updates), it'll need to check the status of the web app, any/all multiple Sidekiq processes/queues, mail system connectivity and the PostgreSQL database: and since all of those could be on separate machines (especially for big instances), it'll be a bit of a task for the main software to handle. Plus if the web app is down, you wouldn't be able to see it anyway.

I'm all for Mastodon software reporting how long things having been sitting in queues for e.g. "Ingress queue last processed within 20 seconds" which can be read by an API or server monitoring tools such as Nixstats, Nagios, Ganglia etc- but then this (in good practice) should be read/displayed on a separate server  (in theory, an entirely different data centre on a different continent to cover for DC failures etc) for access.

**Comment by spaceottercode** [comment]
I'm updating 

> view or check up on the health and status of ongoing work & maintenance of your instance.

to instead read

> view or check up on the health and ongoing remedies.

Sorry, I didn't mean to include routine maintenance, so I'm rewording & dropping the word. Apologies to all.

**Comment by Gargron** [comment]
If this functionality was part of Mastodon it would become inaccessible at the same time as your Mastodon. It's always a good idea to keep the status page on separate infrastructure. Relevant: #23390

**Comment by spaceottercode** [comment]
Mastodon.online & Mastodon.social now have a Status page. With time, hopefully more & more sites will opt for status pages as well.

Marking this issue as resolved.
