### ISSUE TITLE
web UI bug for smaller screens in /settings

### ISSUE THREAD

**Issue by ooozerooo** [mastodon/mastodon#21279]
### Steps to reproduce the problem

1. open /settings 
2. click on the top right button (and a menu will pop up)

### Expected behaviour

'Back to mastodon' button show normally 

### Actual behaviour

only half of the 'Back to mastodon' button is visible 

### Detailed description

v3.5.3 | v4.0.0+
-- | --
![IMG_6892](https://user-images.githubusercontent.com/106132975/202968500-c973423b-ee83-4946-98df-7f5ff2a57aef.PNG) | ![IMG_6891](https://user-images.githubusercontent.com/106132975/202968518-ee8b750f-27ab-4aa9-8dd4-8bf98a6754e5.jpg)

### Specifications

Mastodon v4.0.2
iPhone 13 Pro safari

**Comment by connorshea** [comment]
I think this might be Safari-specific. I can reproduce it on my iPhone 14 Pro, but I can't reproduce it in Firefox's responsive design mode nor in Safari for macOS' responsive design mode (although I'm a version behind on macOS, so maybe it's a newer Safari thing?).

Although, weirdly on iOS it seems to get rid of the sticky top bar (or hide it behind the notch area somehow?), whereas in Safari's responsive design mode it stays.

If I move the address bar to the top of the screen, the effect actually gets worse and even more is hidden. Perhaps the page is calculating based on the _device_ height rather than the actual viewport size?

![IMG_6271](https://user-images.githubusercontent.com/2977353/202970539-94a51b30-d19a-45d2-9d44-6b95f26bdb54.PNG)

**Comment by connorshea** [comment]
I connected my iPhone to my Mac and opened the web inspector, if I remove the `position: fixed` on `.admin-wrapper .sidebar>ul.visible`, the issue is fixed (although I'm unable to scroll up or down as a result)

**Comment by connorshea** [comment]
Alternatively, I can change the default value of `height: calc(100vh - 56px)` on that class to `height: calc(100vh - 150px)` and it works perfectly. We could _potentially_ use the `env` values that Safari allows (https://developer.mozilla.org/en-US/docs/Web/CSS/env) to automatically do `calc(100vh - 56px - env(safe-area-inset-top))`, which would add the dead area of the notch automatically? Unfortunately it's not supported by all browsers, so we'd need to be careful not to break things on browsers that don't understand `env`.

**Comment by connorshea** [comment]
It looks like the _actual_ secret is to use `height: -webkit-fill-available`: https://allthingssmitty.com/2020/05/11/css-fix-for-100vh-in-mobile-webkit/

So that kinda sucks. It also still results in the actual Mastodon header - which _should_ render - being hidden, because the `height` is only applied to the navigation "sidebar", so it looks 

This is what it looks like using `height: -webkit-fill-available` on `.admin-wrapper .sidebar>ul.visible`:

![IMG_9E9CF7AA8C4C-1](https://user-images.githubusercontent.com/2977353/202975889-59923810-057d-4ed9-bda8-ebb637ead52e.jpeg)

For comparison, this is what Safari on macOS thinks it should look like in responsive design mode (*before* any changes to the CSS, once you add `-webkit-fill-available` it does actually cause the header to be hidden on macOS Safari's responsive design mode as well):

<img width="409" alt="Screen Shot 2022-11-20 at 10 57 27 PM" src="https://user-images.githubusercontent.com/2977353/202976074-2fc26bca-9ca2-4b57-974d-52715ca454fe.png">

So anyway, that's one way to fix it. I guess I'll open a PR.

**Comment by ooozerooo** [comment]
> So anyway, that's one way to fix it. I guess I'll open a PR.

Thanks so much for taking your time to investigate the issue!!
 Yeah mastodon v4.0.0 did massive changes to the mobile web UI and that breaks a lot of things.

**Comment by ooozerooo** [comment]
> So anyway, that's one way to fix it. I guess I'll open a PR if we don't come up with a better solution.

Thanks so much for taking your time to investigate the issue!!
By comparing CSS codes of v3.5.3 and v4.0.2 for the page i found that the problem is actually more than just only half of the 'Back to Mastodon' button being visible and the header disappearing.
 

For element `.admin-wrapper .sidebar>ul.visible`, the codes are
v3.5.3 | v4.0.0
-- | --
 <img width="281" alt="Screen Shot 2022-11-21 at 5 33 15 pm" src="https://user-images.githubusercontent.com/106132975/202981294-5c06d4d1-6d2d-4135-8677-d273f3e3978d.png"> | <img width="294" alt="Screen Shot 2022-11-21 at 5 33 26 pm" src="https://user-images.githubusercontent.com/106132975/202981283-5eff8f53-ac6c-4e05-bf62-9a2102f14177.png">

When I comment `/* position: fixed; */` and `/* height: calc(100vh - 56px)*/;`, the header shows up, the 'Back to Mastodon' button is fully visible, but now half of the 'log out' button disappears! And i found you cant scroll on the page (so cant scroll to make the 'log out' button fully visible), but you can in v3.5.3. It was because `.admin theme-default no-reduce-motion` has `overflow: hidden`, delete the overflow variable and everything works perfectly on my phone. But Mastodon did massive changes to mobile web UI in v4.0.0, im not sure whether changing these values back would break other pages.

Cheers.

v3.5.3 | v4.0.0
-- | --
![IMG_6897](https://user-images.githubusercontent.com/106132975/202982035-3a3a1323-ad13-4b77-a0b5-eb2125787e17.jpg) | ![IMG_6894](https://user-images.githubusercontent.com/106132975/202982168-a1a4cafc-c246-449e-b1a3-f2a2a0bda4ce.PNG)
