### ISSUE TITLE
Code or phrase as alternative to rel="me" for those who can't access HTML on their site or page

### ISSUE THREAD

**Issue by FediVideos** [mastodon/mastodon#21353]
### Pitch

It would be nice to provide an alternative to rel="me" for turning a link green. Rel="me" would remain for those who can use it, but this alternative would be available alongside it.

A code or phrase would be provided on their profile settings, which they could paste into their profiles just after the link, or on the same page as the link.

Seeing both a link to their Mastodon account AND the code/phrase would indicate that they actively want their account verified, and that both accounts are theirs. This would fulfil the same criteria as rel="me", but would not require HTML editing.

### Motivation

The rel="me" feature seems to assume that people's online presences are independent websites (or similar) where HTML is accessible to the owner.

Many owners of online presences nowadays do not have access to the HTML on their page, even though the presence is clearly tied to their identity (for example a well known page on Instagram or YouTube or whatever).

It would be nice to give such people an alternative way of getting their green link on Mastodon.

**Comment by TCFox** [comment]
This could be very difficult to do safely, as there are arbitrary ways this could be exploited. Mastodon does not have inherent understanding of what parts of the page are user-controlled, and which parts are controlled by others.

For example, if I linked to my Facebook profile, Mastodon would need to search through the entire page for the specific code/phrase which verifies the link. A friend could post a comment onto this page, which contained a link to their own Mastodon account, and this would still satisfy the requirement for a verified link.

If the code/phrase appeared through an API call or inside an iframe, Mastodon would need to be made Javascript-aware and parse the DOM in order to locate the code/phrase. This will require running a headless browser on the server, which is extremely intensive and opens up a large number of security concerns in itself. Without it however, this feature could cause a lot of confusion ("I can't see it on the page, why can't Mastodon see it?").

If we were to make it so these sites did work, Mastodon would need to maintain a large list of websites in which to do custom checks in specific safe locations for this code/phrase. This would require constant maintenance to both add new websites as well as fix existing websites which have changed their layout. This would also prioritise larger websites, and would disadvantage newer and smaller websites.

I can see a large number of issues getting this over the line as is, but there may be a creative solution to this that could fulfill this particular idea. I can definitely see some advantages to it for sure, and it would be good if there was some way to achieve that goal. Looking to the [Keybase project](https://keybase.io) may provide some inspiration for devs around this area.

**Comment by FediVideos** [comment]
Thank you for that, makes it clearer why rel="me" is useful.

I see what you mean about needing to distinguish between comments and content, especially on a social media page. Definitely don't want to burden developers with having to do large lists of websites.

What's frustrating is that human beings can look at a social media post from an official account elsewhere that mentions the Mastodon account and instantly see it is the same person, but there doesn't seem to be an easy way to do this for the software?

**Comment by FediVideos** [comment]
What if the phrase was in the page title? People could just add it on the end of their username to force it to appear there? That would be safe from comments etc?

**Comment by ineffyble** [comment]
I'm willing to bet it wouldn't be hard to find contexts in which that's exploitable too, unfortunately.

**Comment by ineffyble** [comment]
I'm going to say this is probably a duplicate of https://github.com/mastodon/mastodon/issues/20307

**Comment by FediVideos** [comment]
Good catch, did wonder why there wasn't this suggested before!
