### ISSUE TITLE
Verification issue post-migration

### ISSUE THREAD

**Issue by s-swart** [mastodon/mastodon#21407]
### Steps to reproduce the problem

1. Created account on instance mas.to -- http://mas.to/@alsosara
2. Successfully verified my personal site -- http://saraswart.com
3. Created account on instance techies.social and add link to my personal site - http://techies.social/@sara
4. Updated code on personal site, removing reference to mas.to/@alsosara and replacing with techies.social/@alsosara
5. Here is the problem: The verification remains on mas.to/@alsosara, even though I removed it so that site should NOT be verified any more on mast.to. The verification is also not showing on techies.social/@Sara
...

### Expected behaviour

Old account should not have a verified site any more, new account should

### Actual behaviour

Verification remains on old account

### Detailed description

I wonder if I need to delete the site from my old account to make this work? That's not intuitive but I could try it. I'll wait until seeing if someone sees this bug first, so they can observe the issue while it's visible.

### Specifications

Both are Mastodon 4.X currently. At the time of account creation, both were 3.5.X.

**Comment by rbairwell** [comment]
> I wonder if I need to delete the site from my old account to make this work
Yes, at the moment I believe the code does not automatically recheck previously verified sites.

I'm sure I've seen either an issue or a pull request regarding this, but I can't find it at the moment.

**Comment by ineffyble** [comment]
Two separate issues here.

Verification shows on the old account because there's no mechanism to refresh unless you edit your profile (#20172). However if someone views your account from a remote instance, that remote instance will perform verification and fail, so you won't show as verified there.

Verification not working on the new account is not working because you put the URL as `http://` - verification only works on HTTPs links for security reasons. If you edit your new account and change to `https://` it should work.

**Comment by s-swart** [comment]
@ineffyble  thank you! Your advice worked. I was able to change to https:// and that fixed the verification. I haven't edited my old profile since it's deactivated, but that's fine.
