### ISSUE TITLE
Ability to filter boosts and replies from profile feeds

### ISSUE THREAD

**Issue by hexagontruth** [mastodon/mastodon#21418]
### Pitch

There should be some ability to to view a user's original, top-level posts, without boosts and without replies, from the public profile feed, whether this be effected through refactoring the present three tabs into toggles, changing the functionality and order of the tabs (e.g. having an "All" tab and then individual tabs for each specific post type), or what have you.

This is an expansion of comments I left earlier wrt #10011, #18413, and #20575 re: filtering boost posts from profile feeds, but from a somewhat more general perspective vis-a-vis the lack functionality around what one might call the de-ephemeralization of one's own content stream. I'm posting this as a separate issue because I did not see it really discussed from the perspective I'm primarily addressing here — namely that of the profile owner's interest in having their posts to be readily accessible and able to be clearly presented in isolation — and also because frankly the original and most general issue on the topic, #10011, is almost four years old and has seemingly never been either fully considered or rejected.

### Motivation

The ability to filter out boosts on a user's profile — by tab, toggle, or whatever — is not only useful for e.g. viewing someone's "real posts" at a glance, which I often want to do (and which is discussed in #18413 and #20575 mentioned above), the lack of such a feature also *heavily disincentivizes boosting* for those of us who don't post a lot, or at any rate want to boost far more than we post ourselves, whatever the absolute volume is. If I boost too many posts then my own relatively sparse non-media posts will simply get lost in the depths of the feed. Particularly in this community where there seems to be (at least on the servers I've interacted with most) a fairly liberal culture and set of expectations around boosting, it's regrettable to not have a way to easily isolate one's own content. And I can only assume this is at least subtly pushing many people towards a more restrained style of engagement than they might otherwise adopt.

As something of an aside: I find myself wishing more broadly for something akin to Twitter's (poorly-implemented and seemingly abandoned) "memories" feature: an ability to curate custom collections of posts — by oneself or others — and have these publicly accessible through some sort of sidebar or bio link or whatever. Even just something like the favorites or bookmarks lists being publicly-visible from one's profile would be a step towards this — i.e. some new category of like "public bookmarks" or something, idk. As it stands now there are simply *no tools* readily available for keeping one's non-boost posts, or whatever one considers one's "important" posts from just falling into oblivion and being lost amidst boosts, self-replies, and other ephemera. (And here I am sort of assuming and hoping most of us can agree that a liberal boosting culture is an overall net positive for the ecosystem as a whole.) Pinned posts obviously offer something in this vein as well, but they don't offer any sort of topical sorting, nor can one just keep pinning posts indefinitely, as they compete with every other post for feed space.

The common denominator here is again the utility of being able to see at a glance the tone and substance of what someone is posting, how they are using their account, etc., and conversely (and maybe more importantly) the ability of users to facilitate and to some extent — perhaps — curate this experience for others. And tl;dr the sort of boost filtering functionality outlined here and in the above-mentioned threads seems like it should be one of the easiest, most minimally disruptive improvements that could be made to effect this. I think it's important to bear in mind that while some ppl post an endless stream of daily ephemera, etc. and have no problem with Mastodon's overall feed structure being similarly ephemeral, many of us, again, are posting a relatively thin trickle of content at a daily, weekly, or monthly cadence, coupled with more liberal boosting in between, and I don't think it would detract from the unity of experience or philosophy for the platform to accommodate both patterns of use — or any other — within reason.

**Comment by Cassolotl** [comment]
This is both the same as and opposite to this related issue: *[Feature request] "Posts and replies" tab on profiles could deliberately omit boosts #20575*

**Comment by hexagontruth** [comment]
> 

Right I mean this is why I posted it as a separate issue. I realize there's a lot of overlap between the three issues I mentioned, but none seem to be exactly encompassing my concerns, and at any rate there seems to be pretty widespread agreement that #20575 narrowly construed (changing the functionality of the P&R tab) is not the ideal solution at the moment, so idk. I will happily defer to any other issue thread that this topic consolidates around though.

**Comment by Cassolotl** [comment]
Awesome, I fully support opening a new issue if the other one doesn't quite fit your wants. :) I just wanted to link the two issues up, in case it was helpful for future readers. If this one got implemented I'd be happy about that!

**Comment by afontenot** [comment]
It is incredibly strange to me that despite there being a "posts" tab and a "posts and replies" tab, the posts tab does not omit replies - specifically, it doesn't omit my replies to myself, even if they're opted out of discovery features. I don't know if there's a specific issue for that yet, but at any rate if I understand you correctly this feature request would allow hiding these replies too and that would solve my problem.

> The common denominator here is again the utility of being able to see at a glance the tone and substance of what someone is posting, how they are using their account, etc., and conversely (and maybe more importantly) the ability of users to facilitate and to some extent — perhaps — curate this experience for others.

Agree strongly about the need for this.

<details>
<summary>A mostly-on-topic related thought</summary><br>
<p>My biggest practical issue with Mastodon (other than a number of bugs) is the fact that replies aren't visually threaded. If you look at any post with a large number of replies and replies to those replies, it's an incoherent mess. There is literally no way to understand at a glance who is replying to what. The result of this is that someone will ask a question in a reply, and users will good-naturedly answer the question. But because it's actually quite hard to see the specific subset of replies to the reply (if there are large subthreads), people will keeping posting the answer even if 15 others have already given it. In some cases, this leads to the person asking the question (often a newcomer) feeling that the Mastodon community is talking down to them.</p>

<p>I bring this up on this issue because it affects the profile viewing experience as well. Reverse chronological order is awesome (I use it on every platform, not just Mastodon), but it makes a *mess* out of threads. There's no way to clean up your profile by opting out specific posts (e.g. replies) from being shown. I'd like to be able to toggle showing individual replies (and replies to those replies), but barring that, something like this is really needed to clean up profiles. Finding the top level post so you can follow a conversation is way more difficult than it should be.</p>
</details>

**Comment by hexagontruth** [comment]
Yeah that's what I mean, self-replies as parts of threads — I would be happy to never see another non-top-level thread post in my profile again. (Though admittedly I kind of came to this as an afterthought when thinking about boost-hiding.) My impression is that replies to myself i.e. threads are always included in my profile feed, while those that respond to others — even in comment threads on my own top-level posts — only show up in the P&R tab. I feel like I've seen an issue or two here where it's claimed that this is like some necessary byproduct of the way the feed works, but I don't really get why. The more I think about it, tbh, it's really hard to understand the rationale for this — like, under what circumstances would I want to show anything other than a top-level thread post on profile idk. Indeed I'm *more* likely to want to show one-off replies to other ppl's threads on my feed than whole-ass threads I posted, since the latter can always be accessed by their top-levels anyway. But ideally, yes, I'd like to see them all be behind some sort of toggle or tab.

I agree there seem to be a lot of problems with reply threading. I haven't been using this long enough to have as fully-formed an impression of how this plays out, but yeah it seems pretty confusing just from the few times I've tried browsing complex threads. On Twitter you get a visual cue for at least one level of subthread hierarchy. It should be, I would think, fairly easy to do the same thing — show which replies are one level below the current one, and consequently which comment is their parent on the currently-viewed level. Idk. At any rate it highlights the problem to my mind yes of just throwing them willy-nilly into the profile feed. In some ways I think replies are so qualitatively different from regular posts and even boosts that perhaps they deserve some sort of special handling or formatting in profile feeds, a la media posts. That is beyond my expertise or present range of fully-fleshed-out opinion tho.

**Comment by trwnh** [comment]
#10011

**Comment by VyrCossont** [comment]
BTW the API parameter that supports this use case was added in #9606 (because I asked for it) back in 2018. I tried to add UI for it in #11120 but didn't have the time or frontend skill needed to follow up with the UI concerns once the 4-tab design was rejected. AFAIK only a handful of third-party clients support hiding boosts like this (Mast did, at one point).

Same ask today in 2022: without a way to filter out a user's boosts when looking at their profile, it's impossible to tell what they themselves are posting, if anything.

**Comment by Ghryphen** [comment]
Agreed, would like to filter Boosts. I go to a person's profile to find out more about them and their original contributions to Mastodon, not scroll through a dozen boosts to find their latest original posts.

Ultimately, would like to see Boosts as their own profile tab and not displayed by default.

**Comment by Bloodaxe95** [comment]
> Agreed, would like to filter Boosts. I go to a person's profile to find out more about them and their original contributions to Mastodon, not scroll through a dozen boosts to find their latest original posts.

My exact feelings as well.

**Comment by FlorianMarquardt** [comment]
I happily agree with the suggestion here made by hexagontruth. In fact, a few hours ago I asked about this feature on Mastodon, and the replies indicate that many people would like to see this feature: https://fediscience.org/@FMarquardtGroup/109596750181093857

**Comment by FlorianMarquardt** [comment]
Thank you, VyrCossont, for pushing the implementation of the feature as such already back in 2018. It is a pity that it did not make it yet to the UI, but that also means only a little push is needed now to make it a reality!

**Comment by irag** [comment]
I support this recommendation.  Having it will allow a function like Memories on Facebook which is one of the few useful things about Facebook.

**Comment by trwnh** [comment]
Closing in favor of #10011
