### ISSUE TITLE
Allow to show single toots without opening the advanced UI

### ISSUE THREAD

**Issue by allo-** [mastodon/mastodon#21472]
### Pitch

With Mastodon 4.0, when using the advanced UI, links to single toots always load the full UI (with columns) and open the toot in the UI in the rightmost column when you're logged in. For viewing a single toot, this is less desirable than the standard view before, or the view you get when you're logged out.

1) Steps to reproduce (undesired column layout):
- Someone posts a link to a toot on your instance in your timeline
- You right-click it and select "open in new window"
- The new window contains the full tootsuite UI instead of showing only the single toot.

The UI isn't scrolled to the right, so the toot may only be visible with scrolling when you have many pinned columns.

2) Steps to reproduce (inconsistent behavior):
- Someone posts a link to a toot on another instance
- You right-click it and select "open in new window"
- The toot *does not* open in a column in the Tootsuite view of your instance, but in the simple view like in Mastodon before 4.0.

That means that opening toots now also works differently between your own instance and other instances. This behavior can especially come surprising when you didn't think much about from which instance the link is before opening it in a new window.

### Motivation

*Why do you think this feature is needed? Who would benefit from it?*

Anybody using the advanced UI.

**Comment by rbairwell** [comment]
I don't find this a problem on my Ultrawide monitor (which my Mastodon window takes up less than 60% of the width - and even then it has space to spare) - but I do understand that people have smaller monitors (I doubt any of the UI will look good on a 12" CRT I have next to me!).

I personally prefer it to be all in a single view instead of toggling from advanced to "single thread view" so perhaps this should be user customisable.

**Comment by Cassolotl** [comment]
YES THANK YOU this is ABSOLUTELY DOING MY HEAD IN omg

**Comment by Muskworker** [comment]
Doing this would mitigate a lot of the pain caused by #20540!  

A direct link should go directly as possible to the thing linked, not something that might be offscreen.  Especially for those of us with memory/attention issues, we'll eventually come around to a tab we opened earlier, see the timeline, and start from that (or be distracted to it), instead of thinking to scroll offscreen.  

(And even when the screen is large enough to show all columns, having something old in that far-right column is common enough for it not to be the primary focus when coming in to a Mastodon tab.)

It could have a "back to column view" link for people who find a need to do so.

**Comment by allo-** [comment]
It looks like the problem was introduced in #20540. The use-case there seems to be to have a link open on the own instance, which should be the default when clicking the toot itself.

The use-case here is that clicking the date (like "1d ago") should take you to the thread on the original instance and not to the interface on your own instance.

The problem is probably not that visible when one uses the simple Mastodon UI, but with the column UI, one has the described problem. In both cases, one may want to open the thread in a new tab to read it and later link it somewhere else. And then, one does not want to link the own instance but the original instance.

**Comment by Muskworker** [comment]
> The use-case here is that clicking the date (like "1d ago") should take you to the thread on the original instance and not to the interface on your own instance.

I agree with you on this, but it looks that change was intentional due to discussions in depth (on #19652, #19967, and other places linked from there) that apparently people expect that link to go, not to the canonical remote link to see more information, but to a page they can interact (like/reply) from and were getting confused because remote server = not logged in = not directly interactable.    It is unlikely that they will revert it, though there are issues open (#20827, #20744) that requesting at least some way to get those remote links back again more easily than going through a menu.

**Comment by allo-** [comment]
I see the use-case for a click in the same window, but a click that opens it in a new tab should go to the original page.  
You can still get the link from the ... menu, but it requires more clicks and doesn't support middle click to open in a new tab.

I suggest clicking anywhere *but* the timestamp should open the toot in the current window on the own instance, but the timestamp should be the permalink (like it is on Twitter). I see the point in having Mastodon behave like a (web)app, but posts should also have an easy-to-reach permalink to reference them. And I won't suppose users click on the timestamp to open the toot in the same window or the active column. Compare it with Tweetdeck: Clicking the post opens it in the column (there it is the same column, but that doesn't matter), and clicking the timestamp opens the thread in a form that can be linked somewhere else.

**Comment by Muskworker** [comment]
Still agree. I found this ticket because I was going to suggest the link-to-single-column myself as a way of making their choice on this less onerous, because going to multi-column view for direct links is such a hassle.

But even if they can be persuaded to fix/mitigate it under #20827, making direct links go to a single-column view of the thing will still be useful because of all of the other places one might end up with such a link.

**Comment by allo-** [comment]
Another even worse aspect: When you try to open a toot from your own instance in a new tab and have the advanced interface enabled, you have to use private mode to get the single-thread view.

The direct link will always load the column interface and you cannot get the thread view while you're logged in.

**Comment by trwnh** [comment]
Discussed in another issue: now that the web app handles permalinks too, it would probably make sense to serve the advanced UI via its own URL route like `/deck` and have the single-column UI handle anything loaded in a new tab (with an easy way to get back to the advanced UI). In that sense, the advanced web UI becomes more like a "mode" for the app, and less like a completely separate frontend that gets conditionally loaded based only on a preference.

**Comment by bbbradsmith** [comment]
To summarize this issue I wrote at #22983:
* The simple UI single thread view is very useful for focused reading comprehension, and it would be very appreciated to be able to do this somehow, while still using the advanced UI for quicker browsing and short replies. (Previously on Mastodon, and always on Twitter/Tweetdeck, right clicking a timestamp and opening in new window would accomplish this.)
* The single thread view is also useful if you want to share a link to a thread externally. It will show you how the person you're sending it to will see it.
* Toots on other instances than the readers now behave differently, which makes it harder to navigate the UI. Local toots don't have a link to the toot in the ... menu but nonlocal ones do. There's a "copy" option but it's often not what I want either.
* Links to other instance toots now have a URL redirected through the local instance, presumably to facilitate the function of keeping it inside the window, but this makes it more difficult to share a non-redirected link to it outside of Mastodon.

My current workaround is to right click on a toot's timestamp and open in a new private browser window to escape the advanced UI setting. This also resolves the redirect, and if I want to share it from there I can copy the resulting URL. The downside is having another independent browser instance open, whose tabs cannot share with the main one, and the thread becomes read-only for the private tab.

There are multiple ways to address this, but the suggestion given to be able to go back and forth between advanced and simple UI more fluidly (and automatically through links) did seem sufficient.
