### ISSUE TITLE
Poll results not adding up to 100%

### ISSUE THREAD

**Issue by tofuwabohu** [mastodon/mastodon#21696]
### Steps to reproduce the problem

See this link: https://norden.social/@SheDrivesMobility/109399086475141677

On another instance: https://subversive.zone/@pony/109389132408968376

### Expected behaviour

results should add up to 100%

### Actual behaviour

summed up results are far away from 100%, not in rounding issue range 

### Specifications

Both instances are >=V4
Appears in Tusky as well

**Comment by afontenot** [comment]
Nice find. The raw data is quite strange in this case.

```json
{
  "id": "42246",
  "expires_at": "2022-11-25T14:18:14.471Z",
  "expired": true,
  "multiple": false,
  "votes_count": 468,
  "voters_count": 810,
  "options": [
    {
      "title": "Wenn,dann kaufe ich nur, was ich eh kaufen wollte.",
      "votes_count": 237
    },
    {
      "title": "Ich kaufe zuviel.",
      "votes_count": 25
    },
    {
      "title": "Ich kaufe da nix.",
      "votes_count": 197
    },
    {
      "title": "Ergebnis, mehr will ich nicht.",
      "votes_count": 9
    }
  ],
  "emojis": []
}
```

1. First of all, the frontend JS should presumably be using the `votes_count` to determine the percentages, not `voters_count`. That number is the sum of the votes as expected.
2. It's very strange that `voters_count` can be higher than `votes_count`. I *think* the cause in this case is that the poll was edited. Perhaps all votes before the edit were lost (except in the voter count), or perhaps just votes on edited poll items.

In the other case, the problem is the reverse. `votes_count` is greater than `voters_count`. What I notice is that for this poll `multiple` was set to true, meaning that multiple responses per user were allowed. I'm genuinely not sure what the correct way to present results for a poll like this is. E.g. suppose a poll allows multiple responses, has two answers, and receives votes from only one voter who chooses *both* answers. Isn't the correct presentation of this 100% for both?

**Comment by afontenot** [comment]
@tofuwabohu My fix for this has already been merged. The behavior (after this change makes it into a new release) should be that edited polls work correctly (although they remove all previous votes), and polls that allow multiple results show the same behavior as before (which is probably correct although potentially confusing).

You might, if you like, follow this up with feature requests like:

 * Make it clear when editing a poll that previous votes will all be deleted (a quick test seems to indicate that there's no warning?)
 * Make it clear when viewing a poll that allows multiple options to be selected that this is the case and that the poll total may surpass 100% as a result.

**Comment by tofuwabohu** [comment]
That was fast! I don't think it fixes the second one, though. The values add up to 104% which can't be through empty votes and it appears that it was not edited.
