### ISSUE TITLE
Updating Ruby Versions

### ISSUE THREAD

**Issue by HamptonMakes** [mastodon/mastodon#21741]
### Steps to reproduce the problem

1) Check the version that Bundler recommends by using `bundle platform --ruby`
2) Bundler says that it has detected Ruby 2.6.0

### Expected behaviour

Bundler should have selected our recommended version

### Actual behaviour

It selects the oldest possible supported Ruby version in our Gemfile

### Detailed description

When deploying the Mastodon application, it's standard to use the command `bundle platform --ruby` to identify which Ruby version should be used. With the current Gemfile set up, Bundler reports back `2.6.0`.

This is a problem for several reasons, not least that a bunch of security patches came out on the 2.6.x release meaning that `2.6.10` would include the latest security fixes out of the box (vs us suggesting such an old version).

And second of all, 2.6.x has been EOL since April, and the newest security releases that just came out this month aren't included in the series at all.

I'd like to suggest that we update `Gemfile` to match the version in `.ruby-version` by using a line like...

`ruby File.read(".ruby-version").strip`

This will mean that the Gemfile will always specify the version that we specify in ruby-version.

### Specifications

Mastodon Edge
Bundler version 2.2.33

**Comment by HamptonMakes** [comment]
https://github.com/mastodon/mastodon/pull/21742#issuecomment-1333936019

**Comment by mjankowski** [comment]
As of current main, we have alignment between .ruby-version and the bundler lockfile version.

Bundler has a feature which lets you do something like `file: ".ruby-version"` to specify the ruby version from the Gemfile, which would be ideal to keep them in sync ... but because we support multiple ruby versions we can't go that far.

That said, I think the issue here as originally described is resolved.
