### ISSUE TITLE
Change Referer value to something generic such as "urn:activitypub:mastodon" or similar

### ISSUE THREAD

**Issue by JimKillock** [mastodon/mastodon#21795]
### Pitch

Currently, Mastodon does not appear in webstats anywhere, as it asks browsers to omit any referer value. This is a privacy measure to ensure that individual user accounts and small servers are not identified to webstats. As such it is a valuable and important measure to take.

As an alternative, it may be possible to specify something generic in the refer value such as "urn:activitypub:mastodon" (see discussion at https://social.openrightsgroup.org/@jim/109410874507856716 )

This would allow webstats to see how much traffic is flowing from Mastodon to their services. It would be a valuable indicator to valuable campaign and government organisations that they should consider investing time and energy into proividng content via ActivityPub. 

It would also reduce pressure for an arms race using tracking signals, such as tracking codes and URL redirects.

### Motivation

1. The prime beneficiaries would be campaign organisations and governments who would get an indication of traffic to assess its value.
2. Journalists and newspapers would also be able to see traffic and think about using ActivityPub services to promote their content. 
3. The network as a whole would benefit as such organisations would be more inclined to share content through the network.
4. Users would benefit from reduced pressure for people to try alternative tracking mechanisms.

See https://toot.kif.rocks/@anathem/109416021008127272 for suggestion

**Comment by Ruppsel** [comment]
Seconding that. This should also help webmasters with smaller servers figuring out what goes on in case load/pageviews go up.

**Comment by Gargron** [comment]
It seems like `noreferrer` was added more or less by accident in #12202...

We set `Referrer-Policy: origin`, which is the conscious privacy choice to not reveal which page in the web app the user was on.

**Comment by orithena** [comment]
Adding the linked suggestion directly here: 

A referer header must contain a URI. Since a URI does not have to be a URL, a generic URN of the form "urn:activitypub:mastodon" or suchlike would work too.

**Comment by Gargron** [comment]
You can't control the referrer header value beyond Referrer-Policy

**Comment by JimKillock** [comment]
Thanks @Gargron so looks like we are mostly barking up the wrong tree with the idea of a generic URN, except maybe for mobile apps.

Is it a privacy risk to include domain in the referer information on larger instances, eg 5k users+?

Maybe the policy should or could be set according to instance / active user size?

**Comment by nhhollander** [comment]
I think it would make sense to have it configurable by the user (as an account privacy option) as well as the instance owner/operator.

**Comment by Gargron** [comment]
I think we can remove `noreferrer` from links and that `Referrer-Policy: origin` is sufficient for privacy. After all, we did not have `noreferrer` before 2019 and as far as I can tell nobody complained.

**Comment by ClearlyClaire** [comment]
Having something generic like `urn:activitypub:mastodon` could be useful, but as said previously, we cannot achieve that, at least in the web app.

> I think we can remove `noreferrer` from links and that `Referrer-Policy: origin` is sufficient for privacy. After all, we did not have `noreferrer` before 2019 and as far as I can tell nobody complained.

I disagree with this, `Referrer-Policy: origin` may very well be insufficient, as it will leak the information that someone is coming from a small (possibly single-user) or specialized instance.

**Comment by aendra-rininsland** [comment]
Agreed with @ClearlyClaire — if you have a single user instance and you're checking out a fediblock post link to confirm before domain blocking, you absolutely do not want your hostname to show up in the logs of one of the Fediverse's harassment-focused instances, particularly if you're from a minority group that is frequently the target of harassment from one of those instances.

**Comment by selfagency** [comment]
IMO this should be something optional in the server administration settings so that communities can set their preferences based on their own needs.

**Comment by buro9** [comment]
even if it provided as a server option, privacy for users shouldn't be something that is opt-out. the default should be that it is disabled unless an admin explicitly chooses to opt-in.

I've moderated forums for a couple of decades, and now run a Masto instance, and I've seen firsthand communities use the knowledge of where traffic is coming from as a mechanism to send people that direction to bully people. For years people have been explicitly breaking links in their posts on forums to avoid the referrer revealing the source of traffic and resulting in harassment and "forum invasions". Masto has avoided this because of the lack of referrer and a decision to add support should not be trivially made but very consciously made with awareness of these unintended and negative side-effects.

**Comment by drazisil** [comment]
Please keep `noreferrer`. Or at least if configurable, it should be on by default.

**Comment by axb21** [comment]
This should not be a default setting, and mastodon should not be about tracking people. Tracking people is for surveillance capitalists and other bad actors. The typical person does not want or need this change, and it can cause a lot of potential harm.

Please work on curing yourself of this "must track all the things" mind virus and focusing on people.

And @Gargron , come on--the fact that "nobody complained" about the lack of `noreferrer` before 2019 does not mean it is fine to remove it now. That's a child's logic. You write code, you should be better at analysis than this.

**Comment by Wack0** [comment]
...wouldn't this result in data protection/GDPR problems? If removing noreferrer had to be done (IMO it shouldn't, catering to people who want analytics is the complete opposite of anti-tracking),  then it should be opt-in at the user level.

**Comment by drazisil** [comment]
`Referrer-Policy: origin` is not the same. It exposes the origin.

If you must switch to a header, set it as `Referrer-Policy: no-referrer`

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

I can get behind making it configurable, as long as `no-referrer` is the default.

Instance privacy settings should start locked down and let the admin decide how much to share.

This would be in line with "You have control over your information."

**Comment by mikeelston** [comment]
Make it a config. Per user. No referer by default (opt-in model) let the users maintain control of their privacy. 
Give server admins a config to force noreferer or allow user choice.

**Comment by drazisil** [comment]
> Please work on curing yourself of this "must track all the things" mind virus and focusing on people.

I know this is an emotional subject. Let's try to remember that this is an unpaid, one-person project, and the amount of stress and pressure from wannabe investors and the press is probably insane. I think I'd have a mental stroke and have to be committed if a project went viral as Mastodon has. :heart:

**Comment by probgoblin** [comment]
This is a change that does not seem to offer any direct benefit to the user or even instance administrator, while potentially exposing them to actionable information _without their knowledge_.

I believe that, should this be added in, it needs to:
1. Remain as "no-referrer" by default
2. Be configurable via the admin panel rather than only through the CLI
3. Be visible to the end user of the instance as either a footer on the UI or be required to be clearly stated in the "About" section for any sever joining the Mastodon Server Covenant.

**Comment by drazisil** [comment]
> 3\. Be visible to the end user of the instance as either a footer on the UI or be required to be clearly stated in the "About" section for any sever joining the Mastodon Server Covenant.

Love this as a requirement. One of my models for UX is to show people why something is the way it is. Knowing your instance's privacy settings would be :medal_sports: 

It's probably a separate task though. Scope creep kills.

**Comment by untitaker** [comment]
If you switch to referrer policy origin, the community will come up with a workaround that will be far less nuanced in terms of trading user privacy vs need for analytics. Please solve this problem properly in a way that doesn't fragment the network further or just don't do it at all. I shouldn't have to tell you this.

**Comment by FiloSottile** [comment]
I generally agree that enabling Referer by default for small or sensitive instances would be a privacy issue, but I want to mention that there is value to the conversation in having an idea where interest is coming from, and this would be a useful and safe thing to enable for large instances.

If `infosec.exchange`/`mastodon.social`/`mastodon.online` enabled Referer it would make it possible for me to know where a technical article is being discussed, and try to join the conversation. It also helps knowing where my readers are, and for example if I didn't have a Fediverse account it would tell me whether it makes sense to make one.

The privacy cost of large instances enabling `Referrer-Policy: origin` seems null: the anonymity set is very large, and without instance-wide search, it can't lead to individual follow-up harassment. Sure, some groups might have custom search tooling, but then they don't need Referer at all to search links to a domain.

(Also, folks, as a fellow Open Source maintainer, please be nice to @Gargron.)

**Comment by axb21** [comment]
> I know this is an emotional subject. Let's try to remember that this is an unpaid, one-person project, and the amount of stress and pressure from wannabe investors and the press is probably insane. I think I'd have a mental stroke and have to be committed if a project went viral as Mastodon has. heart

You are literally advocating on behalf of surveillance capitalists by saying this. Why are you doing that?

That is the issue I raised with that aside about mind virus. For too many people, the knee-jerk reaction in situations like this one to side with the powerful, at the expense of the users of the system. *That is a bad way to be because it literally harms people* and we all should work on not having that reaction. 

This particular github issue, if you're focused on user safety, is a very simple one: do not make this change, because its only purpose is to increase the effectiveness of surveillance, which can harm individuals *and only helps businesses*. There's no hand wringer, stroke having, or stress necessary to make a decision about whether to do that. Close the issue, move onto something else, the end. The only reason one would struggle with it is if one is torn about just how much user safety they're willing to trade for $$$, or the promise of $$$, or the possibility of a promise of $$$, or.... And you're only torn in that way if you have this mind virus. 

Frankly, no one person should be in the position to make that kind of decision on behalf of so many others, but that's another issue.

Anyway, `noreferrer = nobrainer`

**Comment by kescherCode** [comment]
If added, this must be opt-in and it must be visible to the user.

Personally, I would completely remove this entirely once added. Browsers are already in the process of yeeting this header anyway, because, well, privacy reasons.

**Comment by drazisil** [comment]
> You are literally advocating on behalf of surveillance capitalists by saying this. Why are you doing that?

I think you misunderstood my message. I was not saying fold to money or the press. I was saying be nice. You can note that at no time have I advocated for the removal of these settings. I'm not going to spend my weekend side-tracking an important issue, so if you still disagree then I wish you a good day.

**Comment by KolyaKorruptis** [comment]
[no-referrer](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noreferrer) implies [no-opener](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noopener). Both prevent the Javascript window object from leaking to the link target. And the window object contains a plethora of private information in Mastodon. 

If you want to remove no-referrer for whatever reason, at least replace it with no-opener, to prevent this information getting leaked to every external link target.

**Comment by untitaker** [comment]
Now that i'm back on the computer, I have some more thoughts.

I think the best idea I currently have is to keep noreferrer but to inject `?utm_source=mastodon` into every link you click on. This "demonstrates value of the network to advertisers" or whatever without exposing which instance a user came from. Opt-in/opt-out or whether this should be configurable is TBD.

This would also solve a problem where a newspaper is actually exposed to a long tail of nondescriptive instance domains like "blahah.zone", which doesn't immediately mean "mastodon" to them anyway.

If your idea is that most of the traffic comes from a handful of large instances, and therefore exposing the origin domain is good enough, then the entire discussion is a no-brainer: make larger instances opt into this relaxed referrer policy, where the privacy implications are nil and most of the traffic comes from.

I'm honestly mostly disappointed in how this change is being communicated: as a single "remove noreferrer from links" on the [roadmap](https://joinmastodon.org/roadmap), an unnuanced, half-baked take that "referrer-policy: origin does not impact privacy" and that adding it was a mistake. Honestly, this alone justifies the emotional debate about this issue because regardless of whether there are better solutions out there (certainly) or whether Eugen might have a more nuanced take on this (maybe), that's not what's being communicated.

**Comment by NickColley** [comment]
"It would also reduce pressure for an arms race using tracking signals, such as tracking codes and URL redirects."

There should be real world evidence this is an issue for the end-users of Mastodon, the needs of governments and corporation should not come before regular people.

Mastodon should not support surveillance capitalism, this one clear reason people use it over alternatives.

**Comment by blakestacey** [comment]
Chiming in to agree that no-referrer needs to remain the default, even if an option to change that is included (and I'm not really seeing the case to include it).

**Comment by JacksonChen666** [comment]
**we, as users, don't benefit from this change.** so we don't have to enable the "Referer" header, by default or at all.

the "[Referer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer)" header is part of the "[Forbidden header name](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name)" list, meaning you (the program) can't touch that header. therefore, the original suggestion is completely broken, by accidental design. so, the suggestion isn't even possible to implement practically.

if we allow the Referer header itself, we aren't benefiting from that.
mastodon (the software) has already disallowed that, and we didn't really care (ref: some comment here).
so why should we care about turning that header back on? again, **we, as users, don't benefit from this change.** so should we really undermine our own [privacy and security](https://developer.mozilla.org/en-US/docs/Web/Security/Referer_header:_privacy_and_security_concerns) just for analytics we don't even get to see?

what are we gaining, and losing, if we enabled the Referer header?
what about if we disabled the Referer header

quoting from a [comment above above mine](https://github.com/mastodon/mastodon/issues/21795#issuecomment-1374540771):
> Mastodon should not support surveillance capitalism, this one clear reason people use it over alternatives.

additional links:
- https://developer.mozilla.org/en-US/docs/Web/Security/Referer_header:_privacy_and_security_concerns
- https://drewdevault.com/2020/12/04/Analytics-and-informed-consent.html

[Referer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer): https://micro.jacksonchen666.com/@feditips@mstdn.social/109648834118064578 (do you really think this will benefit *the users*? the users will *never* see this header (unless they dig real deep, at which point it's too deep))

**Comment by rcanada** [comment]
Is this something that could be made a setting? I, as a server admin, what to:
* Be able to set my server to no-referrer (default)
* A generic reference to Mastodon.
* My specific domain.

I, as a user, want:
To know what a server is set to on the about page.

Personally, I think that collecting referrer information is a violation of individual user privacy and should be banned, but that is just me.

**Comment by LuisMayo** [comment]
Referer-policy: origin only exposes the host name so it doesn't affect users at all
Loads of you are suggesting to make this a per-user setting but it doesn't make sense. The user URL is never going to be exposed anyway.

I'd see the usefulness of this being a per-instance setting but I do agree it should be opt-out. Referer is not only used for "surveillance capitalism" but to look for audiences like it's been said in this thread

If you're a one person instance you can disable it yourself so they can't find your instance and that should be it

**Comment by djnavarro** [comment]
For what it's worth I would strongly support the folks expressing concerns about privacy. To identify individual users in a data set you don't need a unique identifier for each person, you just need enough moderately-informative signals. It's why members of minority groups often lie about their demographics on surveys: if I tell you that I am a trans woman who used to work as an Australian academic and add a few other little pieces of information, I quickly become uniquely identifiable. Enabling referrer information from small instances is a very strong signal and will make users uniquely identifiable if the target site has access to other sources of information. I rarely use analytics on my own sites and try as much as possible never to use the referrer information I receive, but in many cases I can uniquely identify individual readers when they have come from a small website. I don't think we want this for mastodon, and the utility for journalists, etc is not sufficient to justify stripping users of their privacy

**Comment by jubalfh** [comment]
> Referer-policy: origin only exposes the host name so it doesn't affect users at all

good joke.

**Comment by kescherCode** [comment]
> Referer-policy: origin only exposes the host name so it doesn't affect users at all
> Loads of you are suggesting to make this a per-user setting but it doesn't make sense. The user URL is never going to be exposed anyway.

@LuisMayo Sorry but... please read the replies before yours. Your point has already been made moot. However, to summarize:

The Mastodon Network™ does not just consist of large, or even huge, instances. Single-user instances and otherwise small instances exist.  They are often run by small communities made of and run for marginalized folks commonly targeted by harassment.
Awful instances out there will, with `Referer` being set on a link to their instance being clicked, absolutely have more data to go harass exactly these types of folks.

Say, someone on `cozy-space.example.org` reads a post posted by someone on awful behaviour coming from a particular instance, say `literal-neonazis.example.moe`. As a receipt, there's a link to this awful instance. Now, once that is clicked, the Referer header would be set, the remote instance would then know that a request actually came from a specific instance, instead of just being random web traffic that could have come from anywhere, and start harassing that instance.

Further, as a user, I do not want to tell all websites that I am accessing their article or whathaveyou from a link via `cozy-space.example.org`. In fact, I do not want to tell anyone where I was prior to accessing their site before/while/after accessing it. And that, preferably, without first having to copy the link and opening it in a new tab to avoid sharing this type of information.

**Comment by rcanada** [comment]
> Referer-policy: origin only exposes the host name so it doesn't affect users at all Loads of you are suggesting to make this a per-user setting but it doesn't make sense. The user URL is never going to be exposed anyway.

You need to consider the other information the destination website may be collecting such as IP addresses. It is not just the Referrer-policy. It is the referrer-policy plus every other item the destination website collects.

Please keep in mind that the world is not a safe place for many people. 1000 people just had their social media accounts suspended in China. People are being arrested and executed in Iran.

If people with a whole lot of safety privilege want their local media and government on the Fediverse, they can call them and encourage other like minded people they know to do the same.

**Comment by suddjian** [comment]
Hi, I see many takes here like this one:

> The privacy cost of large instances enabling Referrer-Policy: origin seems null: the anonymity set is very large, and without instance-wide search, it can't lead to individual follow-up harassment.

I want to point out that this is not true. **Using domain as origin is a privacy risk regardless of instance size.**

For example, with a log of accesses from a domain you can estimate a pretty reliable timestamp of when the link was posted. You can then quite easily browse to that point in the instance’s local timeline and find all the individuals involved in the conversation. No text search necessary.

I hope that you close this issue and please do not build tracking features into this software ❤️

**Comment by StarWitch** [comment]
Do not expose information about users or their instances without their consent. This is why most people came to Mastodon and the Fediverse at large, and aren't still on Twitter, Facebook, or whatever else is out there.

Since this issue suddenly exploded, and given that there is a humongous propensity to blame this sort of attention on "hate mobs" being "organized on Discord" or whatever, I thought I should just say this: this issue came to my attention *organically* through the Fediverse by concerned citizens trying to bring it to light.

I bring this up, as this discussion reminds me of the horrific decision the [Audacity](https://github.com/audacity/audacity) team made where they decided, unilaterally, to include invasive telemetry into their app after years of it just being a simple-yet-universally-used audio editor, right before they decided to clamp down very hard on discussion or criticism of any kind and do it anyways, against their user's wishes and consent. Open source was poorer then, and it'll be poorer still if this decision goes through.

Do not let Mastodon, the software, devolve into one that dictates policy and brushes aside the people it is meant to serve. Mastodon should serve the people, not the other way around. You have been given tremendous opportunity and responsibility in equal measure to connect people in a way that does not disrespect them and their ability to stay private and secure. 

Use it wisely, and forget this tracking nonsense.

**Comment by MattWilcox** [comment]
Mastodon is a privacy first thing. `noreferer` should be the default for all the reasons stated above. I see no reason to change that; what's the supposed benefit to a users privacy by removing it?

**Comment by rcanada** [comment]
> > You are literally advocating on behalf of surveillance capitalists by saying this. Why are you doing that?
> 
> I think you misunderstood my message. I was not saying fold to money or the press. I was saying be nice.

Imagine the government/media is Afghanistan, Russia, or North Korea. Why are you asking us to be nice to them? Why be nice to Russian state controlled media?

**Comment by theCapypara** [comment]
> > > You are literally advocating on behalf of surveillance capitalists by saying this. Why are you doing that?
> > 
> > I think you misunderstood my message. I was not saying fold to money or the press. I was saying be nice.
> 
> Imagine the government/media is Afghanistan, Russia, or North Korea. Why are you asking us to be nice to them? Why be nice to Russian state controlled media?

Not nice to a country, just be nice in this conversation.

**Comment by lbruno** [comment]
uttering the famous last words "I am not a lawyer", but here goes:

- mastodon operators in Europe are the data controllers[0] of what their users post, and all the metadata info correlated with that
- up until now, the operation of mastodon did not require disclosing an user's clickflow

the above should make you anxious, since having the user's browser snitch the source website of a link they've followed is new processing of people's personal[1] information -- so mastodon server operators would have a higher barrier to justify this new processing since it's clearly not needed for the operation of mastodon

in other words, operators can't rely on the previously obtained consent as the lawful basis to start processing this new flow of information, since this is a **new purpose** for which they'd[2] be processing that personal info. at a minimum, a new consent flow would need to be completed for each user whom a mastodon instance would send a `Referrer-Policy: ...` header, causing their clickflow to be disclosed to an unknown party.

> personally i'd argue [again, not a lawyer, merely an amateur who really loves the GDPR] that you can't rely on consent at all for this new purpose, since the mastodon operators should be aware there's no easy limitation of who'll get that personal info: hence, consent can't be specific and informed nor revoked.

the fact that the fediverse has operated without the referrer function until now also limits the use of the "necessity" lawful basis under the GDPR; trying the "legitimate interests" lawful basis is risible on its face.

hence i ask: under which lawful basis will mastodon server operators be processing this new personal info transfer? possibly into the USA, which the CJEU has decided doesn't possess adequacy? obviously i think none of the lawful basis in article 6.1 of the GDPR allow the transfer and processing of this personal data.

[2]: before someone unwisely says it's the browser that's sending the info: computers aren't parties, the server operator and their users are -- and it's the server operator whom configured the user's browser to transfer that personal information, to parties unknown.

[1]: the GDPR deals with a lot more than people's privacy, hence the definition of personal information is much more wide than merely an IP address or a name: it includes personal info and anything that could be linked to then derive personal info indirectly

[0]: there's an argument to be made that w.r.t. user-generated content website operators are data processors -- since we can't easily control what data is submitted into a free-form textbox -- compare to how we can easily refrain from asking for a date of birth: the former makes you a data processor, but the latter makes you a data controller. I don't think anyone's made that argument, so the requirements on mastodon server operators is as strict under the GDPR as can be, even for UGC.

**Comment by davidmegginson** [comment]
I understand the use case earlier about a researcher being able to discover that their article is being discussed in the fediverse and then join the conversation, but I don't support it.

Even though it's fairly benign, that's still a type of surveillance that wasn't available to most academics until the late 1990s — we didn't bug each-others' common rooms and listen in before that — and it shows the extent to which surveillance has become normalized (and even expected) in society since the rise of popular web search engines ~25 years ago.

I've been complicit in that during my career, but I appreciate now that the fediverse is taking a step back, and don't support any change to make Mastodon activity more visible. We don't need to know everything, including when people are talking about us and our research.

**Comment by Yayroos** [comment]
The only potential benefit I've seen discussed above that isn't pure surveillance is that more people will hear about the fediverse and mage check it out. Which is great in theory, but I think the last few months and the growth that has come with it (including my presence! and a bunch of my friends!) demonstrates that the fediverse isn't struggling for that visibility at the moment.

The line I give people to sum up the appeal of mastodon is 'no ads no tracking no algorithm'. It doesn't make sense to me to throw any part of that away for the nebulous idea that destination sites knowing how much traffic comes from mastodon is somehow good for us. I don't want the fediverse to look appealing as a place for advertisers or massive organisations, it's for, by, and about, people.

And even just by being from mastodon, a destination site can gain a lot of targeting about you, your interests, and intentions. which instance in particular is worse, even just for large instances. If for example someone joins a regional server like aus social but otherwise browses with a VPN now their alternate location in the VPN is useless. 

Also, if this did go ahead for whatever reason, user based consent needs to be opt in (and nobody would, unless it was as disingenuous as all the 'allow cookie' popups everyone clicks through because it's so hard to find the 'go away' button.) And it needs to be no tracking at all for logged out users. People browsing logged out often have good reasons for doing so, and we shouldn't be compromising that.

**Comment by DRKSLV** [comment]
It's a little funny how agressive some of yall are being...
i'm sure Eugen and Contributors got the Memo
The thing is: most links on the internet send referrer information, almost every link on every site.
[including this one](https://google.com)
![image](https://user-images.githubusercontent.com/56208328/211175011-422f33aa-3011-49c5-8f52-afa580720529.png)

And since adding the norefferer attribute wasn't a concious choice, they probably didn't think too much about the issue until everyone came in, to raise concerns - which was important to do.
But immediately implying that they would do this out of greed, and insulting/belittling them?
Not considering that maybe it's normal not to have all answers at the start?

I don't disagree that leaving the `norefferer` attribute by default might be the best choice.
But the way some of you are antagonizing the contributers over this? You're acting like they just joined the project with the intent of turning it into a surveillance tool.
C'mon, be a little bit more polite.

**Comment by jubalfh** [comment]
> It's a little funny how agressive some of yall are being... 

[…]

> (…) But the way some of you are antagonizing the contributers over this? You're acting like they just joined the project with the intent of turning it into a surveillance tool. C'mon, be a little bit more polite.

i see that the civility police have arrived. do kindly learn to not mistake disagreement with aggression.

regarding the reaction – one should *expect* the main author of mastodon to be aware of privacy ramifications of default link policies.

**Comment by DRKSLV** [comment]
@jubalfh there were plenty of people vehemently disagreeing without being disrespectful

**Comment by Gargron** [comment]
Comment above sums it up correctly. The change that introduced the `noreferrer` attribute was not made by me or Claire and there was no discussion or deliberation that accompanied it. It was one random person's decision that I missed during review.

What was always deliberate, is `Referrer-Policy: origin` protecting logged in users' privacy by only exposing the domain, but not the exact path of where they come from.

I think we can all agree that privacy is important. I think we should also acknowledge that the referrer header is something your browser does by default and is part of the web since 1996.

I think that people who run personal websites and blogs can attest that knowing where your visitors come from is useful. For example if you see news.ycombinator.com in your web logs you know you're on the frontpage of Hacker News.

It could be concerning to any website owner that an entity collectively approaching or surpassing Slashdot in size is essentially a black hole of traffic. It's not always little single-user server vs. giant commericial website.

That being said, there are good arguments for abandoning the referrer header. But it has to be a deliberate choice. At the moment, I can't actually guarantee that no link in Mastodon allows the browser to send the referrer header. It could well be inconsistent.

**Comment by Wack0** [comment]
@Gargron

While it's true that the browser indeed sends referer header by default, any links clicked in a native client will always have no referer header anyway, so why shouldn't webui be consistent with native clients here? (Especially when people can use webui as a PWA...)

**Comment by Yayroos** [comment]
'Every other site does it' isn't a good reason, from my perspective. The whole point of mastodon and the fediverse from where I sit, and most of the reason I joined, was to build the web the way we actually want it instead of just going along with what everyone else does. Referrer headers don't add value for users, so to me it's an easy choice to not use them. If they do or don't add value for businesses doesn't even come into my equation because the idea falls at the first hurdle.

**Comment by WisTex** [comment]
I read the comments on the issue and people sure are passionate about it. Considering how divisive this appears to be, I'd recommend giving instance owners an option, and letting users know what the option is.

There is no privacy concern on large instances, since the referrer does not tell you which of the hundreds of users clicked the link. And small instances can set their instance to "noreferrer" if they are concerned about their privacy.

**Comment by aendra-rininsland** [comment]
@Gargron Thank you for responding to this. I'm frustrated and disappointed by how emotional this has gotten, I honestly didn't expect that [mentioning this issue](https://hackers.town/@aendra/109648596037999240) would result in today's response. I looked through that pull request when I was researching the `noreferer` Mastodon puts on links a few months ago, and you're right, it was a surprisingly fast review process for such a hugely important technical decision — but honestly I strongly feel it was the right decision nonetheless, and one which has helped immeasurably to protect communities from harassment.

> I think that people who run personal websites and blogs can attest that knowing where your visitors come from is useful. For example if you see news.ycombinator.com in your web logs you know you're on the frontpage of Hacker News.
> It could be concerning to any website owner that an entity collectively approaching or surpassing Slashdot in size is essentially a black hole of traffic. It's not always little single-user server vs. giant commericial website.

Please realise that by stating this, you are effectively weighing the needs of an unknown abstract website operator versus the very real lived experiences of harassment that users on the Fediverse have encountered. Please read the thread I linked above. People are concerned about this.

> That being said, there are good arguments for abandoning the referrer header. But it has to be a deliberate choice

What needs to happen for this to be a deliberate choice? As somebody with legs in both the trans and journalism communities, I will happily put in whatever work needs to be done to champion this request.

**Comment by rcanada** [comment]
> I think that people who run personal websites and blogs can attest that knowing where your visitors come from is useful. For example if you see news.ycombinator.com in your web logs you know you're on the frontpage of Hacker News. 

From my marketing person and multiple website owner perspectives, I stopped taking the information seriously when I learned that it can be and is spoofed for multiple reasons.

**Comment by pauljacobson** [comment]
> If you're a one person instance you can disable it yourself so they can't find your instance and that should be it

I essentially run a single user instance (the other user is inactive). I'd still prefer to have a more private default, with an option to expose my domain if I decide to do that.

**Comment by Ruppsel** [comment]
I do not want to escalate that further, but....
 
> Please realise that by stating this, you are effectively weighing the needs of an unknown abstract website operator versus the very real lived experiences of harassment that users on the Fediverse have encountered. Please read the thread I linked above. People are concerned about this.

...i surely am not an abstract entity. I am totally with you regarding safety of marginalized/harrased groups. And i can't actually imagine that it should be impossible to protect them while giving webmasters at least some basic information on the amount of traffic mastodon generates on their infrastructure. 

Mastodon *is* a black hole in this context, and as far as i know, nobody actually oversees the infrastructure load it generates outside the fediverse (if there are tools/analysis, please let me know). What i *can* see is that there is a Factor 10-20 more traffic on my site since i joined fediverse. Thats fine for me, but i guess there are others where changes like these are a problem/start to cost money etc.  I also guess among these are actors with good reasons to run own instances instead of joining some centralized services. 

Thats definitely no black/white issue of surveillance capitalism, as some like to put it here. Mastodon is on its way to generate large amounts of traffic/load, and (no offense meant!) it doesn't do this in the most effective way possible, and it doesn't do this on fediverse infrastructure alone (where we already know the cases of skyrocketing traffic/costs after some big account weighing in on a small server). And i guess its not too far fetched to state that there comes some kind of responsibility with that.

**Comment by davidmegginson** [comment]
> Comment above sums it up correctly. The change that introduced the `noreferrer` attribute was not made by me or Claire and there was no discussion or deliberation that accompanied it. It was one random person's decision that I missed during review.

Thank you for your work on mastodon, @Gargron ,  and I'm sorry that you've had to endure personal attacks in this thread.

I respectfully suggest that intentionality isn't as important as you are making it out to be. Even if the feature had ended up in Mastodon only because a cat walked across somebody's keyboard, once it has been there for a while and people come to expect it, it is part of the platform's user experience just as much as if the core developers had sat down and deliberated over it for months. So whatever the decision, I do not believe that it should be based on the process that introduced the feature originally.

**Comment by ClearlyClaire** [comment]
> I can't actually guarantee that no link in Mastodon allows the browser to send the referrer header. It could well be inconsistent.

What about changing `Referrer-Policy` from `origin` to `no-referrer`? (And move it to a default header rather than just for `WebAppControllerConcern`)?

**Comment by suddjian** [comment]
> Mastodon is on its way to generate large amounts of traffic/load, […] And i guess its not too far fetched to state that there comes some kind of responsibility with that.

I would love to see that responsibility fulfilled through organic human interaction rather than automated surveillance of traffic.

**Comment by Ruppsel** [comment]
Its actually helpful to understand a problem before offering "solutions". ATM, there is no way to find out for an overloaded site if its ddosed (-> get defence) or heavily visited through the fediverse ( ->  get more server resources) and "organic human interaction" will not help anything.
Again, this is not about surveilance but respect and transparency for others.

**Comment by suddjian** [comment]
That’s quite a presumptive comment, I do know a thing or two about these issues actually.
