### ISSUE TITLE
Support OAuth PKCE to allow third-party single-page apps to utilize best practice when authorizing with an instance

### ISSUE THREAD

**Issue by ilovecomputers** [mastodon/mastodon#21913]
### Pitch

Mastodon [hasn't configured PKCE on Doorkeepr](https://github.com/mastodon/mastodon/discussions/17207?sort=top#discussioncomment-1913479). Will it be possible to make that OAuth extension accessible?

Also, if PKCE is used, can the client secret _not_ be shared by the instance when the app registers with it?

### Motivation

If you are to write a third-party app that runs completely off the browser and it needs to authorize with an OAuth capable server, the best practice is to use ["the Authorization Code flow with the PKCE extension"](https://oauth.net/2/browser-based-apps/). Since Mastodon doesn't offer that extension, such a third-party client would have to store [the client secret in `localStorage`](https://github.com/takahashim/mastodon-access-token/blob/master/index.html#L189) in order to retrieve access tokens. Storing the client secrets in `localStorage` is [insecure](https://thesecurityvault.com/auth-token-in-localstorage/).

Why not create a backend to keep the client secret safe? Well now you have [to store the client secret for each mastodon instance in a database](https://github.com/diddledani/twitodon/blob/fd943cc163f516b4e943c529ae77f5a17f731407/api/mastodon.mjs#L39). Also, the creation of the backend is extra effort, complexity, and resources 💸.

**Comment by ilovecomputers** [comment]
Upon further review, PKCE was designed assuming apps could [only be registered once](https://developer.okta.com/blog/2019/05/01/is-the-oauth-implicit-flow-dead#the-oauth-authorization-code-flow-is-better). However, Mastodon instances allow you to register your client app multiple times as can be demonstrated with [the Access Token Generator](https://takahashim.github.io/mastodon-access-token/) I linked to above as an example of storing the client secret in `localStorage`.

Even with PKCE, you have to store the `code_verifier` in `localStorage` as seen in [this okta article's code example](https://developer.okta.com/blog/2019/05/01/is-the-oauth-implicit-flow-dead#begin-the-pkce-request). So really, the only difference I see between storing the `code_verifier` or the `client_secret` in `localStorage`, withinin the Mastodon auth code flow context, is the former is generated client-side and the later server-side. 

I'm gonna leave this request open in case others see a benefit in turning on PKCE on Mastodon (even OAuth recommends it to be used [in addition to client secrets](https://oauth.net/2/pkce/)). However, feel free to close it if the maintainers see no reason to support PKCE.

**Comment by MaPePeR** [comment]
If I understand it correctly PKCE is currently not required for pure browser-based applications, because these have to register their own `client_id`+`client_secret` through the `POST /api/v1/apps`, which then kind of acts as a `code_verifier`. If you want to provide a "no trust required" tool, you can't have these on your server, though, because the server sees the oauth `code` in the GET Parameters and then could retrieve the access token without the user knowing. (Normally one would pre-register the application with a single instance and the `client_id` is public, so the `code_verifier` is required to restrict access to the access token to the browser, but here the `client_secret` is only known in the browser, so it should be fine?)

I think there still needs to be something done or clarified in regards to these pure browser based API consumers, though: The current setup requires these clients to register an application with the mastodon instance for every user of the app, possibly multiple times for each user (I think the linked Access Token Generator even does it every time you press the button). So that could add up to a lot of registered apps for a single application, which feels bad to me. Is that the intended workflow?

If yes Mastodon has to make sure, that either:
* There are regular cleanups running that purge registered apps from the database and having lots of them isn't a problem
  * I would not expect that to happen, though, because the normal workflow suggests only registering once and then storing and using that `client_id` and `client_secret` forever?
  * So maybe an additional flag is needed to mark a registered app as "temporary"?
* Or better: Registering the application with the mastodon instance is entirely stateless
  * For example: The Mastodon instance could "sign" the provided `scopes` + `redirect_uris`+ a salt + a secret with something like HMAC and return the result as a client-secret? (But unsure how to present/store stuff like `client_name` & `website` then? Could maybe also store these in `client_id`, so the client resends them when authorization happens)

Is something like this already happening, so it is fine to register multiple apps for each user of an application? Then this should be clarified in the documentation.
If this is not happening and we should refrain from creating applications that do that, that should also be clarified in the documentation and possibly fixed.

**Comment by dezren39** [comment]
Yes, this would be great please.

**Comment by erlend-sh** [comment]
In progress:

- #30329

**Comment by ThisIsMissEm** [comment]
As PKCE is now a OAuth 2.0 Security Best Current Practice, I'm going to try to get this into 4.3, such that in a future version we can enforce usage of PKCE for all clients: https://www.ietf.org/archive/id/draft-ietf-oauth-security-topics-27.html#name-authorization-code-grant
