### ISSUE TITLE
Attempting to create an account on an instance with closed signups just redirects to joinmastodon.org/servers ... if you're on mobile

### ISSUE THREAD

**Issue by untitaker** [mastodon/mastodon#21933]
### Steps to reproduce the problem

1. Go to https://cloudisland.nz/about or https://mastodon.social/about -- both instances have closed signups entirely.
2. Resize your browser window to be not very wide.
3. Click 'Create Account'

### Expected behaviour

The mastodon UI shows me the normal modal for why signups are closed

### Actual behaviour

Straight redirect to joinmastodon.org

### Detailed description

This behavior does not work well with instances where one is expected to follow a custom process for signups. I was quite confused what the signup process for cloudisland.nz was on mobile, because only on Desktop there is a link to their Patreon.

### Specifications

Mastodon v4.0.2, rest doesn't matter IMO because I assume this behavior was coded with intent.

**Comment by untitaker** [comment]
cc @aurynn since she might want to know that cloudisland.nz looks basically entirely locked down on mobile.

**Comment by rbairwell** [comment]
I think this is a duplicate of https://github.com/mastodon/mastodon/issues/21556 and/or https://github.com/mastodon/mastodon/issues/20840 and looks ike it could actually be fixed in https://github.com/mastodon/mastodon/pull/19437 .

If this is the case, please could you leave a comment saying whether the that pull does appear to fix the issue as far as you can tell or if the two other issues are more appropriate: and then just select "Comment and close issue" so the size of the backlog of issues doesn't get too scary looking for the poor devs. Thanks!

**Comment by untitaker** [comment]
#19437 has landed as part of 4.0.2, but I'm reporting the bug against that version. So I don't think it's fixed in main.
 I think this issue is a duplicate of https://github.com/mastodon/mastodon/issues/20840 but not #21556.
