### ISSUE TITLE
Helm: all-queues worker does not handle ingress queue

### ISSUE THREAD

**Issue by michaelburch** [mastodon/mastodon#21962]
### Steps to reproduce the problem

1. Install Helm chart
2. Visit sidekiq page http://instance/sidekiq/
3. Observe error "no worker assigned to ingress queue"

### Expected behaviour

all-queues worker specified in the values file should include all queues

### Actual behaviour

no worker is assigned to the ingress queue

### Specifications

Mastodon 4.0.2

**Comment by nekomeowww** [comment]
I have created a mastodon instance by using the original chart from `mastodon/mastodon` repo previously and encountered some issues that caused by the case where `sidekiq` queues were never being processed.
While such issues has been fixed by mastodon/chart#1, I would like to mention a little bit of the causes and relates I have faced in order to help more people to find out a way out of issues and migrate to the newer chart ASAP if possible.

I have encountered the following issues:

1. The joining request to a relay will always to be shown as `Waiting for relay's approval` and the status never changed even when your local instance has been listed and shown by the relay servers.
2. The outbox from other instance such as replies, new toots, followers, following request won't be shown and updated in local instance even when you confirm that the replies, toots, followers were already present in another working instance.

To make sure you are in such case:

Check the logs of `mastodon-web*` pods by `kubectl logs -f mastodon-web-<hash>-<hash> -n mastodon`, you will find out there are many `method=POST path=/inbox format=json controller=ActivityPub::InboxesController action=create status=202` logs without any errors or warns. However, this still means your mastodon instance have acknowledged and accepted the requests from outer instances/servers, and these `/inbox` messages are waiting to be processed asynchronously.

Next, heck the logs of `mastodon-sidekiq-all-queues*` pods by `kubectl logs -f mastodon-sidekiq-all-queues-<hash>-<hash> -n mastodon` to make sure there are no errors, if you do have, try to resolve them first. Afterwards, you could check the `sidekiq` panel from `Sidebar` -> `Preferences` -> `Sidekiq` of your mastodon instance Web UI, if you have planty of items in the `Enqueued` (in my case, I have 420k items in queue), you are probably facing the same issues as I was.

To resolve this case, you will need to migrate your helm installation to the new one in `mastodon/chart` which have fixed the issues I have mentioned above.
