### ISSUE TITLE
Add a canonical URL tag for search engines

### ISSUE THREAD

**Issue by unbelauscht** [mastodon/mastodon#22907]
### Pitch

Add a `link rel="canonical"` tag, so that search engines know the original source of the post.

### Motivation

This should cleanup results in search engines, as search engines are currently indexing posts multiple times.

**Comment by nemobis** [comment]
Agreed. Canonical URLs also help ensure that the indexing preferences of the post authors are respected. (For example, if a post is deleted or updated, it's easier to update one URL than it is to update thousands. Search engine cache is often stale too.)

> search engines are currently indexing posts multiple times

Do you mean they're indexing URLs like https://mamot.fr/@EU_Commission@social.network.europa.eu/108209466785071868 ? See https://github.com/mastodon/mastodon/issues/22620#issuecomment-1363670888 on a possible approach.

**Comment by unbelauscht** [comment]
I think I understand what you mean, but it would be a cleaner way providing this canonical link rel.

**Comment by ClearlyClaire** [comment]
As pointed out in [my review](https://github.com/mastodon/mastodon/pull/25715#pullrequestreview-1514056327) of the PR implementing this, I am not sure this will actually make a difference.

Indeed, my understanding is that for navigation, the Google indexer will always start with an HTTP request, so when visiting https://mamot.fr/ and stumbing on https://mamot.fr/@EU_Commission@social.network.europa.eu/110655771759688733, the crawler would perform an HTTP request for https://mamot.fr/@EU_Commission@social.network.europa.eu/110655771759688733, which when logged out does a HTTP 302 redirect to https://social.network.europa.eu/@EU_Commission/110655767528190517, meaning the page in which we are adding `link rel="canonical"` tags was never indexed in the first place.

I think that any duplication occurring in search indexes is due to replies and parents being part of the page, which I'm not sure there is a solution for.
