### ISSUE TITLE
Scaling issues with the Sign up button in other languages

### ISSUE THREAD

**Issue by d4f5409d** [mastodon/mastodon#23026]
### Steps to reproduce the problem

1.Go to any Mastodon instance with Hungarian language turned on
2. See the problem

### Expected behaviour

The titlebar (where Mastodon logo, Login and Signup is located) should be scrollable horizontally.

### Actual behaviour

The sign up button goes out of the interface, because the string is too big (but the term is correct and should be used no matter what, we can't make it any shorter) for a mobile phone.

### Detailed description

We should be able to scroll horizontally trough the titlebar if it detects the mobile screen is small enough so we could see the button if we wanted to as expected.

### Specifications

Mastodon v4.0.2

![IMG_20230109_232210](https://user-images.githubusercontent.com/76624594/211421601-343daeb0-e7f1-46bf-9159-343a983b8f94.jpg)

**Comment by velw** [comment]
There's an issue that's either the same as this or very similar for the Follow/Following button in Japanese on mobile web. The text either reads "フォロー" ("Follow") or "フォロー解除" (literally "Follow remove", for unfollow) but because the first part of it is the same for both options and fills the whole button, it's impossible to tell whether or not you are already following.

**Comment by d4f5409d** [comment]
Fixed
