### ISSUE TITLE
accounts I dont follow are on my home tab

### ISSUE THREAD

**Issue by lorenlepton** [mastodon/mastodon#23149]
### Steps to reproduce the problem

1. simply using mastodon

### Expected behaviour

to not have people I dont follow on my home tab

### Actual behaviour

having people I dont follow on my home tab

### Detailed description

simply put. I have had many & many users I dont follow nor am fussed to follow be on my home tab when scrolling to check on friends I do follow

im not 100% sure if this is a feature, but if it is, its an annoying one. it is a bug in my eyes.
im not sure if this is something noticed. again im not sure if this is a bug but even asking people about it, they dont know either & find it an incredibly annoying thing if it is a feature

### Specifications

latest mastodon as of 18/01/23

macOS 11.7.1
safari 16.2

**Comment by lorenlepton** [comment]
obviously freely close this if this is a feature. but could we at least have a choice, because I cant find a way to turn this rubbish off

**Comment by connorshea** [comment]
You may have followed a hashtag, and any posts using that hashtag will now show up in your home feed. That might be why?

**Comment by lorenlepton** [comment]
I wish that was the case. but there are none I follow apart from 1, which is for my band ERUERS. thats the only one I have followed & even the hashtags I use dont link with the accounts that have been posting

I wonder what it is, because this has been happening over the past 3/4month? even really random accounts I wouldnt follow

**Comment by Wild1145** [comment]
Are they boosts by any chance? The only thing you should see in your home feed are either boosts from accounts you do follow, accounts you do follow or any posts that contain a hashtag you're following. If you're still seeing things that aren't any of the above it sounds like it might be an issue...

**Comment by lorenlepton** [comment]
nope not boosts

**Comment by lorenlepton** [comment]
here are just 2 accounts that are on top of each other I have no idea who they are or boosted

<img width="353" alt="Screenshot 2023-01-18 at 15 54 58" src="https://user-images.githubusercontent.com/80318581/213242583-912bb9dc-1a61-40df-a74d-6c3c3bdad2bc.png">

**Comment by Wild1145** [comment]
Given the overlap in hashtags with those, it might be worth double checking you haven't accidentally followed one of the hashtags?

**Comment by lorenlepton** [comment]
its not. already checked & as I said before I only follow 1

**Comment by jdebp** [comment]
The next thing to check is whether your account is listed at https://friendo.space/@kellyn/followers or at https://home.social/@dustcircle/followers .  And in addition to that go to your home instance's `/getting-started` page on the WWW and copy _the exact version_ of Mastodon given there to here, since "latest mastodon as of 18/01/23" does not inform developers that your sysop has in fact kept up to date.

**Comment by ClearlyClaire** [comment]
Hi! Your Home timeline should only contain posts from people you follow, or using hashtags you follow.

Unfortunately, the interface is currently quite lacking in terms of followed hashtags, as it will not show you why the post is in your timeline, and the latest released version does not let you list followed hashtags either (this will come in the next version that is just around the corner, though!)

> The next thing to check is whether your account is listed at https://friendo.space/@kellyn/followers or at https://home.social/@dustcircle/followers .

That is not necessary, even if these servers mistakenly thought you were following them, your own server would not show their posts in your Home timeline because of this.

**Comment by M0IGA** [comment]
I think the following tag button is unclear to understand for a lot of people.
Followed tags definitely should be shown in a dedicated column, or right menu bookmark in simple view.

**Comment by trwnh** [comment]
> Followed tags definitely should be shown ONLY in a dedicated column, or a right menu bookmark in simple view.

that wouldn't be "followed tags", that would be "favorite tags" or "tracked tags" or something like that

i don't think that's necessarily a bad idea, but it would be a different feature

**Comment by jimrhiz** [comment]
I agree with @trwnh, except it already _is_ an existing different feature. Followed tags are designed and intended to appear in the home timeline, and that is very useful. If anyone wants a dedicated column in the webUI, they can  just open the hashtag, then pin.

**Comment by M0IGA** [comment]
> 
I understand your point of view, but look. If I follow 100 people, I can expect toots from 100 people, but if I follow #tag, I could expect dozens of toots from all federated instances. In case, when I follow 10 #tags, my HomeTL is flooded by #tagged toots.

**Comment by jimrhiz** [comment]
@M0IGA, I'm not sure, but are you saying you don't want your home timeline to be flooded? Then you can just not follow so many hashtags. It's not compulsory to follow them :-) Other people prefer to follow a lot of hashtags and skim through their timeline, making it a valuable capability. As I said, you have the option to use pinned columns instead.

You're partly right that followed hashtags are unclear, in so far as functions to support them are missing at present. For example, you can't yet see a list of them, or export them as CSV. @lorenlepton notes they are only following one hashtag, but it's not easy to confirm that now. Some of this may improve in future releases.

**Comment by ClearlyClaire** [comment]
Those posts most probably contain “hidden”/out-of-band hashtags, and we are working on some UI changes to display such tags.

**Comment by VAggrippino** [comment]
> Those posts most probably contain “hidden”/out-of-band hashtags, and we are working on some UI changes to display such tags.

I did some searching to understand better. That's an interesting _feature_. I read in #26260 that the reasoning was because hashtags "look spammy".

I'd offer a different perspective: People abuse hashtags on Mastodon just like they did at Twitter... Social, political, commercial, pornographic, etc... The difference is that now we can't tell which hashtag they're abusing.

I know my opinion carries no weight. And it shouldn't! I'm nobody, but I am a little disappointed that nobody saw the potential for abuse here.

**Comment by ClearlyClaire** [comment]
To be clear, Mastodon does not currently allow writing out-of-band hashtags, nor does it display them, but other federated services make use of out-of-band tags (e.g. Peertube or Plume), which can be confusing, since Mastodon is not rendering them. #26260 adds both displaying out-of-band hashtags and converting the last line of outbound messages to out-of-band hashtags if they consist solely of hashtags.

**Comment by renchap** [comment]
Out-of-band hashtags are now displayed (in 4.2.0).

Showing the reason why you see a status is tracked in #26079
