### ISSUE TITLE
tootctl accounts prune: raises foreign key constraint violation

### ISSUE THREAD

**Issue by waffle2k** [mastodon/mastodon#23188]
### Steps to reproduce the problem

After upgrading to 4.1.0rc1, I attempted to use the `tootctl accounts prune` command, which ran, but exited with a database failure.

```
mastodon@840a14ea29c9:~$ bin/tootctl accounts prune
Error processing 109728563191343203: PG::ForeignKeyViolation: ERROR:  insert or update on table "account_stats" violates foreign key constraint "fk_rails_215bb31ff1"
DETAIL:  Key (account_id)=(109728563191343203) is not present in table "accounts".

64932/64933 |================================================================================================================  |  ETA: ??:??:??
OK, pruned 48550 accounts
```

### Expected behaviour

Application exits cleanly

### Actual behaviour

Application exited with a SQL exception

### Detailed description

After upgrading to v4.1.0rc1 (and upgrading the database), I attempted to run `tootctl accounts prune` which seemed to work, but gave an error at the end when trying to update `account_stats` table:

```
mastodon@840a14ea29c9:~$ bin/tootctl accounts prune
Error processing 109728563191343203: PG::ForeignKeyViolation: ERROR:  insert or update on table "account_stats" violates foreign key constraint "fk_rails_215bb31ff1"
DETAIL:  Key (account_id)=(109728563191343203) is not present in table "accounts".

64932/64933 |================================================================================================================  |  ETA: ??:??:??
OK, pruned 48550 accounts
```

### Specifications

Mastodon v4.1.0rc1

**Comment by ClearlyClaire** [comment]
I could not reproduce it on my test data, but that is not very surprising considering its limited size.

If you run the command again, does it error out again?

I think this may be a pretty rare race condition where one account's deletion somehow triggers an `account_stats` update for another account that got destroyed in the meantime, but I'm confused as to what would have caused an `account_stats` update, since that would be typically be following/follower/status changes but accounts with local followee or followers, or any known status, are exempt from `tootctl accounts purge` in the first place…

**Comment by waffle2k** [comment]
Thanks for checking in on this @ClearlyClaire, and after testing again, I wasn't able to reproduce the error either.

```
mastodon@0c0aca98d22b:~$ bin/tootctl accounts prune
23709/23731 |================================================================================================================  |  ETA: ??:??:??
OK, pruned 7291 accounts
mastodon@0c0aca98d22b:~$
```
