### ISSUE TITLE
Search Modernization while preserving #hashtag paradigm

### ISSUE THREAD

**Issue by supernovae** [mastodon/mastodon#23323]
### Pitch

Search is lacking in many ways and is inconsistent across web and mobile apps.   If an instance has elastic search, search should be able to handle more complexity and do so with user experience in mind as to what they're trying to achieve by searching - discovery - either finding exactly what they're looking for or being guided to discover what they don't know. 

**Boolean Search**

For example, with elastic search enabled - Boolean searches should be possible to search for "#hiking and #pnw" to find posts tagged with #hiking and #pnw.   The search experience should also assume that any word is a hashtag and search for them.  For example, searching for "#hiking #pnw" does a full text search for those words (it appears it is an any, not an AND) but it won't show the click through hashtags of #hking or #pnw because it considers it a full-text-search.  (screenshots below)

existing issue for bool:  https://github.com/mastodon/mastodon/issues/21778

**Synonyms** (related items)

In addition to Boolean search and treating hashtags as full text as well as hashtag search, we should extend the search output to show what most people presume search is.  We should offer "related searches" such as by synonym.  So, if someone searches for #hike the first positions should be exact matched, but under a topic such as "Related searches" we should show #hiker #hiking #trails - _**This will help guide people to discovery of related keywords they may not be thinking of**_.  This would allow search without robots or algorithms limiting this or hiding it behind complexity that isn't needed.  Guide people to discovery.

**Tokenization of query**

Tokenization of query parsing would be nice so if people ask questions, the query could be tokenized to show results such as "where to go hiking" could show results for #hiking and if they said "where to go hiking in California" it could show hashtags for #hiking #california. This is more advanced, but shows how we could extend search to do what people search for - without having to violate #hashtags 

**Existing Problems with Hashtag search:**

Why doesn't it show full text search by default?

![image](https://user-images.githubusercontent.com/1461719/215541376-8c02303c-1f75-4123-a38d-90875cfa1048.png)

Remove the hashtag and search and now we're seeing what i'd expect if i search.

![image](https://user-images.githubusercontent.com/1461719/215541517-e497d093-0342-4b84-88e8-40c15eea38dd.png)

Another account, where you see I have full text search with a saved post.

![image](https://user-images.githubusercontent.com/1461719/215541675-e00d5385-697d-412f-9649-204640afd6ed.png)

### Motivation

The idea is to provide what people want from search, without changing the behavior to full text search being based on hashtags but provide that "human friendly search" as the default position.

All a robot does for full text search is assume tokenization based on its algorithm/dictionary/stemming/and people massaging it. I believe we can stick with hashtags, use them as the means to make things discoverable (opt in) and make keyword search a first rate citizen while offering assistance/rails in front to help with discoverability.

**Comment by supernovae** [comment]
Perhaps even posts tagged with a hashtag and in public, should be considered searchable and our idea should be that a public post with a hashtag is consent to be searched.

Right now, it's discoverable via the hashtag when so much more could be achieved if it was shown in full text search via the hashtag.

**Comment by supernovae** [comment]
If a link is approved or a publisher is approved and those links are trending, they should be searchable as well. Searching within # explore should allow people to discover trending hashtags, trending news and trending accounts to follow.

Extending search to allow people to opt in their profile page to be searchable via #hashtags would be highly welcomed for user discovery as well

**Comment by supernovae** [comment]
I haven't finished going through the code yet, but this line seems problematic.  

https://github.com/mastodon/mastodon/blob/2b00ccdbd555f9391aa87778f8b41eedcb7f8a04/app/javascript/mastodon/features/compose/components/search_results.js#L101

When i search for hashtag, the best thing that could happen is

Show people with #hashtag in their bio (not implemented)
Show hashtags that contain the hashtag (current process)
Show posts with hashtag


The mobile app is broken in similar way where the pivot for searching for hashtag doesn't show posts.  The bug is linked above.

**Comment by sami-huvilanet** [comment]
" a public post with a hashtag is consent to be searched"

A reasonable suggestion, albeit if such an extended search would be implemented, posts sent before **the implementation date** should be left out of its index, even if they had hashtags. Otherwise users should informed to remove their more delicate posts, which would be too much to ask.

**Comment by DataDrivenMD** [comment]
Some version of this warning has been in Mastodon UI since January 2, 2018: "This post won't be listed under any hashtag as it is not public. Only public posts can be searched by hashtag."

Here's the earliest commit I found: https://github.com/mastodon/mastodon/commit/b6af88192ff48372c5f6ed1321f21d99aaffcd3f

<img width="279" alt="Screenshot 2023-01-30 at 3 51 04 PM" src="https://user-images.githubusercontent.com/116459476/215623042-dabb6134-b0ef-45e6-bb02-5365fd84dff1.png">

I think it's safe to say that from the earliest days of Mastodon "public post with a hashtag is consent to be searched" was not only implied, but explicitly stated.

**Comment by DataDrivenMD** [comment]
Some version of this warning has been in Mastodon UI since January 2, 2018: "This post won't be listed under any hashtag as it is not public. Only public posts can be searched by hashtag."

Here's the earliest commit I found: https://github.com/mastodon/mastodon/commit/b6af88192ff48372c5f6ed1321f21d99aaffcd3f

<img width="279" alt="Screenshot 2023-01-30 at 3 51 04 PM" src="https://user-images.githubusercontent.com/116459476/215623042-dabb6134-b0ef-45e6-bb02-5365fd84dff1.png">

I think it's safe to say that from the earliest days of Mastodon "public post with a hashtag is consent to be searched" was not only implied, but explicitly stated.
