### ISSUE TITLE
Add header to notification mails to prevent out-of-office replies

### ISSUE THREAD

**Issue by McPringle** [mastodon/mastodon#23592]
### Pitch

Please add the header `Precedence: bulk` to each outgoing mail. This header prevents most mail servers from sending vacation and bounce messages.

### Motivation

As an admin of a mastodon instance each day I get some out-of-office replies. Most of these mails can be prevented very easily by adding a header to outgoing notification mails.

**Comment by ClearlyClaire** [comment]
Looking around, I see additional suggestions: `X-Auto-Response-Suppress: All`, `Auto-Submitted: auto-generated`.

Looking at mails I receive:
- GitHub uses both `X-Auto-Response-Suppress: All` and `Precedence: list`
- gitlab and discourse use `Auto-Submitted: auto-generated` and `X-Auto-Response-Suppress: All` but not `Precedence`

**Comment by Keisial** [comment]
The standards way would be `Auto-Submitted: auto-generated` (rfc3834)

`X-Auto-Response-Suppress: All` is an Exchange extension, https://learn.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxcmail/ced68690-498a-4567-9d14-5c01f974d8b1

As for `Precedence`, rfc3834 states:
> Because Precedence is not a standard
      header field, and its use and interpretation vary widely in the
      wild, no particular responder behavior in the presence of
      Precedence is recommended by this specification

and rfc2076 tags it as "Non-standard, controversial, discouraged.". From its different values "junk", "list", "bulk". I would use `Precedence. bulk` rather than list.
