### ISSUE TITLE
Normalize Unicode “Fonts” (mathematical bold and so on)

### ISSUE THREAD

**Issue by allo-** [mastodon/mastodon#23641]
### Pitch

Because Mastodon does not support message formatting, many people use "unicode fonts" for formatting, such as 𝐭𝐡𝐢𝐬. Some screen readers have trouble reading these.
Although normalising the letters should probably be a screenreader feature, it must be acknowledged that not all screenreaders do it.

On the other hand, many software packages can normalise most of these fonts. Try searching for them in popular search engines and you will get results for "this" and not just "𝐭𝐡𝐢𝐬". Browsers normalise it for phishing protection, search engines for users not wanting to think about it, and chat clients to prevent identity theft.

There I can imagine two features:
1) Mastodon could add the normalised text in a way that screen readers only see the normalised text and other users see the original text. This feature could be enabled by default for all toots.
2) An account setting to replace such letters with standard ASCII letters. Take care not to replace common accents or umlauts such as äöü, which are used in some languages, but for example mathematical characters can be replaced safely. There should be a profile setting, as some users may use maths fonts to talk about maths, and they should be able to turn off the conversion.

### Motivation

Such Unicode fonts pose a challenge to screen readers that could be solved technically rather than having to educate users not to use them.

Normal users use them to circumvent an intentional limitation of Mastodon, so they have a motivation to use them, especially if there are no plans to remove the limitation (e.g. by allowing markdown formatting). The problem of translating such "fonts" is already solved in many programs, and it won't be too complicated to solve it in Mastodon as well, so users can continue to do what they already do without causing accessibility problems.

**Comment by BazThomas** [comment]
(Github newbie, please don't shoot me if I'm doing this wrong) This post appeared uninvited in my tl, not boosted by someone and I don't follow the account. The unicode at the end causes the web interface to think the post contains the tag #lettering, which I DO follow:
https://mastodon.art/@seebrueckeffm@venera.social/109950765251012148
I guess this comes under this issue?
Many thanks
Baz

**Comment by allo-** [comment]
That's indeed interesting, because it shows that Mastodon internally already normalizes hashtags. I would guess that it tries to normalize Hashtags with accents and as a side effect the function also normalizes math fonts and so on.
The bold text at the end of the post also uses unicode bold letters and no formatting. Try to copy them to the URL bar and you'll see that they are still bold.

**Comment by BazThomas** [comment]
(I'm an ex dev, IIS back end stuff) I looked at the html for this post and a well formatted one and the end of the div and some other stuff is truncated here so the server is clearly choking on something in the unicode. No idea how that makes the leap into hashtags though. I'm well past my sell by coding date so I'm not going to look at the source on this one. Smarter people than me can pick over the entrails :) Thanks for the response.

**Comment by onpon4** [comment]
You can't solve misusing Unicode in a technical way like this, even ignoring the fact that lots of the time people misuse characters that aren't in any sense Latin letters (like Russian), special Unicode variants of Latin characters (like the mathematical symbols) exist for a reason and just en masse converting all of them with the assumption that they're being misused is not proper and would break their *intended* uses. It would also validate the incorrect usage, making the problem worse.

Things like searches and hashtags doing this kind of filtering is different because it's not about presenting something to users, it's about matching your queries. For that purpose, normalizing everything so that the search engine matches any variant of a character (while still presenting each character the same as it was written) makes a lot of sense. To wit: counting \#SoNaive and \#SoNaïve as the same for the purpose of hashtag searching is a reasonable thing to do, but implicitly converting \#SoNaïve to \#SoNaive in its display would be a mistake (not so important in this example but could matter when you get multiple languages involved).

The only way this sort of technical solution wouldn't be an absolutely terrible idea would be if Mastodon made the decision that non-ASCII alphanumerics aren't allowed and will be automatically converted to ASCII *at posting time*, because that would make it clear that those parts of Unicode aren't supported and avoid validating those who attempt misusing Unicode to fake bold and italics. But really, I think attempting a technical fix to what is ultimately a social problem is misguided.

🕷️

**Comment by allo-** [comment]
My suggestion was about providing an optional filter, best on the receiving end, and a way to add a hidden screenreader-visible representation, not about forcing ASCII on people who cannot express themselves in ASCII.
I made the suggestion because I see it the other way around. It's a problem that you can't solve socially (of course you can annoy people by asking them to stop, but that's just you making yourself unpopular), but that has a reasonable technical solution for 99% of these posts. If there *is* a technical solution to such problems, you can provide it, and avoid the unnecessary social conflicts.
But I guess if Eugen closes it, Mastodon has no chance of getting it.

**Comment by BazThomas** [comment]
I can see both of those arguments tbh, but the issue remains that a bit of unicode in text, _for whatever reason_, made the system believe that a post featured a plain text hashtag, which it didn't. That's a bug. It seems fair to allow legit uses for unicode, but can the system decide which uses are legit and which are 'artistic'? I guess not, but letting unicode leak out into the realms of hashtags seems to deserve intervention. imho. Thanks for the responses.

**Comment by allo-** [comment]
For the normalization of Hashtags I wonder how other Fediverse Softwares deal with it. Formatting and converting content is a matter of the sender and reader, but Hashtags are something every participating server has to deal with. I've especially seen clients which, for example, deal differently with hashtags with a "-" in it (causing a search for the wrong tag) and I think some Fediverse-Softwares allow the Hashtag text to be different from the actual tag, not only for non-ASCII characters. But I guess that's something for a new issue.

**Comment by onpon4** [comment]
> I made the suggestion because I see it the other way around. It's a problem that you can't solve socially (of course you can annoy people by asking them to stop, but that's just you making yourself unpopular), but that has a reasonable technical solution for 99% of these posts. If there _is_ a technical solution to such problems, you can provide it, and avoid the unnecessary social conflicts.

You're kind of ignoring the point I raised, that your proposed technical solution would *encourage* the misuse by making it work in this non-standard way and break usages of the Unicode characters in their intended way.

Can't solve socially? The social solution is to change society so that people actually *care* about accessibility and conscientiously think about how what they do affects accessibility. The fact that ableism is widespread (and that people treat it as "annoyance" to simply be told that they're writing in a way that is inaccessible, which I think is succinctly described by the word "fragility") does not mean that it's impossible to solve. It's also at the root of the problem, you can't cure a disease (ableism) by only treating the symptoms (people breaking accessibility for aesthetics). Attempting to do so would just sweep the problem under the rug to be dealt with by someone else later, while (as I pointed out) creating new problems because you're breaking Unicode.

🕷️

**Comment by allo-** [comment]
> You're kind of ignoring the point I raised, that your proposed technical solution would encourage the misuse by making it work in this non-standard way and break usages of the Unicode characters in their intended way.

I am just acknowledging that it is already being used that way. Not only on Mastodon, but on many other sites as well. The way to mitigate this would be to allow at least basic formatting, but I think Mastodon may not be the right platform for that.

> Can't solve socially? The social solution is to change society so that people actually care about accessibility and conscientiously think about how what they do affects accessibility. 

That's the point. You think you can educate the whole world about these issues. I find that you're not going to change the whole world, but that there are technical ways to help about 95% of the time. That's a lot that can be achieved in a fairly simple way if there's a usable normalization library.

> The fact that ableism is widespread (...)

You're raising a political issue, which is off-topic here. The point is that you can't and won't educate the whole world, but you can improve the experience for disabled users, even if other people don't think about them.

You have to change the way you look at the problem from "I demand you change" to "I wonder why you're doing this" to understand users and improve UX. Then you find the answer, "Mastodon lacks formatting options, but allows formatted text to be posted on the web using fancy text generators. Now we understand why people do that.

Next, we need to find a solution. Of course, you can post demanding replies under every post that uses such a generator, but then you're not acknowledging that the person had a motivation to use the generator, and that there is a problem they're solving. You have to look from the user's perspective to understand the problem.

Since it is not achievable to change the whole world (even if it is a great goal) to understand the problem, one should look into tech that can reduce the problem. The technology for this would be a "normalize text" button or even a profile setting.

> Attempting to do so would just sweep the problem under the rug to be dealt with by someone else later, while (as I pointed out) creating new problems because you're breaking Unicode.

This has already been addressed in the original issue. The normalization should be done at the user's request with different levels of automation, and from a normalized view there should be an option to show the original view and vice versa. The details could be worked out if there is interest in implementing the feature.

**Comment by onpon4** [comment]
> You're raising a political issue [ableism], which is off-topic here.

No? Ableism has everything to do with people ignoring accessibility for aesthetics.

> I find that you're not going to change the whole world

> The point is that you can't and won't educate the whole world

> it is not achievable to change the whole world (even if it is a great goal)

A society that ignores accessibility is not a given, maybe stop being so defeatist?

Or is this what you're saying because you're ableist and refuse to change?

Regardless, this idea that social change is *impossible* is wrong on so many levels, humans have been caring for disabled humans since before we even diverged as a species. Ableism is a very modern concept and it's not etched into stone.

> Then you find the answer, "Mastodon lacks formatting options, but allows formatted text to be posted on the web using fancy text generators.

That "but" is nonsense, it's misframing Unicode support as support for "generators" that misuse Unicode.

> but then you're not acknowledging that the person had a motivation to use the generator, and that there is a problem they're solving. You have to look from the user's perspective to understand the problem.

Those "generators" are not solving an actual *problem* any more than leetspeak is. It's literally the same sort of thing, misusing characters for "style".

For bold an italics, the proper way to support that is something like Markdown.

But for people insisting on making their names "look fancy" by using whatever they find that looks a little bit like a Latin letter? They don't need to do that, they *choose* to do that despite not needing to. I've been writing text without things like Markdown for literal decades without ever using these generators, it's really not that hard to do with standard characters. If you want to say "apple", say "apple" and not "@℘🅿️|3".

> The screen readers should implement their text parsing in a more intelligent way.

The reason screen readers don't implement the "solution" you suggest is, as I mentioned, it would break *intended* uses of Unicode. The characters you're talking about are for where visual distinction is important to meaning in a math context, so the proper thing to do with those is to not only read them as letters (because that's how math uses letters), but *also* provide a way for screen reader users to be aware of the visual distinction. Unless you're proposing some complicated language-processing AI that can distinguish proper uses from improper uses, which is asking a bit much of a simple accessibility tool, screen readers "normalizing" text would break it.

🕷️

**Comment by allo-** [comment]
Most of your points are already addressed in previous posts. I also would ask you to stop using ad hominems. Otherwise I will stop answering you.

The point is, if there is a demand for a feature and it is not provided, users will find a way to get the feature and may break things in strange ways to achieve their goal. UX means addressing how to help the users and not telling them that they are doing it wrong and should stop doing it.

> For bold an italics, the proper way to support that is something like Markdown.

Indeed, this would be a solution. Some Fediverse softwares already do it, I think there are even Mastodon forks that support it. As far as I know it is a non-goal for mainline Mastodon and one still has to deal with incoming posts that are not Markdown but using Unicode bold fonts.

> That "but" is nonsense, it's misframing Unicode support as support for "generators" that misuse Unicode.

You and me, as technical people, call it misuse. But for users, it is a solution to their use-case. UX improvement means addressing their use-case. If that's not a goal, we need to deal with the resulting posts, which use the workaround the users found. That's what the issue is about.

> But for people insisting on making their names "look fancy" by using whatever they find that looks a little bit like a Latin letter? They don't need to do that, they choose to do that despite not needing to.

People want to do this. You're suggesting to forbid the use-case, I am suggesting to solve the sideffects caused by the use-case.

A bit off-topic from here:

> The reason screen readers don't implement the "solution" you suggest is, as I mentioned, it would break intended uses of Unicode.

Sorry, but screen readers do weird things. Do you think anyone reading an equation with a screen reader would like to hear "mathematical symbol fracture T mathematical symbol fracture O mathematical symbol fracture O mathematical symbol fracture T"?  
A good implementation would do something like telling the user that the next variable names are in a fracture font and then read the letters. Listen to a math presentation and you will see, that in most equations the font is not mentioned at all when reading an equation. Sometimes it is neccessary when there are both fracture and non-fracture uses of a letter, but as said one would not want a 3 second description of the font in front of each single letter, but current screen readers seem to do it.  
One would also not like to hear 50 times "smiling emoji" but rather something like "Fifty smiling emojis"

**Comment by onpon4** [comment]
> if there is a demand for a feature and it is not provided, users will find a way to get the feature and may break things in strange ways to achieve their goal.

…Because they care more about an unimportant kind of markup that they never even handwrite anyway than they do accessibility.

If someone *does* care about accessibility, though (hi!) then they won't go out of their way to break accessibility for these trivial reasons. It's really not hard to deal with the limitation of plain text. We've done it on paper for centuries if not millennia. I've handwritten italic letters but I've never seen anyone else do it and I can see why, it's inordinately difficult to do and just not ever actually necessary to get a point across.

> UX improvement means addressing their use-case. If that's not a goal, we need to deal with the resulting posts, which use the workaround the users found. That's what the issue is about.

I know, and I'm telling you the "workaround" would actually *break* things and not solve the problem (in fact it would just encourage the practice further, normalizing it).

🕷️

**Comment by allo-** [comment]
> …Because they care more about an unimportant kind of markup that they never even handwrite anyway than they do accessibility.

Indeed. I am not a fan of handwriting "Unicode fonts" and so on. But I know that there are plenty of people who are. I also know that I cannot and do not have the time to educate all users about why this is bad, and that many users will not care.

The users have a use case and they have a workaround to achieve it, and that use case is more important than accessibility to the users who still use such fonts. You can try to educate users, and you can continue to do so even if there are technical solutions to alleviate the problems of users who still use such fonts, but you can't stop everyone from doing so without actually banning such posts or very strict moderation, both of which are undesirable because they make the site unattractive.

> I know, and I'm telling you the "workaround" would actually break things and not solve the problem (in fact it would just encourage the practice further, normalizing it).

I'm not saying it will solve every case. But consider, for example, an "ASCII version" button that would display the converted text. Even if it only worked for 50% of those posts, it would still allow blind people to read 50% more of those posts. So it would definitely be an improvement over the status quo.

Having said that: I don't think anything is going to happen in this issue, so it's kind of pointless to keep discussing it and trying to figure out the best way to do it when it's already been closed as "not planned". So I would now say goodbye and have a nice day!
