### ISSUE TITLE
Why is _mastodon_session id changing on every request and set in first place?

### ISSUE THREAD

**Issue by AInteriorB** [mastodon/mastodon#23843]
### Steps to reproduce the problem

Without login:
1. make a request (Set-Cookie: _mastodon_session=XXX is in response)
2. make another request (Cookie: _mastodon_session=XXX is in request, another Set-Cookie: _mastodon_session=YYY is in response)
...

### Expected behaviour

_mastodon_session stays the same

### Actual behaviour

_mastodon_session is changing

### Detailed description

I observed that the _mastodon_session id never stays the same as a guest user. If you are logged in, then the _mastodon_session id stays on ajax calls but not if you fully reload the page. Is this behavior intended?

I'm asking because I found some proxy caching configurations in the provided nginx.conf
```
  location @proxy {
    ...
    proxy_cache CACHE;
    proxy_cache_valid 200 7d;
```

Is this only intended for media files? Without configuring a proper proxy_cache_key in combination with changing _mastodon_session ids, no data request can be served by nginx as a front end cache.

Another question is why we need a _mastodon_session id as a guest user? Without an id, alle requests for guests could be easily cached.

Thanks for clarification

### Specifications

Mastodon v4.1.0

**Comment by ClearlyClaire** [comment]
`_mastodon_session` is not a session ID but the entire contents of the session, encrypted with a key held secret by the server.

Their main uses are:
1. storing a one-use token used for preventing Cross-Site Request Forgery attacks
2. storing the last-visited page to return users to after log-in
3. keeping track of the state of multi-step log-in (2FA, external auth…)
4. keeping track of which user is logged in, together with a session ID so that the session can be invalidated

For logged out users, 1. and 2. are always set, which causes the session cookie to be set and change on every page. Admittedly, we could do without setting 1. in most cases for logged-out users as that would only be relevant for them when displaying a form (so typically the sing-in and sign-up forms), but that would require special care to correctly invalidate the tokens and make sure they are set wherever they need to be. 2. could possibly be set from the `Referrer` header on specific pages, but this quickly becomes tricky and error-prone.
