### ISSUE TITLE
Scheduler::IndexingScheduler are being lunch even if the previous one hasn’t finished

### ISSUE THREAD

**Issue by alarig** [mastodon/mastodon#23985]
### Steps to reproduce the problem

1. Upgrade to v4.1.0
2. Scheduler::IndexingScheduler piles up
3. mastodon-sidekiq-scheduler.service is OOM-killed

Hello, since v4.1.0 the process holding the scheduler queue is OOM-killed every hour or so and the toots aren’t indexed anymore into ES. My ES cluster hasn’t been modified between releases. But as new Scheduler::IndexingScheduler are there every 5 minutes, it pressures it instead of waiting for the previous one to finish.

I emptied my ES data (`curl -s -X DELETE 'http://10.0.2.3:9200/*'`) en re-deployed the indexation, but it doesn’t change the behaviour.

### Expected behaviour

Check for other Scheduler::IndexingScheduler

### Actual behaviour

Scheduler::IndexingScheduler piling up

### Detailed description

![Screenshot 2023-03-06 at 15-27-53 Sidekiq](https://user-images.githubusercontent.com/13120362/223140859-db17fa74-e8dc-44b1-ad87-4b2fff5ecd92.png)
![Screenshot 2023-03-06 at 15-37-37 memory (Munin swordarmor fr hostux swordarmor fr memory)](https://user-images.githubusercontent.com/13120362/223141361-3aacc01e-b649-4c07-bc0e-44e46ee0be7b.png)

### Specifications

Mastodon | 4.1.0
Ruby | 3.0.4p208
PostgreSQL | 14.5
Redis | 7.0.8

**Comment by fwaggle** [comment]
Hey @alarig - I ran into this today because I am very silly and did not have the scheduler queue running at all since whatever version that was put in place.

I don't speak Ruby at all, but it definitely sounds like a bug where it should not spawn another runner to do the same work, because they'll stack up and if you have memory limits, it'll OOM. But in the meantime there's a workaround that's worked for me and one other admin (YMMV, I take zero responsibility if this breaks your instance):

* In the sidekiq admin UI, stop the runner from doing anything.
* Stop the sidekiq process or container.
* In the sidekiq admin UI, go to "recurring tasks" and disable the one for IndexingScheduler
* Delete the "scheduler" queue in sidekiq. It'll get recreated, don't worry about it.
* Once all the sidekiq processes are dead, drop any hanging locks that are present (not sure if this is necessary or safe, but it's what I did to be sure nothing would get stuck).
* Start sidekiq process/container
* under "recurring tasks", enable, enqueue, and then disable the job for IndexingScheduler (it did not seem to enqueue unless it was enabled, for me, but YMMV).
* Check the "busy" tab and make sure it's running.
* Wait for it to complete (it may be some time, it was ~20 minutes on my single user instance!)
* Repeat the process (previous three steps), it should finish almost instantly the second time around but I guess if you have a busy instance it may not, keep repeating until it's sub-five minutes anyway.
* Re-enable the schedule and let it do it's thing.

I have also found it useful to have a separate sidekiq container for scheduler, in case one of these jobs starts to back up it doesn't hold up all your ingress, pulls, pushes, etc.

**Comment by alarig** [comment]
Hello @fwaggle 
To work around this, I spawned another process with a concurrency of one, so no other task could be executed on it. Eventually the long-running task landed on it, so it ended without OOM. After that the other tasks went smoothly.

**Comment by renchap** [comment]
So if I understand correctly, the issue occurred because the initial indexing job took more than 5 minutes, as it probably needed to re-index everything, but then it works because it only index recent changes and takes < 5 minutes.

Is this what is heppening?

**Comment by fwaggle** [comment]
Yes, that's what it seems like to me. If it takes say, 20~30 minutes for the first run, duplicates will spawn, all apparently doing the same work, and it will either OOM sidekiq or just hog all the runner threads so nothing else happens. I don't know what the solution is, I'm guessing it should probably check if there's one already in place (maybe holding a lock or something) before starting another indexingscheduler run?
