### ISSUE TITLE
Blocked host 127.0.0.1

### ISSUE THREAD

**Issue by JulianDan** [mastodon/mastodon#24062]
### Steps to reproduce the problem

I am running mastodon using docker and configured nginx as a reverse proxy. However, if I set the environment variable **LOCAL_DOMAIN** to my domain name, I cannot access the site. If I set it to 127.0.0.1, I can access it, but the site name on the mastodon homepage will also be 127.0.0.1. I checked the logs and found that before changing the environment variable, there was an error of **[ActionDispatch::HostAuthorization::DefaultResponseApp] Blocked host: 127.0.0.1**

I am not very good at searching for existing issues. After trying my best to find similar problems, I still could not solve my own problem. I appreciate your patience and help.

### Expected behaviour

set LOCAL_DOMAIN as my domain and it works just like I set up a Mastodon instance few months ago

### Actual behaviour

set LOCAL_DOMAIN as my domain and if I access the website it comes up with a blank page

### Specifications

Mastodon 4.1.0

**Comment by ClearlyClaire** [comment]
First and foremost, `LOCAL_DOMAIN` should be set to your domain name, and never be changed ever.

Could you share your reverse-proxy configuration? It sounds like it may not set the `Host` variable appropriately.

**Comment by JulianDan** [comment]
So sorry with adding a new issue!
I found that it is the problem with the reverse proxy configuration and I solved this problem yesterday.

**Comment by airdogvan** [comment]
Well I have the same problem:
[ActionDispatch::HostAuthorization::DefaultResponseApp] Blocked host: mast.xxxx.site

My proxy IS configured correctly, I know because I have other containers running all being proxied by nginx and all working correctly.

mast.xxxx.site is the name I gave during the docker configuration (docker-compose run --rm web bundle exec rake mastodon:setup) and this error is displayed only when I try to connect to mast.xxxx.site from either internal or external IP.

my .env.production does not contain any reference to web address:

DB_HOST=db
DB_PORT=5432
DB_NAME=mastodon
DB_USER=mastodon
DB_PASS=xxxx
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=
SECRET_KEY_BASE=xxxx
OTP_SECRET=xxxx

mast.xxxx.site is available from a public IP (as said can connect for example to search.xxxx.site and many others without problems.

Something in the mastodon config tells it to reject the very address I gave it when asked at config time.

**Comment by airdogvan** [comment]
Thank you but after adding LOCAL_DOMAIN=mast.xxxx.site:

[ActionDispatch::HostAuthorization::DefaultResponseApp] Blocked host: mast.xxxx.site

**Comment by ClearlyClaire** [comment]
Have you restarted the services after setting `LOCAL_DOMAIN`?

> And I would like to emphasize again that this message only appears after a connection attempt from either local or external connection. Otherwise no error message, everything seems to be running smoothly.

What kind of connection is neither local nor external…?

**Comment by airdogvan** [comment]
Yes of course I restarted the service. 

And what I mean is:  the error message in the docker logs pops up when from my machine (external) I try in my browser https://mast.xxxx.site the error message comes up.  Similarly if from the localhost if I try wget https://mast.xxxx.site the error pops up.
If no connection attempts are made, no errors.

**Comment by airdogvan** [comment]
Before that I had installed on ly local machine and tried to connect, only to get the same error.  So I thought it was because this was not an SSL (https) connection.
But apparently that's not the case and of that I'm sure because as already mentioned I can connect to https://test.xxxx.site which runs another app as well as to test1.xxxx.site which runs yet another app, all being proxied by the same proxy as mast.xxxx.site.
On the local machine there was no proxy, so proxy definitively not the problem, nor is SSL.

There's another reason that comes from mastodon itself.  But as you can see from my docker-compose there's nothing that would explain this block.

**Comment by airdogvan** [comment]
I had a look at the code and notices 2 things.

1- Although docker-compose.yml is part of the provided code, no instructions or directives tell us how to run said docker-compose.

2- Mastodon seems to need nginx (see repo code) which needs to be configured and again, when using docker no instruction as to how to do this.

I looked further into the code and noticed that my running docker-compose app has a folder called "app" which contains, amongst others, a directory: "/opt/mastodon/app/javascript/mastodon/features/domain_blocks".  I don't know enough java to really comment on the code, it might only be formatting the message that's going to display the error.  If on the other hand it's implementing a block, this would be in my humble option bad programing. 

Did a search in the running docker-compose "web" app for "nginx" and came up with tons of mentions in the code and binaries for it.  But nothing in /etc...

Anyway it would be nice if clear instructions were provided on how to run this docker-compose since it's provided.  For instance are we supposed to mount something like "./ngnix.conf:/etc/nginx.conf"? 

If no instructions are given, please take out the file from the repo.

**Comment by airdogvan** [comment]
I've also tried the documented way, and this doesn't work for me either.
First failure was at yarn install --pure-lockfile for which I tried proposed solution (forgot but something about yarn set classic) which didn't solve the problem.
Went forward and failed again at systemctl reload nginx (nginx was not running and no matter how I tried could not get it to run). and of course certbot --nginx -d mast.xxxx.site did not succeed...

So I'm really stuck!!!

All this on a brand new, updated system running Ubuntu 22 LTS
