### ISSUE TITLE
Interactions with remote servers show inaccurate interaction counts

### ISSUE THREAD

**Issue by hypermug1** [mastodon/mastodon#24082]
### Steps to reproduce the problem

1. View a post with a high number of interactions (favorites, reblogs)
2. Click "view original posts"
3. Original post on original server has higher number of interactions
...

### Expected behaviour

The mastodon client should sync the counts with the original server

### Actual behaviour

server1 shows lower interactions than the original post on server2

### Detailed description

Post as seen from mastodon.online:
![image](https://user-images.githubusercontent.com/63418967/224570955-552ae4ef-dd6b-490f-b6e3-cf9f8d7d0f18.png)
Post as seen from original server:
![image](https://user-images.githubusercontent.com/63418967/224570979-c111bae6-521a-4744-ae92-7e9510808017.png)

### Specifications

Mastodon v4.1.0
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0

**Comment by trwnh** [comment]
from the later parts of #11339: https://github.com/mastodon/mastodon/issues/11339#issuecomment-1465098738

in short, syncing counts alone is not a good idea because servers can lie and there's no way to verify a count without having and verifying every Like/Announce activity yourself and then counting them yourself. put another way: the number you see is not "the count", it's "the count of what this server is aware of and can verify".

**Comment by hypermug1** [comment]
Alright. Its still a bit of an annoying "feature" though. Federation has its downsides i guess

**Comment by trwnh** [comment]
less of a "feature" and more of a trust issue, plus cache invalidation

**Comment by hypermug1** [comment]
Should i close this?

**Comment by hypermug1** [comment]
Alright im going to assume close. Thanks

**Comment by trwnh** [comment]
you can leave it open if you want! i'm just saying it's a hard problem
