### ISSUE TITLE
live/bin/tootctl search deploy --only tags complains about missing ruby

### ISSUE THREAD

**Issue by gunchleoc** [mastodon/mastodon#24712]
### Steps to reproduce the problem

1. Configure Mastodon to use ElasticSearch
2. `su - mastodon`
3. `crontab -e`
4. add line: `0 */1 * * * live/bin/tootctl search deploy --only tags`
5. Wait for cron to run the job
6. `mail`

E-mails from cron with subject line `live/bin/tootctl search deploy --only tags` are listed.

### Expected behaviour

The job runs through without error message

### Actual behaviour

The job produces an error message

### Detailed description

I am automating the elasticsearch index for hashtags via cron as a workaround for bug https://github.com/mastodon/mastodon/issues/20230

For each run, this produces the error e-mail below. The hashtag search is working without any problems though, so this is only an issue of e-mail spamming the admin.

When I run `mastodon@mastodon:~$ live/bin/tootctl search deploy --only tags` manually, there is no error,.

```
Subject: Cron <mastodon@mastodon> live/bin/tootctl search deploy --only tags
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/home/mastodon>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=mastodon>

/usr/bin/env: ‘ruby’: No such file or directory
```

### Specifications

Mastodon v4.1.2
Ruby 3.0.4p208
NodeJs v16.20.0

Running on Debian-based Linux.

**Comment by aaaaalbert** [comment]
That's probably because `cron` does not set up the Ruby environment needed by `tootctl`, unlike logging in and using an interactive shell for the same command.

#### Background

> When I run `mastodon@mastodon:~$ live/bin/tootctl search deploy --only tags` manually, there is no error,.

I guess you have these following two lines in the `.bashrc` of your `mastodon` user, as demanded by the [installation instructions](https://docs.joinmastodon.org/admin/install/#installing-ruby):

```bash
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
```

`rbenv` is used during installation to create a Ruby environment only for this user (see [lead paragraph of docs section](https://docs.joinmastodon.org/admin/install/#installing-ruby)). The `.bashrc` snippet enables the Ruby environment *on login*.

Since `cron` does not log in interactively, `.bashrc` is not run and the Ruby environment is not enabled.

-------

#### Potential fix

Exectue the `.bashrc` file in your crontab entry with the Bash-builtin command `source` before running `tootctl`:
```cron
0 */1 * * * source $HOME/.bashrc; live/bin/tootctl search deploy --only tags
```

-----------

#### Postscriptum
On my instance, `tootctl` complains about a missing `RAILS_ENV` environment variable and doesn't start unless I set it. That's easy though, just prepend it to the command line:
```bash
mastodon@:~ $ RAILS_ENV=production live/bin/tootctl
```

**Comment by gunchleoc** [comment]
Thanks!

The error has gone away. I have these lines in the `.bashrc` for the `mastodon` user:

```
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
export RAILS_ENV=production
```

**Comment by gunchleoc** [comment]
To unclutter having to execute the `.bashrc` on all my cronjobs, I did the following:

Create symlink to Ruby:

`ln -s /home/mastodon/.rbenv/shims/ruby /usr/bin/ruby`

Then edit the mastodon user's crontab:

`crontab -e`

And insert:

`RAILS_ENV=production`
