### ISSUE TITLE
Unpredictable Post Filtering Behavior Due to Blank Space Processing in Mastodon v4.1.2 / v4.1.1

### ISSUE THREAD

**Issue by cenobitz** [mastodon/mastodon#24960]
### Steps to reproduce the problem

1. Insert a word as  "word " (with a trailing blank space) in the post filter.
2. Observe that the filter does not process these entries correctly, and filtering behavior is inconsistent and unpredictable.

### Expected behaviour

The filter should correctly process words inserted as "word" or "word " (with a trailing blank space), providing consistent and predictable filtering results.

### Actual behaviour

The filter incorrectly processes blank spaces and does not function as expected, leading to unpredictable and inconsistent filtering results.

### Detailed description

In Mastodon v4.1.2, we are encountering a significant issue with the post filtering system that was previously operating as expected. This issue is specifically related to the handling of blank spaces in filter keywords.

In previous versions, if a keyword was inserted as "word " (with a trailing blank space), the filter would operate correctly, whether the match was set to be strict or partial. However, recent updates seem to have disrupted this functionality. Currently, the filter incorrectly processes blank spaces, leading to unpredictable and inconsistent filtering behavior.

Moreover, the filter does not seem to be working as expected in general, possibly as a result of this issue. This bug has significantly impacted the user experience and needs to be addressed promptly.

Please investigate this issue and provide a fix in the next update. Thank you for your prompt attention to this matter.

### Specifications

Mastodon	4.1.2 / 4.1.1
Ruby	3.0.4p208
PostgreSQL	15.2
Redis	6.0.16

**Comment by stevenjlm** [comment]
I'm new to contributing to this repo, so forgive me if I'm asking basic questions, but:
Can you or someone tell me what the expected behavior is on some specific examples?

I ran a small test locally with one user posting the following:
"toot 1"
"toot 2"
"here's a toot"
"There's a toot with a space"
"What's tootthis?"
"here's another toot " (note there was a space after hitting the post button but it was stripped)

After setting up a filter with "toot" (no space), only the post "What's tootthis?" get through to the other test user's feed.

If I switch the filter to "toot " (with space), then the three posts:
"here's another toot" "What's tootthis?" "here's a toot"
Make it to the timeline.

Where we expecting the filter to behave exactly the same for "toot" and "toot "?

**Comment by cenobitz** [comment]
Well the problem on my instance is that i had a lot of working filters with spaces on the end of the word and they just dont work on latest version. But i must admit that those filtered words were on the end of the toot. So there was no blank space. The issue is that someone fixed the function that propably earlier was clearing mistaken put blank spaces on the end of single word. 

I am closing this issue. I had to put this just for other people who have the same problem as me. That some filtering just stopped working recently
