### ISSUE TITLE
Button on images to display alt text

### ISSUE THREAD

**Issue by alxlg** [mastodon/mastodon#24970]
### Pitch

A button near to images to display their alt text in a popuo dialog or something like that.

### Motivation

Some Mastodon clients have this button and I find it useful to be able to check the alt text even if I able to see the image and I don't use a screen reader.

**Comment by mcclure** [comment]
[Current top of tree](https://github.com/mastodon/mastodon/pull/24782) has an "ALT" badge that could be used for this purpose, but it doesn't currently seem to be interactive.

**Comment by magicalskye** [comment]
yes, this, PLEASE. i have a mild visual disability that means i can only read text in specific formats (font size, type, contrast). this means that i depend on alt text to know the content of most text screenshots.

the hover window that pops up to show the alt text has a text size that’s appropriate maybe for ants but not for visually impaired people. there is no way to change it font size, type and contrast. while this is a browser-side issue, it’s one that has been around for decades and is clearly not going anywhere.

so those of us who need to access alt text visually are using a firefox add-on to display the alt text. the issue with this solution is that it’s only available on desktop and there’s nothing at all for the mobile web interface, and also the add-on is currently broken, so i’m back to just not being able to read text images at all when i’m on the computer.

it is quite frustrating that so many people put so much effort into making their pictures accessible, and then there is no way to actually access the accessibility data for a large chunk of those who need it.

so making it possible to show alt text in the browser (i know it needs to be said that this should have regular font size and honour contrast options, meaning in light mode it should also be light mode because otherwise i still won’t be able to read it) would make a huge difference.

thanks y’all

**Comment by cincodenada** [comment]
This would also be useful because even in desktop browsers where you can view alt-text by hovering over the image, not only is the text very small, but some browsers (e.g. chromium-based ones)cut off alt-text in the tooltip after 1024 characters and throw away the rest!

Mastodon allows for much longer alt-text than this, and for many images a good description will use it, but there is no way within the Mastodon UI for users of these browsers to see the full alt-text.

Mastodon should have first-class alt-text support in the UI, rather than punting to the browser which has many caveats and failures.

For anyone looking for a workaround, there are extensions that will add the alt-text, this one seems pretty good and supports Mastodon (albeit not in the Media tab): https://chrome.google.com/webstore/detail/social-visual-alt-text/bkpbmomfemcjdeekdffmbohifpndodmi

**Comment by RemiCardona** [comment]
On Firefox for Android, I just found where to get the alt-text (first click the image in the toot _then_ click-and-hold) and the text is cut even shorter than 1024 chars, it's 2 lines/20 words of text on my device.

So yeah, any faster way to get to the _full_ alt text would be much appreciated :pray:

**Comment by SHiLLySiT** [comment]
+1 to this feature!

I just started using Mastodon. I had been seeing image alt text in Tusky when you select a photo, and was very confused today when trying to look for the alt text on web. Very sad to find its only visible on mouse hover :(
