### ISSUE TITLE
s3 Storage does not display images after successful upload

### ISSUE THREAD

**Issue by tokpig** [mastodon/mastodon#25357]
### Steps to reproduce the problem

1.The configuration is filled in correctly（.env.production）
2.
3.
...
`S3_ENABLED=true‘

’S3_PROTOCOL=https’

‘S3_BUCKET=mastodon-abc‘

’S3_REGION=eu-central-1’

‘S3_HOSTNAME=s3.eu-central-003.backblazeb2.com‘

’S3_ENDPOINT=https://s3.eu-central-003.backblazeb2.com’

‘S3_ALIAS_HOST=files.mastodon.tf/file/mastodon-abc   ‘     

’AWS_ACCESS_KEY_ID=xxxxxx’

‘AWS_SECRET_ACCESS_KEY=xxxxxxxxx`

but

![image](https://github.com/mastodon/mastodon/assets/23582505/8b880c35-f213-4ab8-9255-1345f84d69af)

![image](https://github.com/mastodon/mastodon/assets/23582505/8cd6f459-7a0a-437e-88e7-176f1ef0876d)

Display images correctly without logging into your account

![image](https://github.com/mastodon/mastodon/assets/23582505/7d03ae38-8756-474a-982e-b850abbef76a)

### Expected behaviour

Correct display of images

### Actual behaviour

Cannot display pictures

### Specifications

Mastodon | 4.1.2
Ruby | 3.0.6p216
PostgreSQL | 14.8
Redis | 7.0.11

**Comment by tokpig** [comment]
After closing s3 storage, the images uploaded to the local server are displayed correctly

**Comment by renchap** [comment]
`S3_ALIAS_HOST` does not support a path in Mastodon 4.1.2.

This will be fixed in the next version (https://github.com/mastodon/mastodon/pull/25273).

I the meantime, as recommended in the [Object Storage Documentation](https://docs.joinmastodon.org/admin/optional/object-storage/), we recommend you to use a CDN or a reverse-proxy in front of your Backblaze Bucket, so you can change your storage provider in the future without issues.
You should be able to configure your cdn/proxy to rewrite the path as needed, so `https://files.mastodon.tf/<file>` is proxied to `https://s3.eu-central-003.backblazeb2.com/file/mastodon-abc/<file>`
