### ISSUE TITLE
Timezone Database Migration Has Null Value, 500-s Settings UI

### ISSUE THREAD

**Issue by 9p4** [mastodon/mastodon#25452]
### Steps to reproduce the problem

1. Update Mastodon to after https://github.com/mastodon/mastodon/commit/4c9406bdb0938367615a12083199705304d29e27
2. Do database migrations `rake db:migrate`
3. Open user preferences `https://mastodon.example.com/settings/preferences/appearance`
4. Get 500 error

### Expected behaviour

I should have been able to see the settings page with an unset timezone dropdown.

### Actual behaviour

The settings page 500'd

### Detailed description

Snippet of error: `` ActionView::Template::Error (undefined method `time_zone' ``

Fixed by setting any value in database: `update users set time_zone = 'a'`

### Specifications

Mastodon edge

**Comment by ClearlyClaire** [comment]
Having `null` values should be fine. What seems to have happened is that you may have restarted the services *before* running the migrations.

This is because Rails caches the table definitions and does not expect them to change. So if you started the new code before the migration, it would have cached the `users` table definition without the `time_zone` column, and would not have refreshed it even if you ran the migrations shortly thereafter. When needing to access `time_zone`, it would not know what to do because the method is generated automatically from the cached table definition, which did not include it at that time.

You should always run the pre-deployment migrations before running the new code, and run the post-deployment migrations after restarting the services.
