### ISSUE TITLE
Jittery Scrolling Problem in v4.1.4

### ISSUE THREAD

**Issue by ChadOhman** [mastodon/mastodon#25837]
### Steps to reproduce the problem

1. Scroll down on timeline.
2. Scroll up on timeline.
3. Timeline freezes, jitters in place, and stops scrolling.
4. Intermittent error, but present.

User documents it here: https://mstdn.ca/@60pencilgirl/110679806654594776

![image](https://github.com/mastodon/mastodon/assets/2351/bec20efd-0ba7-4c80-96a7-93790173975b)
![image](https://github.com/mastodon/mastodon/assets/2351/ae3294bf-f911-4f2a-9de6-bcd67c83fded)

### Expected behaviour

Smooth scrolling

### Actual behaviour

Jittery, difficult scrolling

### Specifications

Mastodon v4.1.4+glitch
Ruby 3.2.2
Node 20.4.0

Demonstrated on Google Chrome 114.0.5735.199

**Comment by ChadOhman** [comment]
Video of the bug: 

https://github.com/mastodon/mastodon/assets/2351/6a3b3b4d-8f2c-448a-af60-87971590d066

**Comment by ChadOhman** [comment]
Another user has also confirmed this bug in Safari Version 13.1.2 (13609.3.5.1.5) 

https://mstdn.ca/@gemelliz/110696989568220731

**Comment by ChadOhman** [comment]
Users are getting frustrated with this bug.

https://mstdn.ca/@60pencilgirl/110728067957323062

**Comment by asbam** [comment]
I have the same issue here (at least, I'm pretty sure it's the same one). It seems to be related to posts with audio attachments. Here are steps to reproduce:

Install Firefox 102.13.0esr on Linux
Create a new profile and open a window
Load https://mstdn.social/@feditips
Scroll down to the Jul 19 post with an audio attachment
Scroll down another two screens or more
Grab the scrollbar and *slowly* drag it upward
Watch the screen carefully

Observed behavior:
When the post with audio is the next post above the visible screen (i.e. the post below it is not fully visible), the feed starts to stutter and jump backward, rather than smoothly continuing toward the relevant post. Scrolling faster, or scrolling one screen at a time by hitting PgUp or clicking in the scrollbar trough does not trigger the bad behavior.

I initially saw this behavior related to a different post with an audio attachment, and found this one to report as a reliable source for testing.

**Comment by chx** [comment]
Add `##.site.graze-toot-container` to ublocker. Life is too short to suffer with this.

**Comment by mjankowski** [comment]
Is this still an issue on 4.3? I know there were some fixes related to audio/video player in web app merged late last year...

**Comment by ChadOhman** [comment]
> Is this still an issue on 4.3? I know there were some fixes related to audio/video player in web app merged late last year...

I haven't seen it reported since 4.3. I'll close this.
