### ISSUE TITLE
Enable the place of HashTags underneath Images.

### ISSUE THREAD

**Issue by tinker123456** [mastodon/mastodon#25873]
### Pitch

Enable the place of HashTags underneath Images.

### Motivation

Nobody wants to see a wall of HashTags.

Many people place them out of the way at the bottom of a post.

You can't do this with images.  Images are always on the absolute bottom.

Please allow users to put HashTags underneath images.

**Comment by Dehelssey** [comment]
Yay, i came to open this issue : hashtags should not be inside the text, it clutters the interface and make the content illegible. Hashtags are looking more important than actual text, which they're not.

We already have an issue with usernames being **inside** the content as well, and being accented as well. 

Please let the true content be what visually matters.

a piece of reading to chew on : https://www.theverge.com/23673125/mastodon-separate-tags-hashtag-navigation-accessibility

**Comment by teacherbuknoy** [comment]
I mocked up a few suggestions on how to do this. When hashtags appear towards the end of the post, they will be removed from the content of the post and are hidden away below the media attachments instead. We'll call it a tag list. This tag list is collapsed by default and will only show the total number of hashtags in the post. But on click or tap, it will show an inline list of all the hashtags in the post.

![A comparison between the current design of Mastodon posts and my proposed new design. In the current design, hashtags found at the end of the post are rendered as hashtags like we are used to. In the proposed design, hashtags found at the end of the post are removed from the post's text and are tucked away in a special tag list at the bottom of the post. This tag list is collapsed by default, and only shows the total number of hashtags in the post. When it is toggled open, it shows all the hashtags included in the post.](https://github.com/mastodon/mastodon/assets/96061229/2ce27d09-fc8f-422c-8a1f-9e4a7006b945)

I also think the hashtags at the end of the post shouldn't count towards the character limit since they're not actual content, but just tags for added functionality.

Now, if the hashtags appear in the middle of the post's content, they will be rendered as usual. But they will also be included in the tag list and the total hashtags count.

![Comparison between the current Mastodon posts' design and my new proposed design. In the current design, hashtags in the middle of the post are rendered as links like we are used to. In the proposed design, hashtags in the middle of the post will not be removed from the post's content and will be rendered as usual. But it will now also be included in the tag list at the bottom of the post. This tag list is collapsed by default and will only show you the total number of hashtags included in the post. If it is toggled open, it will show an inline list of all the hashtags.](https://github.com/mastodon/mastodon/assets/96061229/fb8876b3-82b0-4316-930f-7a4028a58204)

This design also gives us an opportunity to indicate why a post appears on a feed. Sometimes, it's confusing why a post appears on my feed when I don't follow the user who posted it. But it turns out, it's because I'm following the hashtag. We currently don't have an indication of that. But in this proposed design, the hashtag you are following and the reason why this post appeared in the feed will be taken out of the tag list and will be displayed in bold at the bottom of the post, just above the status action bar.

![A comparison between the current Mastodon post design and my new proposed design. In the current design, when a post from a hashtag you are following appears on your feed, there is no indication that you're seeing the post because you're following the hashtag. In my proposed design, when a post appears on your feed because you are following a hashtag that's included in the post, the hashtag is taken out of the tag list and is displayed in bold even when the tag list is collapsed.](https://github.com/mastodon/mastodon/assets/96061229/58d7dd0b-9ac4-425e-b305-ff3a54519213)

**Comment by Dehelssey** [comment]
I really like the "highlighted" hashtag when post comes from a followed hashtag not a followed user, great idea !

I didn't think of hiding hashtags at first but tbh it makes sense since their main value is to help posts get found. Most of the time don't really need to read the hashtag.

**Comment by renchap** [comment]
Closing as this should be solved by the new hashtag bar.

Hashtags that are on a single line at the end of a post are now moved to the hashtag bar, which displays under the image.

We will probably make it easier for people to add out-of-band hashtags (attached to the post, but not in the content) from the composer at some point, but for now this seems to solve the issue.
