### ISSUE TITLE
Move opt-in public status indexing (PR #26344) from discoverable to noindex

### ISSUE THREAD

**Issue by joenepraat** [mastodon/mastodon#26418]
### Pitch

Because @Gargron locked commenting on pull request #26344, I do it like this.

I'm not going to debate if this pull request is a good thing or a bad thing. But if it's added I like to ask if the user opt-in can better be added to the noindex option, instead of the current discoverable option. Because this is not about discovering and finding accounts, but about indexing and searching posts. Therefore it can be compared with search engines like Google and Bing. 

On my servers the noindex config variable is set to true, so if this is also used for public status indexing it's easier for servers to offer their users more privacy out of the box. Servers can also keep the noindex=false (Mastodon default) and users will still be able to opt-out. 

Account discoverability is really another thing than full text search.  Thanks for considering this.

cc @ClearlyClaire @jsgoldstein 

### Motivation

My motivation is to give users privacy, but also to option to be discoverable. Another motivation is not alienate existing users and keeping the peace.

**Comment by renchap** [comment]
Hi,

Thanks for sharing your concerns about search with us. The mentioned PR is not done yet and discussions are in progress on how the exact implementation will be, leaning towards having a specific flag for indexing posts into Mastodon's built-in search.

I am closing this issue, not to dismiss your point, but because discussions about this are happening in many places and the mentioned PR will have changes that should fix the issue you (and many other) are concerned about.
