### ISSUE TITLE
Increase moderation abilities when introducing features that might encourage or ease abuse

### ISSUE THREAD

**Issue by ShadowJonathan** [mastodon/mastodon#26411]
### Pitch

Right now, mastodon's guidance wants to add more features for users, ones that would make mastodon more attractable and usable.

This is understandable from a maintainer and developer perspective, and understandable from the perspective of those users.

However, to users who might be targeted or abused through these new features, with little to no recourse, often marginalised communities, this is not acceptable. Same to the moderators and administrators of instances who safehouse these communities.

As a moderator and technician for tech.lgbt, I've encountered a lot of these instances in the past, where I have had to take a look at the existing moderation tools available to us from the console, and realise that it would not be enough to counter some abuse, and so had to settle for sub-par solutions, database scripts, Python scripts, and other ad-hoc solutions to track down abuse, harassment, and hate, and deal with it.

Mastodon has a rich set of instance administrators and moderators, and this issue tracker has many suggestions for better moderation tools, some of which I submitted (https://github.com/mastodon/mastodon/issues/21306, https://github.com/mastodon/mastodon/issues/24214)

When introducing features, listen to instance admins about how it would affect abuse, and take proactive measures *before merging the feature* that could give mods additional capability to counter abuse resulting from the feature.

### Motivation

This is in response to the situation surrounding https://github.com/mastodon/mastodon/pull/26344, which made me realise this is needed to counter subtle introduction of abuse potential, if each feature is accompanied with a risk assessment, and that risk is proactively countered on the side of moderation tools, before the feature is introduced.

**Comment by renchap** [comment]
Hi,

Thanks for your message.

Fighting abuse is definitely something that is considered when features are added, and we are very aware of what abuse can mean and ways that things can be abused. Many features are not yet implemented because we do not want them implemented before there are controls to prevent them to be used for anything nefarious (an example: quote posts).

Please be aware that the main team is very small and we have to make good use of our resources to move the project forwards. We have many ideas about how we could improve moderation, abuse-fighting, spam fighting and other (I even write [a whole blog post with my view on this topic](https://renchap.com/blog/post/evolving_mastodon_trust_and_safety/)), but this will require a lot of work to be implemented properly (including avoiding them to be used for further abuse, and have the best privacy possible).

Right now we are focused on delivering the 4.2.0 version, which brings many feature people are asking for and is taking far too long to be release. Once the release is done, we plan to take some time to think about our future trust & safety plans and make improvements on this front.

I assume your message was triggered by #26344 (but this was only the trigger), so I want to add that this PR is not yet finished, feedback was received, and there will be changes to this PR to alleviate most of the issues (I am not working on it and I cant say what those will be specifically).
