### ISSUE TITLE
bug report: DMs are posted as public

### ISSUE THREAD

**Issue by alreadyinuse** [mastodon/mastodon#26455]
### Steps to reproduce the problem

1. view a random profile, e.g. https://kolektiva.social/@admin
2. click the "..." menu and choose "Direct Message @admin"
3. Notice that "@admin" appears in the text input box and your cursor focus shifts to the text input box
4. type your DM, then press "Toot!" to send your DM
5. notice that your cursor focus is still in the text input box
6. type a second DM, the press "Toot!" to send your DM
7. notice that your second DM was not sent as a DM, but instead was posted as a public "post" on your public timeline.

### Expected behaviour

DM should be sent as DM, not be posted as public post

### Actual behaviour

DM was posted as public post.

### Detailed description

This user interface is messed up.  The presence or absence of the user's handle determines if the text is posed as a post or sent as a DM.  This dynamic change of function of the text input box is completely contrary to standard paradigm, and will be completely confusing to many people, especially autistic people, because the text input is serving dual purpose depending on context of presence or absence of user handle.  Meanwhile all the other contextual cues do not indicate any changed function of the text input box.  Autistic individuals have a lot of problems with context attribution and processing. If you wanted to design a confusing interface, you couldn't do a better job than this, not even if you were a genius, and/or not even if you were profoundly bad at designing user interfaces.

### Mastodon instance

kolektiva.social

### Mastodon version

v4.1.6

### Browser name and version

firefox 116.0.2 (64-bit)

### Operating system

Windows 10 Pro  22H2  19045.3324

### Technical details

Please note that any attempt to rationalize this particular aspect of the user interface as acceptable or as anything other than garbage will be met with hostility.

**Comment by trwnh** [comment]
#23889

**Comment by alreadyinuse** [comment]
NO

**Comment by alreadyinuse** [comment]
> #23889

NO.  Please don't post spam like this.

**Comment by alreadyinuse** [comment]
To trwnh, and to winterqt who reacted with the "confused" emoji, and to all the devs who can't wrap their heads around the most basic of security concepts:
This is a system that causes private DMs to be posted as public messages.  Okay, so you can be forgiven for attentional blindness, for not seeing this problem in the first place.  But here I am beating you over the head with it, and you still can't see it.  If your response is to be confused, to post a flippant link to some tangentially related concept, then you just don't get it.  If you do anything other than form the opinion that a system that posts private DMs as public messages is unacceptable, then you should do the world a favor and quit programming, quit development, and never again touch any system that has anything to do with security.  Don't even "help" someone by replacing their broken doorknob for them.  Don't have children.  Don't have cats.  Throw away any sharp objects that you own.  Open source distributed development is wonderful except for when it produces garbage like this.

**Comment by trwnh** [comment]
#23889 is the PR that fixes this issue, which is why I tagged it. It's not a "tangentially related concept".

**Comment by alreadyinuse** [comment]
So you're telling me that a solution would be to add a preference setting that allows the user to opt out of the default behavior of posting private DMs as public posts?  Is that what you're actually saying?  You're actually proposing that as a "fix?"   You think that by default, Mastodon should NOT respect the user's privacy?  I don't like this idea.  This idea is not welcome.  Please delete your comments here.  Thank you.

**Comment by trwnh** [comment]
> Mastodon should have some actual DM feature (whether we like it or not, people expect to be able to DM on every platform)

#3819

I do agree that there is a mismatch of expectations here, in that the dropdown menu is a one-off action, not a mode switch. The other linked PR (#23889) adds a feature that makes the privacy switch persist, which may itself be unexpected behavior as it leads to the default privacy scope being ignored, and you will be stuck in whatever current scope until you manually switch out of it.

The intended flow to continue any thread is to reply to the last status, so the issue could have been avoided by doing this, but it was not clear that this was necessary.

- Perhaps the "Mention user" and "Privately mention user" menu items could instead launch a modal instead of reusing the stationary compose box? This would make it clear that it is a one-off action.

- Alternatively, they could be removed entirely, if they are too confusing.

Put another way:

> The presence or absence of the user's handle determines if the text is posed as a post or sent as a DM

is an incorrect expectation, and we should do our best to ensure that users do not have this expectation. The presence of a mention and the scope of the post are completely disconnected -- it is equally possible to *publicly* mention someone, just as much as it is possible to *privately* mention them. (In truth, there is no such thing as a "DM" in Mastodon yet, and I have long-argued that the UI should not call them such or present them as such... they're all posts.)

**Comment by ClearlyClaire** [comment]
As other people have said, no DM gets sent as public posts, but the user interface does not match your expectations, which can still lead to accidentally leaking information you did not want to share publicly.

While #23889 is about adding a preference for the UI to have the behavior you expect, it would probably fail to address your issue, since you would have to know about the setting and the discrepancy between the UI and your expectations before the situation happened.

As a side note, what is currently called “Direct Messages” will be called “Private Mentions” in the next Mastodon version. Would that have helped with your confusion? The menu item you refer to would be “Privately mention `@admin`”

**Comment by willhansen** [comment]
That just sounds like it's a public post that has a hidden `@user` that only that person can see.

**Comment by alreadyinuse** [comment]
So your software is social engineering me, taking advantage of my *standard* expectations of how a *standard* user interface *should work*, and it's tricking me into posting private DMs as public messages.  I report this as a bug, and you all have the audacity and temerity and lack of imagination to come on here victim-blame me and euphemistically reference this horrid user interface design an 'expectations mismatch.'  You call it 'clunky but not a bug.'  You have *no respect* for the user's privacy or safety, you don't give a damn about the risks and consequences of a user's private communications being posted publicly.

Given that the developers refuse to fix this, please inform me how to escalate this to the board of directors.

**Comment by alreadyinuse** [comment]
closed in error

**Comment by alreadyinuse** [comment]
this bug has now been copied, ironically enough via Mastodon DM, to these users:
@Gargron@mastodon.social 
@renchap@oisaur.com 
@Claire@sitedethib.com 
@zeitschlag@chaos.social 
@marcus@bearologics.social 
@grishka@mastodon.social 
@andypiper@macaw.social

**Comment by alreadyinuse** [comment]
this bug has now been copied, ironically enough via Mastodon DM, to these users:
@[Gargron@mastodon.social](mailto:Gargron@mastodon.social)
@[renchap@oisaur.com](mailto:renchap@oisaur.com)
@[Claire@sitedethib.com](mailto:Claire@sitedethib.com)
@[zeitschlag@chaos.social](mailto:zeitschlag@chaos.social)
@[marcus@bearologics.social](mailto:marcus@bearologics.social)
@[grishka@mastodon.social](mailto:grishka@mastodon.social)
@[andypiper@macaw.social](mailto:andypiper@macaw.social)

**Comment by andypiper** [comment]
We're aware of this issue, and there is no need to send individual messages, or to tag us individually in the issue. You're in the right place; you've raised the issue; we've responded with an explanation of the design; you're still concerned about the feature, and we hear that.

We've made changes in version 4.2 that rename "direct messages" to "private mentions" to further distinguish the design and behaviour of these kinds of messages on Mastodon, from other platforms you may have used. It looks like the instance you're on is running 4.2 so hopefully you're seeing this in the user interface now. 

There is no intent to mislead a user here (which is what "social engineering" might suggest). It's a different behaviour to what you might see on other platforms, but that's not done in order to trick or deceive. There are a few suggestions already in the backlog that might help to improve the experience, but we do not currently intend to make immediate changes. It might be something that evolves in the future.

Mastodon is not *primarily* a private messaging platform, and you should choose to use other apps or tools if that is what you need to do - particularly with sensitive messages. I personally tend to use Signal for that, there are a range of options open to you.

You're absolutely right that there's no strong user-facing documentation at the moment, and that's potentially an area to improve for the future.  

As someone who has used a range of social networking platforms for many years, private mentions initially confused me as well, but I've become used to how this works. I'm sad that you're dissatisfied with Mastodon's implementation of the feature, but it is working in the way that it was designed.

**Comment by alreadyinuse** [comment]
Mastodon UI tricks / confuses / manipulates / deceives users into posting private DMs as public content.  "There is no intent to mislead" does not at all square with "It is working in the way that it was designed."  My private DM posted as a public message is the way it was designed?  Then you say it's my fault for expecting a direct message to be private? 
 Then you suggest that changing the name from "direct message" to "private mention" might somehow make it all better?  If anything you need to change the name to "sometimes private sometimes public mention" Oh, I shouldn't be hostile towards someone who violates the safety and security of the user, and then doubles down on their anti-social behavior?  You and your team have no respect for the typical user.  You have even less respect for the autism spectrum user.   Your software has real world implications for the safety and security of real people.  I wouldn't care if you applied this obtuse vision over at Facebook or Twitter, but here you are taking people's money, promising them a better tomorrow, and instead delivering this.
