### ISSUE TITLE
`/api/v1/accounts/relationships` do not de-duplicate accounts

### ISSUE THREAD

**Issue by renchap** [mastodon/mastodon#26564]
### Steps to reproduce the problem

1. Make a query to the relationships endpoint, with 10 times the same ID. For example `http://localhost:3000/api/v1/accounts/relationships?id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332`
2. Look at the response

### Expected behaviour

I would expect account 110321186862529332 to only appear once

### Actual behaviour

It appears once for every ID specified in the request

### Detailed description

We probably need to patch the controller to add `uniq` to the list of inbound IDs

```ruby
  def account_ids
    Array(params[:id]).map(&:to_i).uniq
  end
```

I wonder if this could be done in other places as well

### Mastodon version

`main`

**Comment by ClearlyClaire** [comment]
As far as I know, these API endpoints explicitly return the items in the order in which they were requested. If order is to be preserved for client apps, deduplication doesn't seem like a safe change to do. If order is deemed irrelevant, we can save a few steps by not re-ordering and duplicating items.

**Comment by ClearlyClaire** [comment]
The documentation currently does not mention the order in which items get returned:
https://docs.joinmastodon.org/methods/accounts/#relationships
https://docs.joinmastodon.org/methods/accounts/#familiar_followers

As for why the results are ordered this way, `/api/v1/accounts/familiar_followers` was written this way with no rationale provided, but `/api/v1/accounts/relationships` did not initially work in this fashion. This was introduced in #4801, rationale was given here: https://github.com/mastodon/mastodon/pull/4801/files#r139680380

So my belief is that it was never an API guarantee, but just made that way because that logic was reverse-engineered by a contributor from overly-specific test cases (which make no such assumption anymore), and removing those ordering and non-deduplication constraints would not constitute a breaking API change.

**Comment by KevinBongart** [comment]
Thanks @ClearlyClaire for clarifying! As explored in https://github.com/mastodon/mastodon/pull/27982, I can see two paths:

1. Keeping the current logic on ordering the response based on param order, and inferring that if the client requested duplicate accounts, then both the order and the duplicates are intentional. No logic changes required, I can close my PR (or just tweak the tests to confirm both param order and duplicates are honored). We could update the API doc to reflect this guarantee.
2. Deciding that param order isn't guaranteed and duplicates are removed. This lines up with expectations I personally have for APIs, whether web or ORMs like ActiveRecord. As a result, this would simplify the codebase and, I assume, bring small performance improvements to these endpoints.

A potential third option would be what's currently implemented in https://github.com/mastodon/mastodon/pull/27982: remove duplicates params but keep the ordering (use the first instance of an ID as the index for that account). But I think there should be consistency in how the API interprets the list of IDs sent by the client, and option 3 doesn't communicate a clear line between the API logic and the client expectations.

My personal preference is to go with option 2 to keep the codebase simpler and leaner, but I'm new to the repo so I'll follow your recommendation :)

**Comment by ClearlyClaire** [comment]
Yes, option 2 is my preference as well, and I'm not aware of clients making assumptions on the order of returned items. Furthermore, I think such assumptions are already broken when dealing with deleted or suspended posts/accounts.

Therefore I think we should just go ahead and remove the order-preserving code. Do you want to take care of that?

**Comment by KevinBongart** [comment]
Yes, I'll update my PR :)
