### ISSUE TITLE
Filters should use alt-text

### ISSUE THREAD

**Issue by zenspider** [mastodon/mastodon#26671]
### Pitch

Filters on the timeline don't appear to respect alt-text content, which means memes or other images with keywords/phrases you'd rather filter (but contain matching alt-text) are still in your timeline.

### Motivation

discovered here: https://elk.zone/ruby.social/@zenspider/110942018710404988

**Comment by zenspider** [comment]
Assuming I found the right name, I'm not seeing it associated with much at all:
https://github.com/search?q=repo%3Amastodon/mastodon%20image_alt&type=code

**Comment by ClearlyClaire** [comment]
It's not the right name! What you've searched for is just for OpenGraph information extraction, it's unrelated!

The places where filters are applied to post text, including alt-text (the `description` field of media attachments):
https://github.com/mastodon/mastodon/blob/075cc8e8a64bd43b83865c7beddb877787ed674f/streaming/index.js#L873
https://github.com/mastodon/mastodon/blob/075cc8e8a64bd43b83865c7beddb877787ed674f/app/models/custom_filter.rb#L99C63-L99C63
https://github.com/mastodon/mastodon/blob/075cc8e8a64bd43b83865c7beddb877787ed674f/app/models/concerns/status_search_concern.rb#L37

The situation you are opening a report for happens within Ivory, so it may be an issue with Ivory, especially if the following piece of information is still relevant: https://tapbots.com/support/ivory/general/filters

**Comment by ThisIsMissEm** [comment]
Yeah, Ivory doesn't support custom filters yet. There is perhaps related work here to move the calculation of the searchable text to the rails/ruby side, instead of doing it in the streaming server as well (but that's more a performance improvement, not changing the functionality).

@ClearlyClaire do we typically keep issues open for things that aren't issues with mastodon, but with third-party software not implementing certain functionality?

**Comment by ClearlyClaire** [comment]
I was waiting input from @zenspider to confirm that it was an Ivory issue, but I think this is indeed the case.

I'll close it now, feel free to reopen if it is something else!
