### ISSUE TITLE
Automatically following privacy/publicity setting in conversations should have clear warnings

### ISSUE THREAD

**Issue by ghost** [mastodon/mastodon#2675]
As noted here: https://witches.town/@nire/1142473 , a reply's privacy/publicity setting automatically changes to the toot you're replying to. This should not be done without a clear warning in case of _increasing_ publicity, maybe even not be done at all in case of direct messages. There's a real danger of accidentally publishing private information, something which on Mastodon often can't be undone.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by msappir** [comment]
The warning can be something like "USER has set their reply's visibility to LEVEL. Your reply is set to LEVEL now too - you can change it back."

**Comment by msappir** [comment]
Another approach:
Instead of a textual warning, turn the toot button red, and add a tooltip saying "This toot's visibility will be LEVEL!"
This might create less friction for the users.

**Comment by yiskah** [comment]
I know that on Tusky, and some of the mobile apps, increasing the privacy level to being more public than what you're replying to is simply disabled. We could do that instead of creating more warnings?

This wouldn't work if you're interacting with a user on an instance that doesn't support privacy scopes though.

I just get concerned sometimes about users constantly being bombarded with warnings...

**Comment by ClearlyClaire** [comment]
Fixed since very long ago (since v1.1 I think), the default visibility of a reply is the lowest visibility between the poster's default one and the reply's one.
