### ISSUE TITLE
Styling class for followed hashtags

### ISSUE THREAD

**Issue by atrophicshiner** [mastodon/mastodon#26752]
### Pitch

Have a separate class for followed hashtags to enable CSS styling so that they can stand out in toots for better visibility.

### Motivation

Easier to identify why a toot may appear in your feed and highlight the followed hashtag. Allows admins to style them to better fit their instance theme.

**Comment by renchap** [comment]
The issue here is that the API does not return any information to tell the client that a status appears because it comes from a followed hashtag, and the client does not have a list of all followed hashtags.

We plan to add improve this and show more clearly if a status is showed because it contains a hashtag you follow.

This feature is tracked here: #26079
