### ISSUE TITLE
Release Notes for v4.2.0 refer to non existing section

### ISSUE THREAD

**Issue by ilsd** [mastodon/mastodon#27325]
### Steps to reproduce the problem

1. Open https://github.com/mastodon/mastodon/releases
2. Read it until you find: "For more information, scroll down to the upgrade instructions section."
3. Search for a section "upgrade instructions"
...

### Expected behaviour

The section "upgrade instructions" should be there :-)

### Actual behaviour

The section "upgrade instructions" is not visible

### Detailed description

I tried to upgrade from 4.1.9 anyway but failed. All mastodon services are running after the upgrade but the UI shows ERROR. I hope the missing "upgrade instructions" can help me once they are there.

### Mastodon instance

troet.fediverse.at

### Mastodon version

v4.2.0

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
- Node.js version: v16.20.2

**Comment by ClearlyClaire** [comment]
I am not sure whether your issue is that we called the section “Upgrade notes” and not “upgrade instructions”, or if you expect this section to be visible directly on https://github.com/mastodon/mastodon/releases

The section is in https://github.com/mastodon/mastodon/releases/tag/v4.2.0 but unfortunately github truncates the release notes in a way we do not have control over. I thought about adding a link to the section, but it seems we cannot generate anchors either in release notes, so I am not sure what we can do to address this issue.

**Comment by ilsd** [comment]
My issue was, that I expect this section to be visible directly on https://github.com/mastodon/mastodon/releases. So first of all, thanks for pointing me to the correct page https://github.com/mastodon/mastodon/releases/tag/v4.2.0. Now it's clear for me, why my updated failed.

To solve the issue also for others I suggest to put the "Upgrade notes" before the Changelog. This way the Changelog is truncated and not the Upgrade notes.
