### ISSUE TITLE
Allow `*@Addy.io` e-mail addresses at `mastodon.social`.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [mastodon/mastodon#27436]
### Pitch

Allow [`*@Addy.io`](mailTo:contact@help.addy.io) e-mail addresses at `https://mastodon.social/auth/edit`.

### Motivation

https://github.com/mastodon/mastodon/discussions/27431#discussion-5742581

**Comment by nightpool** [comment]
addy.io is one of many services that people can use to generate disposable, anonymous email addresses that are overwhelmingly used for spam. blocking these email providers is unfortunately necessary to maintain a spam-free environment.

**Comment by RokeJulianLockhart** [comment]
@nightpool, but how is that different to any e-mail provider? I can create up to 15 disposable Outlook aliases as I want, right now.

**Comment by nightpool** [comment]
I would invite you to try it. Outlook has significantly better anti-abuse detection and tooling built in, which enables them to suspend automated spam accounts before they're able to cause significant damage. Additionally, the fact of the matter is that mastodon.social blocks these services because of a substantial history of spam accounts being generated using them, and we have not had to block other email providers for the same issue. You're welcome to sign up for any other instance, these blocks have nothing to do with the Mastodon software package that you've opened your issue on.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mastodon/mastodon/issues/27436#issuecomment-1764787698

@nightpool,

> You're welcome to sign up for any other instance, these blocks have nothing to do with the Mastodon software package that you've opened your issue on.

Yes, I apologize for that. However, does the official https://mastodon.social instance have a bug tracker? The absence of an obvious one led me to believe that this also functioned as its.

**Comment by nightpool** [comment]
> Would a substantial improvement in its detection and reduction abilities be satisfactory?

In theory, yes, but in practice I think the usability goals of anonymous email forwarders (sign up and get email immediately with no greylisting period) are in tension with the anti-abuse requirements that e.g. mastodon.social have. I'm not aware of the specifics of how much spam they've seen from addy.io vs other services, but if the percentage of spam accounts to legit accounts were to go down then I don't see any reason that unblocking couldn't be considered.

> However, does the official https://mastodon.social/ instance have a bug tracker?

Not sure what you mean by this. The official mastodon.social instance is not a software package, it doesn't have a public bug tracker because that's not a concept that makes sense for it, it's just a deployment of the mastodon repo. You're welcome to contact the people running it directly at staff @ mastodon.social though, they would have more historical information about what spam specifically caused this domain to be added. 

In general though I think the usability requirements of an anonymous email forwarding service (sign up and receive email immediately with no greylisting period) put it directly in tension with the anti-spam/anti-abuse requirements of e.g. mastodon.social, in a way that "persistent" email inbox providers don't have. So I'm not sure how much room there is for improvement practically and anonymous email forwarders still expose us to significant spam risk as a class.

**Comment by RokeJulianLockhart** [comment]
> In general though I think the usability requirements of an anonymous email forwarding service (sign up and receive email immediately with no greylisting period) put it directly in tension with the anti-spam/anti-abuse requirements of e.g. mastodon.social, in a way that "persistent" email inbox providers don't have.

@nightpool, can you elaborate on this?

I'm unfamiliar with greylisting, and I'm uncertain of what you mean by “persistent” in this case. AnonAddy is just a forwarding service – it doesn't function as a mailbox, so it doesn't even provide public SMTP configuration information. All it does is obfuscate the destination/source e-mail address.

---

> Not sure what you mean by this. The official mastodon.social instance is not a software package, it doesn't have a public bug tracker because that's not a concept that makes sense for it, it's just a deployment of the mastodon repo. You're welcome to contact the people running it directly at staff @ mastodon.social though, they would have more historical information about what spam specifically caused this domain to be added.

Many, many websites, especially instances of other open-source software, have bug trackers. It's not like there's any necessity that they be an extension of a code repository. Bugs can occur anywhere in anything.

**Comment by Gargron** [comment]
staff@mastodon.social is an e-mail address.

**Comment by RokeJulianLockhart** [comment]
Hahaha, thanks. I apologize – I've been handling `mailTo:` URIs a lot recently, so my brain didn't register a handle without a schema as one.
