### ISSUE TITLE
oAuth apps missing in databases - Client authentication failed

### ISSUE THREAD

**Issue by hugogameiro** [mastodon/mastodon#27740]
### Steps to reproduce the problem

Attempt to authenticate using oAuth

### Expected behaviour

Authorization confirmation page

### Actual behaviour

**Page with error**: Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.

### Detailed description

As mentioned in https://github.com/snarfed/bridgy/issues/1602#issuecomment-1795346483, the problem seems to be related to the app being deleted from the `oauth_applications`  database table.

My assumption is that the first time someone on an instance attempts to authenticate with that app, it all works, the app information is stored in the `oauth_applications`, and the remote developer stores the `uid`.

Then the user ends up never using that app or removing the authorization from their account "Authorized Apps". This should not delete the app from `oauth_applications` because the remote developer still believes the `uid` exists.

Months later, when that user or another user on the instance attempts to authenticate again, the remote app requests to authenticate with the `uid` they have stored, and the authentication fails with Doorkeeper `invalid_client`: "Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method".

I have reports of this issue happening with Buffer, Bridgy and elk.zone. I could confirm this issue on a couple of instances that I host and on other instances not hosted by me.

### Mastodon instance

Multiple

### Mastodon version

v4.2.1

**Comment by renchap** [comment]
@ClearlyClaire Can this be caused by the new vacuum we added?

**Comment by wiegelmann** [comment]
Confirmed with the toot.io instance.

**Comment by ClearlyClaire** [comment]
> @ClearlyClaire Can this be caused by the new vacuum we added?

Definitely, this is #24871 at work here. Ideally, apps should gracefully re-register.

**Comment by snarfed** [comment]
@ClearlyClaire the problem is that apps don't know they need to re-register. The failure mode is, when an app redirects a new user to the instance's `/oauth/authorize` with one of these deleted `client_id`s, the instance shows the user this error, and the UX flow stops. The app doesn't get an error from anywhere to notify it of the deletion.

**Comment by ClearlyClaire** [comment]
Hm, this is a good point. I'm not sure what an OAuth app can do, and what we can do to ease that. @ThisIsMissEm, do you perhaps have an idea regarding this?

**Comment by ThisIsMissEm** [comment]
The solution here would be to attempt to [authenticate as the client](https://docs.joinmastodon.org/client/token/#flow), and do a `GET /api/v1/apps/verify_credentials` ([docs](https://docs.joinmastodon.org/methods/apps/#verify_credentials)) call, which would allow you to check the client is still good.

If either fails, then you need to re-register the client (clients can expire with OAuth 2.0, in theory)

**Comment by ThisIsMissEm** [comment]
That said though, if the client is really deleted, then the call to `GET /oauth/authorize HTTP/1.1` should fail...

**Comment by ThisIsMissEm** [comment]
> That said though, if the client is really deleted, then the call to `GET /oauth/authorize HTTP/1.1` should fail...

Actually, just re-checked the spec, that endpoint works as expected (failure happens after approval/rejection)

**Comment by ThisIsMissEm** [comment]
@ClearlyClaire I think client's would have to test their client credentials periodically to ensure they're still valid.

Doorkeeper doesn't support [RFC 7592](https://datatracker.ietf.org/doc/html/rfc7592#section-2) which would allow for a client to read/update/delete it's client registration, with just a "application registration token", which is returned when the client is initially registered.

But OAuth doesn't actually specify behavior here to my knowledge, and in any case, even if Mastodon returned an error immediately on `GET /oauth/authorize`, that wouldn't help the client, as you'd not be redirected back to the application.

The only way the client has knowledge that it's still usable is to use it's client_id/client_secret to request a client credential grant. We could consider expiring clients after a month, but that would require all clients to reauthenticate after a month, which wouldn't be ideal.

**Comment by ThisIsMissEm** [comment]
@ClearlyClaire another option we could look at is doing something similar to our `AccessTokenTrackingConcern` but at OAuth Application level, such that we know when an application's credentials were last used, that way any usage of the OAuth Application would result in it being touched, which would mean that OAuth Applications that have Access Tokens that were deleted would still show up as recently used in the clean up process.

**Comment by snarfed** [comment]
`/api/v1/apps/verify_credentials` makes sense. Unfortunate additional overhead, but definitely not a big deal. Thanks for the idea!

I'm a bit curious about the motivation for garbage collecting OAuth clients, btw. It seems like they wouldn't be a big problem in the common case..were there DoSes where tons of them were registered and filled up db space? Not important, and I'm fine with using `verify_credentials`, just wondering!

**Comment by snarfed** [comment]
Oh, also, any chance you all could formalize the garbage collection period or inactivity threshold a bit? Either hard coded or something we could fetch in eg `/api/v2/instance`? If we're out of sync at all, the silent failure for users is pretty awful UX during the period between when an app gets garbage collected and we later call `/api/v1/apps/verify_credentials` and determine that we need to recreate our app.

**Comment by ThisIsMissEm** [comment]
@snarfed I'd say your best bet is to check once a day for each instance (at time of authentication attempt). Also track your access tokens, and if you get a 401 using one, mark it as expired. If `number of active access tokens == 0` then `check client before requesting new access token`, that way you know that as long as you've an active access token, you're fine, but if you've no access tokens, then you can check to see if you need to create a new client or not, and then allow the old client to be garbage collected.

Really, we should be using short-lived access tokens with refresh tokens (which is more secure), but implementing this would be a pretty major breaking change (we'd have to first support refresh tokens, allow clients to upgrade, then reduce the lifetime of access tokens), but all that depends on being able to introspect access tokens, which is currently broken (`GET /api/v1/apps/verify_credentials` verifies the client credentials, not the access token).

tbh, garbage collection of clients is pretty rare in OAuth / OIDC setups, from what I know, just because of this exact problem.

**Comment by albattran** [comment]
Hey guys,
  Jumping into this conversation here. 
  I think this causes a headache for maintaining apps. We do not know when the failure happens, and a user can easily break this on not popular instances (not an issue for popular instances)
  Imagine this scenario, a user connects their account to an instance, app obtains a token and uses an app then removes it. Even if we added daily registration recheck for each instance, the timing of the vacuum process can still make the app unusable until the next recheck happens.
  Can the vaccum process be changed to something longer than 1 day? I think 30 days is more reasonable, it's not a massive amount of data to store 30 days worth of app registrations, but that gives a much better UX, since the likelihood of this breaking is much smaller.

**Comment by ThisIsMissEm** [comment]
@albattran as an application developer, you do need to maintain a list of access tokens, and a set of client credentials for your users, just like you need to maintain their sessions with your app. Very simply, if you make an API request and get a 401, indicating that the token isn't valid, you delete the token from your database.

On a connect attempt, you do a `COUNT` on the access tokens associated with the instance domain, if it's zero, then you assume your client credentials may have been revoked, and refresh them before proceeding. If greater than zero, then you can use the cached client credentials. (This is the same flow for first-time usage as well, since access tokens will be zero)

There's also a current assumption that applications have offline access by default, which could break or change in the future (i.e., currently access tokens don't expire and you can't refresh them), so without offline access, you'd have to always request a new access token from the user if their token has expired; with offline access, you'd get a refresh token, and regularly refresh tokens that are about to expire, ensuring you've always current credentials for the user.

**Comment by albattran** [comment]
Hey @ThisIsMissEm
Yes, we do maintain the list of tokens, but like I said, checking the tokens (even every day) will not result in good UX
A user can revoke the token on their own (not on our service), and we have no way of knowing they did that until we recheck all the tokens for all users again.
The COUNT is not possible unless we do an audit of all existing tokens to make sure they are still valid. Obviously we shouldn't do this every single minute, or even hour.
Depending on the time of the day when a user revokes a token, there will be a gap that user is unable to connect again, and we would have no idea that they are having trouble because this experience is happening outside of the API (on the Mastodon instance itself as part of authorization)

Just to illustrate again:
1. A user connects to our service to an instance at 11pm UTC
2. Our service checks tokens at 00:00 UTC
3. User revokes token at 1:00 am UTC
4. Vaccum runs at 2:00 am and removes our app registration
6. Another user tries to connect to same instance at 4:00am, they will not be able to until our token check happens 20 hours later
Yes, this is exaggerated scenario, but it is likely to happen, even if it was few hours it is still poor UX

Honestly, I don't see why app registrations should be deleted every day, the upside is so small, and the resulting UX is poor, let alone adding overhead of unnecessary API calls all around!

**Comment by ThisIsMissEm** [comment]
@albattran you'll get a 401 on the next time you use that access token. You can also do a `/api/v1/apps/verify_credentials` call to ensure your client credentials are still valid before attempting a OAuth 2.0 flow (if re-using client credentials).

That is to say, because you're verifying your client credentials prior to doing the OAuth 2.0 flow, you'll always catch when your credentials aren't valid. If you've a lot of users on a given server, you may choose to only revalidate client credentials every N attempts or N minutes.

**Comment by simoncox** [comment]
Think I might have just fallen foul of this as I am trying to set up webmentions on my site using Bridgy. Had tried last year but gave up and i think I revoked Bridgy in Authorised Apps. so this time am getting "Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method." when connecting Bridgy to my instance.

**Comment by snarfed** [comment]
Thanks for all the thought and explanations here @ThisIsMissEm! Complex issue, but worth understanding. And the idea of encrypting tokens inside the db, at app level, as a mitigation against attacks that exfiltrate them, was a new one to me, and a good one!

I ran into another edge case with this garbage collection recently. We have a small fraction of users who make API calls infrequently. We hit a case recently where we had just one user on a given instance, they revoked our app's access inside Mastodon, which then garbage collected the OAuth client, and then a new user on that same instance tried to sign up. We hadn't yet made another API call with original user's token, so we hadn't yet gotten a 401 and learned the client had been garbage collected.

When there's just one outstanding token for a given client, it's easy to call `verify_credentials` first and check it. If there are n outstanding tokens, though, calling `verify_credentials` on all of them would be unfortunate, at best.

The long term answer definitely seems to be moving to short-lved access tokens with refresh tokens, as you mentioned. Hope that's in the cards!

**Comment by albattran** [comment]
@snarfed yep!! I think the scenario you described is what we face as well and explained above. It is really unfortunate and IMHO a poor design choice.
If we are trying to solve the orphaned apps issue, we can ask the developers why they have orphaned apps? I can tell you that allowing the ability to update apps helps because right now you can't change the redirect_url, which is not uncommon to change!
If we are trying to solve for storage, I am sure the storage required for this is much smaller than a single photo.
And I don't think it's a security issue, the tokens are expired and useless anyway. So we are just adding unnecessary overhead to the developer and poor UX to end user during the period of time the server is unaware of app being garbage collected.
When we build something we should think of UX, and sadly the UX here is (as you say) pretty awful both for the end user and the developers (who are the users of the API).

Troubleshooting this issue has gotten so bad that we actually are giving up on helping single user instance with this problem

And yes please, all tokens should be encrypted and salted to make them even harder. And please use a WAF to reduce the attack surface.

**Comment by ThisIsMissEm** [comment]
@albattran iirc, it's a security recommendation not to allow the `redirect_url` to change since that could allow an attack to redirect you off to somewhere you don't expect. Also, there's just no way via API registered apps to update them at all, only user-registered apps.

There's a bit more on this here: https://www.oauth.com/oauth2-servers/redirect-uris/redirect-uri-registration/

Keep in mind, this didn't trigger for apps registered by users. Only apps registered by the API.

**Comment by ThisIsMissEm** [comment]
@albattran oh, also on:
> And I don't think it's a security issue, the tokens are expired and useless anyway. So we are just adding unnecessary overhead to the developer and poor UX to end user during the period of time the server is unaware of app being garbage collected.

Access Tokens in Mastodon currently have no expiry, this is a known issue.

**Comment by albattran** [comment]
@ThisIsMissEm Thanks for the response. 
Re: redirect_url
Yes, it is the recommendation that redirect_url should not change (I am no stranger to OAuth, been using it for almost 2 decades), but it should not be permanent, the owner should be able to update them! If anything it is actually a security risk not to be able to update them, e.g. domain name change, if the owner of the app cannot modify their app redirect_url, they are stuck having to maintain two apps (This is not hypothetical, I have already gone through this already)! AND if for some reason they lose the old domain then they don't even control redirect_url of their old app.
I understand the logistics for federation make manual registration impossible, but it's not impossible to add an endpoint to update the app (name, redirect_url etc), and e.g.:
POST /api/v1/apps can return an additional super_client_secret that can be safely stored and used with client_secret only for app modifications.

Re: expired tokens, I meant the access tokens that triggered the garbage collection discussed here, they expired anyway for all users, hence the garbage colleciton

**Comment by ThisIsMissEm** [comment]
@albattran this isn't really how that'd work:
>  POST /api/v1/apps can return an additional super_client_secret that can be safely stored and used with client_secret only for app modifications.

Instead you'd want something like [RFC 7592](https://www.rfc-editor.org/rfc/rfc7592.html) which handles the Dynamic Client Registration updating itself registration details.

Potentially we could add a `PUT /api/v1/apps` endpoint that requires client credentials for updating.. but this still wouldn't allow you to roll over the redirect_uris correctly, since doorkeeper only supports a single redirect_uri (I'm not sure how this happened, but the database says it's just a string column).

Generally you should simply consider that you've now a new application and encourage the user to uninstall the previous application if they used it.

But also, keep in mind that `POST /api/v1/apps` creates applications that are **not** owned. Only applications created through the `Settings > Development` UI have an owner. That is to say, you don't "own" your dynamically registered application. You just register it and possess the `client_id` and `client_secret`.

--

> Re: expired tokens, I meant the access tokens that triggered the garbage collection discussed here, they expired anyway for all users, hence the garbage colleciton

No, they don't exist, because the user revoked them & they were subsequently deleted. (There's a big difference between revoked tokens and expired tokens.)

The issue people are facing here is that they're dynamically registering an application, then never having a user complete an OAuth 2.0 flow, or they the user completes it, but then later revokes the access to their account for that application, and the instance for that user has no other people using that application, so that application is deleted.

**Comment by albattran** [comment]
@ThisIsMissEm Yes, RFC 7592 describes what I was talking about. I was suggesting an extra security on top of client credentials (See Registration Access Token in RFC 7592) that can be stored securely and not used in regular user OAuth operations.
But I'd be just as happy if the app is updated using client credentials.
I am not familiar with how doorkeeper handles redirect_uri, so if you say it's difficult, let's not waste time on this, I think there are more important issues to deal with (This issue being one!)

As for asking people to uninstall our app because our redirect_uri changed, I don't think that's something we would want to do. 
At the time we supported only 6 social networks, all took a few seconds to change except for Mastodon and we put effort to gracefully migrate instead of downloading the technical issues to the users. Most people already find Mastodon to be difficult to use, we do not want to add another reason why they should quit the platform.

UX is very important, what the user "should do" and what the user expects to do are two very different things. 
And if garbage collection was the only way, fine! However, increasing the collection window to 30 days instead of 1 as I suggested a while back would go a long way, for example Ryan wouldn't even see this problem. It's not uncommon when a user authorizes an app, revokes it then tries again to authorize.  For every user we hear complain, there are at least 10 more who just silently quit.

**Comment by scag1io** [comment]
Are there any news?
I still got the issue trying to login with [toot](https://toot.bezdomni.net/) on https://livellosegreto.it, which runs v4.2.8.
No issue on another instance which runs v4.1.2. Both accounts use 2FA.

**Comment by ThisIsMissEm** [comment]
Have opened this PR to hopefully remove the broken OAuth Application vacuuming, since it was easily circumvented whilst harming developer and user experience: https://github.com/mastodon/mastodon/pull/30316

**Comment by albattran** [comment]
Not all heroes wear capes!

Thanks for stepping in Emelia!

**Comment by ThisIsMissEm** [comment]
Fixed by #30316 being merged. 🥳

**Comment by ThisIsMissEm** [comment]
The work-around for Mastodon 4.2 is to immediately create a `client_credential` grant after registering your application, this gives your application an irrevocable access token, hence prevents it from ever being vacuumed in 4.2: https://docs.joinmastodon.org/client/token/#flow

This was kept under wraps whilst we figured out what to do with the OAuth Application vacuuming process, since it could be seen as a security attack vector; Given the merge of #30316 removed the vacuuming process, there's no longer a security concern in disclosing the workaround for Mastodon 4.2
