### ISSUE TITLE
desktop notifications do not handle mixed RTL + LTR text correctly

### ISSUE THREAD

**Issue by nightpool** [mastodon/mastodon#2777]
![image](https://cloud.githubusercontent.com/assets/233815/25686574/782523fc-303d-11e7-979e-e3d4d7deeec3.png)

----

(the corresponding event in the web ui: ![image](https://cloud.githubusercontent.com/assets/233815/25686593/97586068-303d-11e7-9177-7312693e11b2.png))

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
This is probably a browser-side issue?

**Comment by nightpool** [comment]
maybe? I think there's a way to isolate unicode RTL contexts that we could use here

**Comment by mabkenar** [comment]
I just tested the following solution in Firefox and Chromium, and it works fine on both. So I believe this solution is safe to be implemented.

### Solution
In making the string that shows up in the notification text, enclose the username inside Unicode embeddings. For example, instead of 

 **`{displayname} follwed you`** 

write

 **`&#x202A;{displayname}&#x202C; follwed you`** 

If you do this, the notification text will always be LTR, because {displayname} will be embedded and cannot affect direction of the entire notification. The first magic character is `LEFT-TO-RIGHT EMBEDDING` (LRE, U+202A) and the second is `POP DIRECTIONAL FORMATTING` (PDF, U+202C) [(source)](https://www.w3.org/International/questions/qa-bidi-unicode-controls#basedirection).

However, for RTL locales, the first magic character should be `RIGHT-TO-LEFT EMBEDDING` (RLE, U+202B) instead. So this can be decided in a function that gets the current locale as input and spits out either LRE or RLE. The second magic character (PDF) is the same for both cases.

### Why embeddings and not isolates?

**Unicode isolates** are indeed better than embeddings since they prevent some extra problems. But  none of the major browsers support isolates yet ([test results](https://www.w3.org/International/tests/repo/results/rli-etc)). Therefore, W3 [recommends](https://www.w3.org/International/questions/qa-bidi-unicode-controls#basedirection) to solve this problem using **Unicode embeddings** as a workaround. Fortunately, the edge cases where isolates work better than embeddings do not affect Mastodon (they mainly deal with mixing numbers inside bidirectional text).

Hope this helps. I am happy to provide more help or feedback or testing.

**Comment by mabkenar** [comment]
Using the solution I explained above, I could fix the reverse problem (LTR display name in an RTL instance):

[Mastodon 1.3.1, wrong]
![notification-rtl-bug](https://cloud.githubusercontent.com/assets/3006332/26751190/ec061fca-4833-11e7-8557-9ebc3c144b81.png)
[Mastodon 1.4.1, right]
![notification-rtl-bug-fixed](https://cloud.githubusercontent.com/assets/3006332/26751193/ffc2c07c-4833-11e7-9b63-1e5186d5708d.png)
This was done by adding invisible RLE and PDF characters (see above) in the  `app/javascript/mastodon/locales/fa.json`. 

I still think it's better if this is implemented in the code rather than in the localization file. But at least what I did shows that the unicode embedding solution works.

**Comment by FloatingGhost** [comment]
I have a similar but related issue

A user has `Unicode Character 'RIGHT-TO-LEFT OVERRIDE' (U+202E)` as a trailing character in their username, leading to some pretty amusing text rendering

![RTL Text in english](https://i.imgur.com/rE78zfA.png)

I believe it'd be solved by @mabkenar's solution, but I'll document the interesting behaviour nonetheless

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
