### ISSUE TITLE
Filter#keywords can be null in API response

### ISSUE THREAD

**Issue by saket** [mastodon/mastodon#27977]
### Steps to reproduce the problem

I'm not sure what the correct steps to reproduce this are, but I just ran into a status that was filtered server-side by mastodon, but does not contain any `Filter#keywords` value. 

### Expected behaviour

Filter#keywords should be non-empty as per the API documentation: https://docs.joinmastodon.org/entities/Filter/#keywords

### Actual behaviour

Filter#keywords was null

### Detailed description

FWIW I noticed that mastodon-android does not mark `Filter#keywords` as a required field. It was explicitly removed here:

https://github.com/mastodon/mastodon-android/commit/17957b69d17d7b4374997d577820c77719cff7c5#diff-fb05f829ceea869fb58eafc6203750f0c7d1a9d3a84b32a4e7903541ef065aa0

### Mastodon instance

androiddev.social

### Mastodon version

v4.2.1

**Comment by ClearlyClaire** [comment]
The `keywords` and `statuses` are only returned when you query the filter. They are left out of the `filtered` attribute because that information is generally not useful in that context and would cause an unwarranted increase in payload size.

**Comment by saket** [comment]
Gotcha. Can the [documentation](https://docs.joinmastodon.org/entities/Filter/#keywords) be updated to mark them as nullable in that case?

**Comment by trwnh** [comment]
Please file this against https://github.com/mastodon/documentation

**Comment by saket** [comment]
Done. Thanks!

https://github.com/mastodon/documentation/issues/1343

**Comment by nikclayton** [comment]
> The `keywords` and `statuses` are only returned when you query the filter. They are left out of the `filtered` attribute because that information is generally not useful in that context

Counter-example: I'm building a UI to allow the user to edit the filter that filtered a post; for example, they've created a filter that warns, they've seen a post that's had the filter applied, and they've decided they want to edit the filter. Maybe to change it to "hide", maybe to change the keywords the filter matches, etc.

When building the UI to allow them to edit the filter directly from a status I can't use the filter data that was attached to the status because it's missing `keywords`. I have to make an API call to fetch the full filter using its ID.
