### ISSUE TITLE
Status edits are not sent to streaming clients if they do not appear in a subscribed feed

### ISSUE THREAD

**Issue by marousta** [mastodon/mastodon#28258]
### Steps to reproduce the problem

1. Send a status with direct visibility to a user who doesn't follow you
2. Edit the sent status
3. The recipient does not see the status edit unless they refresh

### Expected behaviour

The recipient should have received the edited status

### Actual behaviour

The recipient does not see the status edit unless they refresh

### Mastodon version

v4.2.3

### Technical details

- Ruby version: 3.2.2
- Node.js version: v20.6.1

**Comment by ClearlyClaire** [comment]
I am unable to reproduce this!

**Comment by marousta** [comment]
https://github.com/mastodon/mastodon/assets/61333854/c3b1dd6f-7946-4aba-8232-a8ffe40b684c

**Comment by ClearlyClaire** [comment]
Ah, I see the issue now, thank you! I'll reword your report to make it clearer and investigate how to fix the issue.

**Comment by ClearlyClaire** [comment]
This happens because `status.update` events are only ever sent to timelines (public, hashtag, and home) whereas private mentions (and mentions from non-followed people) do not appear in those. The easiest way to fix this would be to send `status.update` to mentioned account on their notification streaming channel, at the cost of some duplicate work.

**Comment by marousta** [comment]
Thanks you!!
