### ISSUE TITLE
v4.2.3 upgrade notes wrong version for ruby 

### ISSUE THREAD

**Issue by danorton** [mastodon/mastodon#28769]
### Steps to reproduce the problem

1.  Notes read “Ruby: 3.0 to 3.2”
2. File `.ruby-version` restricts to version 3.2.2
3. sidekiq fails on startup

### Expected behaviour

sidekiq should start without errors

### Actual behaviour

sidekiq crashes on startup

### Detailed description

sidekiq stops on startup, complaining that `.ruby.version` is wrong.

### Mastodon version

v4.2.3

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2) - 3.0.6
- Node.js version: (from `node --version`, eg. v18.16.0) - v16.20.2

**Comment by renchap** [comment]
Sidekiq does not check `.ruby-version`, and Mastodon does not either.

This is probably caused by a ruby version manager tool (rvm, rbenv…) you have installed on your server that installed a custom executable for `ruby`, which checks if the version listed in `.ruby.version` is available, and fails if it is not.
