### ISSUE TITLE
Provide non-gendered German translation

### ISSUE THREAD

**Issue by idc77** [mastodon/mastodon#29492]
### Pitch

There are many people who don't like `*innen`, the majoriy.
There should be an option for the majority to have a clean language, free of gender politics.

That means things like renaming
Nutzer*innen back to Nutzer
and so on and so forth.

Gender politics language is hard to read and understand.

I did so for v4.2.7, as well as changing the post limit from 500 to 5000 characters.
[427.txt](https://github.com/mastodon/mastodon/files/14469938/427.txt)

### Motivation

see above

**Comment by varjmes** [comment]
_There are 23 total uses of `*innen` across the entire mastodon codebase. Almost all of them seem to appear on one part of the interface reserved for instance Administration. This issue was clearly opened in bad faith, "clean language, free of gender politics." is a clear transphobic dogwhistle and I don't expend my energy on those sorts of things. However, I'm curious about schrmh's more informative response, so I thought I'd reply with my thoughts_

Thanks for the links @schrmh, it's always good to learn more about the specifics of another language, as a bit of a language (and gender!) nerd :)

I'd generally argue that an official body is largely not representative of the cultural norms of society, the Council for German Orthography is a group of 41 Governmental employees. There are 90,000 people in the world who speak German as their Native language with an additional 100-125 million people who speak it as a second language or to some other level of fluency beyond "I learned a bit on Duolingo".

https://www.dbsv.org/gendern.html
In the link you provided, the DBSV themselves say 

> Falls jedoch mit Kurzformen gegendert werden soll, empfiehlt der DBSV, das Sternchen zu verwenden, weil es laut Veröffentlichungen des Deutschen Rechtschreibrates die am häufigsten verwendete Kurzform ist und so dem [Wunsch des DBSV nach einem Konsenszeichen](https://www.dbsv.org/gendern.html#konsenszeichen) am nächsten kommt. Zudem ist davon auszugehen, dass Doppelpunkt und Unterstrich für sehbehinderte Menschen schlechter erkennbar sind als das Sternchen.

_Rough English translation_
> However, **if short forms are to be opposed, the DBSV recommends using the asterisk**, because according to publications by the German Settings Council, it is the most frequently used short form and thus comes closest to the [DBSV's desire for a consensus sign](https://www.dbsv.org/gendern.html#konsenszeichen). In addition, it can be assumed that colon and underscore are less visible to visually impaired people than the asterisk.

Their article asks everyone to avoid terms that could have a gender attached to avoid the issue entirely, and go on to say if that's not desirable or possible, then they would prefer it we used the asterisk form because of the variability and often times clunkyness of the screenreading software that partially sighted or blind folk rely on to navigate the web.

As for "the majority is also not really in favor of including symbols within words" it is important to regard any qualitative survey or opinion poll within the wider context they were taken in and consider whether respondees don't like *innen not simply because it looks a bit funky to them and takes 2-4ms more time to parse (according to a study you shared on that Wikipedia page), but because they do not support trans or non-binary people. I am of course not saying these respondents are transphobic, I'm just asking for a consideration of the general hostility towards trans folk across the globe.

As it seems you neither use a screenreader, nor use the interface in German and when encountering German don't seem to have a personal difficulty in parsing _*innen*_ (that you've mentioned), so far all the respondees are a person who clearly harbours unsavory opinions about trans people, and two people who are not personally affected by the issue raised by the original poster. 

Though the amount of *innen the average user will experience via the Mastodon UI is infitsemal to what they'll experience on a daily or weekly base on a general timeline, I'm interested to hear from real users of Mastodon who use screenreaders and speak German. I have a few friends who fit these criteria and I'll ask them, as it's a good learning opportunity.

**Comment by coderbyheart** [comment]
The title of this PR should be: "Provide male-gendered German translation" because this is what the OP is really asking for.

And [here](https://www.dbsv.org/gendern.html) is a text by the German Association of the Blind and visually impaired which recommends the use of the asterisk (Stern).

**Comment by KreerC** [comment]
Hello, blind and German-speaking screen reader user here.

Gender neutral language and the use of the "Gendersternchen" is absolutely not an issue for screen reader users. As with many things, blind people are able to, and in this case even should, adapt, in order to be more inclusive towards everyone. This is a mere tooling issue that is increasingly often fixed in assistive technology itself. The newest versions of synthetic voices (e.g. those of Apple, Google, Microsoft, Nuance, ...) already ship with rules in place to read this stuff correctly, with a "glottal pause" instead of the "Stern" inbetween the words, and users have always been able to supply custom rules to have it fixed for them. 

For the following, please note that I am not proficient at braille: For braille users, the asterisk consists of two separate characters ("," and "in") which might be a bit harder to read or more confusing, especially because "in" is doubled here if you happen to miss the comma that gives context. So Braille users might read "Administrator,ininnen" - but as with the speech output, this can very much be learned. 

At last, one bit of activism: Please don't make blind people the deciding factor on whether or not to use gender neutral language. We are not it, we should not be it, and we really don't want to be it. It's for other groups to decide, in which blind people of course also exist.
