### ISSUE TITLE
Show nodejs, Elastic/OpenSearch versions in the Administration Dashboard

### ISSUE THREAD

**Issue by thegcat** [mastodon/mastodon#29548]
### Pitch

The Administration Dashboard currently shows the Mastodon, Ruby, PostgreSQL and Redis versions. It think it would be helpful to also see the nodejs and may even the Elastic/OpenSearch versions there.

### Motivation

We just upgraded our underlying nodejs version and I wanted to make the new version was used in the running (restarted) process.

**Comment by ClearlyClaire** [comment]
The Elasticsearch/OpenSearch version is already displayed in the admin dashboard since Mastodon v4.2.0. For NodeJS, this would be a bit tricky and require a new communication mechanism between the Ruby and the Node Mastodon components (complicated by the fact that you can run multiple instances of each).

**Comment by vmstan** [comment]
Also the Mastodon container image starting in 4.3 doesn't even have NodeJS included (only the streaming image)

**Comment by vmstan** [comment]
Closing as completed, Node issues aside the other components have been added to the dashboard in 4.3.
