### ISSUE TITLE
Mouse pointer/touch events become horizontally offset from intended location

### ISSUE THREAD

**Issue by fluffy-critter** [mastodon/mastodon#29624]
### Steps to reproduce the problem

This issue randomly occurs and I am not sure of a consistent reproduction aside from using the web UI on an iPad for more than a few minutes.

### Expected behaviour

Pointer events should map directly underneath the pointer location

### Actual behaviour

Pointer events map to a location offset to the left of the pointer

### Detailed description

When using the web UI from an iPad (running iPad OS 17.3 and the stock Safari browser), after scrolling on Mastodon for a little bit the pointer events will start to fire for a location around 100px to the left of the actual pointer, making it very difficult to interact with intended UI elements. For example, attempting to click on the favorite or boost button on one toot might interact with a toot in a different column.

However, scroll events still map correctly.

In this video I am using the touchpad on my iPad keyboard as this makes it obvious that the hover events aren’t mapping to the actual pointer location; similar things occur when using touch events.

https://github.com/mastodon/mastodon/assets/347162/7ff9ea2e-8dfa-4a98-b704-2a270fb684eb

### Mastodon instance

plush.city

### Mastodon version

4.2.8

### Browser name and version

Safari from iPadOS 17.3.1

### Operating system

iPadOS 17.3.1

**Comment by kkostov** [comment]
This is not limited to iPadOS, the issue also happens on macOS with the current stable version of Safari 17.5 (19618.2.12.11.6), especially when the browser window is resized to a smaller width.

**Comment by TheSkorm** [comment]
This is incredibly annoying when you tap on something and it retoots something you weren't expecting.

**Comment by Jolly-Friend-9876** [comment]
I posted an issue with how I reproduce the problem consistently. There may be other ways for the offset to be occurring.

[https://github.com/mastodon/mastodon/issues/30557#issue-2335210940](url)

**Comment by fluffy-critter** [comment]
I just figured out the rhyme (but not reason) for it: the offset occurs when the page is scrolled horizontally, and the offset is precisely by the scroll amount. It’s also visible by the location of the text cursor when writing when there’s a scroll offset.

It seems that scrolling all the way to the left will correct the offset temporarily. I still can’t specifically trigger the offset to occur but when the offset does happen it’s very consistently the same as the horizontal scroll position.

**Comment by Jolly-Friend-9876** [comment]
Thank you very much for looking into this and finding that correlation! I hadn't noticed that it was based on the horizontal scrolling, but it makes sense.

If it would help to do a screen recording, I'm happy to do it in being able to show how it triggers consistently for me. I'll try scrolling to the left, and in the meantime, I've been using the technique of clicking on a link for a person to show their profile off to the right (partially off-browser window), as that resets the position every time.

**Comment by ClearlyClaire** [comment]
Hi! Is this issue still occurring? If so, can you answer these questions?
- which precise version of MacOS and Safari are you using?
- does it only occur when there is horizontal scrolling?
- is the click offset always horizontal or sometimes vertical as well?
- does it still happen if you only ever scroll manually, that is, do not click on something that will open in the rightmost column, nor click “mention” or “reply” (since that would scroll to the leftmost column)?
- when the issue occurs, does it fix itself by manually scrolling all the way in both directions?

This is definitely a Safari bug, but we are still trying to figure out what triggers it.

**Comment by fluffy-critter** [comment]
> which precise version of MacOS and Safari are you using?

I only experience it on iPadOS, and am still encountering it on the latest version of iPadOS but have been seeing it for quite some time.

I don't regularly use Safari on macOS except for compatibility testing of my own sites, so I can't speak to whether it occurs on macOS Safari.

> does it only occur when there is horizontal scrolling?

That has been my experience. It doesn't happen *every* time there's horizontal scrolling, but whenever it does happen, the horizontal scroll offset appears to be the cause.

> is the click offset always horizontal or sometimes vertical as well?

Always horizontal, by the precise amount of scroll.

> does it still happen if you only ever scroll manually, that is, do not click on something that will open in the rightmost column, nor click “mention” or “reply” (since that would scroll to the leftmost column)?

I feel like it only happens when the viewport is scrolled automatically, and that manual scrolling does not trigger it.

> when the issue occurs, does it fix itself by manually scrolling all the way in both directions?

If I scroll back to the left, then the offset goes always away, but if I manually scroll back to the right sometimes it comes back.

And yeah it definitely sounds like a Safari bug to me as well, but I only ever see it happen in Mastodon so perhaps there's a workaround for it that Mastodon can do, or at least a repro case that the Mastodon team can forward along to Apple.

**Comment by daprice** [comment]
Here’s a [screen recording](https://cdn.discordapp.com/attachments/231908446830723072/1284042139956674560/ScreenRecording_09-13-2024_01-34-03_1.mov?ex=66e530ee&is=66e3df6e&hm=4ac8c64f4e436430454b29a47c5009faa2c419fdbecf3a100eb4820000c16bc0&) of what I think is a related issue, where elements don’t render properly when I click a post that opens in a column that’s scrolled offscreen. Sorry about the Discord link, GitHub won’t accept the video.

My answers to the above questions match @fluffy-critter’s except that I see it regularly on both iPadOS and macOS Safari. I’m currently using iPadOS 18.0 RC but I want to say the issue was introduced somewhere in the early iOS 17.x and macOS 14.x releases. I wonder if it might be related to the [extensive performance optimization work that WebKit did around that time](https://webkit.org/blog/15249/optimizing-webkit-safari-for-speedometer-3-0/)?

**Comment by renchap** [comment]
The linked PR should fix this, and we deployed it on mastodon.social yesterday. Could you please try to see if you can still reproduce?

**Comment by Jolly-Friend-9876** [comment]
Renchap, I tried it on mastodon.social and couldn't get it to glitch as before. So it does look like y'all fixed it. Thanks so much!

**Comment by daprice** [comment]
I’ve started experiencing this issue again. What I’m seeing is identical to the OP’s screen recording, and I’ve had it happen I think three times in the last few weeks. I can’t consistently reproduce it. I’m not sure what brought it back, but it did seem to be fixed for a while, until recently.

So far I’ve seen it on mastodon.online (v4.4.0-nightly.2025-01-28) with macOS 15.3, iPadOS 18.2 and iPadOS 18.3.
