### ISSUE TITLE
New "notification request"/DM filter feature requires too many clicks, is exploitable

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#29723]
### Steps to reproduce the problem

Mastodon.social has a new feature for "filtering" DMs/notifications based on criteria like "account less than 30 days old" or "this person does not follow you". It looks like this:

![image](https://github.com/tuskyapp/Tusky/assets/277318/3326c07e-ae2b-4eca-be8d-97b2dcd07356)

I personally like this feature much better than the feature it replaces (the [misleadingly titled](https://github.com/mastodon/mastodon/issues/11882) "Block direct messages from people you don't follow"). I like the available "policy" options; I like the design of the columns; I like what it chooses to show and not show.

However, the new feature creates problems which the old feature set did not have. The problems: it can require many clicks to dismiss; it creates a situation where a malicious person can obtain guaranteed access to your attention. I have suggestions for addressing both these problems.

### Actual behaviour / Expected behaviour / Detailed description

To contextualize why these are problems, here are two actual experiences I personally had on the website "Twitter".

1. "Gamerg‍‍ate": In 2014, a group from what would later be called the "alt-right" began a campaign of harassing indie game developers (including myself) suspected of being feminist or having feminist connections. This campaign consisted of a small group of thought leaders and a large group of foot soldiers, coordinating at first on a site called "8chan" and then on Twitter itself; the thought leaders would pick out one at a time individuals or single tweets they considered ideologically incorrect, and then the foot soldiers would all swarm that person or reply to that tweet in waves, sending messages that ranged from unpleasant to threatening. Blocking did not help because there were dozens of them, each one had multiple "sockpuppet" accounts, and sometimes blocking one of them would lead them to simply create a new account to continue messaging you. By targeting you, this crowd could effectively deny you use of the service; you would not be able to see your legitimate messages and notifications for all the abusive noise, and the only solution was to stop looking at the notifications tab.
2. NFT Spam. From 2021 to 2023, persons selling scam products called "NFTs" created large bot networks that would post lots of simulated "authentic activity", such as inspirational quotes, then start replying to random users with links to scam "drops". These bots were mostly automated and sometimes would go berzerk; on an average day in 2021 I would get one or two of these spam messages per day (I think I somehow got on an "interested in NFTs list"), but then [over a single 12-hour period in 2022 I got seventy-eight Twitter @'s from NFT bots, each from a unique account](https://github.com/mastodon/mastodon/assets/277318/18420afe-f934-4e86-81c5-db0eda06bc02). I have RSI which is activated by repetitive hand actions, and at the time, blocking and reporting a single account on Twitter took nine clicks. I was only able to report about half of the 78 posts before my arm hurt too much from clicking to continue, and my arm continued hurting for the next day.

I tell these stories because these experiences taught two important things to me:

* **Malicious usage— both intentional/targeted and unintentional/automated— can come from multiple accounts simultaneously.**
* **In a targeted attack, someone can create an entire account *solely for the purpose of harassing one person*.**

So, what if something like one of my above two experiences happened on Mastodon, with the "notification filter" feature? Mastodon has some anti-abuse tools Twitter does not; for example, instances hosting the malicious use could be defederated. But it might take hours or days for admins to respond, and in the meantime, someone targeted as above would be unable to use the site.

This brings me back to my two problems with "notification filters":

![image](https://github.com/mastodon/mastodon/assets/277318/2c2a30db-06bb-46d3-9cf7-6822754a6ca3)

1. **It can require many clicks to dismiss.** The "filtered notifications" column design is ideal for one to four notifications. But imagine seventy-eight bots sent me spam in one night. I would have at minimum seventy-eight buttons to click. (More if I chose to report each bot, but never mind that for now.) With my level of RSI, that is a problem.
2. **A malicious person can obtain guaranteed access to your attention.** The "N notifications from persons you may know" box has a fatal problem: The only way to dismiss it is to look at the filtered notifications column. This means if someone wants to send you abusive messages you cannot block, all they have to do is put it in the filtered notifications column: they could create a sockpuppet to target you personally, then put abusive messages to you in the account display name. That may sound wacky or unlikely, but I promise it's something that was actually done to me on Twitter. You the target could avoid this by not looking at the "filtered notifications" tab, but remember that "N notifications from persons you may know" is **always displayed at the top** of the notifications column, and cannot be dismissed or disabled; this means that in an abuse scenario, the messages you don't want to see are given **more priority** than the messages you do want to see.

These two problems are **worse** than in the old system, because in the old system, you could check "Block direct messages from people you don't follow" (or one of the other two old checkboxes? I forget what they said) and the problem would just go away. This feature is gone now.

I believe these problems can be addressed without any major redesigning of the notification filter system. I have filed my two suggestions as separate Github issues:

1. **It can require many clicks to dismiss:** [Add "accept all" / "deny all" options to Filtered Notifications column](https://github.com/mastodon/mastodon/issues/29721). This would help with both the case of many malicious contacts, but also the regular case where inconveniently many *desirable* contacts may arrive at once.
2. **A malicious person can obtain guaranteed access to your attention:** [Bring back the account-level "Block direct messages from people you don't follow" and improve it](https://github.com/mastodon/mastodon/issues/29722).

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-nightly.2024-03-19

### Browser name and version

n/a

### Operating system

n/a

**Comment by jonpincus** [comment]
This is a really important  bug report, thanks for describing the specific attack scenarios.

I'm not sure about the interactions between filtered notifications and limiting an instance.  Do you happen to know if mentions by somebody I'm not following on a limited instance show up as a filtered notification, or are they completely invisible?

**Comment by liza** [comment]
this is a horrible feature. i hate it; exactly because am the usual target for this kind of abuse. 
https://mastodon.social/@blogdiva/112866305393364186

**Comment by sneakers-the-rat** [comment]
Agreed with OP, thanks for the writeup. It needs to be possible for people to simply choose not receive DMs from accounts they dont follow, and for that choice to be respected. Making that choice is a signal that missing some potentially welcome messages is outweighed by their desire to not receive any unwelcome messages, so while the additional subtlety in options from notification filters is good, it shouldnt replace the simple choice to opt out of unsolicited DMs entirely.

**Comment by jwehrle** [comment]
Facilitating guaranteed access to any user's attention from any account is bad design.

Period.

**Comment by dougfinnie** [comment]
Remarkable this issue is still outstanding. It feels serious enough to be reverted to the old behaviour in the name of user safety.

**Comment by renchap** [comment]
We introduced filtered notifications to avoid having posts disappear into the void without users having any way to know about them. This is a real problem that many people were facing and that we wanted to fix.

We understand that this is introducing a regression if you want to not have to review those. But we still want you to have the ability to look into them, for example if you were expecting a reply that has been hidden.

To solve this, we are considering allowing the user to dismiss the filtered notification banner, which will be replaced by a far less visible (and not in-your-face) button or a menu. Here is a mock up on the Android client:
![image](https://github.com/user-attachments/assets/63549468-7064-4e00-b799-3e293964c93b)

We are also considering adding:
- a "block user" button near the "dismiss" and "accept" buttons (but less proeminent to avoid mistakes)
- maybe 2 "accept all" and "dismiss all" buttons in the accounts list

Would this solve the issue mentioned here?

**Comment by rrgeorge** [comment]
People still need to have the ability to flat out block DMs from people they don’t follow, even if it is silently dropping them.

**Comment by ocdtrekkie** [comment]
One of the biggest issues I have is the opposite: On Facebook people have to tell each other in group posts to check for their DM, because DMs are so hard to notice. I have also statistically had almost entirely desirable DMs filtered so far since the feature was added to Mastodon.

I understand why many targeted individuals wish to automatically throw DMs into the void, but I am concerned if it was the default people would not be able to contact each other legitimately over DMs.

**Comment by jmking-iftas** [comment]
> People still need to have the ability to flat out block DMs from people they don’t follow, even if it is silently dropping them.

I think it's fine to add features for folks who /do/ want to review incoming from unknowns, and I think it's fine to consider rejecting instead of discarding, but neither of those preclude a user being able to completely  be shielded from direct mentions and related notifications from people they don't follow. 

In all cases, as we iterate through various levels of "good" on the road to "perfect", it is better to break things for the non-abused, than the ones suffering. It is especially not recommended to remove safety features people have been using without clearly offering an equal or improved alternative.

Unsolicited direct mentions are a documented vector for abuse and harm, and every user should have the option to explicitly never accept anything related to unsolicited mentions, including notifications.

Personally, I feel this should be the default and users should opt /in/ to receiving unsolicited mentions from unknowns, but at minimum a choice at onboarding would vastly improve the experience for the folks who are worried about abuse. I do not think it should take "one first experience of abuse" before asking for help and being told where the option is.

Most platforms by default severely limit direct mentions / DMs to mutuals with varying options to accept more, less, or none. I understand direct mentions are not "DMs" in some comparative senses, but plenty of people using the platform do not see the fine detailed differences. Showing these private messages in the home timeline only adds to harm as it can appear at first glance that the abuse is public, and no-one cares, adding to the distress of experiencing this abuse.

https://cdt.org/insights/more-tools-more-control-lessons-from-young-users-on-handling-unwanted-messages-online/
https://bsky.social/about/blog/05-22-2024-direct-messages
https://newsroom.tiktok.com/en-us/controlling-your-dms
https://help.snapchat.com/hc/en-us/articles/7012337010836-I-don-t-want-to-be-contacted-by-people-I-m-not-friends-with-on-Snapchat
https://help.twitch.tv/s/article/how-to-manage-harassment-in-chat

**Comment by jwehrle** [comment]
That some want to be sure that anyone can access them and that they won't miss that interaction is, objectively, less important than the need some have to control who can interact with their account. Because a need is more important than a want.

**Comment by dougfinnie** [comment]
Just to say along with @jmking-iftas , this is a user safety issue first and foremost
> Unsolicited direct mentions are a documented vector for abuse and harm,

Avoid victims having to react to abuse, THEN look at ways to increase engagement that doesn't compromise their safety.

And test it with those users before releasing it?

**Comment by sneakers-the-rat** [comment]
Totally agreed re: safety > missing some messages. I proposed/implemented an alternative that does both over here: https://github.com/glitch-soc/mastodon/pull/2799

So those people who are concerned about missing messages will still be able to use the new filter features, but those who simply want to drop all unsolicited DMs (and expanding that to make use of the new filter categories) can also do so. The choice is pretty clear and also reuses the existing language and choices from status content filters.

<img width="783" alt="352951151-b3180923-609c-4d89-9af4-8036107fbedb" src="https://github.com/user-attachments/assets/937ee4b1-71b1-4a67-8f69-dbfef79929ac">

I wrote that for glitch s.t. it didnt touch the base masto implementation, so its pretty awkward, but if yall were interested I could refactor to be an enum and less of a hack.

**Comment by renchap** [comment]
> People still need to have the ability to flat out block DMs from people they don’t follow, even if it is silently dropping them.

We still prefer if those are not dropped, but hidden somewhere the user can access if they want to. The proposal above does this, with a button to provide a way to look at those, which you can never click if you do not want to.

Could you clarify what is the problem with this approach, so we can try to figure out how to solve it?

**Comment by jmking-iftas** [comment]
The problem with the approach is

> We still prefer if those are not dropped

There is a segment of the audience, at-risk and often subjected to abuse and harassment, that prefers to never allow such an open method of access to their inbox, regardless of the dev team preference, and regardless of how the messages might be downranked or triaged. 

A notification from an account that has maliciously changed their username to be the actual abusive content is just one vector for how a secondary inbox can still cause harm. 

It's like asking people to allow strangers to place dog poop in their house, but in really well-wrapped, nicely-scented dog poop bags in a cupboard that's never used. Some people are OK with that. Some are not.

I am inferring that the intent from "We still prefer if those are not dropped" is not "we want you to receive all messages, even the harmful ones" but instead is aimed at removing the ability for senders to not know their message was silently discarded, the team would like to be sure a sender knows if their message was delivered or not. This seems like a reasonable goal, just not at the expense of opening up the inbox for accounts that previously were able to avoid incoming unsolicited messages.

Receiver safety should get priority over sender usability.

If the default was "no direct messages from people I don't follow" and the account has the option to "allow messages from people I don't follow" does that solve both cases? Could that be step 1, and step 2 is adding that decision to onboarding and providing a triaged inbox for accounts that opt in?

I am loosely aware of a feature that notices if I am talking to someone I haven't talked to before, so if I understand it correctly there is some level of relationship logic available prior to delivery. If true, use that same logic to forestall undeliverable messages - "this account does not accept messages from accounts they don't follow". Otherwise return a reject message.

**Comment by sneakers-the-rat** [comment]
> We still prefer if those are not dropped, but hidden somewhere the user can access if they want to. 

See: https://github.com/mastodon/mastodon/issues/29723#issuecomment-2259352785

which resolves the problem by allowing someone to explicitly say whether they want to still access and see those messages or whether they don't.

People in this thread and loudly on the fedi are saying "I don't want to see those messages at all"

> The proposal above does this, with a button to provide a way to look at those, which you can never click if you do not want to.
> 
> Could you clarify what is the problem with this approach, so we can try to figure out how to solve it?

The proposal in the OP actually does include restoring the total muting of unsolicited DMs, with an additional notification on the sender side for when someone is refusing dms
https://github.com/mastodon/mastodon/issues/29722

It also articulates the same abuse scenarios as have already been described in this thread and elsewhere.

The PR above demonstrates how the restoration of total mute *alongside, and totally additively with* the new filter system is not all that difficult to implement, but does not attempt the other side notify. Restoring the total muting of unwanted notifications is an important safety feature even without the notifications, which can be added separately.

**Comment by ClearlyClaire** [comment]
> Personally, I feel this should be the default and users should opt /in/ to receiving unsolicited mentions from unknowns, but at minimum a choice at onboarding would vastly improve the experience for the folks who are worried about abuse. I do not think it should take "one first experience of abuse" before asking for help and being told where the option is.

We were not confident with having blocked DMs as the default, but one change we have made with this new filtering system is that unsolicited DMs are filtered by default. Additionally, when you check filtered notifications, media attachments are hidden by default.

> but instead is aimed at removing the ability for senders to not know their message was silently discarded, the team would like to be sure a sender knows if their message was delivered or not

That is accurate, the previous implementation caused a lot of good-faith private messages being dropped without either user knowing.

> If the default was "no direct messages from people I don't follow" and the account has the option to "allow messages from people I don't follow" does that solve both cases? Could that be step 1, and step 2 is adding that decision to onboarding and providing a triaged inbox for accounts that opt in?

I don't understand how it solves anything.

> I am loosely aware of a feature that notices if I am talking to someone I haven't talked to before, so if I understand it correctly there is some level of relationship logic available prior to delivery. If true, use that same logic to forestall undeliverable messages - "this account does not accept messages from accounts they don't follow". Otherwise return a reject message.

I think you're talking about the first-interaction modal on the mobile app, which is purely locally-tracked and does not require either account signaling any of their settings. One of the issue we have is that a “this account does not accept messages from accounts they don't follow” flag can easily get out of sync. Furthermore, there are various complex UX and technical issues due to the different ways a Private Message can be authored. The same can be said about rejecting a message.

**Comment by ClearlyClaire** [comment]
To summarize: we are aware the feature still has shortcomings, and we do plan to work on them before release.

We are reluctant to (but not completely opposed to) re-introducing a setting to completely drop private messages from people you don't follow, because that often results in good-faith desirable private messages being dropped with neither party knowing it happened. As I said in the previous post, signaling that information is something that we have been considering but this is more tricky than one might think.

Separately, we are aware that the filtered notifications banner can take a lot of space (especially in the advanced interface with narrow columns) and put undue emphasis on filtered notifications. We are also exploring that (one change we made recently is for the notifications banner to scroll in the advanced interface, which was not initially the case ; another thing we are looking into is https://github.com/mastodon/mastodon/issues/29723#issuecomment-2259152761)

### Workaround

While we are working on improving the feature, you can restore the previous behavior by changing the settings to their default, and entirely ignore filtered notifications altogether, for instance using some user styles (with something like [Stylus](https://add0n.com/stylus.html)).

![image](https://github.com/user-attachments/assets/e13610b7-06a6-493f-9bec-afe7dcc48433)

Custom CSS to hide the filtered notification banner:
```css
.filtered-notifications-banner {
  display: none;
}
```

(We are aware that this is nothing more than a temporary workaround, that is not satisfactory because it prevents you from enjoying the new feature, and requires you to use additional software)

**Comment by Ember-ruby** [comment]
> We are reluctant to (but not completely opposed to) re-introducing a setting to completely drop private messages from people you don't follow, because that often results in good-faith desirable private messages being dropped with neither party knowing it happened. As I said in the previous post, signaling that information is something that we have been considering but this is more tricky than one might think.

could you not 'just' add a *clearly labelled* onboarding option (as others suggested) for complete dropping, and reinstate the preference 

imo the 'issue' was the setting just wasn't labelled clearly enough, not the setting's existence. 
**i fail to see a justifiable reason for removing a safety feature over bettering the documentation.**

as per notifying people that their message was dropped, ideally this would also be a user setting *(or not added)*, as abusive people knowing they're blocked are more likely to circumvent it than those that just get no response

**Comment by ClearlyClaire** [comment]
> as per notifying people that their message was dropped, ideally this would also be a user setting _(or not added)_, as abusive people knowing they're blocked are more likely to circumvent it than those that just get no response

This is not about blocks. Ideally, this would not be a notification that you've been (personally or otherwise) ignored, but building the UI such that it doesn't offer sending a Private Mention to the account, and adds a warning if you try to do so in another way. Unfortunately, this is a bit more complex than that, see https://github.com/mastodon/mastodon/issues/29722#issuecomment-2259977603

**Comment by sneakers-the-rat** [comment]
understood that the notification ui would be relatively complicated, but since this feature is already live on mastodon.social, to me it seems like restoring the drop-without-notification behavior (which can be done additively! alongside the new filtering system at relatively low complexity) could happen before that's finished?

**Comment by dougfinnie** [comment]
"We are aware", "We prefer", "We are reluctant", "One of the issue we have", "(missed DMs) is a real problem"

"because that often results in good-faith desirable private messages being dropped with neither party knowing it happened"

I just can't weigh up the consequences of a missed DM with the harm this has the potential to deliver.

**Comment by renchap** [comment]
> I just can't weigh up the consequences of a missed DM with the harm this has the potential to deliver.

We are not comparing those, not saying that one is more important to the other, simply that those 2 should be solved. Yes, this feature in its current design is problematic. Yes, we did not think about this when implementing it. Yes, the points raised above have been heard. Yes, we are working on trying to solve them. But we also want to solve the other adjacent problems that we stated above. Both are not incompatible, and we are brainstorming on how to properly solve them.

**Comment by Ember-ruby** [comment]
a good first step would be to allow people to be able to not see unsolicited private mentions again, in any way.

perfection *can come later* (4.3 is still in alpha after-all). people have an immediate need of not seeing these messages.

**Comment by renchap** [comment]
> a good first step would be to allow people to be able to not see unsolicited private mentions again, in any way.
> 
> perfection _can come later_ (4.3 is still in alpha after-all). people have an immediate need of not seeing these messages.

As said above, we are working on this. Hence the proposal I asked feedback about above, and got none. Fixing the issues with filtered notifications is our last item before the release of the first 4.3 beta version.

**Comment by sneakers-the-rat** [comment]
>  Hence the proposal I asked feedback about above, and got none.

i think we are all here in this thread providing feedback about this proposal (i am reading what you mean by this as the OP and the two linked issues from it) and the problem it is describing, we're trying to figure out what's going on and how to help!

fwiw I tried to give specific feedback as well as a demonstration implementation https://github.com/mastodon/mastodon/issues/29723#issuecomment-2259859991 and would be happy to get that up to y'alls standards or help with the effort. we can practice sharing the load so it isn't all on small core dev team which has a lot on its plate. if we agree on it needing to be done, let's do it.

**Comment by Ember-ruby** [comment]
> As said above, we are working on this. Hence the proposal I asked feedback about above, and got none. Fixing the issues with filtered notifications is our last item before the release of the first 4.3 beta version.

i take it that this is the proposal?

>We are also considering adding:
>
>    - a "block user" button near the "dismiss" and "accept" buttons (but less proeminent to avoid mistakes)
>    - maybe 2 "accept all" and "dismiss all" buttons in the accounts list
>
>Would this solve the issue mentioned here?

a quick block button and accept/deny all *does not solve the issue.* it still adds needless work for users who *do not* want to see these messages at all.

why should someone have to clean out their "unsolicited notifications inbox", instead of being able to *remove* said inbox entirely?

**Comment by renchap** [comment]
This is part of the changes we are working on, but the core of it was the screenshots above, which introduce a way to not see the banner anymore, allowing you to never care about those filtered notifications, like if they were dropped, while having a way to get them back if you want to at some point.

An evolution of this can been seen in this PR: https://github.com/mastodon/mastodon/pull/31250
The design is not yet 100% final and we will change a few other things, but we believe this addresses the needs of those who want to completely ignore any notifications that matches their filters (and were previously silently dropped)

**Comment by dougfinnie** [comment]
> Hence the proposal I asked feedback about above, and got none.

Is that true? I read plenty of feedback above, but nobody in this thread agreed.

**Comment by jfietkau** [comment]
> And the PR you refer to, by it's own description, "minimizes" the notification banner, it does not remove it as the feedback in this topic requests, unless I'm misunderstanding the commit messages.

It turns it into a little icon, which in terms of attention seems as good as removing it, assuming the icon is stateless.

By that I mean, in the mock-up the icon has an unread indicator, which IMO it should not have – all it needs to be is a way to access filtered out notifications when specifically needed, and to keep them 100% invisible outside of those times. If that's guaranteed then it seems fine to me, since it would solve the issue with filtered notifications taking up attention.

The only people I can think of who this proposal would not serve, is people who don't want to ever have access to their filtered notifications because they would be checking them compulsively. This group would need a way to filter and actually _delete_ unwanted notifications, as opposed to just hiding them. Should Mastodon ensure that this is possible, and if yes, how should that be weighed against the goal of reducing the number of wanted but inadvertantly deleted incoming messages? Personally I don't know, but If I'm understanding the context correctly, this is the discussion that needs to be had to actually move the proposed solution forward.

**Comment by jonpincus** [comment]
Does it make sense to pull this feature from the 4.3 release and revert back to the 4.2 behavior?  A  testing highlighted a significant bug; fixing it isn't straightforward, and there's an underlying ActivityPub complexity that Claire linked to.  

Even before that, my impression is that grouped notifications were already the blocker for this release.  The May Trunks and Tidbits update said grouped notifications were the last feature update that was needed before beta, the June update said that grouped notifications were one of the last two features before beta, the July update said noted that finishing the front end work for grouped notifications was a lot of work. 

Of course, it's valuable functionality if it's done well, so I can also see arguments for trying to fit it in -- you know more about the development constraints than I do. Still, if you defer it, that would free up some of your time to finish up the other stuff that's needed to get the beta and then release out ... so possibly worth considering.

**Comment by mcclure** [comment]
> We introduced filtered notifications to avoid having posts disappear into the void without users having any way to know about them. This is a real problem that many people were facing and that we wanted to fix.

So I agree this is a real problem and one I personally have been (loudly! sorry about that!) complaining about for some time. However, I think there is a big and important difference between "Mastodon is dropping messages" (because users have no way to control their DM intake other than to drop them) and "This user is dropping messages" (because that user decided that's what they want to do). If they don't want to talk to me they don't want to talk to me.

(And if a user *doesn't want the cognitive load* of having to review a bunch of half-hidden notifications, they will just stop using the site rather than be nagged all the time about filtered notifications they don't care about.)

> We understand that this is introducing a regression if you want to not have to review those. But we still want you to have the ability to look into them, for example if you were expecting a reply that has been hidden.
> 
> To solve this, we are considering allowing the user to dismiss the filtered notification banner, which will be replaced by a far less visible (and not in-your-face) button or a menu. Here is a mock up on the web client: ![image](https://private-user-images.githubusercontent.com/42070/353605883-63549468-7064-4e00-b799-3e293964c93b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NDE4NTYsIm5iZiI6MTcyMjY0MTU1NiwicGF0aCI6Ii80MjA3MC8zNTM2MDU4ODMtNjM1NDk0NjgtNzA2NC00ZTAwLWI3OTktM2UyOTM5NjRjOTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDIzMzIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMTYzZDBkMWM2ZjMyYjJjMTczOTYwZjk3OGRmMWEyOWY2NjVmMzIwODgyMzg1ZDE4ZTUyMzU3ZjllODljYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ebwJi-IBD97ZuW6hLyYs5btZ4jneE-mhYvp62w62l-c)
> 

In my opinion, this addition is of no value. It is in a worst-case "sweet spot" where it is prominent enough to be irritating and add visual noise, but vague enough many people who might *want* to use the filtered-notifications feature will not realize it's there (even if they pressed a button to put it there).

I think the best solution is
* Include a preference somewhere, off by default, to simply drop the filtered notifications
* Make the "you have filtered notifications" box less obtrusive, so people will not feel compelled to drop filtered notifications unless they're coping with actual harassment. Things I would do toward this end:
    * Make the "you have filtered notifications" box scroll with the column [**EDIT**: Testing just now I discovered you did this! Good fix!]
    * If you have 12 notifications from a person and 2 are mentions, do not show a badge saying you have "12 mentions". That is panic inducing to get out of the blue. Just have the number be "2". You don't show ANYTHING if the user has only boosted/faved, so why list those in the number. [**EDIT**: I see you removed "mentions" from the side pane in the mockup above, but in testing, the highlighted number is still total notifications. I suggest making it number of notifications.]

However…

I also have a "compromise proposal"? I think this is halfway between the "just blackhole it" proposal and the "minimal" notification icon in the screenshot above.

Let's say your concern is, specifically, **person A DMs person B, the DM gets swallowed, person B comes to you** (i.e., to the mastodon.social support channel) **and says "what did you do with my DMs, where do I find it :("**.  My proposal fixes that problem specifically:

- Add a checkbox in the preferences saying "Show notification requests in notifications pane". Have it default to checked.
- Change "Follow Requests" in the main ⋯ menu to "Contact Requests". If the "Notification requests in notifications pane" is checked, the notification requests are shown in "Contact Requests" rather than in the dedicated pane, *along with* the follow requests. A very rough mockup of how this could look: 

![image](https://github.com/user-attachments/assets/4fd72fbc-94ba-4c20-9941-5ac35a25f880)

Advantages of this solution:

- If the user goes "I turned off notification requests on purpose but now I need to see a DM that's missing?" you have a specific place you can send them.
- Far less obtrusive than the notifications-pane banner; far more discoverable than the "minimized" icon
- (Critical) Putting notify requests in the follow requests pane instead of the notifications pane, means it does not *interrupt* users while they are trying to do something else. They see it only when they're ready to see it.

Disadvantages of this solution:

- Maybe annoying for frontend to implement, notification requests must now appear in two disparate places
- Notification requests will possibly pile up for a long time. However, you can alleviate this with a "Dismiss all" button in the notification requests section. (If the user checks the checkbox to move the requested notifications out of their view AND intentionally clicks a button to delete all requests, they CANNOT get upset at you the messages are gone. They literally asked for it.)
- "Contact requests" less clear than "Follow requests"

(The reason I do not suggest putting the Notification Requests as a separate item in the ⋯ menu after "Follow Requests" is that menu is already PRETTY long.)

I would, personally, not select EITHER my proposal, OR your "minified" icon proposal, OR a "blackhole" for filtered notifications. I want and like the new notification requests pane in its current UI and it's the UI I would choose if there are options. My concern is for the users who have said that the notification requests feature is bad for them and their use case, because what I understand those users to be saying is they really do just want the filtered DMs/notifications to Go Away.

> We still prefer if those are not dropped, but hidden somewhere the user can access if they want to

But don't you see, it doesn't matter what you prefer? It matters what the user prefers

**Comment by ClearlyClaire** [comment]
> And the PR you refer to, by it's own description, "minimizes" the notification banner, it does not remove it as the feedback in this topic requests, unless I'm misunderstanding the commit messages.

Yes. This greatly reduces the attention taken by the filtered notifications and makes them much easier to ignore. It does not, however, remove them outright, nor as a whole, nor for specific filter types. We are still experimenting, and we might or might not add a controls to completely drop them. We have not marked this issue as solved yet.

> Does it make sense to pull this feature from the 4.3 release and revert back to the 4.2 behavior? A testing highlighted a significant bug; fixing it isn't straightforward, and there's an underlying ActivityPub complexity that Claire linked to.

The “underlying ActivityPub complexity” is sidestepped by this feature and present in full in the previous behavior. The filtered notifications feature attempted to fix two things:
- sidestep the issue you are referencing (good-faith sender not being aware that their message will be ignored without the recipient being aware)
- provide more granular controls about unwanted notifications

(There are also other things we are interested in but are for much later, like e.g. allowing trusted people to review your filtered notifications for you)

> Even before that, my impression is that grouped notifications were already the blocker for this release. The May Trunks and Tidbits update said grouped notifications were the last feature update that was needed before beta, the June update said that grouped notifications were one of the last two features before beta, the July update said noted that finishing the front end work for grouped notifications was a lot of work.
> 
> Of course, it's valuable functionality if it's done well, so I can also see arguments for trying to fit it in -- you know more about the development constraints than I do. Still, if you defer it, that would free up some of your time to finish up the other stuff that's needed to get the beta and then release out ... so possibly worth considering.

I am not sure what you mean, this is not directly related to grouped notifications, which are mostly done now.

> Include a preference somewhere, off by default, to simply drop the filtered notifications

If we end up adding an ability to drop filtered notifications, we probably will do that per-filter type as proposed by @sneakers-the-rat in https://github.com/glitch-soc/mastodon/pull/2799

> * If you have 12 notifications from a person and 2 are mentions, do not show a badge saying you have "12 mentions". That is panic inducing to get out of the blue. Just have the number be "2". You don't show ANYTHING if the user has only boosted/faved, so why list those in the number. [**EDIT**: I see you removed the word "mentions" from the side pane in the mockup above, and I see this is on the live site, but in testing, the highlighted number is still total notifications. I suggest making it number of notifications.]

The current design (not yet live on mastodon.social) now omits the number, the only shown number is “From N people you might know”:
![image](https://github.com/user-attachments/assets/c167b1c0-87f1-42a1-b2fc-5616103f2900)

**Comment by jonpincus** [comment]
> I am not sure what you mean, this is not directly related to grouped notifications, which are mostly done now.

Oops, my bad, I was confused and thought the features were related.

**Comment by ClearlyClaire** [comment]
> The current design (not yet live on mastodon.social) now omits the number, the only shown number is “From N people you might know”

This is now live on both mastodon.online and mastodon.social.

As I said earlier, we are not done with filtered notifications, we have other changes planned (make it easier to report, mute and block from the list of notification requests, as well as make it possible to dismiss and accept such requests in bulk) and are considering other changes as well. We are nonetheless interested in your feedback of the current version.

**Comment by ClearlyClaire** [comment]
Hi! I wanted to keep you updated with the changes we recently made and those that are still planned.

First, as I said previously, we worked on de-emphasizing the notification banner, with an option to further de-emphasize it (https://github.com/mastodon/mastodon/pull/31250). This has been deployed on mastodon.online and mastodon.social at the beginning of the week.

We identified the notification count as a source of confusion, as some people may assume those are all mentions, which was not the case. As a result, going forward, this number will be about mentions exclusively: https://github.com/mastodon/mastodon/pull/31322

Furthermore, we have noticed an oversight when dismissing notification requests: indeed, if someone mentions you again after you dismissed their previous notification request, the list and count will include everything that was previously filtered, contributing to the confusion. Going forward, dismissing a notification request will delete the filtered notifications (but not the underlying activities): https://github.com/mastodon/mastodon/pull/31329

Those two changes should greatly reduce the perceived amount of filtered notifications, and they will be deployed to mastodon.online and mastodon.social tomorrow.

We have the following changes planned:
- add the ability to quickly mute, block or report an account from the list of notification requests (see https://github.com/mastodon/mastodon/pull/31309)
- add the ability to accept or reject notification requests in bulk
- mention that limited accounts are filtered (see https://github.com/mastodon/mastodon/pull/31324)
- better communicating why a specific notification request was made (e.g. was it an unsolicited private mention? a new user? a silenced user?)
- **extend filters with the ability to outright drop notifications**

**Comment by sneakers-the-rat** [comment]
Thanks for the updates, if you make a help wanted issue for the dropping behavior id be happy to help write that. Appreciate your being responsive to this.

**Comment by jmking-iftas** [comment]
This looks like a significant amount of work and thought, and I'm sure many in this thread - like me - are very grateful. Thank you for being so responsive to this thread and the related conversations.
