### ISSUE TITLE
right-click in browser to open post in new tab

### ISSUE THREAD

**Issue by rzeta0** [mastodon/mastodon#29835]
### Pitch

Enable right-click in browser to open post in new tab.

### Motivation

It is useful to be able to scroll down the web page and select several posts to read further, including their replies.

This is made much easier if we can right-click and "open in new tab". This was possible with the Twitter web interface.

The current mastodon web interface doesn't allow this, and it means clicking to a post, and then returning - which means the view of posts often changes due to the updated timeline.

This request should not cause any regressions. I believe it is an oversight and not intentionally disallowed. I think right-clicking a profile name/icon on a post does allow open in new tab.

**Comment by nclm** [comment]
For now, you can middle-click the timestamp in the upper-right corner of a post to open it in a new tab, or right-click and select "open in new tab" the timestamp as well. But indeed, not the entire post itself. I think this is because it’s not actually a link, but a scripted event.

**Comment by Gargron** [comment]
I don't think the post area can be a link element, since it contains many link elements within itself. Indeed, the timestamp is the traditional place to right click.

**Comment by rzeta0** [comment]
> I don't think the post area can be a link element, since it contains many link elements within itself. Indeed, the timestamp is the traditional place to right click.

I wonder how Twitter does it?

I'm no html expert but I suspect the links are link, and the non-links are the post link. maybe something like ...

```
<a heref="pos123">text text text</a>
<a href="actual_link">link</a>
<a href="pos123">more text more text more text</a>
```

**Comment by rzeta0** [comment]
any updates on this?

**Comment by disabledautomatic** [comment]
Im not involved with any dev work here so this is not really my place to complain, but i have to say this is a major issue. 

Due to the way mastodon handles the feed/timeline it is almost unusable when you dont have the ability to open a post without losing your position in the timeline. Clicking the little timestamp in the top right is not a solution, barely even a workaround and new users will most like not even find this workaround before being annoyed enough to leave the site.

The time shift, when jumping back to the feed after left clicking a post, only becomes larger with increasing post rate so if there is any intention to substantially grow mastodon beyond its current userbase, this should be a high priority.

I am perplexed that such a vital core functionality of a feed based website has not been implemented yet.

The post header already seems to receive middle click events, because doing so highlights the post. Why exactly wouldnt this just open the post in a new tab like on virtually every other microblog website on the internet?

**Comment by rzeta0** [comment]
@disabledautomatic I agree 100%

I think mastodon is a young project lead primarily by technical people who are fantastic at technical development but less skilled at understanding user experience.

But that' just an educated guess based on my interactions and what I observe about the project.

**Comment by nclm** [comment]
On Bluesky and on Threads, it is possible to middle click the entire post to open it in a new tab, not just the timestamp (but no right click link menu as those are not actual links either). So at least that could be a first step Mastodon could implement?

**Comment by antimundo** [comment]
I agree, middle click should open the post in new tab, and right click should have an option to open the post in a new tab:

If you left click a post, it will open the link to that post. Making you assume that you can also right click or middle click it to open the post in a new tab... But for some reason you can't do that on Mastodon...

I use the middle click (mouse wheel click) to open things in a new tab on every website, it works on social media too: It works on Twitter, it works on Reddit, it works on Bluesky, it works everywhere, but not on Mastodon, and that feels really weird.

Having this open in a new tab option would be really nice.

**Comment by sersorrel** [comment]
The workaround of "middle-click the timestamp" doesn't seem to work on the "Mastodon Modern" theme – the timestamp can't be interacted with at all, for some reason.

**Comment by rkingett** [comment]
Twitter does it via the same timestamp method if I am not mistaken. I've always had to click on the timestamp for a post and open it in a new tab.
