### ISSUE TITLE
Curly braces in link preview title shown as HTML entities

### ISSUE THREAD

**Issue by tomasandrle** [mastodon/mastodon#30161]
### Steps to reproduce the problem

1. Post a link to [an article](https://hackingcpp.com/cpp/libs/fmt.html) which has curly braces in title
2. 
3.
...

### Expected behaviour

See article title with curly braces in link preview

### Actual behaviour

Curly braces in article title are shown as HTML entities

### Detailed description

Expected:

```{fmt} Formatting & Printing Library```

Actual:

```&lcub;fmt&rcub; Formatting & Printing Library```

### Mastodon instance

https://mastodon.gamedev.place

### Mastodon version

4.2.8

### Browser name and version

Safari 17.3.1

### Operating system

macOS 14.3.1

### Technical details

![Screenshot 2024-05-03 at 10 56 52](https://github.com/mastodon/mastodon/assets/42672549/0d12c859-23ff-43a0-8ca2-bd2eca94bfab)

**Comment by timothyjrogers** [comment]
Reproduced this on latest `main` code in addition to 4.2.8. The cause of this issue is the use of the default decoding flavor from [HTMLEntitites](https://github.com/threedaymonk/htmlentities/tree/f4d759e2bdd30afaa209d8bf43d1b67f91accc7a) here: https://github.com/mastodon/mastodon/blob/main/app/lib/link_details_extractor.rb#L285 .

The curly bracket entity codes (among others) are not included in the XHTML1 or HTML4 specs, only the entity numbers for them are. Thus a site with `&#123;` (one of two entity _numbers_ for left curly bracket) renders appropriately but `&lcub;` does not.

HTMLEntities supports an expanded set of entity names from a variety of public domain sources, as detailed [here](https://github.com/threedaymonk/htmlentities/blob/f4d759e2bdd30afaa209d8bf43d1b67f91accc7a/lib/htmlentities/mappings/xhtml1.rb). Simply instantiating the HTMLEntities decoder with `:expanded` instead of the default flavor should resolve this issue for any entities whose names are not in the XHTML1 or HTML4 specs.

Do note that, because link details are extracted and stored on post, that this will not retroactively fix the display for already posted links. If that same link is then posted again it will fix for all cards since the details are stored based on the link name and a fresh post would trigger a new extraction.
