### ISSUE TITLE
"If you trust this link, click it to continue." breaks embeds, adds friction

### ISSUE THREAD

**Issue by jernejs** [mastodon/mastodon#30327]
### Steps to reproduce the problem

1. Copy a link to post that's on another instance (eg. https://mastodon.social/@vjousse@mamot.fr/112446650777348688 )
2. Paste the link in Discord

### Expected behaviour

The post embeds in Discord, clicking the link opens the post

### Actual behaviour

Post does not embed, clicking the link shows a completely useless warning

### Detailed description

Clicking the above link will show the following page:
![image](https://github.com/mastodon/mastodon/assets/1800143/224f3bc5-7a0b-4361-ba38-6137605713d1)

I don't see the point of this warning at all – it's only shown if you're not logged in in the directly linked instance, and I've only ever seen the warning shown when redirecting to other Fediverse instances. The warning probably also breaks embeds on other services, which used to work in the past.

### Mastodon instance

mastodon.social, infosec.exchange, others.

### Mastodon version

v4.3.0-nightly.2024-05-13, v4.3.0-alpha.3+glitch

### Browser name and version

Multiple browsers (Vivaldi 6.7.3329.19, Firefox 126.0)

### Operating system

Windows 11 22631.3593

**Comment by ThisIsMissEm** [comment]
These "roadblocks" are an important aspect of trust & safety, and were recently added to ensure users weren't phished or otherwise manipulated by an open redirect, which was previously the case.

You can read more about the history here: https://github.com/mastodon/mastodon/pull/27792

An improvement we could add is a HTTP Link rel=canonical to these redirects that automated software can parse in a standardised way to discover the canonical link instead of the redirect & then embed that link instead of the instance's cached URI for that post
