### ISSUE TITLE
Pre-emptive account level blocking (e.g. threads) 

### ISSUE THREAD

**Issue by cmeesters** [mastodon/mastodon#30351]
### Pitch

Hi,

I don't know whether this has been discussed already - could not find anything related.

We at FediScience.org do not want to connect/federate with Threads globally, but allow users to opt-in. We can accomplish this by changing the database and profile code. Yet, we want to refrain from that path, because any API level change might break our setup.

Is any feature supporting this feature (a per-user opt-in to Threads) in development?

Cheers,
Christian

### Motivation

Smaller instances might want to allow their users an opt-in to Threads (default: blocked), to avoid being overwhelmed by traffic.

Instances for special interest groups might want the same: default blocking of Threads but optional per-user connection.

**Comment by renchap** [comment]
Server-level blocks are absolute by design, interactions are blocked at the protocol level. So once there is a server-level block, there is no technical way for a user to be opt-in, even with code changes.

What you could want to do is have a default block set up for every user, that they can remove if they want, but there is nothing in the code for that, and it would have many issues to solve (notifying users when the default block is added, UI to be able to view them and disable them, handling of special cases…).

There are no plans to develop such a feature.

**Comment by cmeesters** [comment]
Hi,

Thanks for the swift feedback! Whilst I occupy myself with a number of FOSS projects and would like to see a PR on this, I cannot do it (lack of time and Ruby knowledge).

Cheers
Christian
