### ISSUE TITLE
LinkCrawlWorker Encoding::UndefinedConversionError

### ISSUE THREAD

**Issue by vmstan** [mastodon/mastodon#30792]
### Steps to reproduce the problem

Starting seeing a lot of these appear recently, connected to links posted by https://mastodon.social/@ukraineforum

`"\xC3" from ASCII-8BIT to UTF-8 on https://ukraineforum.de/unterstaatssekret%C3%A4r-au%C3%9Fenministerium-gespr%C3%A4chen-kyjiw-eingetroffen-t160676.html?mtm_source=mastodon&mtm_medium=social&mtm_campaign=ma`

Encoding fixes just added in #30780 did not cover these.

### Expected behaviour

No encoding errors

### Actual behaviour

Errors

### Detailed description

![CleanShot 2024-06-21 at 08 05 33@2x](https://github.com/mastodon/mastodon/assets/3002053/19bdeb63-4587-4d0f-b62b-b50a8eed5c2b)

### Mastodon instance

vmst.io

### Mastodon version

v4.3.0-alpha.4

### Technical details

- Mastodon	4.3.0-alpha.4+pr-30780
- Ruby	3.3.3p89
- PostgreSQL	16.3
- Redis	7.2.4
- OpenSearch	2.14.0
- libvips	8.15.2
- FFmpeg	7.0.1

**Comment by vmstan** [comment]
- Mastodon	4.3.0-alpha.4+pr-30780
- Ruby	3.3.3p89
- PostgreSQL	16.3
- Redis	7.2.4
- OpenSearch	2.14.0
- libvips	8.15.2
- FFmpeg	7.0.1

**Comment by oneiros** [comment]
@vmstan Would you have (the first couple of lines of) a stack trace for this?

**Comment by vmstan** [comment]
I'll see what I can find.

**Comment by oneiros** [comment]
Never mind, I was able to reproduce.

This site redirects when fetching the URL. The final URL in the `Location` http header is UTF-8 encoded and regularly includes german umlauts. This trips up the `http` gem, as headers are supposed to be ASCII only.

I do not think this a bug that can be easily fixed by us or in the `http` gem. Our only course of action is probably catching the exception and not generate the link preview in these cases.

**Comment by oneiros** [comment]
> Our only course of action is probably catching the exception and not generate the link preview in these cases.

This is what the PR above does. This should get rid of this error even though it is more of a workaround.

I am closing this for now. If someone comes up with a way to actually fix this, feel free to reopen or ping me.
