### ISSUE TITLE
Group Notifications experimental feature: CWs are ignored

### ISSUE THREAD

**Issue by micr0-dev** [mastodon/mastodon#31216]
### Steps to reproduce the problem

1. turn on group notifications
2. post something with a CW
3. someone interacts with it
4. post shows up without CW on your notifications
        

### Expected behaviour

the CW should show up instead of the content

### Actual behaviour

the content is displayed, which could be sensitive

### Mastodon instance

wetdry.world

### Mastodon version

v4.3.0-alpha.5+chuckya

### Browser name and version

Firefox 128.0.2 (64-bit)

### Operating system

EndeavourOS x86_64, Linux 6.10.0-arch1-2

### Technical details

![image](https://github.com/user-attachments/assets/4bc8d508-ed46-4a3a-8cfb-0177b2a51c0a)
![image](https://github.com/user-attachments/assets/d540132a-f8be-4666-90fd-791e6ea48141)

**Comment by cyrneko** [comment]
> v4.3.0-alpha.5+chuckya

this is downstream of [this commit](https://github.com/mastodon/mastodon/commit/1229d2907a4a7ee09ee42cd24043d74561507e0a) currently.

Neither of us currently have an account on mastodon.social or mastodon.online to confirm that this also happens upstream, but it makes sense to assume so because no changes were made to the feature downstream.

I can also reproduce this issue on LibreWolf 128.0-2 on Fedora Silverblue `40.20240730.0`.

**Comment by ClearlyClaire** [comment]
This is indeed a shortcoming of the current design. The upshot is that only your own posts are ever shown like this, but we definitely should have better design around that.
