### ISSUE TITLE
[Accessibility] Radio buttons in mute dialog only have a border color change to indicate the one that is selected

### ISSUE THREAD

**Issue by juliemoynat** [mastodon/mastodon#32427]
### Steps to reproduce the problem

1. Display the mute options ;
2. See that there is only a border for the selected radio.

### Expected behaviour

There should have a plain circle inside the bordered circle.

### Actual behaviour

There is no plain circle inside.

![Screenshot of the bug explained before](https://github.com/user-attachments/assets/a61455a5-d38d-4eb2-8e65-3dee2fffe3bd)

### Detailed description

I saw this issue https://github.com/mastodon/mastodon/issues/31996 where is plain circle is not correctly rendered so there was one before and it disappears. That's not normal.

According to accessibility rules, we can't rely on color only to indicate a state because visually impaired people or colorblind people may not be able to know which radio is selected.

### Mastodon instance

eldritch.cafe

### Mastodon version

v4.3.0-beta.1+glitch

### Browser name and version

Firefox 131.0.2

### Operating system

Windows 11

**Comment by renchap** [comment]
This has been fixed by https://github.com/mastodon/mastodon/pull/31723 (and included in 4.3.0).

eldritch.cafe seems to be running on a version that does not contain this fix. It should be fixed when they update.

From `main`:

<img width="595" alt="image" src="https://github.com/user-attachments/assets/42aaad2d-4b2a-4c2b-90ec-9b7eaaf2fa73">
