### ISSUE TITLE
Update .env.production.sample with latest v4.3 release configs

### ISSUE THREAD

**Issue by melroy89** [mastodon/mastodon#32509]
### Steps to reproduce the problem

1. Go to: https://github.com/mastodon/mastodon/blob/main/.env.production.sample
2. And see the missing ACTIVE_RECORD_ENCRYPTION_*.. keys

### Expected behaviour

I would expect to see all avaiaible settings in the `.env.production.sample` file

### Actual behaviour

I'm missing the ACTIVE_RECORD_ENCRYPTION_* fields

### Detailed description

```ini
ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY=
ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT=
ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY=
```

### Mastodon version

v4.3.0

**Comment by ThisIsMissEm** [comment]
@mjankowski I know we discussed this on discord

**Comment by mjankowski** [comment]
I think it's fine to add these to the sample, as long as:

- Our initializer check still fails/raises when they are not set or set to blank values
- We do not supply any actual sample values here, because you don't want to accidentally put a secret in this repo that people will copy/paste into their own envs w/out realizing they should generate their own

**Comment by melroy89** [comment]
ah yes, for sure comment out these fields. So it's more like a placeholder.

**Comment by melroy89** [comment]
Pr is merged. Thanks!
