### ISSUE TITLE
Can no longer press Ctrl+Z/Cmd+Z to undo emptying of toot entry box after submitting a toot

### ISSUE THREAD

**Issue by andlabs** [mastodon/mastodon#3369]
Sometimes I post a toot too early, so I delete the toot, focus on the text area, and press Cmd+Z to get the toot text back since it's still in the undo history. However, after hard-loading mastodon.social today, I can't seem to do that anymore: Cmd+Z blanks out the box and wipes out the placeholder text, but no longer restores the old text.

Is this a Mastodon issue or a Firefox issue? I don't see anything in the commit log to indicate that would be a problem... Current Firefox build is Firefox Nightly 55.0a1 (2017-05-27) (64-bit) on OS X 10.11.

Thanks.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nolanlawson** [comment]
The issue may be that it's re-rendering the component. I don't think it's a Firefox issue because I can also reproduce in Chrome and Safari.

Note: you don't need to delete the toot to reproduce. Steps to repro are just

1. Write a toot
2. Press "toot"
3. Focus on text area
4. Press Ctrl-Z/Cmd-Z
5. Text should reappear, but instead it's blank

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
