### ISSUE TITLE
Support RFC 4685 "replies" relation in Atom feed

### ISSUE THREAD

**Issue by lokedhs** [mastodon/mastodon#3499]
When loading the atom feed for a given status, the "in-reply-to" field is set to the URL of the status to which this status is a reply. This allows an application to follow the chain of messages backwards to the first status that created the thread.

In addition to "in-reply-to", the "replied" field is specified by RFC 4685. This field is supposed to contain a link to a document that contains the known replies to this message. Currently this field is not implemented in Mastodon, which makes it impossible to follow the thread forwards in time.

RFC 4685 can be found here: https://www.ietf.org/rfc/rfc4685.txt, which contains the following example of a "replies" field:

```
   <feed xmlns="http://www.w3.org/2005/Atom"
         xmlns:thr="http://purl.org/syndication/thread/1.0">
     <id>http://www.example.org/myfeed</id>
     <title>My Example Feed</title>
     <updated>2005-07-28T12:00:00Z</updated>
     <link href="http://www.example.org/myfeed" />
     <author><name>James</name></author>
     <entry>
       <id>tag:entries.com,2005:1</id>
       <title>My original entry</title>
       <updated>2006-03-01T12:12:12Z</updated>
       <link href="http://www.example.org/entries/1" />
       <link rel="replies"
             type="application/atom+xml"
             href="http://www.example.org/mycommentsfeed.xml"
             thr:count="10" thr:updated="2005-07-28T12:10:00Z" />
       <summary>This is my original entry</summary>
     </entry>
   </feed>
```

**Comment by Gargron** [comment]
We could add a feed like that without big problems.

>which makes it impossible to follow the thread forwards in time

Are you also suggesting Mastodon to use that feature? Because if not, even if we add it, no existing software will use that.

**Comment by lokedhs** [comment]
My request is just for Mastodon to provide this data for applications that might find it useful. In my particular case, I am working on an application that needs it in order to resolve a tree of activities on a given message. So there would definitely be at least one application that would use it the second it becomes implemented.

**Comment by sandhawke** [comment]
I'm also working on an application that needs it.

But yes, Mastodon should use this.   Without it, currently, when I look at a toot created on another instance, I can't see some of its replies.   It may look like there are no replies, when there are many.  This might be desirable sometimes, so it could be a setting, but mostly it just seems like a bug.   If I click on the time to see the toot in html (instead of in the ui) then I see the missing replies.  This is much more noticeable on small instances.

**Comment by Gargron** [comment]
When thinking about implementing this I came across an open ended question. Which replies should this endpoint return? All known ones (whole conversation tree, starting with the requested status) or only direct level-one replies? The conversation tree could be incomplete, since origin may not get replies-to-replies if origin is not also mentioned; level-one replies would at least be guaranteed to be complete.

**Comment by lokedhs** [comment]
The RFC states the following:

```
An Atom link element with a rel attribute value of "replies" may be
used to reference a resource where responses to an entry may be
found.  If the type attribute of the atom:link is omitted, its value
is assumed to be "application/atom+xml".
```

The way I read that is that it should only display the known direct replies to the post. If the client application wants to see all replies, it can issue individual requests to see the deatils of those responses.

There are plenty of reasons one would not want the entire tree anyway. For one, it could be very large, and as you pointed out, it would likely be incomplete.

**Comment by lokedhs** [comment]
Is this something that is still being planned? It would be really useful to have this feature, and as far as I can tell it wouldn't be too difficult to implement.

**Comment by albjeremias** [comment]
this is a very interesting proposal... many times I just get lost in threads.. and I can't find the original toot.. :\

**Comment by trwnh** [comment]
atom feeds have since been deprecated and removed
