### ISSUE TITLE
Add Inline Translations

### ISSUE THREAD

**Issue by coilysiren** [mastodon/mastodon#3783]
It'd be great to have birdsite style inline translations.

Here's a real basic example of what I mean

before:

![image](https://user-images.githubusercontent.com/5768468/27201985-aa08a73c-51d4-11e7-91db-c3591e694c4d.png)

after:

![image](https://user-images.githubusercontent.com/5768468/27202047-df492016-51d4-11e7-852b-7aeb17a0df4c.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Exagone313** [comment]
Are you suggesting of using a translation service, incompatible with decentralization, or to be able to write a toot in multiple languages?

**Comment by Cassolotl** [comment]
@Exagone313 It looks like they're asking for a translation service. Why is that incompatible with decentralisation?

**Comment by Exagone313** [comment]
Because those services are centralized.

**Comment by lynnco** [comment]
I'm looking to integrate with a currently existing translation service, ideally a JS one.

**Comment by Cassolotl** [comment]
Then I am curious to see what project leaders say is possible and/or compatible with Mastodon's aims overall. :)

**Comment by Kimik0** [comment]
I don't really like the idea of all our toots being passed through some for-profit translation service :(

**Comment by nightpool** [comment]
In the past gargron has been uncomfortable with the idea of sending toots to a third-party service for translation, although I don't think it's *that* bad if it's behind a click-through (optionally one that warns users the first time they click on it)

**Comment by lynnco** [comment]
My opinion is that if I'm going to be copying every 3rd toot into google translate*, I would at least prefer if Mastodon gave me an button for that same functionality.

* which is being used as an example, I'm not suggesting mastodon integrate with google translate

**Comment by Kimik0** [comment]
But it's not the user clicking the link whose toot gets sent to a third party, it's someone else.
That's not something that can be prevented of course (click "Toot" and it's out of your control), but the official software encouraging it is another thing.

**Comment by Cassolotl** [comment]
I guess there could be an opt-in "allow my toots to get translated by a centralised third party service" option, if the centralised third party service is the only way? (But it might not be the only way, I don't know.)

**Comment by zcdunn** [comment]
The Mastodon team has pointed out multiple times that mastodon is a public forum. It shouldn't be used if you're concerned about the privacy of what you're saying. So passing the toot through a third-party system, which a lot of users are doing anyway, shouldn't be a problem (assuming the third-party service has  a ToS that is compatible with Mastodon's).

**Comment by ticki** [comment]
Yeah, they're most likely crawled anyway.

And what is the alternative really? That people copy-paste it into the translator? Isn't the end result the same?

One way the privacy could be improved is if the translation is proxied by the instance, such that the translator cannot get the IP address of the user, who is translating.

**Comment by yashha** [comment]
Looks interesting:
http://opennmt.net/

**Comment by gkkulik** [comment]
I know this issue is ages old but Mastodon doesn't actually have to depend on centralised translation services. The University of Alacant has been developing the open source machine translation platform Apertium (https://apertium.org) that can be installed on any server alongside Mastodon. You can easily put the text internally through your Apertium instance.

There's heaps of pairs: English-Spanish, English-Catalan, English-Serbo-Croatian, Spanish-French, Basque-Spanish, Afrikaans-Dutch, Asturian-Spanish, Danish-Swedish, Silesian-Polish and many more. I know of three instances:
https://apertium.org/ - the original one, something broke on their side at the time of writing
https://www.softcatala.org/traductor/ - SoftCatalà's instance
https://silling.org/translator - this one is mine
https://jorgal.uit.no/ - from Saami to Norwegian
https://softaragones.org/traductor - this one covers Aragonese pairs

Note that you can choose which languages you want to support.

Now here's my comment automatically translated to Catalan:

Sé aquest assumpte és edats vell però el mastodont  no de fet ha de dependre traducció centralitzada damunt serveis. La Universitat de Alacant ha estat desenvolupant el programa de traducció automàtica del codi obert Apertium (https://apertium.org) es pot instal·lar allò en qualsevol servidor de costat Mastodont. Fàcilment pots posar el text internament a través del vostre cas d'Apertium.

Hi ha càrregues de parells: anglès-espanyols, anglès-català, anglès-Serbo-croat, espanyol-francès, basc-espanyols, afrikaans-holandès, asturià-espanyols, danès-suecs, silesià-polonès i molts més. Sé de tres casos:
https://apertium.org/ - el primigeni un, alguna cosa va trencar en el seu cantó al temps d'escriure
https://www.softcatala.org/traductor/ - de cas de SoftCatalà
https://silling.org/translator - això un és mina
https://jorgal.uit.no/ - des de Saami a noruec
https://softaragones.org/traductor - això u cobreix parells aragonesos

Nota que pots triar quines llengües vols recolzar.

**Comment by EchedeyLR** [comment]
I would prefer an option to add my post in different languages instead.

Other option would be to, optionally, be able to self-generate these translations with an optional FLOSS software as LibreTranslate.

**Comment by Gargron** [comment]
Added in #19218
