### ISSUE TITLE
Show the list of muted/blocked users/instances by the instance in about/more

### ISSUE THREAD

**Issue by ghost** [mastodon/mastodon#3874]
Currently if an admin mute/block users/instances you can't know if they do write it themselves somewhere.
It would be better for both users and admins if it would be added automatically to a page (about/more is an example). 

This way the admin wouldn't have to manually do it every time.
And users would be able to know who is muted/blocked while using the instance . Or before coming to this instance it would be easier for them to chose to come in or not as they would know who they could reach and by whom could they be reached.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Kimik0** [comment]
Users are blocked or muted because you don't want to hear from them anymore. Listing them would just invite arguments. Plus the list might be pretty long for instances that have been around for a while.

For whole instances it might be useful, although that list too can grow quite long.

**Comment by Dostoi** [comment]
"Users are blocked or muted because you don't want to hear from them anymore."
I can understand that argument when you're an user but it is different when you are an instance because your decision will impact all your users and they deserve to know how you are really handling the instance.
And they have the right to argue with it because it impact their account (or you just specify in the code of conduct that if they disagree they just have to leave) and admin can't just do as they want, they also have an obligation toward their user. It goes both way 

"Plus the list might be pretty long"
It's not an issue if it's put on its own page.
Plus users deserve more transparency to be able to leave the instance if they disagree with the moderation of the instance.

**Comment by gled-rs** [comment]
I favor a list like this. 

At least new users would know what the moderation team has done in the past, and choose more wisely if they still want to join or not the instance.

**Comment by deutrino** [comment]
I'd like to see this but I think it would work best if limited to instance blocks only. User blocks are too granular, not enough consumers of this data would care, and it would invite arguments.

**Comment by deutrino** [comment]
I'm gonna amend my prior comment, having seen some related Discourse(tm) from admins on Mastodon: I think this should be a feature, but instance admins should be able to choose whether or not the list is published.

My perspective is as someone who tries to avoid [way too many options](https://i.imgur.com/4kKbz2Y.png) and as someone who won't use an instance which won't share their instance-level blocklist. I've also read statements from a couple admins of "safe speech" instances who made good points about why they choose not to publish their instance-level blocklist. I believe it would be best for the fediverse as a whole to have this feature, but allow it to be toggled.

**Comment by fsnk** [comment]
I'm 100% in favour of potential users being informed up front of any issues they might have communicating with users other servers.

I think @deutrino's suggestion of being able to toggle this is a good compromise. I wouldn't personally use a server that doesn't make this information available to its users because I wouldn't trust the administration. But likewise, it seems some people wouldn't trust any administration that makes information about federation blocks available to users. It should be possible to accommodate both.

In the case an instance opts in, it should display the block list as it appears in the admin interface, with the server name, block level, and media setting. (I think block lists that include reasons for the block are often used to generate drama, and the why isn't relevant to a potential user, only whether they're really going to be able to talk to their friends, no matter what server they're on.)

If an instance opts out, there should still be some kind of "Federation Status" area; it should be boilerplate stating the instance chooses not to make its block list public. (There's no reason to hide _that_ from a potential user, and this information should be standardized on the display, like user count and number of instances federated with, to help new users make an informed choice.)

**Comment by deutrino** [comment]
It'd be *extra* great to make this available in machine-readable form for instance choosers like instances.social to consume ☺️

**Comment by rugk** [comment]
For users that may be one thing, but please **don't do that for instances**! Really!

You don't want to promote nazi, hate-speech etc. instances by listing them as a block.
They are blocked, because you don't want to promote them/place them there. Thus, listing them would not be useful

**What you can do (alternative):**
* SHA-256 hash them and put them there!

This way, users can check whether an instance is blocked, if they know the instance. But the instance does not get "advertisement" for being blocked.
That said, even that may be optional.

**Comment by melissaboiko** [comment]
Just to make sure, currently there’s no API-level or machine-readable way of getting an instance’s advertised domain blocks?

**Comment by Anthchirp** [comment]
> Just to make sure, currently there’s no API-level or machine-readable way of getting an instance’s advertised domain blocks?

Looks like there is?
https://docs.joinmastodon.org/methods/accounts/domain_blocks/
