### ISSUE TITLE
Twitter Sync: Option to crosspost Toots as Tweets

### ISSUE THREAD

**Issue by heyakyra** [mastodon/mastodon#3888]
The original implementations of GNU Social provided the option to post statuses to other social media apps like Twitter. This would be very powerful to have here. 

This may or may not be useful: https://github.com/halcy/MastodonToTwitter

**Comment by Cassolotl** [comment]
I'd love this! It's currently bodgeable with things like IFTTT, but it's not great. Various ways get confused with various things. Like, sometimes they don't cross-post if you're over the Twitter character limit, or images are not posted to both places. So something actually made for purpose, that uploads images and gifs to both places correctly, etc. would be amazing.

A lot of users (including me) don't have the skills to use halcy's Mastodon to Twitter tool, and I think they said it wasn't going to be maintained any more, so that's not a long-term solution.

I'd ideally like something that would post from Twitter to Mastodon, because the character limit is more strict on Twitter. I guess there would always be limitations (like, threading might not be possible?), but I would still use it.

**Comment by egypturnash** [comment]
So my idea is that the tweet should look about like this:

* As many of the original toot's characters as will fit
* Rudely truncated with "..." if it needs to, don't try to find word boundaries, we want it to be a little passive-aggressively ugly
* A link to the Mastodon status generated by this
* And an image of the toot's text. Maybe it's the mobile version generated by a headless web browser. Maybe it's the result of sticking it into a LaTeX template and turning that into an EPS and rendering that to a GIF. Whatever's the best combination of 'quick to get working' and 'doesn't eat up multiple minutes of CPU time every time someone toots'.

(Alternative text:  'Thread 👇[cr][truncated toot text][Mastodon status link][image attachment]')

**Comment by thekyriarchy** [comment]
A support that format! Would the image attachment add to the character count? No big deal either way

**Comment by Gargron** [comment]
I always wanted this kind of thing to be done by a 3rd-party webapp because I don't want to stick Twitter API code into Mastodon itself.

**Comment by thekyriarchy** [comment]
hmm, how come? even GNU social has that as purist as it was, at least if i remember correctly

**Comment by davidpgil** [comment]
The underlying issue is here is that once you stay exclusively on Mastodon you fall off of all other social networks radar. The desire to crosspost comes from wanting to gain more visibility. I think the way to solve this is through having more social networking style integrations sprinkled all over the web. Such as "Toot This" buttons, sign in to X app with your Mastodon profile, etc. Viva, FOSS!

**Comment by GluedToTheScreen** [comment]
Gargron said: "I always wanted this kind of thing to be done by a 3rd-party webapp because I don't want to stick Twitter API code into Mastodon itself."

Are you picturing a full Mastodon CLIENT that, as one of its features/options, could simultaneously post a toot to Twitter?

**Comment by kemenaran** [comment]
For the record, there are now two easy-to-use tools for cross-posting toots to Twitter:

- [Mastodon Twitter Crossposter](https://crossposter.masto.donte.com.br/): a web app that mirrors a Mastodon feed to a Twitter feed. _No need to setup a personnal web server._
- [BirdSite](https://gitlab.com/pmorinerie/birdsite/blob/master/README.md): a browser extension for cross-posting selected toots to Twitter, right from the Mastodon web app. _Basically fixes this issue, without shoving down a Twitter client into the Mastodon codebase._

**Comment by ThisIsMissEm** [comment]
Related to this, has anyone create a rubygem that adds twitter support to mastodon, inparticular resolving accounts on the twitter domain to twitter accounts and creating them (and optionally oauth connecting them together)

I basically don't want to see `@mistressemelia@twitter.com` in toots, and would rather see a link to a twitter account.

**Comment by ThisIsMissEm** [comment]
Actually, have just managed to hack this together, is there any reason why this sort of diff wouldn't be accepted @Gargron ? https://github.com/tootsuite/mastodon/compare/master...Unobvious-Technology:feature/twitter-linking

**Comment by Cassolotl** [comment]
> I basically don't want to see `@mistressemelia@twitter.com` in toots, and would rather see a link to a twitter account.

@ThisIsMissEm I don't have anything technical/helpful to add but I can point this out: *Link @username@twitter.com to Twitter profile pages #1849*

**Comment by ThisIsMissEm** [comment]
@Cassolotl ah, yeah, you've implemented it roughly the same way. I'm going to take your idea on the `and domain !=` part, as that's clearer. I'm also going to go with just the twitter icon before the username.

**Comment by ThisIsMissEm** [comment]
See the thread here, I changed my mind at Eugen’s prompting: https://github.com/tootsuite/mastodon/pull/7016#issuecomment-378093916

**Comment by roipoussiere** [comment]
A cross-post app for Twitter to Mastodon, Mastodon to Twitter, or even Mastodon to Mastodon and other funky bridges like RSS to Mastodon could be easily done with IFFT or Zapier (see #7352).

**Comment by Cassolotl** [comment]
Now that Twitter will be charging for its API, maybe this feature is a bit doomed? :S

**Comment by trwnh** [comment]
closing this issue for... multiple reasons, not least of which is that twitter won't allow it.
