### ISSUE TITLE
Please restore default PageUp / PageDown behavior

### ISSUE THREAD

**Issue by unarist** [mastodon/mastodon#4449]
On the master, keyboard navigation on timeline has been supported for accessibility (https://github.com/tootsuite/mastodon/pull/4417). It uses PageUp / PageDown key to move focus to previous / next status, according to the recommendation from [WAI-ARIA Authoring Practices](https://www.w3.org/TR/wai-aria-practices-1.1/#feed).

However, this breaks default browser behavior "scroll up / down" of those keys, which I've regularly used.

I don't know how it can be with attention to accessibility, the solution may be...

* Change key binding (e.g. `j` `k` like Twitter and Facebook)
* Make this behavior toggleable
* etc.

**Comment by sorin-davidoi** [comment]
Maybe @yiskah has some input on this? I think you can still use the Up/Down key to scroll through the timelines. Maybe we can use other keys to move focus, like you suggest, and advertise them using ‘aria-controls‘?

**Comment by sorin-davidoi** [comment]
Also just realized that I messed up the key-binding for moving to the first/last toot: they should `Control + End` / `Control + Home`, not `End` and `Home`.

**Comment by Gargron** [comment]
hjkl are quite common navigation shortcuts, on tumblr too

**Comment by sorin-davidoi** [comment]
I will open a PR once we decide - I really want to hear yiskah's take on this before though.

**Comment by yiskah** [comment]
To start, please keep in mind that Tumblr especially is more of an example of what *not* to do in regards to accessibility. None of their buttons on the app are even labeled so it just says "unlabeled button" instead of "like" or "reblog" etc. Just because a website is popular does not mean they're doing accessibility right. Facebook is actually a pretty OK example of a dynamic app that does accessibility well, and they do use hjkl but i think they might also use pg-up/pg-down. PayPal does things OK too in regards to accessibility.

Sorin's idea of using aria-controls to announce whatever system one should use is a good idea. My main concern with hjkl is that these keys, unlike CRTL, Tab, Shift, etc. are in the middle of the keyboard. `j` is easy to find because of the notch (is that standard on every keyboard?) but if you can't see and use voice dictation or a braille writer I'm unsure how familiar QWERTY's layout would be. You also need to make sure you add code to distinguish hitting `j` when typing in compose or search from when it is in a column. That said, if we're talking about sighted dexterity-impaired users, hjkl is a very good set-up since it requires very little movement and it *is* commonly used on other social media sites. 

Keep in mind sometimes these buttons map to some kind of software or device which expects a certain keypress to do something specific. Before you implement into `master` any new system please test it first using a desktop screen-reader and a mobile screen-reader (Apple's VoiceOver on MacOS and iOS are the most commonly used ones, but if that's not available other common ones are Android's TalkBack for mobile, and Microsoft's Narrator or the open-source Orca for Desktop.). Mobile screen readers use gestures like "swipe right to proceed to next element" and it's important that those still work, and it's not like the screen-reader was inputting Page-Down and now it doesn't know how to input `j` to proceed instead. 

Also as a side note... you use page-up and page-down on the Mastodon web interface? Don't those skip forward entire screens? Does it do it for whatever column has focus? I'm not sure how common this use-style is. Making everyone happy is always good but I really want to make sure we don't hamper accessibility because of a less common way of interacting with the site. Like Sorin said, the up/down arrow keys still scroll normally so if it would be easier for you to change your habit rather than expecting all users with disabilities to change theirs that's another option worth considering. We can try finding systems that work for everyone first if this seems important but if A11Y software expects pg-up/pg-down then this might be a situation where the solution is to have users who used pg-up/pg-down switch to using arrow keys rather than changing the code.

Also Sorin you're the best.

**Comment by unarist** [comment]
yiskah, thanks for a explanation!

I was able to use page-up / page-down to scroll timeline on the Mastodon web, by clicking inside of timeline in advance. This only works for focused column, but it's not a problem with single column layout.

Since up/down arrow keys only scrolls a line, and scrolling a page by holding those keys takes a while with a blur which prevent me from reading it, I often use page-up and page-down to scroll a page quickly. Also it helps me who doesn't use a pointing device without wheel / scroll feature.

I have requested this because I thought it might be able to fix like Facebook and Twitter, but I also thought it might not be with attention to a11y. I'm not sure how many people does this too. So I think we can release this as is if fixing this is hard. Then we can consider this again with more feedback.

**Comment by unarist** [comment]
Ah, I found that I can scroll by page-up / page-down by focusing somewhere except status itself. For example, an account header and buttons. This will work as a workaround.

![test](https://user-images.githubusercontent.com/705555/28758432-ad3db57e-75d2-11e7-81c8-8683333b1c82.gif)

**Comment by yiskah** [comment]
Fantastic! In that case I propose we can close this issue! If we wanted to implement hjkl in addition to pg-up/pg-down that would be cool too but it seems the original conflict is solved

**Comment by wakest** [comment]
HJKL would be really nice. I was just searching if this had a issue yet. This hasn't been talked about for ages it seems; sorry for the bump.

**Comment by realityfabric** [comment]
This is partially done:

- H maps to "show/hide"
- J maps to "next post"
- K maps to "previous post"

But instead of L mapping to "like/dislike" it is F which is mapped (as "favorite/unfavorite")

However, when I use a screen reader (Gnome's Orca, specifically) some of the  hotkeys break (such as k and g+n (which is supposed to open the notifications page).

I'm going to open a new issue for those, but I thought I'd mention that HJK (and F) are implemented, since it's been a year and a half since anyone's said anything here.

**Comment by trwnh** [comment]
it's not toggleable, but has been switched to j/k for single status scroll and pgup/pgdn for page-of-statuses scroll
