### ISSUE TITLE
Feature proposition : Private hastags

### ISSUE THREAD

**Issue by N07070** [mastodon/mastodon#4513]
I was thinking about a great addition to mastodon; which would make it possible to have "private conversations" in mastodon.

Let's say I create the hastag #_cat ( the underscore shows that it's a private hastag ).
Now, anyone one can toot to that hastag, and if the original creator replies, then a conversation is created. The users can toot to the hastag, and be part of a conversation in a from of a thread. 

If they is no reply by the original creator, then the user cannot see what was tooted to this hastag. 

What do you think about this ideal ? It would make it easy to organise for a group for example, without needing more apps/tools/etc...

I hope I was clear enough. 

Thanks 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment]
You can already tag several people in DMs and have a private group chat, right? So I guess the advantage of a private hashtag is that individual people don't have to be tagged every time, which would use up lots of characters?

**Comment by Cassolotl** [comment]
Your needs might be met by *Support groups #139*?

**Comment by pwFoo** [comment]
Maybe instead of private hashtags visibility by list members? A list is a timeline / stream filtered by users.
List users -> group members

So lists could be additional visibility / access filter like public, followers only or direct?

Select a list to share direct to all list users (shortcut for mention all the users to Post direct / private).

If that would be possible it would be great to have a way to share a list (group) with all the users (group members) to the members.
