### ISSUE TITLE
Ability to enable a setting, where either toots with replies, or the media tab shows first when visiting a profile

### ISSUE THREAD

**Issue by mareklach** [mastodon/mastodon#5675]
[Issue text goes here].

Let the user enable and save a setting related to their profile, whether the first tab that someone sees when visiting that person's public profile is Toots, or Toots with Replies as a first displayed view. The viewer would still be able to switch between different profile views, as now, only the default view when coming upon the profile's an option.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
Doing old issue triage ... I'm going to close this on the assumption that zero replies in seven years suggests a lack of interest from the team, and due to the [general policy of not accepting external design changes](https://github.com/mastodon/.github/blob/main/CONTRIBUTING.md#project-specific-considerations)

Please reopen with current app screenshot if you want to push forward.
