### ISSUE TITLE
Add list owner itself to lists.

### ISSUE THREAD

**Issue by tateisu** [mastodon/mastodon#6041]
I want to use list TLs instead of home because home TL has all of following and it is too cumbersome,
But I can't see my toot on list TL, it's make difficult to track conversation on list TL.

Why lists can't has list owner itself ?

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by SoniEx2** [comment]
Use-cases are accessibility:

Followers-only posts are not accessible, since you need to follow the poster to be able to see them. This is important in the case of replies - a poster makes a followers-only post, someone replies to the post, you can't see their reply.

The solution is to follow them.

By having a custom home timeline, you avoid polluting your home timeline, while still being able to see replies to followers-only posts.

(The "proper", long-term solution would be to rename "followers-only" to "OP's followers-only" and have it so replies can be seen by OP's followers.)

**Comment by tateisu** [comment]
yes, already I'm following all of lists member.

but I can't follow myself. then i can't add myself to list.

**Comment by Alienglyph** [comment]
I agree. It would be useful to add oneself to lists, sometimes.

**Comment by clarcharr** [comment]
Is there any plan to add this soon? It seems simple enough.

**Comment by trwnh** [comment]
this issue can be closed now
