### ISSUE TITLE
Tag cloud on about page

### ISSUE THREAD

**Issue by clayote** [mastodon/mastodon#6073]
This is a feature request.

When you're looking at an instance's about/more page, and trying to get a sense for what people actually post about, you currently have the public timeline and whatever text the admin thought to put there. You'd have to watch the public timeline for kind of a while to get a sense for it, and well intentioned admins don't always do the best job of describing their own community.

If the local users have been using tags, though, we can use that information to create a tag cloud, and let you click on tags in it to go to the public feed for that tag. That will give you a good idea of what people actually talk about on this instance.

It might be a good idea to make recent uses of tags count more toward a tag's size in the cloud.

**Comment by Cassolotl** [comment]
I like this, and I especially like the idea of it taking into account the age of the tag. :)

I am thinking someone's going to ask whether it should be local tags or all tags that have been in the instance's federated timeline. I think it would make more sense to me to match with the timeline that you can see when you're not logged in - so, federated. That way it's an expression of everything that you would *have access to* when you joined, which is still a reflection of the tastes of members of *this* instance. But if folks preferred that it only showed locally used hashtags that'd be fine too, I'm sure.

**Comment by duck57** [comment]
Considering all the recent drama over the trending topics (see #7702 and #7711 for some recent flare-ups and the original issue #271), I would suggest that a tag cloud is a much better vehicle for getting new users to find commonly-discussed topics than a trending list.

Tag clouds surface the consistently-popular topics (which trending lists try to suppress) while simultaneously being harder to game (since your new tag has to compete for attention with all the long-established tags).  To increase the difficulty of gaming the system, we should only count the unique users of the tag so small groups can't get something into the tag cloud by spamming about it.  Counting users rather than toots also will decrease the width of the frequency distribution so that instance admins would not need to mute over-dominant tags (such as #np) or spammy ones (#Patreon) because each user who uses them would only count as one (since those are two example tags that are repeatedly used by the same groups of users).

My suggestion for the default is local-only over the past week (to highlight discussion topics that are recently popular on that instance without being too subject to the variability of day-to-day tag use).  However, I'd also give options to view [local|federated] over [day|week|month|everything], with an optional additional [hour] option for instances that are at the scale of the m.s mothership or Pawoo.

**Comment by Cassolotl** [comment]
There's `[instance]/explore/tags`, which is definitely newer than 2017, and is probably meeting the OP's needs. It's not a cloud, just a ranked-by-popularity list, but I think it's probably enough?

**Comment by clayote** [comment]
Yea, that's fine
