### ISSUE TITLE
Gif autoplay dosen't work on iOS

### ISSUE THREAD

**Issue by chriswmartin** [mastodon/mastodon#6217]
Tested on iOS 10 in Safari and Firefox: gifs must be clicked to play even when "Auto-play animated GIFs" is enabled. I feel like it is because we don't add the "muted" attribute to converted gif's `<video>` tags (I think?) https://webkit.org/blog/6784/new-video-policies-for-ios/ 

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by fwenzel** [comment]
I can confirm this. Is there a setting (CSP?) I have wrong, or is it generally broken in Mastodon?

**Comment by hughrun** [comment]
I would also love to know the answer to @fwenzel's question because for my instance (ausglam.space) GIFs in posts won't play at all in Safari either desktop or iOS, regardless of whether they are clicked/tapped. GIFs in **user profile pics** *do* play on hover, however, and all play in desktop browsers that aren't Safari.
