### ISSUE TITLE
Separate column for Pinned toots on the web profile page

### ISSUE THREAD

**Issue by LeeteqXV** [mastodon/mastodon#6828]
I love the pinned feature, but when using it extensively, IMO it should not push the latest toots out of sight.

I therefore suggest to put only 1 pinned toot in front of the normal toots/boosts/replies, and the rest of the pinned toots in a separate column titled "Pinned:" along the right side.

**Comment by Gargron** [comment]
The idea of pinned toots is for them to appear at the top of the profile. If people pin too many, that sounds like a social problem. I'm not sure hiding them behind a special area would be in the spirit of the feature...

**Comment by trwnh** [comment]
Perhaps semantically it would be better to consider the difference between a "pinned" toot and a "highlight". It is not uncommon to use pinning functions as a highlight reel, which becomes an issue when you want to highlight more than 3-5 things... so what is the best way to handle a highlight reel? Should they have a new section? Or should users adapt their use-case and highlight less things?

**Comment by trwnh** [comment]
Revisiting this, it still makes sense IMO to have a "featured" Collection, which AFAIK is exactly what's happening in the backend for pinned toots currently. Although perhaps #1208 might make more sense and users should be able to create arbitrary Collections of their outbox. Since pinned posts are currently found via /users/username/collections/features, the extension would allow Collections via /users/username/collections/collectionname (pending API/UI changes to allow users to actually manage those Collections, of course)

**Comment by trwnh** [comment]
the web profile page has been removed in 4.0 so i'm closing this issue as stale
