### ISSUE TITLE
Main page should show login in addition or instead of sign up

### ISSUE THREAD

**Issue by elharo** [mastodon/mastodon#6981]
If I go to a mastodon home page I should be able to immediately see the login form and have it autofilled, not have to click through a separate link. People login far more often than they sign up. 

I.e. flip sign up and login on these pages:

![image](https://user-images.githubusercontent.com/1005544/38166109-41660d9a-34ec-11e8-9316-241d684a0b0e.png)

Login on the front page, sign up behind  a button.

see https://cafe.elharo.com/ui/put-the-login-on-the-front-page/

* * * *

- [X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
Logging in happens more often but signing up is more crucial—a returning user has already demonstrated intent to visit the page, and is willing to click a few buttons to make that happen. A new user that doesn't see an easy way to sign up is just going to leave, and never come back

The page you link even outright says "it is far, far easier to keep an existing customer than it is to recruit a new one" but it makes exactly the wrong conclusion from the data—new users are way easier to scare away, and need to be handled with extra care because they're not as familiar with the software yet.

**Comment by elharo** [comment]
Twitter manages both:

![image](https://user-images.githubusercontent.com/1005544/38167286-d19fa858-3500-11e8-927e-c9538f492ca1.png)

And although this confuses password autofill, it does work.

**Comment by elharo** [comment]
And of course it's also possible that the login and sign up form are the same:

![image](https://user-images.githubusercontent.com/1005544/38172421-410bb3ac-357a-11e8-8b06-822c5017700d.png)

**Comment by Cassolotl** [comment]
If that was the case on Twitter it would have saved me so much trouble. :D

**Comment by ThisIsMissEm** [comment]
Login/Signup being one in the same is a really bad dark-UX pattern, because it means incorrect details results in new accounts. It's commonly used by sites trying to harvest information.

**Comment by zcdunn** [comment]
I agree, login and signup should not be a single form, but it would still be better to show both forms on the /about page

**Comment by trwnh** [comment]
![image](https://github.com/mastodon/mastodon/assets/10606431/7dde5f43-745c-4596-a317-3995a9500811)
