### ISSUE TITLE
Configurable mime types and extensions for attachments

### ISSUE THREAD

**Issue by mbajur** [mastodon/mastodon#6987]
Hello!

Would you accept a PR with an option to configure available media attachment mime types and extensions using .env config files?

I want to completely disable video uploads on my instance, forking mastodon and making my own "distro" just for that tiny modification seems like an overkill.

Thanks

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by JonasDralle** [comment]
I also think that having the choice would be very good.
Personally I like to be on an instance which allows all media.

I'd like to upload `.txt` and `.xml` files. Today I struggled uploading a `.graphml` file and have to resort to a file hoster.

**Comment by swilso793** [comment]
I would like that as well :)

**Comment by jacotec** [comment]
@mbajur Do you like to share your modification? I have the urgent need to allow PDF uploads on one of my sites, and there seems to be no "official" movement in that direction unfortunately.

**Comment by mbajur** [comment]
sorry @jacotec but i never implemented that. Mostly because of lack of reply and, right now, i don't need that anymore.

**Comment by EwonRael** [comment]
Having some kind of option to allow various unrecognized filetype uploads would be tremendously useful. It would be nice to have support for PDFs and it seems that's echoed somewhat within this issue or issue #7495, but just letting folks upload and download unrecognized filetypes is a more than satisfactory fix.

**Comment by Gargron** [comment]
I don't want to encourage using Mastodon as a generalized file hosting solution. The privacy-oriented "pre-download file on each server" model is ill-suited for distributing a file efficiently, and, most importantly, most file hosting solutions aren't free because disk space and bandwidth aren't free. On Mastodon, sysadmins eat the cost of storing some files because images, videos (and now audio) are an integral part of the expected social media experience, and that cost is reduced somewhat because images, videos, and audio can be heavily optimized with quality loss. You can't do that with a PDF or an .exe. Furthermore, images, videos and audio can be reasonably secured against malware while arbitrary file uploads would introduce the risk of viral malware spread in the network. Sorry!

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mastodon/mastodon/issues/6987#issuecomment-726480730

@Gargron, with the existence of the private messaging feature, it makes sense to permit file uploads.
