### ISSUE TITLE
Make Post/Toot available to selected List(s)

### ISSUE THREAD

**Issue by aquariusdev** [mastodon/mastodon#7182]
Interested in having the ability to toot to selected lists, as shown here.

<img width="300" alt="mastodon mockup posting to lists" src="https://user-images.githubusercontent.com/28520002/38941974-a976fefe-42fb-11e8-88e0-165d56d7592d.png">

This would mean that the post/toot is only visible to certain people without having to make your your whole account private. 

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment]
Potentially conflicting issue: #6982 - _add accounts to list without following them_

I am a bit more in favor of this request than the other one, but I think there's potentially room for both if there are two types of lists (one for following, one for not following). This could also increase complexity a bit, however, so some slight reimagining might be needed to work it into something better and easier to understand than Diaspora* aspects or Google+ circles.

**Comment by annfables** [comment]
I would really love having such lists, since there's currently no social network available which manages public posts & private posts to certain defined lists on one account in a usable way. I really loved the idea of Google+ circles, although it haven't seen any major UX design updates since like 2012 & seems to be still buggy as a concept. I brainstormed on this for a few minutes, and basically the following features may come in handy:

* being able to toot to multiple lists.
* creating shared lists with other users (where users can see those in their own dashboard posting to them)
* maybe a role management for editing such lists
* a sorting function so the most active lists will appear first
* having the possibility of filtering dashboard streams (e.g. disabling the public stream only showing content of the lists cats, technology, tschunk and so on)

**Comment by maralorn** [comment]
Is this technically possible in OStatus/ActivityPub without changing the protocol? I would love to see this feature! I wouldn't want all the nice features listed above.

**Comment by trwnh** [comment]
@maralorn I think this is technically possible because yes, in ActivityPub you can set the `to:` / `cc:` / etc audience without necessarily adding a `Mention` `tag`. The current problem is that Mastodon currently has weird rules for parsing this kind of ActivityPub response; both addressing and tagging are required/sent by default, but some mentions can be sent without being tagged as mentions (especially from other software like Hubzilla) -- however, these posts appear in your notifications column and not your Home column. It'd take a rework of how Mastodon treats mentions; under a pure addressing system, it's possible that a post may be addressed to you but not visible to you unless you follow that person.

One other thing I'd like to add: I don't think it's a good idea to mix up "categorizing your follows" with "categorizing your followers". I wrote more in https://github.com/tootsuite/mastodon/issues/5686#issuecomment-414149712 about this, which I currently think is a better solution. Lists IMO should stay for sorting the people you *follow*, while a new feature should be created for sorting your *followers*. Maybe call it Audiences.

**Comment by trwnh** [comment]
closing in favor of #983 (but applied to specific accounts instead of specific servers)
