### ISSUE TITLE
Allow regex mutes in pinned search columns

### ISSUE THREAD

**Issue by psmalone** [mastodon/mastodon#7639]
Pinned search columns could be much more useful if we could also mute other keywords/regex in the column. For example, if a hashtag is commonly used for two different meanings, careful regex mutes could exclude most of the usage that I'm not interested in.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mjankowski** [comment]
First - still relevant to latest version?

Second - is the request here *separate from* the existing filters that do exist, and instead targeted at similar filters but just for that focused column? Would those persist over time or be just in an active session?

**Comment by trwnh** [comment]
nope, this was filed back when we still used client-side regex instead of server-side filters.

i think the best path forward is going to be adjacent to #18955 but i wouldn't hold out hope -- the new paradigm seems to be server-side filtering for years now, and regex was rejected for being too expensive at scale. i don't know if there's reconsideration of this last point, but this issue is stale.
