### ISSUE TITLE
Boost / Favorite / Reply to profile content

### ISSUE THREAD

**Issue by LordFratz** [mastodon/mastodon#7885]
I noticed that you can't Boost, Favorite, or Reply on posts when viewing someones profile when right clicking on their name and choosing open as new tab (or clicking middle mouse button). I don't know if this is a bug or a feature yet to be implemented. If it has yet to be implemented, that would be a great addition in my opinion.

In case this is a bug, I am using chrome to run the website.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by rubahness** [comment]
I have this issue sometimes when linking another person to a toot directly. It opens on a single-column view page, and the interactions are disabled. Sometimes there's a "open in web view" link that will open the 4 column view, but sometimes not, and I haven't figured out what drives it

**Comment by Krinkle** [comment]
> In this case, viewing another standalone toot on the same instance has an Open in Web link, […]

Indeed, this trick only works if the toot in question is on the same instance (and requires discovery and understanding of "Open in Web"). If the toot is on another instance, it's much harder as one would have to open the home page of your local instance in a new tab, copy the remote URL, search for it, and then you can view it in a separate tab.

My suggestion would be to have the permalinks in the web app (for logged-in users) always use the web-specific URL routes instead of the canonical routes. In other words, when I'm viewing <https://mastodon.technology/web/accounts/7>, <https://mastodon.technology/web/statuses/102739653093293181>, or otherwise see that toot in a timeline somewhere, the pemalink would link to the local `/web/statuses/•` url both for local and remote messages. That way, it can be safely opened in a new tab.

The dedicated "Copy link to status" option, and any other web share interfaces, should of course keep using the canonical public URLs. Although even if someone shares the permalink directly without seeing what it does, it would still functionally work as Mastodon will naturally redirects these URLs to the public view of of the originating instance (local or not) if the recipient is not logged-in with a local account on that server.

Would this be acceptable in a pull request? I'm curious if there are past motivations for using public URLs in the permalinks, which might still apply.

**Comment by carlwgeorge** [comment]
I'm new to mastodon and noticed this today.  I [tooted out a few screenshots](https://fosstodon.org/@carlwgeorge/109248343525945475) before I found this issue.  It's quite confusing and could sour the experience for new users that think that's just what federation looks like.  At first I thought it was a federation issue until I realized it also happened within the same instance.

**Comment by Gargron** [comment]
> I'm new to mastodon and noticed this today. I [tooted out a few screenshots](https://fosstodon.org/@carlwgeorge/109248343525945475) before I found this issue. It's quite confusing and could sour the experience for new users that think that's just what federation looks like. At first I thought it was a federation issue until I realized it also happened within the same instance.

In your linked post, you write "On this page it treats you like you're not signed in (even if it's the same instance),", but in the screenshots, the address bar shows that you are on fosstodon.org in the first screenshot, and on mastodon.social in the second screenshot. So, everything is as expected here, you navigated to a web page where you are not logged in, and the interface tells you *how* to do the stuff you want to do from there.

In 4.0, there is no more "Open in web", if you *are* on the server where you are logged in, *there is only one interface and you are always treated like you are signed in*. This is the big change from previous versions. And when you navigate to another server where you are not signed in, the new interaction modal tells you how to perform the trick described above in this GitHub issue with a convenient one-click copy to clipboard of the URL.

**Comment by carlwgeorge** [comment]
I get that, but I didn't ask to go to another instance, and the problem is repeatable on the same instance ([screenshots](https://fosstodon.org/@carlwgeorge/109248637106675173)).  In both cases the screenshots are from left clicking (open in place) versus middle clicking (open in a new tab) the timestamp of a notification.  Those two actions shouldn't take you to different URLs.

It sounds like this will be improved within the same instance in 4.0, which is good to hear.  Thanks for your work on that.  Will left and middle click on a notification timestamp open the same URL?

**Comment by trwnh** [comment]
closing this issue as stale; for local posts, the public pages have been removed in v4.0, and for remote posts, there is an interaction dialog that currently explains how to load the post on your home server (and soon will offer a redirect to your home server)
