### ISSUE TITLE
Statuses pages doesn't display all the replies

### ISSUE THREAD

**Issue by kit-ty-kate** [mastodon/mastodon#8120]
Example (post content: SFW Yuri pictures): https://social.wxcafe.net/@kit_ty_kate/100092297369593318

This page doesn't show all the thread/replies and there is no ways to know there are.
However if you load it using the search bar in the web interface, every replies are shown.

Is it possible to have everything shown or is there a post count limit ? (which seems unlikely considering clicking on the last post shows more posts: 30 with the first one and 52 with the last one: https://social.wxcafe.net/@kit_ty_kate/100320974586484632)

**Comment by nightpool** [comment]
this is the thread depth limit I think? we raised it to a super high number
so people stopped running into it, but it's probably still not high enough
for this thread. I'd have to check to make sure.

**Comment by kit-ty-kate** [comment]
Any news on this bug? It's super annoying to not be able to sent a link to the beginning of a thread and not having any `show more` button like when you link the end of the thread

**Comment by ThibG** [comment]
Indeed, the depth limit is set to 20 toots, which is too low for that kind of thread. Interestingly, it's not set at all in the controller for the REST API requests.
I'm not too sure how much this would impact performances, but maybe it should be raised or dropped entirely?

**Comment by kit-ty-kate** [comment]
Is there no way to just know if there are more replies and display `Show more` at the end if that's the case?

**Comment by ThibG** [comment]
This is how it is supposed to be.
However, the code is wrong and there is at the very least a off-by-one error in that code:
https://github.com/tootsuite/mastodon/blob/master/app/controllers/statuses_controller.rb#L103-L134
Indeed, depth should be incremented when considering a new thread (line 129).
The code also seem to work under the assumption that nodes are ordered following a bounded depth-first search in the tree, which may not be the case anymore since 0eaf6d7693ba1f5568c9b857a306e01250f2f714

**Comment by ThibG** [comment]
In addition to breaking (already broken) depth computation, 0eaf6d7693ba1f5568c9b857a306e01250f2f714 also breaks the assumption that the thread cut short by the overall `DESCENDANTS_LIMIT` is the last one.

**Comment by ThibG** [comment]
Replies cut off by `DEPTH_LIMIT` may not work because of the broken computation of the depth, as described above.

Replies cut off by `DESCENDANTS_LIMIT` do show a link either, for two reasons:
- the HAML file depends on `@next_descendant_thread`, which is not set anywhere
- even with that fixed, the use of `since_descendant_thread_id` will not work if the reply is not a direct reply, since the ancestor will be filtered out

**Comment by ThibG** [comment]
Ok there's one other reason that may break pagination altogether: filtered and private statuses. Indeed, they break the controller's ability to compute depth as well as its ability to rely on the number of returned value to figure out if there's more.

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
