### ISSUE TITLE
UX Concept: Extended timeline.

### ISSUE THREAD

**Issue by kek-coin** [mastodon/mastodon#8159]
### Motivation
I want to discover people to follow. Not just those in my local instance, but anywhere - but my interests don't necessarily align with all those in my instance. Case in point, someone in my instance started following several escort accounts, which suddenly appeared in my federated timeline. I can easily mute/block them, of course, but it made me realize the federated timeline is not exactly filtered the way I want it to be.

### Proposal
An Extended timeline, which shows the local timeline + all follows of my follows. Perhaps even an Extended+ timeline, which additionally shows all the follows of my follows' follows. This way, I can discover new interesting people to follow or interact with, while still having some control over what shows up there by choosing who I follow.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate. At least, I tried. My apologies if this has been suggested elsewhere, there are a lot of open issues.

**Comment by kek-coin** [comment]
After reading a bit more how the federation works, I realized this would also imply that an instance needs to "subscribe" to all such people indirectly followed. Perhaps the Extended+ timeline would be too much.

**Comment by kek-coin** [comment]
The Extended timeline would have a fundamental advantage over the Federated timeline, though - being able to discover content through interesting people that are on different instances. Right now I need to essentially crawl through people's profiles to find interesting content outside my own instance.

**Comment by makoConstruct** [comment]
I wonder if it'd be worth thinking about doing a variant of this that only shows friends of friends who are also on your instance. Intersection of local and extended. I think I'd use it.

**Comment by trwnh** [comment]
This is basically asking to look at the second-degree network (friends of friends), isn't it? I do agree that this would be perhaps more useful than the current Federated TL, but that's only because the Federated TL is effectively a second-degree network of everyone on your instance. It might be best conceived as either a separate/new column, or as a filter to the existing Federated column, but knowing whether a post fits into your extended network might be kind of complicated. You'd have to calculate a distance value between every single account, I think... Still, it might be feasible on a single-user instance.
