### ISSUE TITLE
"Please review 2 errors below" but there is only one error

### ISSUE THREAD

**Issue by angristan** [mastodon/mastodon#8227]
If I'm not wrong the only issue here is the image file being too big : 

<img width="503" alt="screen shot 2018-08-16 at 22 41 16" src="https://user-images.githubusercontent.com/11699655/44235306-5278e600-a1a9-11e8-8de2-9491d756c936.png">

**Comment by trautwein** [comment]
The duplicate error is also present for other attachment uploads (e.g. when uploading the profile avatar).

I'm pretty sure this is caused by the Paperclip gem (see https://github.com/thoughtbot/paperclip/issues/2040 and https://github.com/thoughtbot/paperclip/issues/1367).

Since Paperclip is deprecated there will be [no fix from their side](https://github.com/thoughtbot/paperclip/issues/1367#issuecomment-385081907), though there is a workaround described [here](https://github.com/thoughtbot/paperclip/issues/1367#issuecomment-217934878).

There's also a currently open issue on migrating mastodon to ActiveStorage which would most probably resolve this as well: https://github.com/tootsuite/mastodon/issues/7414
