### ISSUE TITLE
Unread marker on notifications icon

### ISSUE THREAD

**Issue by swedneck** [mastodon/mastodon#8285]
Right now there's no way to see when you have an unread notification, just a dot next to the notification bell icon would fix this.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by trwnh** [comment]
Related: #710, #8050

**Comment by MirceaKitsune** [comment]
Is this theoretically resolved? In Mastodon 3.3.0 the unread counter sticks to the notifications icon until you access the tab, just as desired. At least for the simple UI didn't test the complex one. Could this be done for other tabs too? DM's sound like a good candidate, otherwise it looks good at least in my book.

**Comment by eobet** [comment]
At least for me in the "advanced web view" it's not resolved (looking at mastodon.social). The bell icon was unchanged and yet when I clicked on it I had three new notifications (indicated by blue lines).

**Comment by trwnh** [comment]
https://github.com/mastodon/mastodon/issues/8050#issuecomment-538872986
