### ISSUE TITLE
Move the filter pannel to the "Setting" section

### ISSUE THREAD

**Issue by Sylvhem** [mastodon/mastodon#8318]
Right now, the filters panel is the only setting panel targeted at end users that is not in the "Settings" section. I would suggest to move it there.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by theotix** [comment]
I possibly agree with you, but not sure to understand what you mean by "filter panel": is this the mute options inside of the profile hamburger menu?

**Comment by ThibG** [comment]
Alright, it's because it was introduced in the latest release. It's meant to replace the column-specific regexp filters.

![screenshot_2018-08-20 ajouter un nouveau filtre - mastodon instance perso de thibg](https://user-images.githubusercontent.com/384364/44349904-6caf0e80-a49e-11e8-8ab0-be005b18de77.png)

**Comment by AirDur** [comment]
Well, it's so unbalanced because "Setting" will be for all things except administration and as an user, it'll be weird to have "Setting" and "Development". The whole UI needs to be rebuild.
