### ISSUE TITLE
Allow more HTML in the sanitizer

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [mastodon/mastodon#8474]
Currently, as it is, even simple Markdown cannot federate. It would be nice if we could support more kinds of posts, and that includes allowing more formatting. I recommend that at the very least, we allow simple formatting tags.

Edit: As @KScl has noted [over on Mastodon,](https://is.a.qute.dog/@KS/872334) this would require reaugmenting the CSS so that the formatting tags actually do something.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by trwnh** [comment]
fixed by #23913 -- and authoring more HTML is also in the works

**Comment by dahlia** [comment]
I'm not sure if I should open a new issue or leave it in this already closed one — but here goes. Please let me know if this isn't appropriate.

With the merging of PR #23913, the following tags are now allowed: `<del>`, `<pre>`, `<blockquote>`, `<code>`, `<b>`, `<strong>`, `<u>`, `<i>`, `<em>`, `<ul>`, `<ol>`, `<li>`, and `<h1>`–`<h6>`.  In addition, I would like to see the following tags for Ruby characters: [`<ruby>`][1], [`<rt>`][2], and [`<rp>`][3].

Ruby characters are a common element in so-called CJK, East Asian texts, and are often needed due to the fact that Chinese characters are not phonetic (basically).  They are used primarily …

- to attach phonetic characters to esoteric Chinese characters that are difficult to read,
- to help children who can't yet read Chinese characters well,
- and to give screen readers hints about the pronunciation of rare words that aren't in the dictionary,

… all of which are basically to increase accessibility.

For more information on Ruby characters, you can check out the [Wikipedia on this topic][4].

[1]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ruby
[2]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rt
[3]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rp
[4]: https://en.wikipedia.org/wiki/Ruby_character

**Comment by renchap** [comment]
@dahlia please open a new issue for this topic, and we will have a look.

**Comment by dahlia** [comment]
@renchap I filed a new issue: <https://github.com/mastodon/mastodon/issues/26592>!
