### ISSUE TITLE
About/more: doesn't fit on mobile screens 

### ISSUE THREAD

**Issue by scroom** [mastodon/mastodon#8651]
Hi, 

Since an update to the new version 2.5.0 the about/more-page does no longer fit on screens of mobile devices. 

![screenshot_20180908-221300](https://user-images.githubusercontent.com/5347731/45258255-d2632c00-b3b4-11e8-9a88-9175c39028e0.jpg)

**Comment by scroom** [comment]
Huawei P20 pro (tested with Firefox 61.0.2 and Chrome 68)

**Comment by scroom** [comment]
Mastodon.social/about/more

![screenshot_20180908-223617](https://user-images.githubusercontent.com/5347731/45258440-bca33600-b3b7-11e8-877c-c12e188990d5.jpg)

**Comment by trwnh** [comment]
There's a breakpoint at (min-width: 416px) that causes a reflow and puts the stats block next to the admin block; this is a problem because some smartphones use web resolutions that exceed 415px. For example, my Sony Xperia X Compact has a web resolution of 424px wide. But that's a much more secondary problem, because the real issue is that the layout is just utterly broken between 416-832px.

![image](https://user-images.githubusercontent.com/10606431/45258684-69ae8c00-b381-11e8-86bf-c8f978532519.png)

**Comment by trwnh** [comment]
the page in question has been redesigned/removed, so i'm closing this issue as stale
