### ISSUE TITLE
When a user account has moved, notify new followers they're following a deprecated account

### ISSUE THREAD

**Issue by haiitch** [mastodon/mastodon#8660]
Real use case:

I have moved from @h@social.coop to @h@sunbeam.city
A number of people have kept following my old account after I set it up with the "Moved" notice.

People don't always see a user's profile when they follow them, they may follow a user in the middle of a thread, or through a search result, and they never see a "Moved" notice in such contexts.

I could set this account to be by request-only, but that wouldn't solve the problem, because I will have to keep going back to the old account to check who has followed me from time to time, and inviting me to join elsewhere.  

Things would be more intuitive and effortless for all involved if new followers got a warning message saying:  "This account has moved to @h@sunbeam.city.  Do you wish to follow that account instead?"

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
i'm pretty sure we block users from following moved accounts in all cases, so this may be a federation or out of date instance problem?

**Comment by htrob** [comment]
Social.coop is running the latest 2.5.0, in that case, if there's a problem it's possibly a regression problem.

**Comment by nightpool** [comment]
the out of date instances would be the ones with users that followed you. unless those are also social.coop users?

**Comment by htrob** [comment]
They aren't social.coop users. The social.coop instance should still reject new follows anyway, this is counter-intuitive behaviour.  Also users who send messages should get a similar notice: "You are messaging @h but this account has moved. Do you wish to follow @h@sunbeam.city and message them instead?" .
See attached below what happens when you are attempting to leave a not exceedingly popular account, people keep replying to old posts, people like Chocobozz (in that screenshot) only follow back after weeks of having been contacted, and so on.  
I know, this is probably new, and it doesn't affect everybody, but it's something we will begin to see more often as Mastodon matures and communities evolve over the years.

![screenshot at 2018-09-09 21-59-41](https://user-images.githubusercontent.com/23458/45271283-2c7af480-b47c-11e8-9807-c5e001a17cda.png)

**Comment by nightpool** [comment]
Of the four users you posted, one is on 2.2.0, and three are on non-mastodon software that apparently does not respect moved accounts. Not sure how much more we can do technically to fix this, but an auto-responder is an interesting idea......

**Comment by htrob** [comment]
Right, I had missed that, sorry.  Maybe if at least the instance that is up-to-date can block the follow request and send back an automatic reply that will do, as that will  be backward compatible, and compatible across implementations.  It won't be a GUI warning but a warning sent over the wire, so that could have some security repercussions if bad actors find a way to forge follow requests on behalf of somebody else. If those security concerns aren't difficult to check and the danger of generating crazy traffic is avoided, this may be the best available solution.
