### ISSUE TITLE
Option to expand filtered toots on click

### ISSUE THREAD

**Issue by CosineP** [mastodon/mastodon#8914]
I need to auto-expand CWs because clicking on nearly every toot is irritating. Others have mentioned that this is especially bad if they have poor fine motor control, etc.

Nonetheless, I need to see *some* content warned. How can I make this work? Why, if filters could optionally collapse instead of dropping, they could serve a role similar to CW!

Since auto-expand CWs has landed, we can now make this amazing dynamic duo!

As a model, see pleroma's filter system.

Gargron: I know you've said "I have received a lot of positive feedback for the fact that the filter does not let you click to see what's underneath" - I don't ask that you remove this feature, but rather that you add the ability to do this. The add filter dialogue already has lots of checkboxes, this can't harm it any.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kimonoki** [comment]
For similar reason I want a single switch for enable/disable filters

**Comment by ljoonal** [comment]
Not completely hiding filtered content is something that I also would like to see officially supported. I even wrote an [userscript](https://git.ljoonal.xyz/ljoonal/user._/src/branch/master/scripts/mastodon-cw-filter.user.js) for my own requirements that pretty much matches this issue, but due to technical issues related to CSPs' it's hard to get it to work, and the implementation is quite botched. It demonstrates though that automatically collapsing filtered content instead of hiding it would be a powerful feature that'd at least make my own mastodon usage experience way better.

Is there some technical reason that this hasn't been implemented yet?

**Comment by ObsidianWolf64** [comment]
This would be absolutely wonderful. As it is, I can't even see _what filter_ a post hit, much less what the post is if I decide it's worth opening.

And there's no technical reason! Glitch does this already, very nicely too. It has a "(show why)" link next to the "Filtered" text; clicking that brings up a dialog that shows who wrote the post, what filter it hit, and lets you see the original post if you want.

!["Show Why"](https://user-images.githubusercontent.com/58482583/105638609-81e3b080-5e41-11eb-8e98-420d29a33eb6.png)
![Filter preview panel](https://user-images.githubusercontent.com/58482583/105638617-945dea00-5e41-11eb-847b-8b8754f62f9f.png)

**Comment by ClearlyClaire** [comment]
Addressed in #18058
