### ISSUE TITLE
The / at the end of URLs in posts could be removed where it is not necessary

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#8970]
It's untidy-looking!

I have no other justification. :D If there's a good reason why it's there then just say, but Twitter omits it, so I assumed that it can't be that internet-breaking, right?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by trwnh** [comment]
It might be fine to do this for display, but it absolutely cannot be done for actually trying to load that URL, because different servers are configured differently. On the backend, a URL like `http://example.com/test` is NOT always the same as `http://example.com/test/` -- it depends on which file it's trying to load! The bit after the domain name (the URI) is resolved based on a bunch of pre-defined rules for each server configuration; `/test` might redirect to a different location block, but `/test/` might try to load `/test/index.html`. This is actually something Twitter shouldn't do, but then again, Twitter already wraps everything in its t.co shortener, so it's not like Twitter cares about best practices...

**Comment by Gargron** [comment]
I think OP might mean URLs with empty path? Where the slash is the only thing after hostname?

**Comment by Cassolotl** [comment]
>Twitter already wraps everything in its t.co shortener,

Ahh maybe that's how they can remove forward slashes from things - it's all an illuuuusion.

>I think OP might mean URLs with empty path? Where the slash is the only thing after hostname?

Yeah, basically anything where the / is optional. If I type mastodon.social into my browser it still finds the right website, right?

**Comment by trwnh** [comment]
I think if it's just `http://example.com` or `http://example.com/` then it gets handled by your browser. In both cases, your browser will most likely simply request `/` regardless of whether you explicitly specify it, and they'll remove it from the URL bar so that you only see `example.com` or `http://example.com`.

This is also technically incorrect, but ultimately harmless because there's no ambiguity at all. Typically the trailing slash indicates that you're accessing a folder instead of a file, and there _isn't_ a file at `example.com` -- there is only the root folder, so most browsers know to convert back-and-forth between `...com` and `...com/` with no problems, and then fetch something like `/index.html`. But there _is_ ambiguity for everything past the `/` root folder, because it's possible to have both files (`/test.html`) and folders (`/test/index.html`), as well as redirects and rewrites and all sorts of things.

In a practical, real-life example you can test right now, you can load the following and see certain results:

- https://mastodon.social = https://mastodon.social/ (browser requests root)
- https://mastodon.social/web => https://mastodon.social/web/web (rewrite, not found)
- https://mastodon.social/web/ => https://mastodon.social/web/getting-started (redirect, found)
- https://mastodon.social/about/more = https://mastodon.social/about/more/ = https://mastodon.social/about/more.html = https://mastodon.social/about/more* =/= https://mastodon.social/about/more/index.html (pattern matching)

**Comment by Cassolotl** [comment]
Right! And http://mastodon.social looks much nicer in a post than http://mastodon.social/ and the / is added by the browser, so the / is basically optional.

**Comment by justinmayer** [comment]
From my perspective, I don't think trailing slashes are untidy, nor do I find any places in Mastodon where the user experience is improved by removing them.

**Comment by dracos** [comment]
@trwnh Just to note that when you said "This [no path] is also technically incorrect", that is not true; as RFC3986 states: "When authority is present, the path must either be empty or begin with a slash ("/") character."

**Comment by jfietkau** [comment]
This came up in the conversation of #36410 and it seems like it's been a while since the trailing slashes were considered.

Previous comments here suggest that Mastodon's post formatter was still leaving the protocol part of links visible at the time (in 2018) – now the `https://` gets hidden from view through a CSS class, which changes the aesthetics of leaving the trailing slash visible. I would argue that for links with a path of only `/` (that is, links pointing directly at the root of an origin), the trailing slash should be hidden the same way. “Check out [example.com/](https://example.com/)!” is simply uglier than “Check out [example.com](https://example.com/)!” and, just to mention another random platform I use, Discord trims this slash for display as well.

Edit: Also discussed in #6351.
