### ISSUE TITLE
Add support for more constructed languages in "Posting language" dropdown menu

### ISSUE THREAD

**Issue by KNTRO** [mastodon/mastodon#8995]
Hello all,

Only Esperanto is available, but I would like Mastodon to add support for more constructed languages as: Bâleybelen, Ido, Interlingua, Láadan, Lingua Ignota, Lingwa de Planeta, Mänti, Na'vi, Toki Pona, Volapük, etc.

I speak one of these constructed languages and currently it is hard to find another people at Mastodon tooting in the same language, because they're not available at Mastodon for the time being.

Thank you so much for reading!

**Comment by maliktunga** [comment]
I write in Ido and I agree that Ido should be added. I am trying to convince a group of Idists to join Mastodon, and in addition, it would be useful to have Ido among the filter languages.

**Comment by VyrCossont** [comment]
Looking at the most recent RC's [`app/helpers/languages_helper.rb`](https://github.com/mastodon/mastodon/blob/v4.0.0rc2/app/helpers/languages_helper.rb), a few of these have already been added, as well as a few other conlangs not listed in this issue.

| language | ISO 639-1 | ISO 639-3 | already supported |
| --- | --- | --- | --- |
| [Balaibalan/Bâleybelen](https://en.wikipedia.org/wiki/Balaibalan) | *none* | `zba` | ❌ |
| [Esperanto](https://en.wikipedia.org/wiki/Esperanto) | `eo` | `epo` | ✅ |
| [Ido](https://en.wikipedia.org/wiki/Ido) | `io` | `ido` | ✅ |
| [Interlingua](https://en.wikipedia.org/wiki/Interlingua) | `ia` | `ina` | ✅ |
| [Interlingue](https://en.wikipedia.org/wiki/Interlingue) | `ie` | `ile` | ✅ |
| [Láadan](https://en.wikipedia.org/wiki/L%C3%A1adan) | *none* | `ldn` | ❌ |
| [Lingua Ignota](https://en.wikipedia.org/wiki/Lingua_Ignota)| *none* | *none*  | ❌ |
| [Lingwa de Planeta](https://en.wikipedia.org/wiki/Lingwa_de_planeta) | *none* | *none*  | ❌ |
| [Lojban](https://en.wikipedia.org/wiki/Lojban) | *none* | `jbo` | ❌ |
| [Mänti](https://en.wikipedia.org/wiki/Daniel_Tammet#M%C3%A4nti) | *none* | *none*  | ❌ |
| [Na'vi](https://en.wikipedia.org/wiki/Na%CA%BCvi_language)| *none* | *none*  | ❌ |
| [Toki Pona](https://en.wikipedia.org/wiki/Toki_Pona) | *none* | `tok` | ❌ |
| [Volapük](https://en.wikipedia.org/wiki/Volap%C3%BCk) | `vo` | `vol` | ✅ |

If a language has an ISO code but is missing from one of the language maps in `languages_helper.rb`, we can probably just add it, and I'd like to propose PR #20168 where we add at least Toki Pona, since I've been seeing a lot of it on my timeline lately, do not speak it, and want users to be able to tag posts in it so that my language prefs can filter it out in the future.

If a language *hasn't* had an ISO code assigned, it's not going to work trivially with existing Mastodon code, which uses either [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) or [ISO 639-3](https://en.wikipedia.org/wiki/ISO_639-3) codes internally to identify languages in places like the post editor and the user's language preferences. That seems like the kind of change a conlang-focused instance should try out locally first.

**Comment by KNTRO** [comment]
Could we consider Lingua franca nova (A.K.A. Elefen) as well (ISO 693-3 = lfn), please?

**Comment by VyrCossont** [comment]
@KNTRO Sure. Wikipedia claims that the translated language name is `lingua franca nova`; do you know if that's correct?

**Comment by KNTRO** [comment]
@VyrCossont Yes, in Lingua franca nova, its name is in lowercase, even _elefen_ or _lfn_, same as the case of the Toki Pona language (in Toki Pona all words are always written in lowercase).

**Comment by VyrCossont** [comment]
Great, I've made those corrections in the linked PR.
