### ISSUE TITLE
SVG image uploads in toots

### ISSUE THREAD

**Issue by christianp** [mastodon/mastodon#9283]
I'd like to be able to attach an SVG image to toots. 

What are the considerations for allowing that? I suppose there are security implications, so SVGs would need to be sanitised, but is there anything else?

**Comment by ThibG** [comment]
There are security considerations, see #9253 (although this PR only applies to custom emoji, not to uploads in general) for some of them.

The main concern is that unless the web servers serving the media files are specially configured (which is somewhat out of scope of Mastodon itself), those can be used to execute scripts. Sanitizing SVGs is notoriously hard and I'm not sure there is a reliable tool to do that (haven't searched a lot though).

Another concern is that server-side processing is somewhat more involved than the image types we currently accept, so the attack surface is also larger (XML processing, etc.). I'm not *too* concerned about that, because I trust rsvg, which is used by ImageMagick under the hood, but it is a security consideration.

There are probably some client-side performance considerations too, since SVGs can be arbitrarily complex to render.

As for implementing support for them, I think #9253 would be a good starting point.

**Comment by trwnh** [comment]
Duplicate of #6569
