### ISSUE TITLE
popup "You want to interact with this toot:" keeps getting in the way

### ISSUE THREAD

**Issue by allefeld** [mastodon/mastodon#9514]
I'm sometimes checking out the toots of a user on their page (https://instance/@user) and want to favourite them by clicking on the star icon below. This doesn't work, because a popup "You want to interact with this toot:" keeps getting in the way.

### Expected behaviour

Expected behavior would be that the post simply gets favourited (spinning star animation, then star highlighted).

### Actual behaviour

When clicking on the star icon below a toot, I get a popup "You want to interact with this toot:" and I am asked for my handle.

This happens even though I'm logged in and *the user is on the same instance as me*!

When I enter my handle and click "Proceed to interact", there's very briefly a message that something isn't found, and then the popup goes blank (but stays open).

When I reload the user's page, the respective toot is still not favourited.

This happens generally, for all user pages and all toots on them.

### Steps to reproduce the problem

Open a user's page (on the same instance) and click on the star icon below a toot.

### Specifications

My account is on a Mastodon instance running version 2.6.5.

Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by allefeld** [comment]
@ThibG, thanks for the explanation, that makes sense.

What I don't understand is why it is so simple to leave the WebUI, without really notifying the user? I noticed the link ("return to Mastodon") which I guess is an indicator of having left the WebUI, but it just confused me – first, if that's what it means it should say "return to WebUI", optimally with a small link to an explanation (a "?" icon for example). Second, I see the advantage of getting a public URL to share with people who don't have an account on the instance – but having open multiple tabs to the same site (including JavaScript-driven aka UI) is completely normal to me, and I would guess plenty of other users. Why not have links for logged-in users always remain in the WebUI, and have an extra "share public URL" button at strategic points? That's more in line with the way other web-based UIs work.

**Comment by schipplock** [comment]
"reply" and "boost" don't work at the public page as well.

I faced the same problem and was confused :). I'm used to open links with the middle mouse btn and constantly were bugged with this dialog :). For me it's clearly a bug because it works in the single page app but not the in public page. And as you stated already: it doesn't work even if you provide the required input :). 

Also the public page doesn't show if you faved something using the single page app. It's not in "sync" :).

The problem also exists in v2.7.1. Happy mastodon user. I hope that, one day, someone will sacrifice oneself for this issue :).

Regards,
Andreas
