### ISSUE TITLE
Appeals Function

### ISSUE THREAD

**Issue by CitizenPrayer** [mastodon/mastodon#9791]
Just saw the new update for mastodon's moderation tool for putting accounts in limited mode or banning mode. I'd like to see a form available to folks who are in these modes to be able to submit an appeal request, to which a moderator/admin can review and consider either to deny, to remove their limited or banned mode, or to give them a certain time of being banned/limited as a smaller form of punishment.

**Comment by Laurelai** [comment]
This will just be used as a method for bad actors to harass mods and admins

**Comment by MirceaKitsune** [comment]
Absolutely necessary! There are a lot of websites out there with trigger-happy mods on which users have experienced abuse in the past. When that happens they need a way to make their case to other moderators on the team and explain why they believe a decision is wrong. Without this many instances will become a place where you'll be afraid to say or do anything.

I can say this based on cases I've experienced myself: I've been nearly banned from Youtube for 3D animation after it was maliciously flagged as porn by a troll group, or temporarily suspended from a big art site for simply mentioning someone while on their block list. One of those places I barely use today, the other I'm afraid to randomly find myself banned from over saying something I never thought was wrong. In some of those cases having a way to appeal helped clarify the issue... without it things would have been even worse for a longer time.

Bad actors have enough means to get back at an admin if they want to, the most obvious being to make a new account from another device / IP or simply on another instance. A proper way to appeal might in fact discourage that course of action (ban evasion). It's important to make sure that appeals go to other moderators on the instance, rather than being a hotline to the same mod that banned you: That would quickly encourage a conflict while not offering the user a fair trial.

**Comment by shawneric** [comment]
> This will just be used as a method for bad actors to harass mods and admins

Those issues are simple to resolve. Appeals are based on accounts that are only currently banned for whatever reason, and the appeal can only happen once per a certain time limit (or one time only). If an appeal is denied, then the end user must wait some time before being allowed to submit another appeal. Additionally, it'd be wise to require appealees to wait a given time period prior to submitting an appeal, so it gives them time to cool off emotionally.

**Comment by N07070** [comment]
I would really like to see this happen.

Currently, it's done via email. But it's not ideal, as it detaches the issue from the instance moderation panel. It would be nice to be able to follow an issue, it's appeal, and more directly from mastodon.

I would also like to be able to make the ban public, like on instance.free/banlist, so people can see why others where banned. It's a transparency issue too, but it might be an issue of it's own.

**Comment by MirceaKitsune** [comment]
From personal experience, I noticed most admins have the habit of instantly deleting your account and all its data without warning the moment anything upsets them. It would be nice if by default this process wouldn't be irreversible right away, but offer a 7 day period in which you can appeal the decision before the data is irreversibly deleted. Granted it's not an emergency to delete it at once, such as an account posting something that was illegal for the admin to have on their drive.

**Comment by test2a** [comment]
reddit has this ban appeals where anyone banned by a moderator can appeal the ban. there is a sidebar showing crm style recent activity of that particular person in hopes that the moderator should not have to go and find that particular persons activities. This is also transparent as everyone in the moderation team can see how a particular mod is interacting with that person and option to put a private mod note to help another mod, right on the same page.
