### ISSUE TITLE
User's avatar doesn't appear in conversation page if the `accounts` length greater than four.

### ISSUE THREAD

**Issue by shuiRong** [mastodon/mastodon#9901]
### Expected behaviour
Display the four avatars correctly.

### Actual behaviour
it just displays two avatars side by side.
![image](https://user-images.githubusercontent.com/16076993/51518940-75937a00-1e5a-11e9-9898-fea41f6f2629.png)

### Steps to reproduce the problem

You can just open your mastodon web page,  and see it. (Almost forgot, you need a conversation that includes  four users or more)

### Specifications

mastodon version: 2.7.0
My browser: Chrome 71.0.3578.98
My System: macOS Mojave 10.14.2

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this issue can be reliably reproduced on an updated version please request that this issue be reopened or open a new issue. For either option please provide updated logs/troubleshooting on a recent release. Thank you.
