### ISSUE TITLE
VerifyAccountLinksWorker not being executed for some users

### ISSUE THREAD

**Issue by hugogameiro** [mastodon/mastodon#9903]
### Expected behaviour

On Edit Profile when pressing save there should be a Sidekiq pull issued to test remote links for verification.

### Actual behaviour

I get VerifyAccountLinksWorker in the Sidekiq log for user A whenever I save the profile info, no matter if there are links in the Profile Metadata or not and no matter if the profile has changed, it always fires VerifyAccountLinksWorker. 
For user B it never does no matter what, tried all I could think of (compare settings, compare database records for both users) but there are no noticeable differences between the two users.

### Steps to reproduce the problem

Can't reproduce but found the same issue with another user in another instance.

### Specifications

V2.7.0

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this issue can be reliably reproduced on an updated version please request that this issue be reopened or open a new issue. For either option please provide updated logs/troubleshooting on a recent release. Thank you.
