### ISSUE TITLE
Delete and Redraft not working properly with CW's

### ISSUE THREAD

**Issue by delightfulagony** [mastodon/mastodon#9918]
When deleting and redrafting a CW'd image post with no body (or being the body the CW since that's the behaviour when leaving a blank body) it eliminates the content warning, placing it in the body's image and eliminating the NSFW state of the image.

### Expected behaviour
Preserving the NSFW state of the image and the CW correctly.

### Actual behaviour
NSFW state being removed and using the CW as body of the toot.

### Steps to reproduce the problem
* Post a NSFW image with a CW and no body
* Delete and redraft that toot

### Specifications
I tested it in [cybre.space](https://cybre.space), which runs v2.7.0-cybre and also tested it in vanilla Mastodon v2.7.0.

**Comment by tmm576** [comment]
This is arising due to preprocessing the attributes of the toot prior to persisting it to the DB.

If a CW is present but not body, the CW will be deleted and used as the body instead. 

It looks like this is intentional behavior. Unfortunately the result is that there is no reliable way to pull that out of the database and know that it was originally tooted as a CW and not as the body.

I imagine this was done as typically a toot is not valid without text, however because this is a toot with media, that validation does not apply.

@Gargron - Prior to working out a solution, can you confirm intended behavior of `post_status_service` - 
```rb
  def preprocess_attributes!
    @text         = @options.delete(:spoiler_text) if @text.blank? && @options[:spoiler_text].present?
```

Media attachment exception was made in commit: cfa9b6e13ab3c434f3901df6f614d0aa94a3d1ed 

It doesn't look like we would fail validation and creation of the toot, so can we persist a record with no body (text) in this case? If so, redrafting can repopulate the CW/Body intelligently. Was there another unrelated reason to 'merge' these fields if text was empty?

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this issue can be reliably reproduced on an updated version please request that this issue be reopened or open a new issue. For either option please provide updated logs/troubleshooting on a recent release. Thank you.
